### ISSUE TITLE
Eager loading relation that have a union loads only first query

### ISSUE THREAD

**Issue by Locustv2** [yiisoft/yii2#10294]
There seems to be a problem with eager loading a relation when a union has been used.

```php
class Team extends ActiveRecord
{
    ...
    public function getTeam1Games()
    {
        return $this->hasMany(Game::className(), ['team1Id' => id]);
    }

    public function getTeam2Games()
    {
        return $this->hasMany(Game::className(), ['team2Id' => id]);
    }

    public function getGamesPlayed()
    {
        return $this->getTeam1Games()->union($this->getTeam2Games());
    }
}
```

When `gamesPlayed` is eager loaded, only the `$this->getTeam1Games()` retults are returned, but when it is lazy loaded, both results are returned.

```php
$team = Team::find()->where(['id'] => 1)->one();
var_dump($team->gamesPlayed); // both team1 and team2 games are returned;

$team = Team::find()->where(['id'] => 1)->with(['gamesPlayed'])->one();
var_dump($team->gamesPlayed); // only team1 games are returned.
```

FYI: the sql generated are:

```SQL
(SELECT * FROM `game` WHERE `team1Id`=1) UNION ( SELECT * FROM `game` WHERE 0=1)
```
The union part in the sql is not correct. When eager loading was removed, the sql generated was:

```SQL
(SELECT * FROM `game` WHERE `team1Id`=1) UNION ( SELECT * FROM `game` WHERE `team2Id`=1)
```

**Comment by klimov-paul** [comment]
This can not fixed.
The issue happens because during eager loading `ActiveQuery::primaryModel` processed in the different way.
When you use another relation in `union()` to bound it to the particular model which is not available during eager join.

Using `union()` with regular `Query` or `ActiveQuery` without a link works fine.

`ActiveQuery` can not trace over union in search of possible othe relation involved.

You may try to bypass the issue specifying the whole union query as a sub-query for selection, so the result query will be:

```sql
SELECT *
FROM (SELECT * FROM `game`  WHERE played=1) UNION ( SELECT * FROM `game` WHERE played=2)
WHERE `team1Id`=1
```

But I am unsure it will work.
