### ISSUE TITLE
Gii generates model code incorrectly. Uses 'integer' for TYPE_BIGINT instead of 'number'.

### ISSUE THREAD

**Issue by starrychloe** [yiisoft/yii2#10399]
See http://stackoverflow.com/questions/34304138/how-do-i-print-out-a-long-bigint-in-yii-in-php#comment56351098_34304266

---------------

When I print a BIGINT in Yii, it is rounding to MAX_INT. How do I print longs in Yii?

```php
      foreach ($negativeKeywords as $i=>$v) {
        echo "$i: Removing $v->id, $v->campaign_id, $v->keyword, $v->google_id\n"; 
```

```
    # 11: Removing 103, 2, gamtech, 2147483647
```

Real values:

```sql
    => select * from negative_keyword where id in (103,413);
     id  | campaign_id |  keyword   | match_type | status |  google_id  | bing_id
    -----+-------------+------------+------------+--------+-------------+---------
     103 |           2 | gamtech    |          3 |      0 | 31883722149 |
```
```sql
    => \d negative_keyword;
       Column    |          Type          |                           Modifiers 
    ...
     google_id   | bigint                 |
```

Here is the migration which created the table
```php
      $this->createTable('negative_keyword', [
        'id' => Schema::TYPE_PK,
        'google_id' => Schema::TYPE_BIGINT,
        ...
```
PHP 5.6.12 (cli) (built: Aug 11 2015 13:13:58)

**Comment by SilverFire** [comment]
I'm not sure that your problem relates to validation rules, because validation may affect data only on save. Even on save, `integer` validation rule does not typecase your value and only checks it against float, so representing of `TYPE_BIGINT` as `integer` is correct.

Could, you, please, show `var_dump($v)` from your first code block?

**Comment by Faryshta** [comment]
@SilverFire 2147483647 is a very special number the fact that is the number being echo'ed gives us the source of the problem https://es.wikipedia.org/wiki/2147483647

It looks like the issue is here https://github.com/yiisoft/yii2/blob/master/framework/db/Schema.php#L595

```php
if ($column->type === 'bigint') {
    return PHP_INT_SIZE === 8 && !$column->unsigned ? 'integer' : 'string';
}
```

Because of the server configuration we can see that php is type casting string `'31883722149'` to integer `2147483647`. Which is an 8 bit integer, the maximum integer you can get on php.

We need to include a unit test and patch those lines above.

**Comment by SilverFire** [comment]
Yeah, I've checked exactly the line you've pointed to, prior to my previous comment publishing :)

**Comment by SilverFire** [comment]
Failed to reproduce. Closing the issue because author is inactive.

@starrychloe if there is still a problem - please, show dumps I asked in the [comment](https://github.com/yiisoft/yii2/issues/10399#issuecomment-165016046) above

**Comment by wirwolf** [comment]
I have some problem.
In Gii generator @property string $balanceInt in 
I use MariaDB 10.2.10 field  balanceInt bigint(16) unsigned NULL
I use PHP Version 7.1.13-1+ubuntu16.04.1+deb.sury.org+1
var_dump(PHP_INT_MAX); => 9223372036854775807
