### ISSUE TITLE
Class yii\db\Connection

### ISSUE THREAD

**Issue by jonny7** [yiisoft/yii2#10512]
Hi

In the docs for `Class yii\db\Connection` it says: `Connection represents a connection to a database via PDO` 

I'm updating some code to take parameters, but the query won't execute without `use PDO;`. If this connection is already by PDO why do I have to explicitly include it within the model? (I'm curious as to it's working)

**Comment by SilverFire** [comment]
It's abnormal and I guess you do something wrong. Closing the issue because I'm sure that the problem does not relate Yii core, even though post your code.

For future please notice, that GitHub is for bug reports. We are happy to help you on [support forum](http://www.yiiframework.com/forum/) or in gitter room https://gitter.im/yiisoft/yii2. It's always better to text there, unless you are sure it is a Yii2 core problem.
