### ISSUE TITLE
ActiveForm multiple submit buttons and enableClientScript enabled, when output outside browser

### ISSUE THREAD

**Issue by tsdogs** [yiisoft/yii2#10555]
Generating an ActiveForm with multiple submit buttons and rendering the output based on the button value will keep last pressed button value active if output is not HTML (es. PDF)

To reproduce:
```php
// view
    <?php $form = ActiveForm::begin([ 
        'type' => ActiveForm::TYPE_INLINE, 
        'method' => 'GET',
        'action' => Url::to(['model/action']), 
        'enableClientScript' => true, // default
    ]); ?>
    <?=$form->field($model, 'date')->textInput(); ?>
    <?= Html::submitButton('View',[ 'name'=>'view', 'value' => 'view', 'class' => 'btn btn-default','data-pjax' => 0]) ?>
    <?= Html::submitButton('Print',[ 'name'=>'print', 'value' => 'print', 'class' => 'btn btn-default','data-pjax' => 0]) ?>
    <?php ActiveForm::end(); ?>

// controller action

public function actionAction()
{
    if (isset($_GET['print')) {
       // output something that is not HTML. i.e PDF or XLS
       \Yii::$app->response->format = \yii\web\Response::FORMAT_RAW;
       return $pdfcontent;
    } else if (isset($_GET['view'])) {
       $this->render('view', [ 'model' => $model ]);
    }
}
```
If you press the view button everything is fine. But if you press the Print button and the PDF file opens outside the browser (not with the internal pdf viewer), then after this every time you click on the View button the Print button action gets triggered.
This is because the client javascript is generating an hidden input with the "print" value before submitting, and the page does not get refreshed (as it opens outside the broswer)

the incriminated code is in the javascript which creates the hidden input.

**Comment by andrewnester** [comment]
Reproduced in Chrome.
You need to disable Chrome PDF plugin first like this http://chris.dziemborowicz.com/blog/2010/12/12/how-to-disable-chrome's-built-in-pdf-viewer/

After this when you click Print it will download pdf file without page reloading

**Comment by SilverFire** [comment]
@andrewnester that's not a solution.

I the problem is in submit button name. We have a code in [yii.activeForm.js:551](https://github.com/yiisoft/yii2/blob/master/framework/assets/yii.activeForm.js#L581), which searches for a hidden input with name eq to submit button name and creates one, if it does not exist yet. But if the input exists, the script sets its value to the button value.

@tsdogs set the same name but different values for both of your submit buttons and update action to check for the value. Then it will work as expected

**Comment by kritika555** [comment]
can anyone help me with the issue of submit button to be clicked twice. I had more than two submit button with name= submit. What do I need to do in activeForm.js ?
Thanks

**Comment by neovmt** [comment]
@SilverFire Are you sure that the correct solution is to check for submit value, not name?
I tried to use same name but different values: form can be submitted on second click. I also tried to fix this by using input instead of button, no success.
I guess activeForm.js SHOULD NOT add hidden input if input is used.

**Comment by SilverFire** [comment]
@neovmt this issue is old and I do not remember what is going on here.
Could you create a separate issue with your problem detailed description?
