### ISSUE TITLE
Current implementation of file download does not encode UTF8 filenames correctly

### ISSUE THREAD

**Issue by cebe** [yiisoft/yii2#10563]
see https://github.com/yiisoft/yii/issues/2620#issuecomment-20663991

https://github.com/yiisoft/yii2/blob/8f1245553f1b3dcb5b4022780eb83a69f5065f33/framework/web/Response.php#L565

**Comment by andrewnester** [comment]
Hi @cebe 
Could we go for this option? http://stackoverflow.com/a/25704866
I guess it is best one comparing complexity and result

Also we can try smth like http://stackoverflow.com/a/4968835 but it is a little bit more complex

**Comment by cebe** [comment]
@andrewnester if the first option covers the RFC correctly I would use it. seconds looks a bit overcomplicated.

**Comment by andrewnester** [comment]
@cebe actually it doesn't cover RFC2231. I will look for some other implementations of this RFC

**Comment by samdark** [comment]
So the problem is using `Yii::$app->getResponse()->xSendFile()` or `Yii::$app->getResponse()->sendFile()` or via any other file sending method with file names like `中文.txt`. Downloading it with, for example, IE11 won't show correct file name.

The issue could be solved by sending `Content-Disposition` with both fallback-name `filename=x` (for old browsers) and utf-name `filename*=utf-8''x` for newer ones.

fallback-name is known to cause issues if:

- It contains non-printable characters.
- It contains urlencoded characters (starting with `%`).
- It contains path separator characters such as `\` or `/`.

Since input could contain non-ASCII characters, fallback should be obtained by transliterating it.

utf-name causes issues if:

- It contains path separator characters such as `\` or `/`.
- It's not urlencoded.

**Comment by samdark** [comment]
Additionally, if file name isn't specified, file system file name is used which could be in non UTF-8 encoding. In this case non-ASCII characters may be either transliterated or replaced with placeholder such as `_`.

**Comment by samdark** [comment]
@PowerGamer1, @shirase am I missing something?

**Comment by shirase** [comment]
> The issue could be solved by sending Content-Disposition with both fallback-name filename="x" (for old browsers) and utf-name filename*=utf-8''x for newer ones.
Yes, but you need a different name for fallback-name.

**Comment by PowerGamer1** [comment]
@samdark 
> Additionally, if file name isn't specified, file system file name is used which could be in non UTF-8 encoding. In this case non-ASCII characters may be either transliterated or replaced with placeholder such as  _ .

You can't do ANYTHING with "file system file name": neither substitute characters in it nor encode it for use in `filename*` since encoding of provided "file system file name" is not known.

**Comment by samdark** [comment]
> Yes, but you need a different name for fallback-name.

Correct. This name could be obtained by transliteration replacing non-ASCII symbols with `_` or `-`.

> You can't do ANYTHING with just "file system file name": neither substitute characters in it nor encode it for use in filename* since encoding of provided "file system file name" is not known.

`mb_*` functions work well with any multibyte and single byte encoding. ASCII range chars are still single byte in UTF so if we'll choose to leave ASCII chars only and replace everything else with `_` then it could be done no matter what source encoding is.

**Comment by PowerGamer1** [comment]
@samdark 
>  mb_*  functions work well with any multibyte and single byte encoding. ASCII range chars are still single byte in UTF so if we'll choose to leave ASCII chars only and replace everything else with  _  then it could be done no matter what source encoding is i.e. iterate char by char. If character is from ASCII range, leave it. If not — discard it.

Well, apparently under Windows PHP can't deal with native UTF-16 filenames directly - filenames are treated (in `fopen`, etc) as encoded in one of the ANSI codepages. The codes for ASCII characters in ANSI codapages are the same as in ASCII. So yes, I guess you can do the substitution for non-ASCII characters if you rely on the fact that filename can come either as UTF-8 or ANSI. Still this substitution solution without knowing the actual encoding of filename is not ideal since it will produce a sequence of multiple substitution characters for a single 2, 3 or 4-bytes UTF-8 character (i.e. `中文.txt` will become not `__.txt` but `______.txt`) .

**Comment by samdark** [comment]
Yes. That's a drawback, of course. We can use https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseInflector.php#L488 for the purpose so if intl is available, it will generate proper transliteration.

**Comment by PowerGamer1** [comment]
There are many different ANSI codepages and since you don't know in which one exactly the filename is encoded you can't transliterate non-ASCII characters correctly.

**Comment by samdark** [comment]
I think it's handled by intl/ICU internally.

**Comment by PowerGamer1** [comment]
> I think it's handled by intl/ICU internally.

I doubt that. It seems `transliterator_transliterate()` expects its string argument to be in UTF-16:
http://php.net/manual/en/transliterator.transliterate.php

**Comment by samdark** [comment]
It's confirmed that it works well with UTF-8 as well.

**Comment by PowerGamer1** [comment]
@samdark 
> fallback-name
> Causes issues if contains non-ASCII characters with codes less than 32 or more than 126.

This problem is still not fully fixed. In particular, if filename contains a character with US-ASCII code 127 (hex 7f) it is passed unaltered into 'Content-Desposition' HTTP header field (which leads to Apache 500 error AH02430: "Response header '...' value of '...\x7f...' contains invalid characters, aborting request").

**Comment by samdark** [comment]
@PowerGamer1 please open new issue. Thanks!
