### ISSUE TITLE
ActiveRecordInterface::countAll

### ISSUE THREAD

**Issue by lynicidn** [yiisoft/yii2#10571]
/me suggest add static method `countAll` in `yii\db\ActiveRecordInterface`

```php
    /**
     * @param array $condition
     * @return integer
     */
public static function countAll($condition);
```

**Comment by klimov-paul** [comment]
And what should it do?

**Comment by lynicidn** [comment]
return count records based on `static find` query.

**Comment by githubjeka** [comment]
This Interface for the ActiveRecord. 
/me suggest :hocho: 
- delete the methods : `deleteAll`, `updateAll`, `findAll`,
- rename the methods:  `getAttribute($name)` to `findAttribute($name)` or update phpDoc to 
```php
/**
 * @return mixed the attribute value.
 * @throws \yii\base\InvalidParamException
 */
```
instead `* @return mixed the attribute value. Null if the attribute is not set or does not exist.`

**Comment by SilverFire** [comment]
@lynicidn it's not clear for me what is the difference between `count()` and `countAll()`

@githubjeka :open_mouth: it's harsh :)

**Comment by klimov-paul** [comment]
> return count records based on ActiveRecordInterface::find

This does not make any sense. There is no reason for adding extra shortcut methods here.

> delete methods : deleteAll, updateAll, findAll

???
Methods `deleteAll()` and `updateAll()` are necessary. They allows deleting or updating several records performing *single* query.
Methods `findAll()` and `findOne()` are shortcuts, which have been introduced mainly for the IDE type-hinting feature, because they have `@return static` at doc block, while `ActiveQuery` returns `ActiveRecordInterface`.

**Comment by githubjeka** [comment]
For me ActiveRecord is reflection of one row from storage and because I don't accept the word `all`

The `findOne` let it be, but demanding it is as something strange in the interface.

And about `getAttribute($name)`

methods like as `getValueByName($name)` should be get me valid value always. Null - not valid, because better use words `findValueByName($name)`

<sub><sup>P.S. IMHO :)</sup></sub>

**Comment by cebe** [comment]
> For me ActiveRecord is reflection of one row from storage

note the difference between static method and non static:
- The class represents a table
- an object of it represents a row.

**Comment by githubjeka** [comment]
Table is just a place,storage for rows.
The Active Record is a class for working with one row from a table.

Methods that return multiple rows move to ActiveRecordCollection. 

<sub><sup>P.S. IMHO :)</sup></sub>

**Comment by githubjeka** [comment]
Let's lock this issue.
