### ISSUE TITLE
how configure console routes?

### ISSUE THREAD

**Issue by mirkhamidov** [yiisoft/yii2#10585]
I got this simple module https://github.com/mirkhamidov/yii2-console-dbextend
That module just for console
Adding to console config like 
```
'modules' => [
        'dbex' => 'mirkhamidov\dbex\Module',
    ],
```

and it appears in console 
```
- dbex/dbex
    dbex/dbex/drop-all-tables  Drop all tables in existing DB
```

this `dbex/dbex` confusing me, but it works fine
But how to make it not repeated `dbex` twice?
for example
```
- dbex
    dbex/drop-all-tables  Drop all tables in existing DB
```

**Comment by andrewnester** [comment]
@mirkhamidov I guess that's question mainly to developer of https://github.com/mirkhamidov/yii2-console-dbextend

**Comment by mirkhamidov** [comment]
@andrewnester thanks, im developer is myself ;)
Thats why, I cand understand how console routes works.

**Comment by SilverFire** [comment]
GitHub is for bug reports. We are happy to help you on [support forum](http://www.yiiframework.com/forum/) or in gitter room https://gitter.im/yiisoft/yii2. It's always better to text there, unless you are sure it is a Yii2 core problem.

However, here are solutions for you:

### Option 1

Cheat. Register single controller instead of module:

```php
//    'modules' => [
//        'dbex' => 'mirkhamidov\dbex\Module',
//    ],
    'controllerMap' => [
        'ab' => 'mirkhamidov\dbex\console\controllers\DbexController'
    ],
```

### Option 2

Use bootstrap properly. Your module bootstrapping function will be never called, because you didn't define it nor in the app config, neither in composer.json.

Simplify your bootstrap function:

```php
    public function bootstrap($app)
    {
        if ($app instanceof \yii\console\Application) {
            $app->controllerMap[$this->id] = 'mirkhamidov\dbex\console\controllers\DbexController';
        }
    }
```

```php
    'bootstrap' => ['log', 'dbex'],
    'modules' => [
        'dbex' => 'mirkhamidov\dbex\Module',
    ],
```

or

composer.json
```php
    "extra": {
        "bootstrap": "mirkhamidov\\dbex\\Module"
    }
```
