### ISSUE TITLE
GridView and DetailView empty cells

### ISSUE THREAD

**Issue by massimilianomancini** [yiisoft/yii2#10588]
After upgrade to 4b511fb GridView and DetailView stop working. 
Every cell of both GridView and DetailView is shown as empty (no value in red).

**Comment by SilverFire** [comment]
Could you try to checkout to https://github.com/yiisoft/yii2/commit/25138d337c3dee2979dccbf3576451626ae46b54 ?

**Comment by SilverFire** [comment]
And if it works - try https://github.com/yiisoft/yii2/commit/eda1e7b0277098ebca01997d2e72c8f502acb982

**Comment by SilverFire** [comment]
Confirmed, reverted https://github.com/yiisoft/yii2/commit/f72e9d5bcf4642a0fe54ccbc3bd58d7e05e3ff7b
Thank you

**Comment by SamMousa** [comment]
I am totally confused on why this would be desired behavior inside the `ArrayHelper::getValue()` function...

1. The goal of the function is to extract something from that is a collection of key value pairs (array or object).
2. This function now behaves differently for arrays than it does for objects (bad practice, then there should be 2 separate functions instead).

This basically makes the function useless for objects, consider the scenarios:
1. I know I have an object, use: `$object->$attribute` 
2. I don't know if have an object or an array, can't use `ArrayHelper::getValue()` with a default since that will get unpredictable. Calling it without a default will give me a silent `null` when there is a missing key in the array, but if it happens to be an object then it will instead throw an exception.


````
$values = ['a' => 1, 'b' => 2];
ArrayHelper::getValue($values, 'a') === ArrayHelper::getValue((object) $values, 'a')
ArrayHelper::getValue($values, 'c') !== ArrayHelper::getValue((object) $values, 'c')
````

It is unclear for me in which scenario this behavior makes more sense than the previous.
