### ISSUE TITLE
REST access via token and session

### ISSUE THREAD

**Issue by thejahweh** [yiisoft/yii2#10704]
I've encountered a case where I have to give access for a REST method via oauth and session. It works if only one access rule is on this method, but if both are assigned it doesn't work anymore. The problem is described in #4575, but it isn't solved for me, because it must be accessed from both and not only one.

My current approach looks like this:

``` php
public function behaviors()
{
    return ArrayHelper::merge(parent::behaviors(), [
        'authenticator' => [
            'class' => CompositeAuth::className(),
            'authMethods' => [
                ['class' => HttpBearerAuth::className()],
                ['class' => QueryParamAuth::className(), 'tokenParam' => 'access_token'],
            ],
            'except' => ['generate-password'],
        ],
        'access' => [
            'class' => AccessControl::className(),
            'rules' => [
                [
                    'allow' => true,
                    'roles' => ['@'],
                    'actions' => ['generate-password'],
                ],
            ],
            'only' => ['generate-password'],
        ],
    ]);
}
```

With this method the `generate-password` action is accessible via a normal logged in user, but isn't via oauth.

Currently I see two options:
1. Make the method public.
2. Copy the method and use it with another name.

**Comment by cebe** [comment]
> 1. Make the method public.
> 2. Copy the method and use it with another name.

which method?

**Comment by thejahweh** [comment]
@cebe Sorry, that are just options which I could do, so make the `generate-password` method public to all users. I've not done any research, why this is not possible with this two behaviors.

**Comment by lynicidn** [comment]
if u want auth users in all actions except `generate-password` why u write role for guest as
'roles' => ['@'],
need `?`

**Comment by thejahweh** [comment]
@lynicidn auth users should also have access to `generate-password`.

**Comment by lynicidn** [comment]
also or only ?

**Comment by kyrandita** [comment]
For what it's worth I agree with @thejahweh 
if in his example he sets authentication to ? all users can access BUT he can not access Yii::$app->user for logging or other purposes because of the 'except' on the authenticator. This is a problem I've run into on many apps I've done in Yii. This limitation frequently causes duplication of actions just so I can have both a public and "authenticated" version.

If he removes the authenticator then any role type access rules defined by AccessControl are useless (except for actual RBAC, which still works just fine) since it won't allow unauthenticated users to access it even when the rule allows anonymous users.

And allowing only '@' but having the 'except' condition makes the action completely inaccessible as the AccessControl doesn't check for the types of authentication he needs.

I dislike that the Authentication Filters deny access in direct opposition to any AccessControl rules that have been set. @kirill-konshin said something very similar at the end of #4575 more than a year ago. However I understand that implementing such behavior would very likely break backwards compatibility unless you released a whole new set of authorization filters that only set the user if the AccessControl filter is used and maybe follow the existing behavior IFF AccessControl is not being used. And likely since filters wouldn't easily be made aware of each other you'd probably just make an AccessControl compatible version that defers all authorization to the access control.

I accept that my knowledge in security matters is lacking and if there is some solid reason why this isn't as safe I'm willing to learn. But I think the TLDR of his point would boil down to "the authenticator is currently performing authorization tasks, why?"

**Comment by kyrandita** [comment]
On second look I think I misread the thread. but I think what I propose would still fix the issue.
I have the problem of wanting the user object in an action that doesn't need it to be accessible.
From my latest reading of the problem whatever authenticator is getting the user object from session is doing it's job just as I suggest the other filters should. but because the user is logged in by session and not one of the other methods from the CompositeAuth filter they are rejected by the CompositeAuth filter doing authorization tasks and not letting the AccessControl handle it.
Correct me if I'm wrong

**Comment by riyaskp** [comment]
@kyrandita I think the 'optional' parameter will solve the issue you mentioned.
[](http://www.yiiframework.com/doc-2.0/yii-filters-auth-authmethod.html#$optional-detail)
