### ISSUE TITLE
Suggestion: AttributeBehaviour callable to get value should contain the attribute name.

### ISSUE THREAD

**Issue by Locustv2** [yiisoft/yii2#10722]
When using AttributeBehavior, sometimes we need to assign the values differently for each attributes.

The callable to obtain the currently contain only the event and it would be great if we could get the attribute name also.

```php
public function behaviors()
  {
      return [
          [
              'class' => AttributeBehavior::className(),
              'attributes' => [
                  ActiveRecord::EVENT_BEFORE_INSERT => 'attribute1',
                  ActiveRecord::EVENT_BEFORE_UPDATE => 'attribute2',
              ],
              'value' => function ($event) { /* Contains only the event */
                  return 'some value';
              },
          ],
      ];
  }
```
Maybe we could add a second parameter, `$attribute`, to the callable. This would be really helpful

**Comment by SilverFire** [comment]
The `AttributeBeavior` is designed to set the same value for one or more attributes. That's why the `getValue()` method, calls the closure only once.

As far as I see, we should not implement this idea because it leads to bunches of if conditions inside the closure and causes the logical break of BC (developers could design the closure to be executed only once per event).

I'd prefer to describe different instances of `AttributeBehavior` for different attributes and have two different clear callbacks. 

I'm closing the issue, but if you have other arguments - feel free to post them.
