### ISSUE TITLE
Yii2 renderAjax() clientSide validation doesn't work

### ISSUE THREAD

**Issue by Alijon** [yiisoft/yii2#10754]
I have a form. I want to render part of form parametrs with ajax,  when selected category
**Controller.php**
```
public function actionCreate()
{
        $model = new Offers();
        $param = new Param();
        if ($model->load(Yii::$app->request->post()) && $param->load(Yii::$app->request->post())) {
            $isValid = $model->validate();
            $isValid = $param->validate() && $isValid;
            if ($isValid) {
                $model->save();
                $param->save();
                    return $this->redirect(['view', 'id' => $offer->id]);
            }
        }
        return $this->render('create', [
            'model' => $model,
            'param' => $param
        ]);
    }
```
**_form.php**
```
$form = ActiveForm::begin([
    'options' => [
        'enableAjaxValidation' => true,
        'enableClientValidation' => true,
    ]
]); 
$form->field($model, 'category_id')->dropDownList($category, [
'onchange'=>'
    $.get( "'.Url::toRoute('/controller/params').'", { id: $(this).val() } )
           .done(function( data ) {
                     $( "#offers-param-content" ).html( data );
           }
     );'
]);
<div id="offers-param-content"></div>
<?= Html::submitButton('Create', ['class' => 'btn green']) ?>
<?php ActiveForm::end(); ?>
```
**Controllers action render params**
```
public function actionParams($id)
{
    $param = new Param();
    $attributes = EavAttribute::find()->where(['category_id'=>$id])->all();
    $this->renderAjax('_params', ['param' => $param, 'attributes' => $attributes];
}
```
**_params.php**

```
foreach($attributes as $attribute){
    echo Html::activeTextInput('text', $param, $attribute->name);
}
```
ActiveForm attributes validation work, but rendered params doesn't validated.

**Comment by dynasource** [comment]
hi Alijon, nice to see you are using Yii for your project. Please keep in mind that this is an issue tracker which is meant for issues only. I dont think you want to disturb the Yii developers with support questions right? 

With respect to your issue. Perhabs its because you are not rendering the output of $this->renderAjax by either :
- return $this->renderAjax()
- or echo $this->renderAjax

**Comment by Alijon** [comment]
Thank you for your answer.  I added **echo**
```
public function actionParams($id)
{
    $param = new Param();
    $attributes = EavAttribute::find()->where(['category_id'=>$id])->all();
    echo $this->renderAjax('_params', ['param' => $param, 'attributes' => $attributes];
}
```
Client side validation works only for activeForm fields but rendered params not validated with js.

**Comment by SilverFire** [comment]
Duplicates #1422

That's because the client side validation does not know anything about your new field and its validation rules. You must register each field with JS function.

```
$form.data('yiiActiveForm').add(options);
```

Options is an array, its design is defined in [yii.activeForm.js](https://github.com/yiisoft/yii2/blob/master/framework/assets/yii.activeForm.js#L130) and is normally generated by [ActiveFiled::getClientOptions()](https://github.com/yiisoft/yii2/blob/master/framework/widgets/ActiveField.php#L691).

The tricky thing for you is that you have `ActiveForm` in order to render `ActiveField`, but `ActiveForm` will echo unnecessary for you `<form>` tag and will register some redundant JS. I think you can sole it with creating your own `ActiveForm` and method overriding.

I see that currently there is no manual how to do it well, so if you caught the idea, can implement it and contribute the manual - we will be thankful.
