### ISSUE TITLE
yii2 checkbox always submit 0 in POST

### ISSUE THREAD

**Issue by dangi-kuldeep** [yiisoft/yii2#10807]
If a field value is 0 while rendering checkbox its value is always renderd as value="1" in html coz of this line number 712 **$value = array_key_exists('value', $options) ? $options['value'] : '1';** on class **BaseHtml.php** in helpers.
now if you will select the checkbox its value will be set to 0 & if you didnt select the checkbox , hidden field value will be submitted but in both the cases submitted value will be 0, there is no way value again could be set to 1

**Comment by cebe** [comment]
please show the code you are using, what you describe makes no sense to me, `array_key_exists` does not have anything to do with checking for 0.

**Comment by martynshutt** [comment]
If you're binding already submitted values, shouldn't you be using ActiveFields? `Html::checkbox()` will behave exactly the way you have described it. Using ActiveFields as associated Models will avoid all of these issues.

> "now if you will select the checkbox its value will be set to 0"

This absolutely shouldn't happen. Checking the checkbox simply applies the checked attribute to the input tag, which then overrides the hidden field's default value of 0 to become 1 when it's submitted to the server.

**Comment by dangi-kuldeep** [comment]
I am rendering 
                    echo $form->field($model, 'is_active')->checkbox();
a field `is_active` of type tinyint possible values 0 & 1 for a specific record with record value in db for is_active is zero, rendered html through this code is 

<div class="form-group field-document-is_active">

<input type="hidden" value="0" name="Document[is_active]"><label><input type="checkbox" value="1" name="Document[is_active]" id="document-is_active"> Active</label>

<div class="help-block"></div>
</div>

Now if I check the checkbox, value of checkbox get changed to 0 and obviously submitted value will also be 0, if I didn't  check the checkbox hidden field value be send which is also 0. so in any case I am not able to POST checkbpx value equal to 1. I am doing something wrong here ?

**Comment by martynshutt** [comment]
> Now if I check the checkbox, value of checkbox get changed to 0

I think you're misunderstanding how the checkbox works. It's not the `value` that changes. It's the "checked" attribute. The value of the checkbox will always be 1. If the checkbox is `checked`, the server will see the value if one. If the `checkbox` is not checked, it will see the hidden input value of 0 instead.

I think you need to check if you're properly validating the `'is_active'` in your model, because your problem doesn't appear to be with the checkbox. The behavior you're describing is not how it functions. The `value`of the checkbox is always `1`.

**Comment by dangi-kuldeep** [comment]
But what happening here is, I am always getting 0 in Post for is_active field irrespective of checkbox is checked or not, I am on linux machine using yii2 advance template, browser is mozilla, PHP version 5.6

**Comment by dangi-kuldeep** [comment]
Problem is not only on my , same is happening on my server (AWS), on my team mates machine.

**Comment by TerraSkye** [comment]
has this todo with the hidden field that is also posted? for the "uncheckked" value?

**Comment by dangi-kuldeep** [comment]
I guess it all has to do with the how checkbox html is rendered, for a specific records with `is_active` = 0; in rendered checkbox I am seeing its `value="1"` and checkbox is unchcked.

**Comment by martynshutt** [comment]
I would suggest you post this question on Stack Overflow with the related MVC code, as it's very difficult to determine if this is an actual bug in Yii, a problem with your server, or something in your code. We're not really getting any closer to figuring out what the problem is. I'll be happy to take a look at it on Stack Overflow. Just post it with the same question title and let me know.

**Comment by dangi-kuldeep** [comment]
Already posted it on the same day , sharing the url
http://stackoverflow.com/questions/35335548/yii2-checkbox-not-working-its-always-submit-0-in-post/35335731

**Comment by cebe** [comment]
closing until someone finds a reproduceable bug in the framework.
