### ISSUE TITLE
tooBig does not  work on validation model

### ISSUE THREAD

**Issue by alemedinam** [yiisoft/yii2#10819]
In my model have the next code:

```php
public function rules()
    {
        return [
            [['LlenadoPorcentuado', 'CantidadPruebas'], 'required'],
            ['CantidadPruebas', 'integer', 'max' => \Yii::$app->params['maxPruebasLaboratorio'], 'tooBig' => 'La {attribute} no puede ser mayor a {max}']
        ];
    }
```
But when the value introduced for 'CantidadPruebas' is over \Yii::$app->params['maxPruebasLaboratorio']  it shows the default value in english. Is there any bug?

**Comment by cebe** [comment]
what exactly is shown in english?

**Comment by alemedinam** [comment]
The message is:

"Please select a value that is no more than 25"

Of course my param maxPruebasLaboratorio = 25

**Comment by VirtualRJ** [comment]
I believe to use the model rules you should use `Html::activeInput` instead of `Html::input`. Besides that I can't find anything in the documentation about a 'number' type input. The accepted values for Html::input are `text` and `password`.

For the docs of activeInput: http://www.yiiframework.com/doc-2.0/yii-helpers-basehtml.html#activeInput()-detail

**Comment by alemedinam** [comment]
Well it was a html validation for a number input.  

I solved changing like this:

```php 
<?= Html::input('number', 'Configuracion[CantidadPruebas]',  $model->CantidadPruebas, 
                    ['min' => 1, 'max' => \Yii::$app->params['maxPruebasLaboratorio'], 'class' => "form-control", 'id' => 'configuracion-cantidadpruebas', 'oninvalid' => "setCustomValidity('No puede ser mayor a ".\Yii::$app->params['maxPruebasLaboratorio']."')"]); ?>
```

Thanks at all
