### ISSUE TITLE
Documentation for rbac

### ISSUE THREAD

**Issue by vladim1** [yiisoft/yii2#10930]
In the documentation for the rbac rules we have the following code:
```php
$auth = Yii::$app->authManager;

// add the rule
$rule = new \app\rbac\AuthorRule;
$auth->add($rule);

// add the "updateOwnPost" permission and associate the rule with it.
$updateOwnPost = $auth->createPermission('updateOwnPost');
$updateOwnPost->description = 'Update own post';
$updateOwnPost->ruleName = $rule->name;
$auth->add($updateOwnPost);

// "updateOwnPost" will be used from "updatePost"
$auth->addChild($updateOwnPost, $updatePost);

// allow "author" to update their own posts
$auth->addChild($author, $updateOwnPost);
```
and then we check if user has the update permission:
```php
if (\Yii::$app->user->can('updatePost', ['post' => $post])) {
    // update post
}
```
So, shouldn't the code
```php
// "updateOwnPost" will be used from "updatePost"
$auth->addChild($updateOwnPost, $updatePost);
```
be replaced with
```php
// "updateOwnPost" will be used from "updatePost"
$auth->addChild($updatePost, $updateOwnPost);
```
as ```updatePost``` should contain ```updateOwnPost``` and not backwards?

**Comment by bizley** [comment]
I believe the hierarchy and the comment is right here so this

    // "updateOwnPost" will be used from "updatePost"
    $auth->addChild($updateOwnPost, $updatePost);

is proper. It might be confusing because comment describes the functionality shown in the image and this is more "the flow" of access checking rather than hierarchy (while addChild takes $parent, $child parameters in that order).
Hierarchy is quite nice described here http://www.yiiframework.com/wiki/136/getting-to-understand-hierarchical-rbac-scheme (Yii 1.1 but still valid).

If I'm wrong here please let me know.

**Comment by samdark** [comment]
Docs are correct.
