### ISSUE TITLE
Yii2 RESTful response to OPTIONS ignores only/except, does not list DELETE

### ISSUE THREAD

**Issue by matthewdaize** [yiisoft/yii2#10949]
Yii2 supports `OPTIONS` to return back the available RESTful interactions on a route. it returns a response header `Allow` with the available commands.

This however displays commands which are not allowed (and omits DELETE) due to `only` or `except` within the defined routes. I also cannot find anywhere in the documentations that says this is intended behaviour, so I'm raising this issue incase of this being unintended operation. Please flag this issue if my assumption is incorrect.

## Steps to reproduce:

Perform an OPTIONS on `http://<fqdn>/users`, response header:
   `Allow: GET, POST, HEAD, OPTIONS`

Now, configure the UrlRoute so that:
   `['class' => 'yii\rest\UrlRule', 'controller' => ['v1/user'], 'except' => ['delete']]`
Perform the same OPTIONS on `http://<fqdn>/users`, response header:
   `Allow: GET, POST, HEAD, OPTIONS`
Attempt a `GET` and it works as expected returning a 200.
Attempt a `DELETE` and it returns `405: Method Not Allowed` as expected.

Lastly, configure the UrlRoute so that:
   `['class' => 'yii\rest\UrlRule', 'controller' => ['v1/user'], 'only' => ['delete', 'options']]`
Perform the same OPTIONS on `http://<fqdn>/users`, response header:
   `Allow: GET, POST, HEAD, OPTIONS`
Attempt a `GET` and it returns `405: Method Not Allowed` as expected.
Attempt a `DELETE` and it works as expected returning a 200.

**Comment by SilverFire** [comment]
Thank you for the detailed and well-formatted issue. It's a pleasure to read :)

The options action is handled by [OptionsAction](https://github.com/yiisoft/yii2/blob/master/framework/rest/OptionsAction.php).
Since the same action can satisfy multiple routing rules, and you can configure VerbFilter in your controller, it's hard to guess the allowed HTTP methods list.

You must configure the list of available methods manually for your controller by overriding the `OptionActions`'s config in the `actions()` method of controller.
