### ISSUE TITLE
ability to apply a specific migration without reverting/marking migrations  ?

### ISSUE THREAD

**Issue by duynguyen0511** [yiisoft/yii2#11001]
Hi all, 

The migration I want to apply simply add new entry to several tables in database and it was applied already. When I cleansed the data, I accidentally remove it. Therefore, I just want to re-apply this migration forcefully. 

```php
php yii migration/to 160123_002810

Total 9 migrations to be reverted:

Revert the above migrations? (yes|no) 
```

Yii2 allows me to do this if I want to revert 9 migrations after it. I dont want to revert any migrations who know what could happen.

**Comment by samdark** [comment]
Migrations concept should not allow that because migrations should be sequential. Would not support that. Developer should never touch database directly.

**Comment by Faryshta** [comment]
I think you need fixtures not migrations http://www.yiiframework.com/doc-2.0/guide-test-fixtures.html

**Comment by rikipm** [comment]
> Migrations concept should not allow that because migrations should be sequential. Would not support that. Developer should never touch database directly.

I understand that its bad practice, but this dont mean that developer dont need this functionality. Its regular task when you want to run invalid non-working migrations, for example in project where no one cares about it.

Yes, in this case correct solution will be refactoring, but I think that developer must choose himself, need he refactoring right now or he may be limited to this crutch temporary.

According to this logic unit-testing should not be used, because ideally developer must write code without bugs.

**Comment by samdark** [comment]
@rikipm would you please clarify "Its regular task when you want to run invalid non-working migrations, for example in project where no one cares about it"? I do not get it.

**Comment by snathan9** [comment]
Ideally you would never break a sequence, but there are situations where you decided to mark a migration as completed and moved on, but want to come back later and complete it.  This happens to me when I want to rerun data migrations which includes a refresh of data of certain reference tables.

**Comment by schmunk42** [comment]
@snathan9 As @samdark said, migrations need to be sequential.

For your use-case either 
- `mark some-point-in-time`, `up 1`, `mark latest` or 
- rename your data migration to the current day/hour an run it

**Comment by snathan9** [comment]
Thank you schmunk. However, these require changing the migration script. Sometimes in an environment, far away from development, or even production, we need to refresh a migration. And this may be required in only that one environment. I only ask because I would image (hopefully correctly) that a feature to simply run a given migration may not be that hard to implement.

**Comment by schmunk42** [comment]
@snathan9 Just do not rely on migrations for your use-case. IMHO it would be bad practice, if you could just re-apply any migration, they are just not meant to be used in such a way.

You can use fixtures or plain SQL, like so:
https://github.com/dmstr/yii2-db/blob/febb1ea2322d2b909213b2d4956a2605d8e8b656/console/controllers/MysqlController.php#L410-L431

Or - **use at your own risk** - remove the migration entry from `app_migration` table.

**Comment by snathan9** [comment]
I agree that this is a one-off request. But none the less, sometimes required and I would rather run a command than complete a few manual steps to achieve my adhoc need. I started looking into BaseMigrateController Class and it seems easy enough to update.  Question is, before I spend time on it, would it be accepted if I create this feature?

**Comment by snathan9** [comment]
On further thoughts about it, I think all that is required is a counter to the "mark" option - say "unmark".  That will serve the purpose of reserving an accidental mark - without having to tinker with the database record. Providing option to undo a mistake is always a good feature. It will also allow running the said migration again.

**Comment by schmunk42** [comment]
> Providing option to undo a mistake is always a good feature. It will also allow running the said migration again.

If your migrations are done right you can use `yii migrate/redo 1`.

PS: For your use-case you might want to look into `migration-path` and `migration-table`.
