### ISSUE TITLE
Why is not supported in the Migration tinyint

### ISSUE THREAD

**Issue by MittWillson** [yiisoft/yii2#11049]
Why is not supported in the Migration tinyint

**Comment by mdmunir** [comment]
```php
        $this->createTable('{{%my_table}}', [
            'id' => $this->primaryKey(),
            'other' => 'tinyint not null',
        ]);
```

**Comment by MittWillson** [comment]
@mdmunir I think do 
$this->createTable('{{%my_table}}', [
            'id' => $this->primaryKey(),
            'other' => $this->tinyint()->notNull(),
        ]);

**Comment by SilverFire** [comment]
This data type exists in MySQL only, therefore we did not create a shortcut for it.

**Comment by thiagotalma** [comment]
@SilverFire  then what about creating a generic method, where we can tell the type and length?
```PHP
$this->createTable('{{%my_table}}', [
            'id' => $this->primaryKey(),
            'other' => $this->nameForGenericColumnCreator('tinyint', 3)->notNull(),
        ]);
```

It's bad not to have a specific type because when we make a schema synchronization always accuses fails because the tinyint field.

Simply ignore their existence should not be the best option.

I believe that other DBMS must have the same problem of specific types and would be resolved with this general solution.

Cheers!!

**Comment by Faryshta** [comment]
@thiagotalma 

'other' => (new yii\db\ColumnSchemaBuilder('random', 3, $this->db))->otherMethods(),

**Comment by asmodai1985** [comment]
tinyint() is useful when i use mysql。 i write code
like 'tinyint not null' ,then if i want use it for other database,i shoud write   like this everywhere
`$this->db->driverName === 'mysql'?'tinyint not null' :$this->smallInt()->notNull()`

**Comment by chen6850a1** [comment]
$this->tinyInteger(1)->unsigned()
