### ISSUE TITLE
bower path changed

### ISSUE THREAD

**Issue by easelify** [yiisoft/yii2#11074]
```
 // Yii::setAlias('@bower', $this->_vendorPath . DIRECTORY_SEPARATOR . 'bower');
Yii::setAlias('@bower', $this->_vendorPath . DIRECTORY_SEPARATOR . 'bower' . DIRECTORY_SEPARATOR . 'bower-asset');
```

**Comment by SilverFire** [comment]
It's not, for sure.

Duplicates https://github.com/yiisoft/yii2/issues/10554, https://github.com/yiisoft/yii2/issues/9794
This problem was [discussed many times](https://github.com/yiisoft/yii2/issues?q=is%3Aissue+%27The+file+or+directory+to+be+published+does+not+exist+is%3Aclosed). 

Check out the solution suggested by @cebe in [this comment](https://github.com/yiisoft/yii2/issues/10554#issuecomment-171623038)

Fix your installation of FXP plugin and all will be ok. It might be a little tricky, but it's solvable

**Comment by easelify** [comment]
Thanks! @SilverFire
