### ISSUE TITLE
Module getInstance() doesn't work in unit testing?

### ISSUE THREAD

**Issue by nsanden** [yiisoft/yii2#11100]
It is recommended to use `MyModuleClass:getInstance()` in order to get the module instance you're currently running which makes sense because the end user could change the module ID

However, in unit testing a method which calls `MyModuleClass::getInstance()` I get `null` returned from it.

It isn't until I use `\Yii::$app->getModule('forum');` that it then works in my unit test.

Is this something that can be fixed or is it just the way it is?

**Comment by nsanden** [comment]
Here is how to duplicate:

/myproject/components/SomeClass.php
```php
class SomeClass {
   public function someMethod() {
      $module = MyModuleClass::getInstance();
      return $module->id;
   }
}
```

/myproject/tests/codeception/unit/SomeClassTest.php
```php
public function testSomeMethod() {
   (new SomeClass())->someMethod();
}
```

error: `Trying to get property of non-object`

**Comment by klimov-paul** [comment]
This is expected behavior.
See the docs: https://github.com/yiisoft/yii2/blob/master/framework/base/Module.php#L141-L145
It says:

> Returns the currently **requested** instance of this module class.

Which means it returns the module instance, which respond the current request.

In unit test you can bypass this restiction using `Module::setInstance()`:
https://github.com/yiisoft/yii2/blob/master/framework/base/Module.php#L158
