### ISSUE TITLE
count() on Query with orderBy()

### ISSUE THREAD

**Issue by zuozp8** [yiisoft/yii2#11122]
I have relation defined like

``` php
class Company {
    public function getAddresses()
    {
        return $this->hasMany(Address::class, ['company_id' => 'id'])->orderBy('address_id');
    }
}
```

as i always want addresses of companies ordered in the same way

Unfortunately I can't do `$company->getAddresses()->count()` because psql is complaining `[42803] ERROR: column "address.address_id" must appear in the GROUP BY clause or be used in an aggregate function`

Check for orderBy presence could be added here https://github.com/yiisoft/yii2/blob/master/framework/db/Query.php#L392

**Comment by Alex-Code** [comment]
Do you have the debug toolbar enabled?
Could you show what SQL gets generated?

**Comment by zuozp8** [comment]
sure, its:
```sql
SELECT COUNT(*) FROM "address" WHERE "company_id"='17e49540-d3e7-11e4-b3ef-53b449010d08' ORDER BY "address_id";
```

**Comment by SilverFire** [comment]
You can not use order by with `count()`.

```php
$company->getAddresses()->orderBy([])->count();
```

**Comment by zuozp8** [comment]
@SilverFire i thought it should handled like #8068

**Comment by SilverFire** [comment]
Hmm... Yes.

**Comment by herroffizier** [comment]
It seems that check for non-empty ```offset``` and ```limit``` must be also added here https://github.com/yiisoft/yii2/blob/master/framework/db/Query.php#L392. I think that ```count()``` should return actual count of records that may be returned by ```all()``` but as for now it is not working that way.

For example, we expecting to get 200 or less records from this query:
```php
$query = (new \yii\db\Query())->from('offer')->offset(0)->limit(200);
```
But following code will fail when table have more than 200 records in it, because ```$query->count()``` will return total count of records in table.
```php
assert(count($query->all()) == $query->count());
```

**Comment by SilverFire** [comment]
Resolved by https://github.com/yiisoft/yii2/commit/25e6eb04a5e23203cd6e5da8db427afe5a46f5bb

**Comment by SilverFire** [comment]
Thank you for the report!
