### ISSUE TITLE
Repeated loading jquery file

### ISSUE THREAD

**Issue by hiscaler** [yiisoft/yii2#11219]
```php
'assetManager' => [
            'bundles' => [
                'yii\web\JqueryAsset' => [
                    'sourcePath' => null, // do not publish the bundle
                    'js' => [
                        '/js/jquery.min.js',
                    ]
                ],
            ],
        ],
```
in view file, write it
```php
  $this->registerJsFile($baseUrl . '/jquery.treetable.js', [
        'depends' => ['\yii\web\JqueryAsset']
   ]);


```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      |  2.07
| PHP version      | 5.5
| Operating system | Win7

**Comment by SilverFire** [comment]
What do you expect and what happens indeed?

**Comment by hiscaler** [comment]
Expect jquery.js only reload once. but current reload two times. is `/js/jquery.min.js` and '/web/assets/23232a3/jquery.js'

**Comment by SDKiller** [comment]
@hiscaler 

This is because of starting backslash in your `depends` ```'\yii\web\JqueryAsset'```

**Comment by samdark** [comment]
Yes. I think it should be done. It's not the first time I see the issue.

**Comment by SilverFire** [comment]
This thing is documented explicitly in [View::registerAssetBundle()](http://www.yiiframework.com/doc-2.0/yii-web-view.html#registerAssetBundle()-detail) method's PHPDoc.



> BTW, may be sanitize unnesessary extra slashes in AssetManager like it is done in many other places across the framework?

Since there is no single entry point, we need to add `ltrim($name, '\\')` in 10 to 15 places all over the code. Not only `AssetManager` reads `depends` property, it is also done by `AssetController`, `View` and, probably, in some 3rd party extensions. I don't like the idea of copy-pasting this line everywhere it is possible.

The best way will be to change `AssetBundle::depends` property visibility to `private` and sanitize slashes in public setter, but this change is a BC break and I don't like it as well.

Since PHP 5.5 we have magic constant `::class` and it is a good replacement for our `Object::className()` because it does not need class autoloading, gives better code highlighting and navigation in IDE.

This issue is about misconfiguration and I tend to do not think that we must change something here.

**Comment by SilverFire** [comment]
Resolved by moving to `::class` instead of `::className()` in 2.1
