### ISSUE TITLE
I turn validation though Ajax, does not work client validation

### ISSUE THREAD

**Issue by magvan** [yiisoft/yii2#11228]
### What steps will reproduce the problem?

```php
$form = ActiveForm::begin([
    'id' => 'contact-form',
    'enableAjaxValidation' => true,
]);
echo $form->field($model, 'email');
```

### What is the expected result?

Tutorial: It will trigger an AJAX request in the background to validate the input while keeping the same user experience as the regular client-side validation.

### What do you get instead?

Client validation does not work. Can enter the an email in the wrong format. Immediately a request is sent to the server side.

### Additional info

| Yii 2.0.7      | 
| PHP 5.4      | 
| Ubuntu |

**Comment by SilverFire** [comment]
> Immediately a request is sent to the server side.

What kind of request?

**Comment by magvan** [comment]
Ajxa on server

**Comment by SilverFire** [comment]
To the validation URL?

**Comment by magvan** [comment]
yes

**Comment by SilverFire** [comment]
It's expected. Do you handle validation request on the server side correctly?

**Comment by magvan** [comment]
The first validation on the client side. second validation on the server side. But the first does not work, just running second.

**Comment by SilverFire** [comment]
What validation rule is applied to email?

**Comment by magvan** [comment]
```public function rules()
{
    return [
        [['name'], 'required'],
        ['email', 'email'],
    ];
}```

**Comment by dizeee** [comment]
```js
if (this.validate) {
    // This is the client side validation.
    this.validate(this, getValue($form, this), msg, deferreds, $form);
}
if (this.enableAjaxValidation) {
    // This will trigger AJAX validation later.
    needAjaxValidation = true;
}
// ...
if (needAjaxValidation) {
    // ... AJAX validation.
} else {
    // This displays client side validation messages.
    updateInputs($form, messages, submitting);
}
```
So client side validation is performed if it's enabled but the result is never used if AJAX validation is enabled as well. While this logic isn't quite straight forward, I don't see a simple yet consistent way to combine client and ajax validation, mainly because of the possibility to display more than one error message for an attribute. It could be done this way:
```js
if (this.validate) {
    this.validate(this, getValue($form, this), msg, deferreds, $form);
}
if (msg.length === 0 && this.enableAjaxValidation) {
    needAjaxValidation = true;
}
```
but if we want to display multiple validation errors for an attribute (`\yii\validators\Validator::$skipOnError` is set to false) it becomes quite non-trivial to determine whether to continue with AJAX validation after client side validation or not, as well as to combine client side validation error messages with AJAX validation ones.

Another possible solution is to restrict one-way validation to avoid the confusion. This one won't break current behavior:
```js
if (this.enableAjaxValidation) {
    needAjaxValidation = true;
}
else if (this.validate) {
    this.validate(this, getValue($form, this), msg, deferreds, $form);
}
```
Either way it should be explicitly documented.

**Comment by phuczeero** [comment]
This problem still exist in 2.0.12, my client side validation work fine when blur, change input, but sending ajax request when submitting although all required fields are invalid.

**Comment by samdark** [comment]
@phuczeero should be another problem that is alike. This one was fixed. Please open new issue with details on how to reproduce the issue.
