### ISSUE TITLE
\yii\rbac\DbManager getRolesByUser() ignores defaultRoles

### ISSUE THREAD

**Issue by vercotux** [yiisoft/yii2#11230]
It would make sense for [getRolesByUser()](https://github.com/yiisoft/yii2/blob/049ea37f778fae576d10835c48b476364a457436/framework/rbac/DbManager.php#L454) to also return the roles specified inside `defaultRoles` parameter, because logically every user should have those roles.

**Comment by samdark** [comment]
Agree.

**Comment by Oxyaction** [comment]
I can see the following problem implementing this feature:

Usually defaultRoles are implicitly given to the all users but, in fact common practice is that such a roles are used with some rules and that rules may require some context params that are passed as 3rd param `Rule::execute()`. So simple doing something like in:

`PhpManager::getRolesByUser($userId)`
```php
$deafultRoles = array_filter($this->defaultRoles, function($role) {
  return $this->checkAccess($userId, $role);
})
```

will make no sense due to lack of `$params` that should be passed to `checkAccess`.
any ideas @samdark ?

**Comment by samdark** [comment]
Nope. I don't have any ideas about getting it right in all contexts in this case...
