### ISSUE TITLE
[proposal] Static late-bound action name.

### ISSUE THREAD

**Issue by Kolyunya** [yiisoft/yii2#11249]
My proposal is related to the `yii\base\Action` class and it's usage.
When we add actions to controllers via the `yii\base\Controller::actions()` method it's a common practice to specify the action class name via the `Action::className()` method in order to eliminate the usage of magic strings and to improve refactoring capabilities.
The problem is that we still have magic strings defining action names. I propose to implement the static late-bound `yii\base\Action::name()` method which will tell the action name by it's class name and allow us to use the following syntax:
~~~php
public function actions()
{
    return [
        MyAction::name() => MyAction::className(),
    ];
}
~~~
This will improve the quality of our controllers code and will not break backward compatibility.
I can make a pull request if you approve my proposal.

**Comment by mdmunir** [comment]
For me, prefer using `'page' => 'yii\web\ViewAction'` instead of `'page' => ViewAction::className()`.
Why? Beacuse i dont need to load `ViewAction` class when my request not to action page.

**Comment by SilverFire** [comment]
Thank you for your idea and attention to Yii framework.

@mdmunir is right, `::className()` forces PHP to load the class, but since PHP 5.5 we can use default constant `::class` (like `ViewAction::class`) which does not require class loading. 

Using of static function or even property of the `Action` class to build `actions()` array WILL load all possible actions, that will slow down your application.
You can do it in your own project, if you feel that you need it, but we are not going neither to recommend it in our guide nor include possibility to the core `Action` class just for performance reasons.

**Comment by Kolyunya** [comment]
@SilverFire thank you for your response. That's the classic example of a premature optimisation. You are forcing poor programming practices which lower the code quality significantly in exchange for some theoretical performance improvements.
What is the overhead of suggested approach in milliseconds for say ten medium-sized actions? I've made a series of tests and in my environment the answer is zero. Those action classes are cached by the OPcache which gives zero overhead in procession time (though there is some memory overhead).
