### ISSUE TITLE
fatal error throwed when use GroupUrlRule and rest UrlRule

### ISSUE THREAD

**Issue by lichunqiang** [yiisoft/yii2#11579]
### What steps will reproduce the problem?

I init the api module rules like this:

```
\Yii::$app->urlManager->rules[] = new \yii\web\GroupUrlRule([
    'ruleConfig' => [
        'class' => \yii\rest\UrlRule::class,
    ],
    'rules' => [
        ['controller' => ['api/tweet']]
    ]
]);
```

when request `/api/tweets`, throwed an exception:

```
Unknown Property – yii\base\UnknownPropertyException

Getting unknown property: yii\rest\UrlRule::name
```

I find that caused by https://github.com/yiisoft/yii2/blob/master/framework/web/CompositeUrlRule.php#L51

the rule instance is `yii\rest\UrlRule`, but used as `yii\web\UrlRule`

### What is the expected result?

Can used normally.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8
| PHP version      | 5.6.19
| Operating system | win8

**Comment by tunecino** [comment]
As far as I know [\yii\web\GroupUrlRule](http://www.yiiframework.com/doc-2.0/yii-web-groupurlrule.html) is about grouping `yii\web\UrlRule` instances under a commun **$prefix**. But `yii\rest\UrlRule` itself is about using controller names as input to build their related `yii\web\UrlRule` instances. those rules should be hold at its parent `CompositeUrlRule::rules` and the `yii\rest\UrlRule` also has a **$prefix** property which does the same as `\yii\web\GroupUrlRule`. So I'm not sure if it make since to use `GroupUrlRule` with `yii\rest\UrlRule`.

**Comment by lichunqiang** [comment]
> do you have any particular use case that can't be solved using yii\rest\UrlRule::prefix ?

Not yet.

What i want  to do is group the url rules for the rest api. generally, it  works after commented the log code.

**Comment by tunecino** [comment]
I think `GroupUrlRule` propose is to group many web rules. rest rules is already many web rules.
here is an example using `yii\rest\UrlRule::prefix` to group them : https://github.com/yiisoft/yii2/issues/9474#issue-101950485.

**Comment by lichunqiang** [comment]
So i done a wrong way. Thank you very much.
