### ISSUE TITLE
Unique validation rule getting skipped while form submission

### ISSUE THREAD

**Issue by turalsprofile** [yiisoft/yii2#11754]
### What steps will reproduce the problem?
Unique validation rule doesn't work at all: 

`  [['phone'], 'unique'],`

Yii2 just bypasses this validation rule and tries to insert values. 

Here is create SQL of table:

```
SET NAMES utf8;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
--  Table structure for `EGCampaign`
-- ----------------------------
DROP TABLE IF EXISTS `EGCampaign`;
CREATE TABLE `EGCampaign` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `firstname` varchar(255) NOT NULL,
  `lastname` varchar(255) NOT NULL,
  `phone` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `countryID` int(10) unsigned DEFAULT NULL,
  `promoCode` varchar(255) DEFAULT NULL,
  `createdAt` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` datetime DEFAULT NULL,
  `reported` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk2` (`email`),
  UNIQUE KEY `uk3` (`phone`),
  UNIQUE KEY `uk1` (`promoCode`),
  KEY `countryID` (`countryID`),
  CONSTRAINT `FC_FK1` FOREIGN KEY (`countryID`) REFERENCES `Country` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1090 DEFAULT CHARSET=utf8;

SET FOREIGN_KEY_CHECKS = 1;
```
Here is the model:
https://gist.github.com/anonymous/0886dd56b72c270b0c38cca08b040e16

And here is the controller:
```
            $model = new EGCampaign();
            $model->promoCode = Yii::$app->security->generateRandomString(4);
            $model->load(Yii::$app->request->post());

            if ($model->validate() && $model->save()) {
                $result = "<h1>" . Yii::t("campaign", "Well done! Please, check your mailbox.") . "</h1>";
            } else
                $result = HTML::errorSummary($model,
                    [
                        'class' => "error-summary"
                    ]);

            return $result;
```
### What is the expected result?
Expected result is preventing duplicate value insertion. 
### What do you get instead?
```
Exception (Integrity constraint violation) 'yii\db\IntegrityException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '(050) 999 99 99' for key 'uk3'
The SQL being executed was: INSERT INTO `EGCampaign` (`promoCode`, `firstname`, `lastname`, `phone`, `email`, `countryID`, `createdAt`, `updatedAt`) VALUES ('nQKb', 'Test', 'Test', '(050) 999 99 99', 'test@me.com', 5, NOW(), NOW())' 

in /usr/share/nginx/www/vendor/yiisoft/yii2/db/Schema.php:633
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      |  2
| PHP version      |  7.0
| Operating system | Ubuntu Server 16.04

**Comment by nevermnd** [comment]
Humm, I was unable to reproduce the problem. The validator worked as expected.

**Comment by turalsprofile** [comment]
@nevermnd what can go wrong?

**Comment by samdark** [comment]
@turalsprofile which Yii version exactly are you using?

**Comment by arturf** [comment]
Tested with 7.0.7 (Debian), works as expected

**Comment by turalsprofile** [comment]
@samdark 2.0.9-dev

**Comment by turalsprofile** [comment]
@samdark why did you close?

**Comment by samdark** [comment]
Because I wasn't able to reproduce it.

**Comment by turalsprofile** [comment]
@samdark but it doesn't mean that problem doesn't exist

**Comment by samdark** [comment]
If I we can't reproduce it we cannot fix it. You can provide a unit test that fails to make sure we have all data necessary to do it.

**Comment by turalsprofile** [comment]
@samdark it's not fair and respectful at all to close existing issue just because you can't reproduce it. What else do I need to provide to make you sure that issue exists?

**Comment by rob006** [comment]
@turalsprofile If no one can reproduce this bug, the problem is probably in your application, not in the framework.

**Comment by samdark** [comment]
@turalsprofile ideally a unit test that fails.

**Comment by samdark** [comment]
It's not only myself who weren't able to reproduce it. See https://github.com/yiisoft/yii2/issues/11754#issuecomment-225827478

**Comment by arturf** [comment]
@turalsprofile  may be you have some "magic" in application (like [this](http://www.yiiframework.com/doc-2.0/guide-concept-events.html#class-level-event-handlers)), that can change your model's behavior?

**Comment by luqmansungkar** [comment]
Sorry for bringing back this old issue. Actually I'm also encountering this issue for quite a long time. I got random error notification about this integrity constraint violation in production but unable to reproduce it in my dev environment. The `unique` rule works fine most of the time in my prod and works all the time in my dev env, so I just ignore it and thought there's something wrong with my db server.

But lately this problem occurring more often in my prod environment on an action that never showed this problem before. And I notice that this newer problem start showing up after I moved the action to a background job using yii2 queue. And I think the problem might be around **concurrency**, because I run multiple worker and from the log I see that there's 2 job run at almost the same time trying to insert the same thing. And that's why this occurred randomly and only on production.

So what I think is happening is like this:

thread 1 | thread 2
------------|-----------
unique rule check if record already exist | unique rule check if record already exist
record is not exist yet | record is not exist yet
try to insert new row | try to insert new row
row inserted successfully | row already exist, integrity constraint violation

I try to reproduce the problem by spawning 2 worker on my dev env and pushing 2 jobs that trying to insert the same record. One of the job succeed, and one of the job failed with the same error.
I know this might not be the same issue with what the OP posted, but maybe this can help to find a solution (or if there's any already, please tell me).

**Comment by luqmansungkar** [comment]
Done at #14693

**Comment by MakamuEvans** [comment]
Did anyone solve this issue? Now am getting it
