### ISSUE TITLE
Mongo Aggregation using existing Query for $match

### ISSUE THREAD

**Issue by ptheofan** [yiisoft/yii2#11788]
It would be very nice to be able to easily design the query using the ActiveQuery and use it as $match criteria in the aggregation.

i.e
```php
$query = self::find()->published()->inBox($boundingBox);
$ag = self::getCollection()->aggregate([
    ['$match' => $query],
    ['$group' => ['_id' => '$votes.total', 'count' => ['$sum' => 1]]],
]);
```

Currently going with `$query->where` works but it feels so much more right to be able to just put it there directly.

**Comment by klimov-paul** [comment]
`Query` instance can not be used as `$match` since it may contain `sort` and `limit`, while `$match` require filter condition.

`$match` is already processed through `QueryBuilder::buildCondition()`, thus it is already easy enough to compose it.

You can pass `Query::where` as a `$match` value, if you with to reuse conditions built by scopes:

```php
$query = self::find()->published()->inBox($boundingBox);
$ag = self::getCollection()->aggregate([
    ['$match' => $query->where],
    ['$group' => ['_id' => '$votes.total', 'count' => ['$sum' => 1]]],
]);
```
