### ISSUE TITLE
Model::loadMultiple converts numbers to strings

### ISSUE THREAD

**Issue by Nasreddine** [yiisoft/yii2#11941]
### What steps will reproduce the problem?
Model::loadMultiple($myModel)
if $myModel contains an attribute "a" of type "float"
after calling Model::loadMultiple($myModel, , Yii::$app->request->post());
attribute "a" will be of type "string"
### What is the expected result?
attributes have to retain their original type "float"
### What do you get instead?
"a" is of string type

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      |   2.0.8 
| PHP version      |  5.4.16 
| Operating system |  Ubuntu 16.04

**Comment by cebe** [comment]
The problem does not arise from loadMultiple() but from Yii::$app->request->post() which returns the values as string because everything that is sent from the browser in a form is represented as strings. if you want to convert to a certain format, you have to apply filter validators: http://www.yiiframework.com/doc-2.0/guide-tutorial-core-validators.html#filter
