### ISSUE TITLE
Strtotime for Formatter

### ISSUE THREAD

**Issue by webadequate** [yiisoft/yii2#12129]
#### What steps will reproduce the problem?
Default, asDatetime expect **Datetime (object)** or **timestamp (int)**
`<?=\Yii::$app->formatter->asDatetime('2015-03-15 12:02:73', 'php:H:i, d F Y')?>`
When I put the first parameter as text, yii2 rendered output date (almost right). Without errors. 
But I must to put Datetime or timestamp.

Why not make enhancement as react on simple text input?

#### Additional info

| Q                | A
| ---------------- | ---
| Yii version      |  2.0.9
| PHP version      |  7

**Comment by cebe** [comment]
That is already possible:

> $value: 
> [...]
> - a string that can be parsed to create a DateTime object. The timestamp is assumed to be in $defaultTimeZone unless a time zone is explicitly given.
>
> [...]
http://www.yiiframework.com/doc-2.0/yii-i18n-formatter.html#asDatetime%28%29-detail

**Comment by webadequate** [comment]
I put the string, and got the wrong formatted time. When i surrounded string in strtotime or Datetime object, output was right

**Comment by cebe** [comment]
can you be more concrete about which output you expected and which output you get?

**Comment by webadequate** [comment]
`<?=\Yii::$app->formatter->asDatetime('2015-03-15 12:18:23', 'php:H:i:s, d F Y')?>`

output:
> 19:18:23, 15 марта 2015

`<?=\Yii::$app->formatter->asDatetime(new \DateTime('2015-03-15 12:18:23'), 'php:H:i:s, d F Y')?>`

> 13:18:23, 15 марта 2015 

timezone for both "Asia/Novosibirsk"

**Comment by cebe** [comment]
this is because a DateTime Object has a timezone property so we know the timezone of the time value. The same is true for a unix timestamp, which is always in UTC.
If you put in a string that contains no timezone information, the used timezone will be taken from $defaultTimeZone property of the formatter.

See http://www.yiiframework.com/doc-2.0/guide-output-formatting.html#time-zones for more details.
