### ISSUE TITLE
Unbound composer constraints are unsafe

### ISSUE THREAD

**Issue by rob006** [yiisoft/yii2#12154]
This does not affect framework itself, but in extensions and templates in `composer.json` there are many dependencies defined like: 

``` json
"yiisoft/yii2": "*",
```

This setting is dangerous and even composer complaining about it (yii2-app-advanced template):

```
$ composer validate
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
./composer.json is valid, but with a few warnings
See https://getcomposer.org/doc/04-schema.md for details on the schema
require.yiisoft/yii2 : unbound version constraints (>=2.0.6) should be avoided
require.yiisoft/yii2-bootstrap : unbound version constraints (*) should be avoided
require.yiisoft/yii2-swiftmailer : unbound version constraints (*) should be avoided
```

When Yii 2.1 will be released (which can break BC), composer will just upgrade Yii to v2.1 even if used extensions and application itself will be incompatible with new version. There are already problems with this: https://github.com/yiisoft/yii2-bootstrap/issues/150

Yii extensions, app templates and extension template generated by Gii should use more safe constraints, like:

``` json
"yiisoft/yii2": "~2.0.0",
```

**Comment by klimov-paul** [comment]
This is debatable matter.

> When Yii 2.1 will be released (which can break BC), composer will just upgrade Yii to v2.1 even if used extensions and application itself will be incompatible with new version.

This is actually is unknown. It could be that particular extension will be not compatible with the next major release, but it could it will. Unless there is no centaintly for such matter I prefer to have flexible version constaint to avoid possible version conflict in the future.

For example.
Assume we have a major release of `yii2-framework` - '2.1'. We have extension `yii2-mongodb` which have dependency specified as `yii2-framework: "~2.0.0"`, while it can work with `yii2-framework: "~2.1.0"`.
And we have extension `yii2-jui` with dependency `yii2-framework: "~2.1.0"` because it relies on some BC changes at main repo.
While  `yii2-mongodb` can function fine with `yii2-framework: "~2.1.0"` you are unable to install in this way due to the version restiction. And thus you are unbale to install both `yii2-jui` and `yii2-mongodb`.

The answer to the question "why there could be no version of `yii2-mongodb`, which refers `yii2-framework 2.1`" is it may be not necessary. Since there is no code changes for such migration - no release has been made.

Thus developer ends with unresolving situation of version conflict.

On the other hand, if version constants remain flexible, e.g. `yii2-framework: "*"` and there is a BC break for extension `yii2-jui` you can easily fix it inside root (project one) composer.json, adding a strcit constraint to `yii2-framework`:

```json
"yii2-jui": "~2.0.0",
"yii2-framework: "~2.0.0" 
```

Thus problem can be solved.

I prefer to meet possible BC issues and be able to handle them rather to be protected from such issue and end up with unresolvable version conflict.

**Comment by rob006** [comment]
> This is actually is unknown.

And this is a reason why you should not assume that it will work. Constraint in dependencies should mean "This package/app works with this dependencies with this versions" not "This may work, but nobody knows - do your own tests".

> Thus problem can be solved.

This problem should be solved by composer - that's the point of dependency managers. People should know that upgrading some package will bring compatibility issues. Right now `composer update` just upgrade some package without any complaining and silently break your project.

>Thus developer ends with unresolving situation of version conflict.

There are lot of ways to solve this. You can fork package and use `replace` section in `composer.json`. You can use `2.1.0 as 2.0.9` in constraint. You can always override some package, but this should affect only abandoned packages (which should die anyway) - active projects should release new version with updated constraints. And there is no reason why they should not release new version with only constraints update.

**Comment by rob006** [comment]
@SilverFire Why you set target to 2.1?

**Comment by samdark** [comment]
I agree that constraints should be specified.

**Comment by cebe** [comment]
I also agree that these constraints should be conservative, especially for extensions like mongodb, which are tightly coupled with the core AR code. I have reviewed extension constraints and adjusted them where appropriate. Some I left as is, e.g. Imagine, which has nearly no dependency on core code.

**Comment by cebe** [comment]
also updated the guide and application templates. Seems some extension readme and docs need to be adjusted.

**Comment by samdark** [comment]
Seems to be in order.
