### ISSUE TITLE
"Off serializer of cache" causes errors.

### ISSUE THREAD

**Issue by githubjeka** [yiisoft/yii2#12188]
[If serializer of cache is off then value for cache is array.](https://github.com/yiisoft/yii2/blob/e8d309dddb6e12a0c07891ef2f6d95cef83acc70/framework/caching/Cache.php#L337-L350)

It's wrong for [value of Cache::setValue()](https://github.com/yiisoft/yii2/blob/e8d309dddb6e12a0c07891ef2f6d95cef83acc70/framework/caching/Cache.php#L389)

- This causes an error for RedisCache https://github.com/yiisoft/yii2-redis/issues/80
- This causes an [delusion in FileCache](https://github.com/yiisoft/yii2/blob/master/framework/caching/FileCache.php#L141) (value of file_put_contents can be array. PHPDoc has only string)
- This cause an erron for DbCache (PHP Notice – yii\base\ErrorException Array to string conversion...)
- and likely, similar for other ..Cache

**Comment by SilverFire** [comment]
However ApcCache, ArrayCache, XCache and WinCache support saving arrays and even objects without serialization.

The only thing that seems right to me:

* Update PHPDocs and change `string` to `mixed` in methods of classes, where the caching `$value` can be something different from string
* Add condition to `init()` method in classes where `serializer` must not be `false` in order to prevent wrong behavior

**Comment by githubjeka** [comment]
And what about Redis/DbError errors?

**Comment by samdark** [comment]
Technically we can introduce exceptions for the case but since cache should be as fast as possible and these extra checks could slow it down, I'm not sure if these checks are worth adding.

**Comment by SilverFire** [comment]
Agreed with @samdark 

@githubjeka  Would you like to submit a PR with PHPDoc updates?

**Comment by githubjeka** [comment]
Ready,

**Comment by SilverFire** [comment]
https://github.com/yiisoft/yii2/commit/3ce36573b69c2c7df51f4ca5b128221e0626887e
