### ISSUE TITLE
Allow POST request from Perfect Money to my site?

### ISSUE THREAD

**Issue by RNKushwaha022** [yiisoft/yii2#12365]
I have to allow POST request from Perfect Money to my site. How to do this? Its always showing

Unable to verify your data submission

While I have added

`public function beforeAction($action) { 
     $this->enableCsrfValidation = false; 
    return parent::beforeAction($action);
 }`
Also added $this->enableCsrfValidation = false; in action of the controller. Still it doesn't work.

**Comment by RNKushwaha022** [comment]
I'm so disappointed by your response. Is it why people use your framework?  Can't you take 2 minutes to read and provide the solution to the problem? You don't have time to answer but have time to read the question and close it without any help? One of the worst response which I received.

**Comment by RNKushwaha022** [comment]
Anyway thanks for your worst support.

**Comment by tunecino** [comment]
@RNKushwaha022 this is not the framework's support page, they already built a website and a forum for that. this is an issue tracker and as you may see there is already 865 of them waiting to be solved. and many people like me are waiting for those issues to be solved. I just wish the core team to only dedicate their time on improving this framework instead of answering questions as those new days there is more open-source killers than contributors. if you didn't find any issue please don't open an issue page. If you didn't like the way how Yii works just use something else. use laravel. laravel is good. and to answer your other question, **Yes** it is because we didn't find the equivalent of that guy in any other framework we decided to use his framework. your code looks correct to me as it is already explained [here in docs](http://www.yiiframework.com/doc-2.0/guide-security-best-practices.html#avoiding-csrf) and as it seemed to work for others [here](http://stackoverflow.com/questions/28526873/disable-csrf-validation-for-individual-actions-in-yii2). if it doesn't work for you then something else should be wrong. post more details in forum or connect to gitter and we will try to help.

**Comment by RNKushwaha022** [comment]
@tunecino @qiangxue Yeah! I'm planning to move to Laravel. 
Anyway if my code looks correct and if its not working then surely its a bug. 

By the way @tunecino how did you come to know that the equivalent of that guy in any other framework is not available.
However I'm also a big fan of @qiangxue . Thanks

**Comment by rob006** [comment]
>  Anyway if my code looks correct and if its not working then surely its a bug. 

If you think that this is a bug in the framework, please provide way to reproduce it. For now you give only laconic information that suggests that the bug is in the structure or the configuration of **your** application.

**Comment by samdark** [comment]
https://github.com/samdark/yii2-cookbook/blob/master/book/csrf.md#disabling-csrf-protection it may help.

**Comment by samdark** [comment]
https://github.com/samdark/yii2-cookbook/blob/master/book/csrf.md#disabling-csrf-protection — it's confirmed to work. If it does not, there's something wrong with the application or server setup.

**Comment by samdark** [comment]
We don't have your application so we can't find out what's wrong exactly and there are not enough details to reproduce the issue. Thus we can't fix it.

**Comment by samdark** [comment]
Probably someone with more free time could dive into your application code to find out what's wrong with it. Linked pointed in @yii-bot message are to places where you can chat with community. They are usually more helpful than us in such questions.

**Comment by samdark** [comment]
Yii isn't commercial product so we don't have 24/7 support or anything like that. We're doing all the development and support in our free time which is left after our fulltime jobs.

**Comment by tunecino** [comment]
@RNKushwaha022 simply because he always knew how to prevent Yii from becoming [this](https://twitter.com/ircmaxell/status/632422970636419072) even if it requires getting people upset. anyway I did answer you in gitter. if you didn't find solution I'll be there.

**Comment by RNKushwaha022** [comment]
@samdark I'm not expecting to get support/help/answer immediately instead I just need help about how can I do that. Yes I know that Yii is not a commercial product that's why I'm using it.

**Comment by samdark** [comment]
Well, @tunecino gave you a hand. Hopefully you both will solve the issue. If you'll find a way to reproduce the issue starting from a basic project template, please post it. It will be considered a bug in the framework and eventually will be fixed.

Thanks for understanding and sorry if our automated GitHub bot was too rude with the answer. btw., if you have any ideas on how to improve the message, let us know.
