### ISSUE TITLE
Use jQuery alias

### ISSUE THREAD

**Issue by kr0lik** [yiisoft/yii2#12382]
Is it possible to make the possibility of the initialization function through jQuery alias, not $?

**Comment by samdark** [comment]
Please elaborate.

**Comment by kr0lik** [comment]
When jQuery works in compatibility mode, the usual shortcut '$' does not work and instead used jQuery. A widget script uses '$': `$js .= '$("#' . $id . '").' . self::PLUGIN_NAME . '(' . $this->_hashVar . ');';` Therefore, it would be desirable that it were possible to use the plug-in compatibility mode.

**Comment by samdark** [comment]
Ah. Got it.

**Comment by WadeShuler** [comment]
Wouldn't this cause issues, for other users down the road, due to conflicts?

You should use the `jQuery` alias. I think a user should specifically map this alias **when** needed on their own. I don't think the framework should handle this.

In this person's case, he should handle the alias himself. Why does Yii have to do this, when the user should handle this on their own.

Yii can't possibly support 100k different use cases, specific to 1 individual.. 5 years of this, and the framework will be bulky and all over the place.

**Comment by samdark** [comment]
Which conflicts?

**Comment by cebe** [comment]
`jQuery` is always present compared to `$`, which is not. So I see no problem to use jQuery by default in all widgets.

**Comment by kr0lik** [comment]
It would be nice in this widget yii2/framework/widgets/MaskedInput.php replaced $ to jQuery. In other widgets already done it.

**Comment by samdark** [comment]
Fixed.
