### ISSUE TITLE
namespace yii\db\BaseActiveRecord  in this class has save()  function as shown below 

### ISSUE THREAD

**Issue by murat-celik** [yiisoft/yii2#12602]
```
 public function save($runValidation = true, $attributeNames = null)
    {
        if ($this->getIsNewRecord()) {
            return $this->insert($runValidation, $attributeNames);
        } else {
            return $this->update($runValidation, $attributeNames) !== false;
        }
    }
```

Why must doesn't support  $runBeforeSave  and $runAfterSave parameters ?
@cebe @samdark

**Comment by SilverFire** [comment]
Because it's not necessary.
If you do not want to trigger events in some special cases you have a plenty of options how to do it:
 * unbind listeners using [off()](http://www.yiiframework.com/doc-2.0/yii-base-component.html#off()-detail) method;
 * override `beforeSave()` method
 * manage it with scenarios
 * etc

**Comment by cebe** [comment]
best option for updating without events is `updateAttributes()`.
