### ISSUE TITLE
hasFlash() deletes the flash

### ISSUE THREAD

**Issue by starrychloe** [yiisoft/yii2#12685]
### What steps will reproduce the problem?
In a controller:
```
    public function actionDelete($id)
    {
Yii::$app->session->addFlash('alert', "Failed to delete keyword # id. Check logs.");
Yii::$app->session->hasFlash('alert');
return $this->redirect(['index', 'KeywordSearch[id]' => $id]);
```

### What is the expected result?
I expect the flash to show.

### What do you get instead?
No flash shows.

### Additional info
If you comment out the `hashFlash()` line, then the flash shows every time.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8
| PHP version      | 5.6.24
| Operating system | Win 8.1, Cygwin 2.5.2

**Comment by githubjeka** [comment]
Can you try Yii::$app->session->addFlash(..., ...,, **false**);

```php
public function actionDelete($id)
{
    Yii::$app->session->addFlash('alert', "Failed to delete keyword # id. Check logs.", false);
    Yii::$app->session->hasFlash('alert');
    return $this->redirect(['index', 'KeywordSearch[id]' => $id]);
}
```

**Comment by SilverFire** [comment]
I'm closing the issue unless further information provided.

**Comment by KirkHicks** [comment]
I would open a new issue, but this is already exactly my issue, though I am using:
Yii version 2.0.40
PHP 7.4.12
Windows 10 v2004

What I have to add is that this functionality appears to be happening because hasFlash() directly calls getFlash(), which updates the flash message counter even though the message has not been retrieved, only checked for existence.

Shouldn't hasFlash() be totally read-only without causing any side effects or updates.

from Session.php:
`public function hasFlash($key)
{
	return $this->getFlash($key) !== null;
}

public function getFlash($key, $defaultValue = null, $delete = false)
{
    $counters = $this->get($this->flashParam, []);
    if (isset($counters[$key])) {
        $value = $this->get($key, $defaultValue);
        if ($delete) {
            $this->removeFlash($key);
        } elseif ($counters[$key] < 0) {
            // mark for deletion in the next request
            $counters[$key] = 1;
            $_SESSION[$this->flashParam] = $counters;
        }

        return $value;
    }

    return $defaultValue;
}
`
