### ISSUE TITLE
Update the guide for the Pjax ID requirement

### ISSUE THREAD

**Issue by dynasource** [yiisoft/yii2#12969]
We're getting many issues about PJAX. I see a red line which is proven by the guide. 
http://www.yiiframework.com/doc-2.0/yii-widgets-pjax.html
There is no Pjax example with an ID.

We should either update the guide with an example with an ID or generate an unique ID by default. This latter is a challenge but can be solved if you generate the ID by the {class}:{line} in which the pjax widget is called.

**Comment by SilverFire** [comment]
Agrred

**Comment by SilverFire** [comment]
> This latter is a challenge but can be solved if you generate the ID by the {class}:{line} in which the pjax widget is called.

I don't like this kind of magic. Let's just say that ID is vital for PJAX blocks with navigation

**Comment by dynasource** [comment]
is this kind of magic really a problem? Currently it seems that we have a BC break and its confusing for developers. This is a problem we all ran into (or at least >95% of the community). 

Having this fixed out of the box is desireable. We don't want people to burn their precious hours in the 'logic' behind Pjax.

**Comment by SilverFire** [comment]
@dynasource We have a sequential auto-generated id in the `Widget` class and it the very first thing that forces new developers spend hours of understanding why something does not work with PJAX. Use case described:

views:
 - `index.php`
 - `counter.php`

controller actions:
 - `index` (renders `index.php`)
 - `update-counter` (renders `counter.php`)

___

View `index.php`:

```php
echo GridView::widget([...]); // widget gets w0 id
$this->render('counter');
```

View `counter.php`:

```php
Pjax::begin(); // widgets gets w1 id
// counters, whatever
echo Html::a('update', ['site/update-counter']);
Pjax::end();
```

After the `Update` button pushing, the `update-counter` action will render `counter.php` and the PJAX widget will get id `w0`. Thus response from `update-counter` will be invalid because it will not contain element with `w1` ID.


How do you suggest to implement auto-generated widget ID that will work for this use case?

**Comment by dynasource** [comment]
ehmmm...with my PR? https://github.com/yiisoft/yii2/issues/12977

**Comment by SilverFire** [comment]
Sorry, your PR was not ready when I opened 50 issues in my browser, so I did not see it when posted my comment.
