### ISSUE TITLE
Yii components split

### ISSUE THREAD

**Issue by Deele** [yiisoft/yii2#13065]
Backstory: I am slowly working towards finishing my first component for Yii (#12862) that is a step towards separating controller from code, that should be sitting in model (referencing MVC pattern, not Model class in Yii) and then I stumbled upon project in this repository and got curious. I haven't found any issues regarding this, so I'm starting this issue to question idea behind such move.

> **[Yii components split](https://github.com/yiisoft/yii2/projects/2)**
> Attempt to split Yii components into framework-independent universal libraries

What is meant by this initiative/project? Does it mean just that there will be less code in yii2 repo, and more packages in vendor?

If so, what remains in core and what will be taken outside then? In terms of basic parts parts of code, like Object, Configurable, Component, that are used everywhere, where do they remain, in core or separate package? Who will decide what really is framework, and what is  _just a component_ ?

If there would be some sort of description what such splitting initiative would look like, new components (like my _Migrator_ ) could be created with that idea in mind and created, using words of mentioned project, "into framework-independent universal libraries".

How do we contribute to that project page, what are guidelines, what are rules, who will decide on the level of separation? Are we looking for compatibility with low level [Symfony components/bundles](http://symfony.com/doc/bundles/)?

Lets talk about this.

**Comment by samdark** [comment]
> What is meant by this initiative/project? Does it mean just that there will be less code in yii2 repo, and more packages in vendor?

Yes.

> If so, what remains in core and what will be taken outside then? In terms of basic parts parts of code, like Object, Configurable, Component, that are used everywhere, where do they remain, in core or separate package? Who will decide what really is framework, and what is just a component ?

Core stuff remains in the code. Core team will decide what is what.

> If there would be some sort of description what such splitting initiative would look like, new components (like my Migrator ) could be created with that idea in mind and created, using words of mentioned project, "into framework-independent universal libraries".

We aren't really going to create "framework-independent universal libraries" unless it makes total sense to free code of framework dependency overall. Some degree of dependency on the core is beneficial to both reusability and code clarity.

Migrator still belongs to the core and could be extracted later. Since it depends on schema and loses much if not, it makes sense to either keep it in the core or extract it to core-dependent package.

See https://github.com/yiisoft/yii2/issues/8452. That's where we want to start.

I'm closing the issue since it's kinda meta-one but feel free to ask more questions.
