### ISSUE TITLE
Allow AssetManager component to be disabled

### ISSUE THREAD

**Issue by artur-ciesielski** [yiisoft/yii2#13171]
After the recent update to Codeception builds started to fail, so I checked the source of the problem.

From Codeception changelog:
```[Yii2] Removed mockAssetManager by githubjeka.```
This caused the real AssetManager to be instantiated, but the $basePath was set incorrectly (ie. not set at all) in test config. And even though I already fixed the problem this got me thinking: about half of my applications are REST APIs that don't really need an AssetManager component (or am I wrong here?). So maybe this component should be made optional or at least the ability to disable it should be added.

**Proposed 'solution':**
- ability to pass 'false' as the configuration for AssetManager component (which would be consistent with many other components, eg. passing 'false' to DataProvider as Sort configuration or Pagination configuration - _this is probably the preferred 'solution'_

OR
- make the whole AssetManager component optional (which would probably break a whole lot of existing code after upgrading the framework which is suboptimal, but this way we would only need to use components we explicitly stated we need)

**Comment by cebe** [comment]
The asset manager component (as also every other default application component) is optional. If you do not access it in your code, it will not be instantiated. So:

- if you use it in your code, it should be properly configured or mocked in testing env
- if you do not use it in your code, it should not cause any problem because it should never get instantiated.

**Comment by artur-ciesielski** [comment]
Yes, I ran the application through a debugger and it seems to be the case indeed. Thank you and please close the issue.
