### ISSUE TITLE
Why unlink and unlinkall not triggering delete function 

### ISSUE THREAD

**Issue by m-wardany** [yiisoft/yii2#13389]
I think it would be much better if unlink() and unlinkall() in  the ActiveRecord trigger the delete function in the Model .

**Comment by m-wardany** [comment]
**When does the issue occur?**
when I use unlinkAll('posts', true) in the model to delete all related posts in beforeDelete() function and the related item has children that must be deleted before I delete the Item
for example : 
single category has many posts , single post has many details
in Category::beforeDelete() $this->unlinkAll('posts', true);

**What do you see?**
DB error : Cannot delete or update a parent row: a foreign key constraint fails. thats because post has details that must be deleted before 

**What was the expected result?**
I expected that unlinkAll will trigger delete() function in Post model so I could delete related post details

**Comment by samdark** [comment]
Can't be done since there are many ways dealing with that. You can solve it in PHP code or you can solve it on DB constraints level by specifying ON DELETE CASCADE for foreign keys.

**Comment by IGaMbLeRI** [comment]
@samdark 
I believe you are addressing a use case rather than the underlying "issue".
For example, using ```bedezign/yii2-audit``` to track ```ActiveRecord``` changes. As far as I can tell, ```AuditTrailBehavior``` reacts to ```ActiveRecord::EVENT_AFTER_DELETE``` which is not fired when the relation is ```unlink```ed.

Example "Junction Table":
```public function getTasksAccountsAssigned() {
        return $this->hasMany(TasksAccountsAssigned::className(), ['TaskId' => 'Id']);
    }
    public function getAccountsAssigned() {
        return $this->hasMany(Accounts::className(), ['Id' => 'AccountId'])
            ->via('tasksAccountsAssigned');
    }
```
so then
```$this->unlinkAll('accountsAssigned', true);```
doesn't produce records in the Audit extension, which normally produces Deletes.

Leads me to believe that ```ActiveRecord::EVENT_AFTER_DELETE``` is not getting fired on Delete of ```TasksAccountsAssigned``` which is issued by the ```unlinkAll(... , true)```.

If there is truly no way for ```unlink``` to fire ```ActiveRecord::EVENT_AFTER_DELETE```, then how would you propose I go about my issue. If it's not too much trouble ;)

**Comment by samdark** [comment]
@IGaMbLeRI what you've described is not related to this issue. The issue was about not deleting at all, not about triggering events. For events triggering you may create a separate issue.
