### ISSUE TITLE
redirect() is not working as expected

### ISSUE THREAD

**Issue by tsanchev** [yiisoft/yii2#13430]
### What steps will reproduce the problem?

i have a module with normal CRUD actions
after last composer update
the redirect in create and update to view are no longer working as expected

### What is the expected result?

it should be /module_name/default/view?id=1

### What do you get instead?

i get redirected /view?id=1

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11-dev
| PHP version      |
| Operating system |

**Comment by samdark** [comment]
@tsanchev it's not clear on how to reproduce it. Could you elaborate what "normal CRUD actions" are?

**Comment by tsanchev** [comment]
By "normal CRUD actions" i mean, i have generated model and CRUD using gii module, using latest gii version from several months ago. 
i'm using advanced template.
the problem occurs in the backend of the project.
i have lots of modules with models in them and CRUDs (all of them generated with gii) and after updating yesterday, none of the generated code by gii involving redirects is working properly.

for example this is code for update from DefaultController.php from module 'products' which is the backend

`

    /**
     * Updates an existing Products model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->product_id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }
`


on post after model get saved, it redirects me to
http://localhost/myproject/backend/view?id=X
instead of
http://localhost/myproject/backend/products/default/view?id=X

the redirect acts as it is 
redirect(['/view' ....
and not
redirect(['view'

**Comment by teruk** [comment]
I experience the same problem with the same behavoir and no redirect is working probably if only the action is given. I'm also using the advanced template but with no modules so far. There is no difference between redirect with or without additional parameters. I did not use the Gii to generate the actions.

- Yii version: dev-master
- PHP version: 5.6.26

The problem occurred today after an composer update, but strangely nothing is shown in the logs. Still need to investigate that a little more. Some changes in the last 5 days must have caused the problem because that was the last time before today that I ran composer update  and it worked fine until today.

With Yii version 2.0.10 everything works as aspected

**Comment by rob006** [comment]
Probably #13393 caused this bug.

**Comment by samdark** [comment]
@teruk can you revert that change and try it w/o it? Will be able to do it evening or tomorrow myself...

**Comment by teruk** [comment]
@samdark I changed my version to dev-master again and I can confirm, that this change caused the problem.

**Comment by samdark** [comment]
Reverted https://github.com/yiisoft/yii2/commit/eab3489ec711b1ad9de0158e402fffaba999f4ff. Thanks for checking.
