### ISSUE TITLE
UniqueValidator now 'Select only primary keys'. Other attributes have null values when BaseActiverecord::afterFind is called.

### ISSUE THREAD

**Issue by pyd** [yiisoft/yii2#13453]
### What steps will reproduce the problem?
Set a 'unique' validation rule for an attribute in a model.
Add some code that requires attributes to the afterFind() method:
```php
public function afterFind() {
    $this->emailUsername = $this->extractEmailUsername($this->email);
}
//...
public function extractEmailUsername($email)
{
    $username = substr($email, 0, strpos($email, '@'));
    if (false !== $username) {
        return $username;
    } else {
        throw new InvalidParamException("Failed to extract username from email '$email'.");
    }
 }
```
Run validation **with an existing value** for the expected-unique attribute.

### What is the expected result?
A validation failure with an error message.

### What do you get instead?
An InvalidParamException is thrown when I validate the 'email' attribute with an existing value.

### Additional info
Changes were made in this [commit](https://github.com/yiisoft/yii2/commit/729ddc5b76e8159d051e9c5783f5534eeb212efb)

 Yii version      | 2.0.11

Thanks

**Comment by samdark** [comment]
Right. It should not trigger any extra model method calls...

**Comment by samdark** [comment]
Commit caused issues reverted: https://github.com/yiisoft/yii2/commit/bede9feba5b39169381d7af3c48ae89753fbe9e5

**Comment by developeruz** [comment]
Напишу на русском, тк не уверена что смогу донести мысль на англ:
afterFind должен работать с текущей моделью и имеет смысл только для модели, с которой потом будут работать. Он вызывается всегда, поэтому для ``$models = $query->limit(2)->all();`` он тоже вызовется, причем дважды, если найдет совпадение. Но эти модели не будут нигде использоваться. Эти модели храняться в локальной переменной функции, которая используется только для ``count($models)``.  Валидировать по этому вычисляемому параметру в текущей реализации все равно нельзя, поэтому смысла их расчитывать тоже нет.  Я предлагаю добавить что-нибудь в afterFind чтобы можно было передать отмену выполнения кода в afterFind, тем более что это лишние не используемые движения как минимум в случаи с ``UniqueValidator``

``afterFind`` makes sense only for a model that will be used somewhere but it calls every time when some ActiveQuery runs. So for ``$models = $query->limit(2)->all();`` in UniqueValidator it calls twice (if model exist, or once if not) but both models will not used after function is done because this models stored in local variable and do not used anywhere except in line ``count($models)``. Running ``afterFind`` for this models is totally needlessness. I suggest adding an opportunity to skip ``afterFind``  for some cases, especially for ``UniqueValidator``.

**Comment by developeruz** [comment]
I will change my PR, it is better to use low-level query here, so it won't trigger  ``afterFind``.

**Comment by samdark** [comment]
Yes. The idea itself is good.

**Comment by samdark** [comment]
Please open new pull request.
