### ISSUE TITLE
Bash and Zsh completion installation security

### ISSUE THREAD

**Issue by tom--** [yiisoft/yii2#13578]
Enhancement suggestion

[Docs for installing](https://github.com/yiisoft/yii2/blob/master/docs/guide/tutorial-console.md#console-command-completion-) Bash and Zsh command completion suggest injecting the output of a curl get into shell startup scripts. This seems a bit risky.

It might instead be more secure against tampering/spoofing if the completion configs were included (hard-coded strings) in the framework. Then the user (typically) has the added confidence from git and Composer.

Moreover it would be even better for usability if we could do

    ./yii install-shell-completion

especially if that command says what it is going to do and asks for permission.

**Comment by SilverFire** [comment]
The manual contains HTTPS link to GitHub website. CURL does not allow to establish connection to the host with self-signed certificate, so I see two possible vectors of attack in this case:

1. Add custom CA to allowed list on the target machine. In this case the target machine is already compromised and we have nothing to do with it.
2. Force person to run `curl --insecure`. In this case it's a human factor and it's out of our scope as well.

I don't think we should include completion to framework itself.

**Comment by tom--** [comment]
There are more risks:

1. DNS spoofing (probably less likely)
2. tampering with the URL that appears in the manual
3. tampering with the completion script itself

The latter two are my concern primary. But the manual and the framework code are equally vulnerable to a malicious PR so my suggested remedy probably doesn't help much.

**Comment by rob006** [comment]
> But the manual and the framework code are equally vulnerable to a malicious PR so my suggested remedy probably doesn't help much.

There is a little difference. If you're installing `yii2` via composer, you probably will get stable (tagged) release. Links in docs points to master branch. Technically it is easier pass some malicious code to master than release. 
Also, if I want to install my app in 20 environments, I need to do download this script 20 times - it is not only more work, but also more chance that something will go wrong. And if I will want to update these scripts, I also need to do it 20 times.

**Comment by SilverFire** [comment]
> And if I will want to update these scripts, I also need to do it 20 times.

How does including script in framework dir will help you, when you have 10 project on the same server? I don't think you will symlink script from one of that projects to your server config because it does not make sense. Once you copy script from framework to any server dir, you get no difference with script downloaded with CURL.

**Comment by rob006** [comment]
If I will have 10 project on the same server, I will run them on 10 different user accounts and configure this separately for each one. 

> /.../ you get no difference with script downloaded with CURL.

That depends. If this would be part of framework, with `composer.lock` I could be sure which version of script I will get. Right now I can test script on dev environment and tomorrow I will get different version on production server (because in the meantime scripts was updated in master branch).

If we really don't want to distribute this with framework core, we could extract this to separate repository and composer package - it could be easily installed by composer or just `git clone`.
