### ISSUE TITLE
ajaxPrefilter error in yii.js

### ISSUE THREAD

**Issue by netcelli-tux** [yiisoft/yii2#13717]
### What steps will reproduce the problem?

The problem occurs randomly when performing ajax request with jQuery.

### What do you get instead?

The following error is triggered:

> Uncaught TypeError: Cannot read property 'xhrList' of undefined

Error: http://imgur.com/a/swKd5

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.2
| PHP version      | 7.0.15
| Operating system | Linux

**Comment by arogachev** [comment]
What kind of AJAX requests do you send and how often? Please provide more details so we can reproduce this bug.

**Comment by netcelli-tux** [comment]
Hi arogachev,
thanks for the answer. Here is the scenario I am able to reproduce the issue every time:

1. the user click on button A (_URL A_). A JS sends an AJAX request ($.get) to get a view and populate a modal dialog.
2. the user sends the form in the view (AJAX request with $.post) and the modal is closed.
3. the user clicks on button B (_URL B_). The same JS opens a modal dialog. This time the user simply closes the modal without any additional interaction.
4. the user clicks again on button A (_URL A_) and the error is triggered.

Please note the user never reloads current page.

Please let me know if you need additional information.

**Comment by netcelli-tux** [comment]
I was able to do some debugging.
At step 4, both _forbiddenRepeatedLoad_ and _cleanupRunning_ are **false**. In the other steps forbiddenRepeatedLoad=true and cleanupRunning=false so xhr is aborted.

**Comment by arogachev** [comment]
@netcelli-tux Thanks, while it's already something to start from, it will be better if you include even more details. I barely understood what's going on but don't have complete picture of it yet.

We can either:

- abstract from HTML completely and concentrate only on AJAX requests. What urls they are sent to? What are responses' types and their contents? You can simplify / omit unnecessary markup / data and leave only what's important. But in case of HTML please leave scripts inserted with `<script>...</script>`, because I'm sure this is a key part of this problem.
- for test with HTML, can you provide miminal setup without any extra code and files so we can just drop it in our basic app skeleton and see. It would be awesome if you will do something like this - https://github.com/yiisoft/yii2/issues/13379#issue-200348879. But you can paste the code examples right in the post if you don't have time / desire to do it.

**Comment by netcelli-tux** [comment]
@arogachev Thanks for the answer. Unfortunately at the moment I cannot reproduce it with a simple application (The one in production is a real-time dashboard which involves different AJAX request).

I was able to identify the script causing this issue. The AJAX request with URL _//assets/js/yii.validation.js_ fails with _textStatus_  equals to **canceled**.
The [callback](https://github.com/yiisoft/yii2/blob/master/framework/assets/yii.js#L419) registered whether the deferred object is rejected, only checks the text status **aborted**. Checking the status **canceled** as well fixed the issue.

**Comment by TerraSkye** [comment]
would that mean that your browser cancaled the request due to many concurrent (slow speed ) ones?

**Comment by netcelli-tux** [comment]
I don't think so. I'm in my local/test environment.
Also the networking panel in Chrome inspector doesn't show any failed connection. I will try to debug it by using chrome://net-internals/#events and report back.
Thanks

**Comment by netcelli-tux** [comment]
Sorry for the delay.
I cannot find the reason why Chrome cancels that request. The script, other than checking for "aborted" request, should check also for "canceled".

**Comment by arogachev** [comment]
@netcelli-tux As far as I remember, canceled scripts are handled in other place.

**Comment by TerraSkye** [comment]
It can be caused by chrome due to connection throttling

**Comment by netcelli-tux** [comment]
@arogachev I couldn't find where. Shouldn't the ajaxPrefilter callback be fixed to handle canceled request as well?
