### ISSUE TITLE
Can't properly extend yii\data\Pagination - $_pageSize and $_page are private

### ISSUE THREAD

**Issue by icefront** [yiisoft/yii2#13713]
### What steps will reproduce the problem?
Extend the Pagination class and read or assign value $this->_page or $this->_pageSize

### What is the expected result?
Be able to read and assign values to $this->_page or $this->_pageSize without PHP error

### What do you get instead?
PHP error: Getting unknown property: common\yii\PaginationEx::_page

### Additional info
$_page and $_pageSize should be set as protected, not of private. BTW this is true for all classes if the property in question is not really private.
Now it's not possible to extend this class without modifying the framework.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11
| PHP version      | 5.4
| Operating system | Linux

**Comment by arogachev** [comment]
Could you describe a use case related with overriding these properties?

**Comment by icefront** [comment]
I wanted to override the getPage function (L 170) to support special page params, like /something?page=last or /something?page=beforelast . The new function was meant to convert last and  beforelast to numbers. 

So everything went fine except for the error "Getting unknown property: common\yii\PaginationEx::_page"
Then I changed the framework file, replaced private with protected and the code worked.

Now I solved the problem otherwise, but I still think it isn't good to declare private properties, insetead declare protected. From outside the class it's the same, but for overriding the class it's very different.

**Comment by arogachev** [comment]
That's why I prefer Python's approach to private properties. Nothing is truly private there, it protects you from accidently accessing or modifying them, but if you really need to, you have all the power to do it.

Back to this problem, I'm not sure if we need to fix this, especially for this specific class and with existing workarounds. In Yii2 the most important properties and methods that have a chance to be overridden (because of according logic) are made protected. However you can't imagine or predict all possible use cases for overriding.

So maybe it should be solved not on specific class' level but for the whole framework. Can be implemented in 2.1 for example.

But still it's ambiguous, we need other core members' opinions.

**Comment by samdark** [comment]
> So maybe it should be solved not on specific class' level but for the whole framework. Can be implemented in 2.1 for example.

If you mean making everything protected then the answer is no, it should not be done. If you mean fixing particular use case — yes, it's discussable.

**Comment by samdark** [comment]
In this case you can use `parent::getPage()`, `parent::setPage()`, `parent::getPageSize()`, `parent::setPageSize()`.

**Comment by icefront** [comment]
I can use parent::getPage(), parent::setPage(), parent::getPageSize(), parent::setPageSize() without overriding the class.
The original problem is that the whole class cannot be extended because of important properties set to private.
I just can't understand, if something isn't fully usable, why isn't meant to be fixed...
Here is the situation:
- either private or protected, it cannot be accessed from outside - check
- set to private, it cannot be used in descendant classes - problem

Also, setPage() and getPage isn't just returning a property, but it's doing something. In this case, if somebody wants to change the original behavior, he overrides the method. This is the basic concept of OOP. But again, important properties set to private render the class terminal, denying the possibility to override the class.

**Comment by samdark** [comment]
> The original problem is that the whole class cannot be extended because of important properties set to private.

It can since properties are accessible via getters and setters.

> either private or protected, it cannot be accessed from outside - check

Except there's a method for it or if it's protected and you're in a subclass.

> set to private, it cannot be used in descendant classes - problem

Again, if there's no method to access it.

> This is the basic concept of OOP. But again, important properties set to private render the class terminal, denying the possibility to override the class.

The basic concept of OOP is encapsulation. Internal behavior itself should never be exposed as public API. Important properties exposed via getters and setters with additional checks are actually good, not bad.
