### ISSUE TITLE
SqlDataProvider total count

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii2#13883]
During code inspection for #13852 I noticed the implementation in `SqlDataProvider`:
````
    /**
     * @inheritdoc
     */
    protected function prepareTotalCount()
    {
        return 0;
    }
````

Is there a reason not to just wrap the query in a count?

**Comment by samdark** [comment]
SQL data provider is often used to achieve best performance possible. For DB engines like InnoDB doing `count(*)` is not a simple task when amount of data is really high (it does full table scan) so often people are adding a trigger which is updating counter stored separately.

I guess that's the reason. It is like that since Yii 1.0 even before I've joined the project so I'm not entirely sure.

**Comment by SamMousa** [comment]
Well, if you provide a total count this would never get called anyway.
Current implementation doesn't ever do what you want; if you always want to provide the count it should throw an exception, if you want it to fallback to the slow behavior it should implement something.

Returning 0 is just wrong :|

**Comment by samdark** [comment]
Makes sense.

**Comment by SamMousa** [comment]
So, exception or slow implementation?

**Comment by samdark** [comment]
Slow implementation.
