### ISSUE TITLE
Stop using Courier and Courier New fonts by default

### ISSUE THREAD

**Issue by rimas-kudelis** [yiisoft/yii2#13945]
When an exception is thrown, Yii displays a stack trace if configured to do so. The trace uses inline styles, which specify "Consolas, Courier New, monospace" for snippets of code.

I don't have Consolas on my Linux box, but I do have Courier New, and I must say, this font is barely readable unless I zoom in like crazy.

I'd like to suggest to drop explicit usages of Courier and Courier New in Yii, and perhaps even other monospace fonts by name, and let the user choose the font that she likes the most by just specifying that we need a monospace font here.

**Comment by samdark** [comment]
The reason for specifying font explicitly is that unlike Ubuntu and many other Linux distributions where you can set default monospace font, you're not able to do so under Windows. It's fine in recent Windows 10 since it uses Consolas by default but in Windows 7, which is still widely used for development, default is something totally ugly.

Therefore I don't think it's a good idea to just specify `monospace`. Adjusting the list to be `Consolas, Monospace` sounds OK though.

**Comment by rimas-kudelis** [comment]
What I meant was that this is probably configurable in the browser, but I only had Firefox in mind, and I'm not sure if Chrome or IE allow configuring these font settings.

`Consolas, monospace` is fine by me. I just really don't want `Courier` or `Courier New` in that list. :)
