### ISSUE TITLE
Empty assets folders

### ISSUE THREAD

**Issue by Hsidhu** [yiisoft/yii2#14083]
Hello,

I am having a problem with assets folder and files. It creates empty folders. 
I checked permission on folder which looks good. Some folder has files and some don't.

Even yii.js and bootstrap.js doesn't get created in the asset.
I tried `composer clearcache`, `composer  dump-autoload` and `composer  update`. Didn't  fix the problem.

I am using Yii 2.0.12 version and PHP 7.0.12 and OS windows

Thanks in advance

**Comment by samdark** [comment]
We need more info on how to reproduce the issue exactly.

**Comment by Hsidhu** [comment]
Thanks for reply  
I don't really know whats causing it?
I delete all the folders in the assets folder and reload everything still go same error.
![yii2-assets file](https://cloud.githubusercontent.com/assets/6515812/25662737/90526732-2fe3-11e7-8517-068758d779f8.PNG)

**Comment by SilverFire** [comment]
http://173.231.102.80/assets/4d83c3d2/yii.validation.js

According to the response headers, Abyss web server tries to handle requests to assets with PHP:

```
Status Code:500 Internal Server Error
Server:Abyss/2.11.2-X1-Win32 AbyssLib/2.11.2
```

Directory http://173.231.102.80/assets/4d83c3d2/ is empty.
Probably, web server does not have sufficient permissions to write files in it.

The problem is out of Yii scope.

**Comment by Hsidhu** [comment]
It was composer error. Composer didn't clone all those files in vendor folder.
