### ISSUE TITLE
the ezyang/htmlpurifier  need  ‘log‘  config ？？

### ISSUE THREAD

**Issue by lxp521125** [yiisoft/yii2#14174]
### What steps will reproduce the problem?

I changed the log of the configuration file, just use graylog, found in the change menu, there will be an error, can not create the directory.
![image](https://cloud.githubusercontent.com/assets/13718014/26183250/37da911e-3bb0-11e7-8551-dd69d165c2c0.png)

Now I find the problem is: This component uses the directory structure created by log, resulting in the success of the creation of multi-level directory. Throws an exception that does not have a base directory.

the OK‘s log config：
![image](https://cloud.githubusercontent.com/assets/13718014/26183396/0f4a7984-3bb1-11e7-9b22-385a80e8da3b.png)

when you del the file config and del the cache will found error;

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.6
| PHP version      |  5.6
| Operating system | Linux

**Comment by samdark** [comment]
How would you propose solving the problem?

**Comment by cebe** [comment]
I don't understand the problem description, how is HtmlPurifier related to logging?

**Comment by lxp521125** [comment]
the log component  will create directory.like 'thebase/admin/runtime/'.  and the HtmlPurifier use the dir like 'thebase/admin/runtime/HTML/',  when the log not create directory, just ues web , the HtmlPurifier will error.

**Comment by cebe** [comment]
the runtime directory of a Yii application is expected to exist and to be writeable. it should not be automatically created by the application.

The issue is a problem with HtmlPurifier then, which does not create directories recursively:

https://github.com/ezyang/htmlpurifier/blob/65d5cdee50ebd9a11b3d1bb907f27144b734cea9/library/HTMLPurifier/DefinitionCache/Serializer.php#L222

Please report to their issue tracker instead.
