### ISSUE TITLE
yii.activeForm.js and dinamically fields validation.

### ISSUE THREAD

**Issue by vova07** [yiisoft/yii2#1422]
`AJAX` validation work fine for static fields, but if we'll try to add some fields dinamically with `Javascript`, they will not be validated on client side. I mean that error classes, and error messages will not be added to the page because for `yii.ActiveForm` they just not exist.
The problem is [here](https://github.com/yiisoft/yii2/blob/master/framework/yii/assets/yii.activeForm.js#L141):
```
...
$.each(attributes, function (i) {
    attributes[i] = $.extend({value: getValue($form, this)}, attributeDefaults, this);
});
$form.data('yiiActiveForm', {
	settings: settings,
	attributes: attributes,
	submitting: false,
	validated: false
});
...
var errors = [];
$.each(data.attributes, function () {
	if (updateInput($form, this, messages)) {
		errors.push(this.input);
	}
});
...
```

**Comment by gauravparashar12** [comment]
@samdark @qiangxue @6pblcb @vova07  what is the correct method to validate dynamically added form fields of another model .I search all arround but i am not finding please help me out .what i use in js and correct method. http://stackoverflow.com/questions/31286133/yii2-add-dynamic-form-fields-and-their-validations

**Comment by samdark** [comment]
https://github.com/samdark/yii2-cookbook/blob/master/book/forms-activeform-js.md ?

**Comment by gauravparashar12** [comment]
@samdark  Thanks for the reply ,but do you have any doc how to use in my form

**Comment by samdark** [comment]
Not yet.

**Comment by gauravparashar12** [comment]
@samdark  Ok ,so do you provide me the solution i am stuck in this situation that how i validate my dynamic fields added . for example :i have form in which fields are dependent on dropdown change then the newly dynamic fields added are not validate properly .

**Comment by samdark** [comment]
I guess in this case you have to come up with custom validation coded in JS.

**Comment by gauravparashar12** [comment]
@samdark  will you please provide me a simple example so that i can use it properly .
I am stuck in this situation . http://stackoverflow.com/questions/31286133/yii2-add-dynamic-form-fields-and-their-validations

**Comment by gauravparashar12** [comment]
@samdark i already did with custom js on many of my project but i am still finding the correct and best method for validate dynamically added fields in form.

**Comment by gauravparashar12** [comment]
@samdark can you please translate this http://habrahabr.ru/post/239147/ blog in English i am stuck in the same situation.

**Comment by samdark** [comment]
It's a big article. Will take time to translate it...

**Comment by duynguyen0511** [comment]
@gauravparashar12 use Chrome and google translate for  http://habrahabr.ru/post/239147/ . It is decent translation

**Comment by andrewblake1** [comment]
@gauravparashar12 and whoever else is looking for reason why and a simple solution for ajax added fields not triggering validation.

In your view or as per answer at http://stackoverflow.com/questions/31286133/yii2-add-dynamic-form-fields-and-their-validations do something like:
```
foreach ($form->attributes as $attribute) {
    $attribute = Json::htmlEncode($attribute);
    $this->registerJs("jQuery('form').yiiActiveForm('add', $attribute);");
}
```
The validation data is stored in the form and not the field. Therefore if you dynamically add fields and not the form you need to get the validation out of the ActiveForm on the server ($form->attributes) and add it into the form in the client.

**Comment by andrewblake1** [comment]
@samdark, further to my last comment above re the commented problem described by @gauravparashar12 (not sure if the original issue was raised regarding fields created in javascript or added via ajax so could be a new issue).

Rather than documenting a solution (like my comment above), could it be worth considering altering ActiveField and ActiveForm suitably such that the 'attribute' validation object is stored with the field rather than in array within the form.

I haven't looked too deeply into the inner workings of ActiveForm and ActiveField but it would seem that perhaps the magic might happen by ActiveForm handling bubbled events raised on the fields (blur and change) and then using the array of attribute validation objects attached to a data element in the form to handle the event. Could this not be altered in a minor way so that instead of getting the attribute validation object out of the array of objects in the form, it takes it from the field/input instead?

If done this way then @gauravparashar12  and anybody else using ajax (pjax etc) to retrieve fields dynamically wouldn't need to do anything special (like above) - client validation would just work.

**Comment by samdark** [comment]
Closing since cookbook is now linked from validation guide.

**Comment by icyfox-bupt** [comment]
@samdark @qiangxue 
I use the `$('$#w0').yiiActiveForm('add', 'xxx')` and `$('$#w0').yiiActiveForm('remove, 'xxx')` , they did work and I can see the object changed in attributes, but there is no change on webpage, did I miss something or this function was not designed for dynamically add form field?

**Comment by samdark** [comment]
No. It is for adding validation only. No the field itself.
