### ISSUE TITLE
Unexpected content in AJAX response.

### ISSUE THREAD

**Issue by andriykonoz** [yiisoft/yii2#14285]
### What steps will reproduce the problem?
1. Use \yii\web\Controller::renderAjax for render view with ActiveForm in try/catch section.
2. Throw exception during view rendering after render part of view.
3. Handle exception in try/catch section.
4. Send JSON (or any other) response.

### What is the expected result?
Expected result is formed by your handling logic response.
### What do you get instead?
Before handling logic response placed part of ActiveForm that was rendered before exception.

### Additional info
Caused by missing error handling in  \yii\web\View::renderAjax. 
I think https://github.com/yiisoft/yii2/blob/2.0.12/framework/web/View.php#L212 must be placed in try/catch section. If exception occurred, we should call ob_get_clean in catch section and throw this exception again.
| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 7.1
| Operating system | Ubuntu 16.04

**Comment by andriykonoz** [comment]
@samdark 
Controller action:
```
public function actionAjaxGetEditModal()
    {
        $response = ['error' => false];

        try {
            /** Unimportant code **/
            $response['form'] = $this->renderAjax('editMappingForm', $params);
        } catch (Exception $e) {
            $response['error'] = true;
            Flashes::setFlash('mapping', $e->getMessage(), Flashes::TYPE_ERROR);
        }

        $response['flashMsg'] = Flashes::getAllFlashes();
        Yii::$app->response->format = Response::FORMAT_JSON;

        return $response;
    }
```

View (php file):
```
<?php
declare(strict_types = 1);
use yii\bootstrap\ActiveForm;

?>
<div>
    <?php $form = ActiveForm::begin([
            'id' => 'edit_mapping_form',
            'enableAjaxValidation' => false,
            'enableClientValidation' => false,
            'validateOnChange' => false,
            'validateOnSubmit' => false,
        ]
    ) ?>
    <div class="row">
        <?= $form->field($model, '_id')->hiddenInput()->label(false);
        throw new Exception()?>
    </div>
    <?php ActiveForm::end(); ?>
</div>
```

Response:
```
<![CDATA[YII-BLOCK-HEAD]]><![CDATA[YII-BLOCK-BODY-BEGIN]]><div>
        <div class="row">
        <div class="form-group field-brandmapping-_id">

<input type="hidden" id="brandmapping-_id" class="form-control" name="BrandMapping[_id]" value="5926c77d2a64d100220425c2">

<p class="help-block help-block-error"></p>
</div>{"error":true,"flashMsg":{"__flashes-mapping":{"message":"","type":"error"}}}
```

**Comment by samdark** [comment]
Unable to reproduce it.

**Comment by lieszkol** [comment]
I had the exact same issue: calling a view inside a controller action try-catch block, with some error handling. If the view crapped out then YII2 would generate "<![CDATA[YII-BLOCK-HEAD]]><![CDATA[YII-BLOCK-BODY-BEGIN]]>" inside of the response. 

I guess this is because [View.php](https://github.com/yiisoft/yii2-framework/blob/master/web/View.php) uses php buffers to store the generated output and it had already put the CDATA tags in the buffer but never got to endPage which would have replaced the CDATA with the actual head/body etc.

So the solution in this case is to run [ob_clean();](https://www.php.net/manual/en/function.ob-clean.php) to clear/erase the output buffer before generating some useful output to handle your error. 

So something like this:
```
public function actionWhatever()
	{
		$retVal = '';
		try {
			$retVal = $this->renderAjax('device-list', [
			]);
		}
		catch (\Exception $e) {
			if ($e instanceof \yii\base\ExitException) {
			    throw $e;	// Thrown by: Application->end(), must rethrow it
			}
			\Yii::$app->errorHandler->logException($e);
			ob_clean();
			$retVal = $this->renderRaw('@app/views/application/systemportfolio/error', ['exception' => $e]);
		}
		return Json::encode($retVal);
	}
```

**Comment by Commifreak** [comment]
Exact same issue. Costs some time to find that.

We also have an try/catch block and if it raises a ViewNotFound Exception, the output gets scrumbled:

`<![CDATA[YII-BLOCK-HEAD]]><![CDATA[YII-BLOCK-BODY-BEGIN]]>` and the beginning instead of the `link hrefs`

But it happens only if the source page gets requestetd via AJAX and if you call another **renderAjax** inside that, in between a try/catch block.

* jQuery AJAX GEt to controller/action => this action calls `return $this->renderAjax` and inside this:

```php
						try {
							$return .= Yii::$app->view->renderAjax( 'view' );
						} catch ( ViewNotFoundException $e ) {
							Yii::error( "View not found!", __METHOD__ );
//							Yii::error( $e );
							$return .= "VIEW NOT FOUND!";
						}
```

So: Its about nested renderAjaxes, @samdark . Maybe there is no way to fix it but I think exactly this constellation is the reason.

**Comment by Commifreak** [comment]
I would suggest, that Yii checks the existence of the view BEFORE the `ob_` things starts.

Currently the View::findViewFile does NOT check the existence of the file, it just gets the path.
`View::renderFile` checks the existence but that seems too late, because the buffer things already got called.

I dont know if there would be an issue, to move the `if (is_file($viewFile)) {` from `renderFile` to `findViewFile` method.

**Comment by bizley** [comment]
This sounds like a reasonable thing to do with that check you suggest. Could you prepare the PR?

**Comment by Commifreak** [comment]
It seems, that my idea breaks BC. The Test https://ci.appveyor.com/project/samdark/yii2/builds/44659337#L196 fails, because these theme specific tests are handled later, inside `renderFile`: `if ($this->theme !== null) {`

So, I believe some other dev should check the feasibility of this idea.
