### ISSUE TITLE
[ENH] Inlude cache query in request

### ISSUE THREAD

**Issue by pana1990** [yiisoft/yii2#14306]
let's me explain with example : 

```php
// execute query
$record = MyRecord::findOne(1);
// get from cache query
$record = MyRecord::findOne(1);
```
Currenly it executes two queries, it's true that i can cache it but sometimes it is not easy, for example when it executes from extensions where you can't modified code or when it executes in differentes places  (layouts, model, controllers, views...)

Rails and others frameworks has this behaviour in her ActiveRecord.

What do developers think about it ?

**Comment by Offout** [comment]
But what if data in DB changed between two queries? I think there is no way to implement this by default. RoR can do caching like you say, as, I think, many Java applications do. But Java, RoR are non stateless like PHP. PHP is "born to die" between requests. And this sort of caching have great bonus when you applikation "lives" more than one second. And don't forget about two greatest programming problems: cache invalidation and naming things.

**Comment by pana1990** [comment]
@offout this type cache already implementend in other places (rbac, relations, url...).


if you execute any query that it can change the database then the cache should clear.

**Comment by Offout** [comment]
@pana1990 Offout this type cache already implementend in other places (rbac, relations, url...).
But eventually, you will have all DB in cache. This can consume realy huge piece of memory.
And what must be cached? Serialized model, or just "toArray"?
And they will be in cache just by their id, or you want to get it from cache by some ->andWhere() too?

**Comment by samdark** [comment]
It clearly should not be done by default because you may actually need to have two separate objects that may differ in data.

The question is do you want it to be cached per request? If yes, that's called identity map. While it may improve performance it also would introduce invalidation problems and complicate DB layer.

**Comment by samdark** [comment]
@yiisoft/core-developers thoughts?

**Comment by klimov-paul** [comment]
I am against such change:

1) automatic caching of any `ActiveRecord::findOne()` will deplete the memory in case you are searching for the different records:

```php
$item1 = Item::findOne(1);
// ...
$item2 = Item::findOne(2);
// ...
$item3 = Item::findOne(3);
```

2) What is the problem of using `Connection::beginCache()`/`Connection::endCache()`? If you wish to cache particular requests you can use those: it will create the same cache key for all queries built by `ActiveRecord::findOne(123)`.

> if you execute any query that it can change the database then the cache should clear.

This can happen only if you updating data via ActiveRecord, while it is not always so: you can run SQL like:

```sql
UPDATE `Item` SET (...) WHERE categoryId IS NOT NULL
```

which will change the data for several records at once, while PK for thoses records are uknown.

> Currenly it executes two queries, it's true that i can cache it but sometimes it is not easy, for example when it executes from extensions where you can't modified code or when it executes in differentes places (layouts, model, controllers, views...)

You should control your program on your own. It is a pretty weird that you are fetching the same single(!) model several times during the page rendering.
Quering same result often happens for the list of models, while building drop-down lists for the filters or menues. But this should be handled manually be developer. In particular: for drop-down composition it is better to cache the final `value => name` pairs instead of the whole ActiveRecord instance.

You may create a `Lookup` component or extend ActiveQuery adding necessary functionality:

```php
class ItemQuery extends \yii\db\ActiveQuery
{
    private static $cachedRecords = [];

    public function oneCached($pk)
    {
        if (!isset(self::$cachedRecords[$pk])) {
            self::$cachedRecords[$pk] = static::findOne($pk);
        }
        return self::$cachedRecords[$pk];
    }
}
```

**Comment by pana1990** [comment]
@klimov-paul nice tip, i agree with you.

@samdark maybe this issue is better move to cookbook with that code example?

**Comment by samdark** [comment]
@pana1990 I don't think it's common enough to be in cookbook.
