### ISSUE TITLE
Why do you support two versions?

### ISSUE THREAD

**Issue by Rishats** [yiisoft/yii2#14328]
Why do you support two versions?
And how long will you support the two versions?
Yii 1 and Yii 2?

What is better to choose for development?

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0
| PHP version      | 7.1
| Operating system | Linux

**Comment by Charius** [comment]
https://github.com/yiisoft/yii/blob/master/README.md

**Comment by georgekaf** [comment]
http://www.yiiframework.com/news/90/update-on-yii-1-1-support-and-end-of-life/

**Comment by xiaoxing598** [comment]
I suggest you choose version 2.x

**Comment by cebe** [comment]
> Why do you support two versions?

Because upgrading from 1.1 to 2.0 is similar to the effort of a rewrite and a lot of projects do not have the budget to do that.

> And how long will you support the two versions?

For Yii 1.1:
Security support until 	Dec 31, 2019 (may be extended further if needed) 
http://www.yiiframework.com/download/#yii1

Support for 2.0 will be announced when 2.1 is released.

> What is better to choose for development?

We recommend to use Yii 2.0 for new projects. See http://www.yiiframework.com/news/137/yii-1-1-19-is-released/

**Comment by Rishats** [comment]
Thank you so much :)
