### ISSUE TITLE
wrong bower path alias

### ISSUE THREAD

**Issue by konorlevich** [yiisoft/yii2#14324]
### What steps will reproduce the problem?
Fresh-installed yii2 base app

### What do you get instead?
Invalid Parameter – yii\base\InvalidParamException
The file or directory to be published does not exist: /home/travkin/my_hosts/united_ua/vendor/bower/jquery/dist

### Way to resolve
/vendor/yiisoft/yii2/base/Application.php line 461
```php
Yii::setAlias('@bower', $this->_vendorPath . DIRECTORY_SEPARATOR . 'bower');
```
change to 
```php
Yii::setAlias('@bower', $this->_vendorPath . DIRECTORY_SEPARATOR . 'bower-asset');
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12

**Comment by shirase** [comment]
@konorlevich  i think you need upgrade your `fxp/composer-asset-plugin` because installer-paths format is changed, and old version do not understands new format and installs to default bower-asset folder. Try run `composer global require fxp/composer-asset-plugin`.

**Comment by sizeg** [comment]
define aliases in your config:

```
'aliases' => [
    '@bower' => '@vendor/bower-asset',
    '@npm'   => '@vendor/npm-asset',
],
```

**Comment by sizeg** [comment]
This string `Yii::setAlias('@bower', $this->_vendorPath . DIRECTORY_SEPARATOR . 'bower');` cann't be changed cause of bc break

**Comment by moltam** [comment]
I had the same problem with `fxp/composer-asset-plugin 1.2`. The error disappeared after upgrading the plugin to version `1.3`.

In `Yii 2.0.12` the config options for the asset-plugin have changed ([see](https://github.com/yiisoft/yii2-app-advanced/commit/785c933ba31c0827dfdab92363898b461d7d40e3)), because the old config format was deprecated, and changed in [fxp/composer-asset-plugin v1.3](https://github.com/fxpio/composer-asset-plugin/releases/tag/v1.3.0).

The section for the asset-plugin has been removed from the install guide in the master branch, and this causes confusion for new installs. This has been discussed at the [related commit](https://github.com/yiisoft/yii2/commit/9a18748e1f68fd51fa08c2c99bffa190281d144d#diff-ac5b77d7f1a2bbf990a4d64f84ac3c95L61).

**Comment by schmunk42** [comment]
Related https://github.com/fxpio/composer-asset-plugin/issues/293

**Comment by SilverFire** [comment]
@konorlevich Have you installed application template as it is listed [in the manual](https://github.com/yiisoft/yii2-app-basic#install-via-composer)?

**Comment by bahirul** [comment]
I had same problem, where i want overrides @bower, @npm, @vendor dir.
I set alias on a bootstrap file, but seem yii/base/Application overrides it.
Maybe on setVendorPath method you can add validation is @bower, @npm, @vendor not null.
So use value from Yii::setAlias on bootstrap file.

Thanks.

**Comment by bahirul** [comment]
Or maybe we can use oomphinc/composer-installers-extender globaly for replace fxp/composer-asset-plugin.
And then add : 

`"extra": {
        "installer-types": ["bower-asset", "npm-asset"],
        "installer-paths": {
            "vendor/bower/{$name}": ["type:bower-asset"],
            "vendor/npm/{$name}" : ["type:npm-asset"]
        }
    },`

I solve my problem by doing this.

**Comment by konorlevich** [comment]
>  i think you need upgrade your fxp/composer-asset-plugin because installer-paths format is changed, and old version do not understands new format and installs to default bower-asset folder. Try run composer global require fxp/composer-asset-plugin

Thank you, it works
