### ISSUE TITLE
Unable to override yii\validators\Validator using Yii::$container->set()

### ISSUE THREAD

**Issue by senguttuvang** [yiisoft/yii2#14409]
### What steps will reproduce the problem?
Yii::$container->set('yii\validators\Validator', 'app\components\Validator');

### What is the expected result?
It supposed to invoke the init() method.

### What do you get instead?
The custom class's init() method not honoured

### Additional info

I'm trying to override the core validator so I can add 'code' & 'shortMessage' properties. The overriding of core class works for yii\db\ActiveQuery but did not work for Validator.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | 7.1
| Operating system | Ubuntu 16.04

**Comment by cebe** [comment]
Validator itself is never instantiated, only classes that extend from it, thus DI does not apply to what you have set. If you want to replace a core class of Yii, you need to configure the Yii::$classMap to replace it.
This however should be done only in very rare cases where you can't find another way, otherwise upgrading Yii may break as your class gets out of sync with the Yii implementation.
