### ISSUE TITLE
doc http://www.yiiframework.com/doc-2.0/guide-rest-quick-start.html deprecated

### ISSUE THREAD

**Issue by des1roer** [yiisoft/yii2#14457]
### What steps will reproduce the problem?
http://www.yiiframework.com/doc-2.0/guide-rest-quick-start.html

### What is the expected result?
this tutorial don`t work

### What do you get instead?
update this tutorial

### Additional info
https://toster.ru/q/442841

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 7.1.0
| Operating system | Win 10 x64

**Comment by tunecino** [comment]
why?? REST works fine for me by just following documentation. 

Yes you need CORS for preflight requests but that can be added as a note and not as a requirement because it is a web browsers thing and REST is not meant to be only consumed by web browsers. (*cors part was documented [here](http://www.yiiframework.com/doc-2.0/guide-rest-controllers.html#cors)*)

The other maybe missing note is remembering people to not skip this part when installing Yii:
http://www.yiiframework.com/doc-2.0/guide-start-installation.html#configuring-web-servers

also that link is mixing REST and WEB apps. the following shouldn't be used for rest:
```php
'request' => [
            'enableCookieValidation' => true,
            'enableCsrfValidation' => true,
```
REST should be stateless. mixing both isn't correct IMHO.

**Comment by des1roer** [comment]
https://gitlab.com/des1roer/yii2game don`t work
