### ISSUE TITLE
HttpBearerAuth filter is not calling validateAuthKey() of the IdentityInterface

### ISSUE THREAD

**Issue by waza-ari** [yiisoft/yii2#14461]
### What steps will reproduce the problem?
Create any module (in my case REST API module) and protect a controller using the HttpBearerAuth filter. Use a custom User Model as Identity:

```php
'user' => [
     'class' => 'common\components\UserComponent',
     'identityClass' => 'common\models\User',
     'enableSession' => false,
     'loginUrl' => null,
],
```

Actually I moved the auth_key to a separate table, which is why I defined the `findIdentityByAccessToken()` function as follows. 

```php
public static function findIdentityByAccessToken($token, $type = null)
{
    return Token::findOne(['auth_key' => $token])->user;
}
```

I did not check the validity of the auth_token at this point, as the name is `findIdentity...` and there is the `validateAuthKey()` function as well, which is implemented as follows:

```php
public function validateAuthKey($authKey)
{
    $auth_key = Token::findOne(['auth_key' => $authKey, 'user_id' => $this->id, 'active' => true]);
    return $auth_key && $auth_key->valid_until >= time();
}
```
 
However during my tests it looks like the validateAuthKey is never called and evaluated. If `findIdentityByAccessToken` returns a identity, the login using the auth_token is accepted.

### What is the expected result?

Only looking at the name of the functions, I would have assumed that `validateAuthKey` is used, well, to validate the auth key before it is accepted. Hence I would accept an access request auth an expired auth key to be rejected.

### What do you get instead?

When using an expired auth key, the request is accepted nevertheless. Looking at the actual implementation of `yii\web\User::loginByAccessToken', it assumes the class to be implementing the `IdentityInterface`interface. Hence we can safely assume that the IdentityClass implements the `validateAuthKey()` function, so I would expect this to be used. 

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 7.0.14
| Operating system | Debian 8.6

**Comment by waza-ari** [comment]
As a workaround, I created a custom `UserComponent` class extending `yii\web\User` and changing the `loginByAccessToken` method as follows:

```php
public function loginByAccessToken($token, $type = null)
{
    /* @var $class IdentityInterface */
    $class = $this->identityClass;
    $identity = $class::findIdentityByAccessToken($token, $type);
    if ($identity && $this->login($identity) && $identity->validateAuthKey($token)) {
        return $identity;
    } else {
        return null;
    }
}
```

I simply added ``` && $identity->validateAuthKey($token)```, my suggestion would be to add this to the base class.

**Comment by tunecino** [comment]
Those are the only places I've seen `getAuthKey()` and `validateAuthKey()` being called:

```php
yii/web/IdentityInterface::sendIdentityCookie($identity, $duration)
yii/web/IdentityInterface::getIdentityAndDurationFromCookie()
```
Also In documentation of both it says: 

> This is required if `User::enableAutoLogin` is enabled.

So I guess they where only meant to be used with cookie's related token. Their naming was confusing to me too but I don't think they should be involved with rest because there still many implementations not respecting the recommended stainless nature of it. Also in theory HttpBearerAuth should involve 2 different kind of tokens: refresh and access tokens. Having the same method to validate different kind of tokens for OAuth2 and cookies doesn't look correct. 

In such case of not involving cookies I'd suggest disabling them like I have done [here](https://github.com/tunecino/yii2-app-builder/blob/master/auth/models/User.php#L66-L80) the same way it was done for `findIdentityByAccessToken()` in the web interface of the advanced template, then different validators should be introduced for OAuth2 or bearer related tokens.

**Comment by samdark** [comment]
Access token is not the same as auth key so it doesn't make sense.
