### ISSUE TITLE
Problem with hasMany() and onCondition() + orOnCondition()

### ISSUE THREAD

**Issue by hagier** [yiisoft/yii2#14503]
Hello,

I have two tables:

|- currency -|
|| CurrencyID ||
|| Name ||

|- currency_pair -|
|| BuyCurrencyID || ==> FK -> CurrencyID
|| SellCurrencyID || ==> FK -> CurrencyID

I have relation in Currency model - getCurrencyPairs(). I need it to retrieve information about all CurrencyPair either having this Currency in BuyCurrencyID or in SellCurrencyID.

My code usage for retrieving records:

> $currencies = Currency::find()
>                         ->joinWith('currencyPairs')
>                         ->where(['MarketID' => $market->MarketID])
>                         ->all();

1. My first thought was to use onOrCondition like this:

> public function getCurrencyPairs()
>     {
>         return $this->hasMany(CurrencyPair::className(), ['BuyCurrencyID' => 'CurrencyID'])
>             ->orOnCondition(['SellCurrencyID' => 'CurrencyID']);
>     }

But this is generated query:

> SELECT `currency`.* FROM `currency` LEFT JOIN `currency_pair` ON (`currency`.`CurrencyID` = `currency_pair`.`BuyCurrencyID`) AND (`SellCurrencyID`='CurrencyID')

First problem is that there is "AND" instead of "OR". Second problem - there are no table prefixes.

2. Second one was to change it a little bit and give empty array to hasMany condition and use onCondition().

> public function getCurrencyPairs()
>     {
>         return $this->hasMany(CurrencyPair::className(), [])
>             ->onCondition(['BuyCurrencyID' => 'CurrencyID'])
>             ->orOnCondition(['SellCurrencyID' => 'CurrencyID']);
>     }

But generated query is looking like this:

> SELECT `currency`.* FROM `currency` LEFT JOIN `currency_pair` ON (`BuyCurrencyID`='CurrencyID') OR (`SellCurrencyID`='CurrencyID')

First problem - there are single quotes around CurrencyID so it's used like string. Second problem - no table prefixes at all.

I tried many different options but I can't get expected results. What am I doing wrong here? Am I missing something important on generating queries or usage?

**Comment by cebe** [comment]
You can not create a relation that points to two foreign keys at once, you need to create a normal query for that instead.

**Comment by pxao02** [comment]
Should it be of help to someone with the same problem, a workaround would be to define two separate relations both pointing to the same target table. 

As in the above example with the currency pairs, define in the Currency ActiveRecord class:

```
public function getBuyCurrency()
{
    return $this->hasMany(CurrencyPair::className(), ['BuyCurrencyID' => 'CurrencyID']);
}
```
And
```
public function getSellCurrency()
{
    return $this->hasMany(CurrencyPair::className(), ['SellCurrencyID' => 'CurrencyID']);
}
```
And then use in your query:
```
$query = Currency::find()
    ->select(' `currency_pair`.*, `b`.*, `s`.*) //Skip or use your own select here depending on your needs
    ->joinWith(['buyCurrency b', 'sellCurrency s']); //Using aliases to avoid ambiguity
$query->all();
```
Make sure to refer to the proper table name when getting your fields, otherwise you may encounter errors concerning the ambiguity of variables. 

I found this approach to work well with Search classes for a Gridview where filtering needs to be done straight on the relations, but in every other place where I just want to get the value of the relational data, to use a with() statement for easier identification (at the cost of the extra queries).

E.g. in a Search class (same query as above without the all() part):
```
$query->andFilterWhere(['like', 'b.name', $this->buyName)
    ->andFilterWhere(['like', 's.name', $this->sellName);
```

And for other cases:
```
$currencies = Currency::find()->with(['buyCurrency', 'sellCurrency'])->all();

foreach($currencies as $record){
    $buyName = $record->buyCurrency->name;
    $sellName = $record->sellCurrency->name;
}
```
