### ISSUE TITLE
Migrations: Can't add tinyint column after another column

### ISSUE THREAD

**Issue by gvanto** [yiisoft/yii2#14638]
Following on from this post: https://github.com/yiisoft/yii2/issues/11049

### What steps will reproduce the problem?
```php
$tinyInt = (new yii\db\ColumnSchemaBuilder('tinyint', 1, $this->db))->after('image_src_filename')->notNull();
        $this->addColumn('blog_site', 'is_published', $tinyInt);
```

### What is the expected result?
Expecting to see column added after the 'image_src_filename' column

### What do you get instead?
Column is added but at end of table ('after()' command seems to be ignored)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12?
| PHP version      | 5.6
| Operating system | ubuntu

**Comment by samdark** [comment]
What's the database you're using? If it's MySQL, which engine? Does it behave like that with all column types or tinyint only?

**Comment by gvanto** [comment]
MySql with innodb

Doesn't happen with other fields created with for example this->smallInteger

**Comment by rob006** [comment]
You should use `yii\db\mysql\ColumnSchemaBuilder` in this case. `yii\db\ColumnSchemaBuilder` is more general and does not support `after()`.

```php
$tinyInt = (new yii\db\mysql\ColumnSchemaBuilder('tinyint', 1, $this->db))->after('image_src_filename')->notNull();
```

But probably better option is:

```php
$tinyInt = $this->getDb()->getSchema()->createColumnSchemaBuilder('tinyint', 1, $this->db))->after('image_src_filename')->notNull();
```
___

Anyway missing support of `tinyint` in core is really PITA. Right now I'm using something like:

```php
public function tinyint($length = null) {
	return $this->getDb()->getSchema()->createColumnSchemaBuilder('tinyint', $length);
}
```

and

```php
$this->tinyint()->unsigned()->notNull()->defaultValue(0)
```

And it simply does not work as expected - `unsigned()` is silently ignored. That's because `tinyint` is not considered as numeric type,  so unsigned clause is ignored.

https://github.com/yiisoft/yii2/blob/ae83dd0524cab9841b9632c0c904aaac506a4a57/framework/db/mysql/ColumnSchemaBuilder.php#L57-L69

https://github.com/yiisoft/yii2/blob/ae83dd0524cab9841b9632c0c904aaac506a4a57/framework/db/ColumnSchemaBuilder.php#L81-L106

I have no idea how to fix this in clean way (without hardcoded `TINYINT UNSIGNED...`). Can't we just add `tinyint()` shortcut that will fallback to `smallint()` in other DB engines? This will really help writing database-agnostic migrations, when `tinyint` is preferred type. This could be easy implemented at framework level, and is really problematic at app/extension level.

**Comment by gvanto** [comment]
Thanks @rob006 this worked!  I agree with your idea about having tinyint() fall back to smallint() too ...
