### ISSUE TITLE
Cannot use DI in migrations

### ISSUE THREAD

**Issue by vtvz** [yiisoft/yii2#14864]
I try to use DI everywhere. But I cant define dependency in Migration, like
```php
public function __construct(CronTab $cronTab, array $config = [])
```
And why don't you use something line this:
```php
return Yii::createObject([
    'class' => $class,
   ...
]);
```
Instead of this:
https://github.com/yiisoft/yii2/blob/9c83703a0639bf64172ef88f0c58e5a73c61b446/framework/console/controllers/MigrateController.php#L188

**Comment by SilverFire** [comment]
Would you like to create a pull request?

**Comment by vtvz** [comment]
@SilverFire I'll try

**Comment by rob006** [comment]
This is probably a bad idea. Migrations should be independent from application logic and you probably should not use other components at all.

Read notes in http://www.yiiframework.com/doc-2.0/guide-db-migrations.html#db-accessing-methods

**Comment by samdark** [comment]
I partially agree with @rob006. Constant dictionaries and services still could be used.

**Comment by vtvz** [comment]
@rob006 For example, I use migrations to configure RBAC roles and CronTab schedule.
I think migrations can be used to run some scripts once, not only DB schema, but rename or move files, create roles for RBAR and a bunch other things.

@samdark In my opinion its my choice to use dependencies in constructor or not. And framework must create all classes through DI container.

**Comment by rob006** [comment]
@samdark Not really. Constant dictionaries are not really constant - they can change in future, if business logic changes. Same for services. Such dependencies are really hard to track - when you change dictionary you don't really think about migration created 2 years ago, so you're unaware that you can break it.

Obviously you can ignore this for one-shoot-app, which you create and forget, but I have 4+ year old systems, first migrations uses app components and models, and all of them are broken till now because of this. I don't think framework should promote such approach. If someone really need to use DI he can do this with `Yii::$app->get()`.

**Comment by samdark** [comment]
@rob006 how about RBAC?

**Comment by rob006** [comment]
Same story. I already moved RBAC management from migrations to console command which refresh rights tree. Now I have more clean rights structure and much less migrations.

Of course you can create services that are designed to be used in migrations and take attention on BC, but they need special attention anyway and using DI magic is a bad idea in this case.

**Comment by samdark** [comment]
@yiisoft/core-developers, @yiisoft/reviewers  need opinions.

**Comment by dmirogin** [comment]
I don't mind this changes from framework itself. If user want to shoot a knee, he will do it. We all aware about aftermath using application logic in migrations, but people still using that.

**Comment by sergeymakinen** [comment]
If devs want to use migrations as "fixers" (console helpers, etc.) - it's not a big deal to replace an one line -> I agree with @dmirogin.
