### ISSUE TITLE
[Idea] Change DI set signature?

### ISSUE THREAD

**Issue by vtvz** [yiisoft/yii2#15104]
Now setting of definition looks like this:
```php
[
    'class' => SomeClass::class,
    'prop' => 'value',
    // ... etc
]
// or 
```php
[
    [
        'class' => SomeClass::class,
        'prop' => 'value',
        // ... etc
    ],
    ['argument1', 'argumrent2'],
]
``` 

I propose to change this to something like this:
```php
[
    'class' => SomeClass::class,
    'singleton' => true,
    'config' => [
        'prop' => 'value',
        // ... etc
    ],
    'arguments' => ['argument1', 'argumrent2'],
    'call' => [ // Issue #15085
        'setSomething' => true
    ],
]
```

Maybe in v2.1. What do you think about it. 

I think it simplify things a little bit and make definitions more intuitive. In my point of view

**Comment by cebe** [comment]
`Container::set()` method has three arguments, you show arrays here. Its not clear to me, what you propose. How does this change the set() method?

**Comment by njasm** [comment]
I believe you want to change the configuration's definition syntax, not the Container set() signature..

**Comment by SamMousa** [comment]
I think that advanced syntax is just another language people must learn.
Practically it's something that can easily be done outside of the core.
Just create something like a DI helper that configures a DI container exactly how you want it based on an array configuration syntax according to your preferences.

Boolean arguments to functions are considered bad practice since and are candidates for refactoring into separate functions (`set` and `setSingleton` in this case).
Having array syntax to call generic functions just hides the fact that your configuration is code, making it less easy to check for errors as opposed to a closure.

**Comment by SilverFire** [comment]
New DI is in development: https://github.com/yiisoft/di
