### ISSUE TITLE
Question for "Upgrade from Yii 2.0.11"

### ISSUE THREAD

**Issue by turkelt0n** [yiisoft/yii2#15103]
Hello. I have a question conserning the Upgrade from Yii 2.0.11 (https://github.com/yiisoft/yii2/blob/2.0.13/framework/UPGRADE.md#upgrade-from-yii-2011)

> - yii\filters\AccessControl now can be used without user component.
In this case yii\filters\AccessControl::denyAccess() throws yii\web\ForbiddenHttpException and using AccessRule matching a role throws yii\base\InvalidConfigException

As there is only one method mentioned (denyAcess) i do assume that this mentioned method potentially throws the ForbiddenHttpException and ForbiddenHttpException. As far as the phpdoc does not show any possibility of a InvalidConfigException and i can't find any source within the denyAccess-method which would throw this exception aswell. 

I might be missunderstanding this upgrade-notice or it is in fact unclear. Could someone enlighten me if possible?

**Comment by cebe** [comment]
https://github.com/yiisoft/yii2/blob/22467864834b78236469882e6bd169144995161e/framework/filters/AccessRule.php#L227

this is what is meant with 

> using AccessRule matching a role throws yii\base\InvalidConfigException

these are two effects of using AccessControl without user component:

1. If there is no user component, `yii\filters\AccessControl::denyAccess()` throws yii\web\ForbiddenHttpException instead of redirecting to login page.
2. If there is no user component and you try to match an access rule against a role, this is a configuration error and ` yii\base\InvalidConfigException` is thrown.

**Comment by turkelt0n** [comment]
Thanks for the clarification @cebe
