### ISSUE TITLE
2.0.12 not support 2.0.13 cache

### ISSUE THREAD

**Issue by Cuihongsen** [yiisoft/yii2#15138]
### What steps will reproduce the problem?
I have two servers, one version is v2.0.12 one is v2.0.13, they use the same memcache server, the server version 2.0.12 error
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12 &2.0.13
| PHP version      | 7.1
| Operating system |centos 7

**Comment by sergeymakinen** [comment]
Since 2.0.13 there's a schema cache version check to prevent errors but it doesn't matter in this case: cache format may change from time to time and it's a bad idea to share same cache configurations across different versions.

Solution: specify a database schema cache prefix in your configuration. For example:

```php
'components' => [
    'db' => [
        'schemaCache' => [
            'keyPrefix' => 'v2012' // 'v2013' for 2.0.13
        ],
    ],
],
```

**Comment by samdark** [comment]
Forwards compatibility isn't guaranteed. Sorry.
