### ISSUE TITLE
console - silent death in relations

### ISSUE THREAD

**Issue by yurii-github** [yiisoft/yii2#15206]
### What steps will reproduce the problem?
Create relation based on language
```
    public function setCities(array $cities)
    {
        $this->unlinkAll('cities', true);

        foreach ($cities as $city) {
            $this->link('cities', $city);
        }

        return $this;
    }

    public function getCities()
    {
        return $this->hasMany(ASD::className(), ['asd_id' => 'asd_id'])
            ->where(['lang' => \Yii::$app->request->get('lang')])
            ->viaTable(ASD_trunk::tableName(), ['id' => 'id']);
    }
```

Try to set cities in console during migration

```
 $rCities[] = ASD::findOne(1);
 $rCities[] = ASD::findOne(2);
 $r->setCities($rCities);
```

### What is the expected result?
added  cities to MODEL (via trunk table)

### What do you get instead?

> Exception 'yii\base\InvalidParamException' with message 'app\models\MODEL has no relation named "cities".'

### Additional info
If I run in console
                
> \Yii::$app->request->get('lang');

It properly fails with

> 'Calling unknown method: yii\console\Request::get()'

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13.1.
| PHP version     |   7.0
| Operating system | Debian 9

**Comment by cebe** [comment]
> 'Calling unknown method: yii\console\Request::get()'

the console request can not obtain the language from a request.

> Exception 'yii\base\InvalidParamException' with message 'app\models\MODEL has no relation named "cities".'

The ActiveRecord tries to find a relation by calling the related getter, in case of UnknownMethodException it assumes that there is no such getter and thus no relation.

In your case UnknownMethodException is not thrown because of the getter but because inside the getter your call an unknown method.

As far as I see we can not improve this further. You should already see `Calling unknown method: yii\console\Request::get()` in the previous exception attached to `InvalidParamException`.

**Comment by yurii-github** [comment]
problem is really hidden in console. It returns only the last exception, and trace is useless

So, for my usecase when AR is dependent on language in console I have to put

> \Yii::$app->language = 'en_US';

But because error output is cut it lacks any info on the issue, and if your start to forget about it.. boom. 
I'll see with what solution I may come.

regards
