### ISSUE TITLE
[ENH] Add traceline to ErrorHandler

### ISSUE THREAD

**Issue by pana1990** [yiisoft/yii2#15216]
This one https://github.com/yiisoft/yii2-debug#open-files-in-ide but in the errorHandler
 view 
I want to click here(whatever line) and open file in my ide : 

![screenshot_1](https://user-images.githubusercontent.com/6630197/33221059-2ccaa3e4-d14d-11e7-8521-1d827b4e0a4b.png)

I can handle it :)

**Comment by samdark** [comment]
Let's do it.

**Comment by asamats** [comment]
Do somebody use this a function? I want to use. I love this function.
But, who tested it? I've just tried to use but I can't. First - We can't to click on a link. Second - The UI like "doesn't matter what I'll show".
Please, can we open the issue and fix it?

Thanks.

**Comment by samdark** [comment]
@asamats did you configure it as described?

**Comment by asamats** [comment]
@samdark Yes, I did. I configured my OS. From debug toolbar, I can open my IDE. From the error log, I also can but it's not easy because the link looks so strange (Chrome). Yes, if we look at the HTML code it looks correct.
![screenshot](https://user-images.githubusercontent.com/3476245/53109996-24ef6980-354b-11e9-9677-c40d57d6b82e.png)
1) Files should go one by one.
2) Links must be clickable.
