### ISSUE TITLE
TagDependency::invalidate not work

### ISSUE THREAD

**Issue by nicdnepr** [yiisoft/yii2#15295]
### What steps will reproduce the problem?

```
TagDependency::invalidate(\Yii::$app->cache, 'test_key');
        return Yii::$app->cache->getOrSet('test_key', function () use ($parent_id) {

            $tree = $this->getTree($parent_id);
            Yii::$app->cache->set('test_key', $tree, Yii::$app->params['cache'], new TagDependency(['tags' => 'test_key']));
            return $tree;

        });
```

### What is the expected result?
All calls must run without cache
### What do you get instead?
only first call run without cache

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13.1?
| PHP version      | 7
| Operating system |ubuntu 16

**Comment by MysteryDragon** [comment]
I may be wrong, but in this code you're pointing dependency INSIDE getOrSet function, and not OUTSIDE, as params for getOrSet.
That's why there will be executed `set` two times: first time with dependency, and second time - without it.
And actually this value will not have tag after that.

This must work:
```
TagDependency::invalidate(\Yii::$app->cache, 'test_key');
return Yii::$app->cache->getOrSet('test_key', function () use ($parent_id) {
    return $this->getTree($parent_id);
}, Yii::$app->params['cache'], new TagDependency(['tags' => 'test_key']));
```

**Comment by nicdnepr** [comment]
Yes it's work
