### ISSUE TITLE
[yii\base\ErrorHandler] convertExceptionToError() will convert Exception to Fatal

### ISSUE THREAD

**Issue by mikk150** [yiisoft/yii2#15306]
### What steps will reproduce the problem?

Create `yii\mail\BaseMessage` or `yii\widgets\ActiveField` that has `toString()` method which will throw \Exception

### What is the expected result?

Looking at those base files, it should return empty string

### What do you get instead?

`ErrorHandler::convertExceptionToError` converts error to Fatal error

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13.1
| PHP version      |  5.6.32
| Operating system | Ubuntu

**Comment by samdark** [comment]
It is known issue that PHP can't catch exceptions thrown in __toString(). We can do nothing about that...

**Comment by mikk150** [comment]
I'm not judging the fact, that php does not like exceptions being throwns in `__toString()` method..

![screenshot from 2017-12-07 13-32-49](https://user-images.githubusercontent.com/4953629/33713288-5bc40996-db53-11e7-9689-f2ab8e5ee31c.png)
I'm asking, why is that return there, if code is never reached there

**Comment by klimov-paul** [comment]
The final `return` reach depends on actual implementation of the `ErrorHandler::convertExceptionToError()`.
Since it triggers `E_USER_ERROR` no further code will be reachable. However in case `E_USER_WARNING` is used method return will be invoked.
Consider following example:

```php
<?php

class Test
{
    public function __toString()
    {
        trigger_error('To string error', E_USER_WARNING);
        return 'default';
    }

}

function send($object)
{
    return (string)$object;
}

$object = new Test();
@$string = send($object);

var_dump($string); // outputs "default"
```

I would rather keep `return` statement in case `ErrorHandler` is replaced using autoloading class map with different implementation of `convertExceptionToError()`.
Besides presence of the statement is good for IDE syntax check as it expect method return unawaring of `trigger_error()` inside `convertExceptionToError()`.
