### ISSUE TITLE
Creating Views on migrate

### ISSUE THREAD

**Issue by neoacevedo** [yiisoft/yii2#15426]
There is a support to create views on migrations?

I mean, `yii migrate/create create_view_myview`

Just like described in the post https://github.com/yiisoft/yii/issues/2886#issuecomment-24696462

**Comment by samdark** [comment]
No. Related to #8347. You can, of course, execute any SQL in migrations.

**Comment by vladis84** [comment]
Hello.
I want to help.
I need to make a new pull request?
Me  need finish https://github.com/yiisoft/yii2/pull/14699?

**Comment by samdark** [comment]
Yes. Make a new one based off #14699

**Comment by samdark** [comment]
Since this one is about migrations, leaving it open for now.

**Comment by samdark** [comment]
Planned for 2.1.1.

**Comment by stereochrome** [comment]
I'm creating views via createCommand() in migration files in a project with around 350 migrations. Views are a bit special. Changing a table structure can be done incrementally with migrations. Changing a view means recreating the whole thing with the changes included. So i'm constantly searching for the latest migration file which has changed a certain view. This is dangerous, because if i use the wrong file, i overwrite changes which have been done some time ago.

It might be a better way to have a single view definition file per view which can be changed and a command to refresh the views inside the database.

There is another thing, at least with mysql databases and phpmyadmin exports: The Database name the view was exported from is written in its exported structure. If imported into another database, the views are using the old database table. A command for recreating the views would be a simple way to solve this problem.

**Comment by samdark** [comment]
> It might be a better way to have a single view definition file per view which can be changed and a command to refresh the views inside the database.

That contradicts what migrations are.

**Comment by neoacevedo** [comment]
At least in MySQL/MariaDB on SQL syntax you can use **CREATE OR REPLACE VIEW** what helps to you too make changes on your views. I'm not sure if it applies for SQL Server, Oracle or PostgreSQL.

**Comment by samdark** [comment]
It applies to PostgreSQL and Oracle. MSSQL seems to be a bit different. `CREATE OR REPLACE` isn't supported by SQLite.

**Comment by neoacevedo** [comment]
Then would be useful top drop and create the view in a new migration file.

**Comment by adiramardiani** [comment]
UP :)
For added bassic support view in migration (and console command) feature @sergeymakinen , @brandonkelly , @vladis84
