### ISSUE TITLE
checkboxList wrong checked

### ISSUE THREAD

**Issue by jai3232** [yiisoft/yii2#15644]
### What steps will reproduce the problem?

 echo \yii\helpers\Html::checkboxList('test', [3, 'a'], [4, 3, 2, 1, 'a' => 'a']);

### What is the expected result?

only last 2 checkboxes are checked (key 3 and 'a').

### What do you get instead?

first check box is checked and the the last 2 checkboxes.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13
| PHP version      |  7
| Operating system | Linux Redhat

**Comment by berosoboy** [comment]
That's because the method uses in_array function (in your case) to determine if the input will be checked or not. PHP has a strange behavior in this function, due to loose comparison and type juggling.
It's explained here: 
http://www.csavino.com/php-in_array-function-avoid-string-compare-always-returning-true-2/
https://stackoverflow.com/questions/13846769/php-in-array-0-value

Currently, you need to specify your item's array keys as string.
