### ISSUE TITLE
Yii2 trace logs floating numbers wrongly

### ISSUE THREAD

**Issue by nileshanand11** [yiisoft/yii2#15752]
### What steps will reproduce the problem?
\Yii::trace(23.10, 'debug');

### What is the expected result?
23.10

### What do you get instead?
23.10000000000000142108547152020037174224853515625

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      |  5.6
| Operating system | mac os 10.12.6

**Comment by samdark** [comment]
What version of Yii is that?

**Comment by nileshanand11** [comment]
Yii2 varsion : 2.0.13

**Comment by DecoderReloaded** [comment]
The problem is here with the function `var_export(23.10, true)`. Which subsequently drills down to how actually [floating point numbers are dealt in a language](https://stackoverflow.com/questions/588004/is-floating-point-math-broken).
PHP manual warns on [_floating point numbers_](http://php.net/manual/en/language.types.float.php):

> Floating point numbers have limited precision. Although it depends on the system, PHP typically uses the IEEE 754 double precision format, which will give a maximum relative error due to rounding in the order of 1.11e-16.
