### ISSUE TITLE
Headers already sent error after upgrading to 2.0.14.1 

### ISSUE THREAD

**Issue by spiro-stathakis** [yiisoft/yii2#15782]
Following fix in #15046: Throw an yii\web\HeadersAlreadySentException if headers were sent before web response (dmirogin). I now cannot process ajax actions 

### What steps will reproduce the problem?
```php
protected function sendContent($data)
    {
            $data = 'hello'; 
            \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON; 
            echo \yii\helpers\Json::encode($data);
            Yii::$app->end();
    }
```
### What is the expected result?
An Error occurred while handling another error:
yii\web\HeadersAlreadySentException: Headers already sent in 
### What do you get instead?
Output without errors 

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14.1
| PHP version      | 7.1.8
| Operating system | macOS 10.12.6

**Comment by cebe** [comment]
this can be caused by a lot of things. The simplest workaround is probably to [enable output buffering in PHP config](https://secure.php.net/manual/en/outcontrol.configuration.php). As far as I see this is not a problem in Yii, but something in your app that is sending headers before they should be sent.

**Comment by berosoboy** [comment]
You can do this, rather than echoing it:
`\Yii::$app->response->data = $data;`

But I still think that throwing a HeadersAlreadySentException is so much radical. Maybe it will be better to log a Yii::warning;

**Comment by spiro-stathakis** [comment]
@berosoboy , Thank you. 
This is working well: 
```php 
 \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON; 
 \Yii::$app->response->data  =  $data;
```
I would rather not enable output buffering due to strict guidelines.

**Comment by samdark** [comment]
Yes, it may be a bit extreme but it tells about the problem right away, not hiding it.

**Comment by berosoboy** [comment]
@spiro-stathakis , Alternatively you can simply return the data (I prefer this way):
```
    \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
    return  $data;
```

Understood @samdark . I changed my opinion. I agree with it now. 
I refactored some old ajax calls that have echo to simply returning content. I think I was programming out of Yii2 pattern :D

Good work.

**Comment by evgenybukharev** [comment]
In console migrate controller:
`Yii Migration Tool (based on Yii v2.0.14.1)

Total 1 new migration to be applied:
	m180306_103000_partners_promo_web_url

Apply the above migration? (yes|no) [no]:y
*** applying m180306_103000_partners_promo_web_url
    > add column promo_web_url string to table {{%partners}} ... done (time: 0.524s)
*** applied m180306_103000_partners_promo_web_url (time: 0.566s)
1 migration was applied.

Migrated up successfully.
**Error: Headers already sent.**`

**Comment by samdark** [comment]
@evgenybukharev should not happen if you aren't using web config in your console app.

**Comment by cebe** [comment]
that exception is thrown in `yii\web\Response`, how did you manage to create a web response in console environment?

**Comment by evgenybukharev** [comment]
@samdark @samdark 
Sorry, the question was resolved.
When configuring the console application, the response component was inherited from yii\web\Response

**Comment by nikosid** [comment]
I had the same error with rss generation. I use https://github.com/zelenin/yii2-rss for my rss. And in 2.0.14 I got "Headers already sent error". It works for me only with "die();" at the end of action but as we know "die" is not very good solution.

**Comment by berosoboy** [comment]
@nikosid use `return` rather than echo.

**Comment by sizeg** [comment]
Change format from default HTML to RAW `Yii::$app->response->format = Response::FORMAT_RAW;`

**Comment by attybean** [comment]
I had the same problem and found this line hidden in a view file:
`<?php flush(); ?>`
I removed the line and the error was gone.

**Comment by AandD** [comment]
Is it posiible to make it optional or xdebug error like in development mode? Its very often you need to place echo or var_dump in code not starting debug

**Comment by sizeg** [comment]
@AandD what's the problem to add `exit` right after echo?

**Comment by cebe** [comment]
or enable output buffering as explained above. https://github.com/yiisoft/yii2/issues/15782#issuecomment-368553054

**Comment by ejoful** [comment]
just edit php.ini , set output_buffering = 4096 to output_buffering = On;
sed -e 's/output_buffering = 4096/output_buffering = On/g' /etc/php.ini

**Comment by gomonkey** [comment]
I had the same issue and this code save me:

```
 \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON; 
 \Yii::$app->response->data  =  $data;
```

The big problem is that I found it in dektrium user too and I can not log inside website.

Now I don't know if they solved with new version, but other extensions can have the same problem

**Comment by artmart** [comment]
There was the same issue in my (Centos7/PHP7.2) server too. I solved it by doing "php init" with root permissions user. i.e you must do "sudo php init".

**Comment by jmper** [comment]
This should definitely be added to UPGRADE.md. It is breaking change, blowing up existing applications. I know, now I learned I actually had masked header problems, which is good. But I learned it the hard way, after upgrading Yii on production server.

**Comment by HubQin** [comment]
I encounter this problem when workingg with file_get_contents() method, if I put the code: 'ob_end_flush()' before using file_get_contents(), the problem disapears.

**Comment by basic-app** [comment]
I see this error when I lost $this->beginPage() in layout,  when you have endPage without beginPage you get this error.

**Comment by nd4c** [comment]
I find this exception to be very problematic during developement.  There are times when you want debugging info displayed while working through a form or some looping scenario.  There would be no simple way to "exit" and there is no longer any view to interact with.   Kind of blows away the whole concept of debugging.

It would really be nice to have some control over whether it fires, logs an error or is simply ignored, other than setting output_buffer = On in php.ini.  I even tried setting with ini_set in the yii config files but that doesn't work.

So for now I've set the php.ini file, but I've lost the benefit of the exception.  That just doesn't seem right.

**Comment by samdark** [comment]
Simple way to exit is `exit()`.

**Comment by rob006** [comment]
In debug extension there is also "Dump" panel, so you can just use `Yii::debug()` to log some debug stuff.

**Comment by nd4c** [comment]
@samdark 
That was my point - in certain scenarios it's hard to add the exit().  

For example you're in a method that gets called many times from different places in code and you want to see what's passed to it each time it's called.  If I exit() then it breaks all future calls.

Another scenario is when you want to use a form to pass in different edge case data - exit() will prevent the form from displaying.

**Comment by nd4c** [comment]
@rob006 
I really like the way Yii::debug() displays it as pretty json.

So \Yii::debug() works, but it's not very convenient.  It takes me two mouse clicks and a scroll to see the output.  Then it takes me two more mouse clicks (on the back arrow) to get back to the page I was working on.  I did try opening the debug panel in another window - that saves a two clicks, but then I have to refresh the page - so it's six of one and a half dozen of the other.

var_dump is sooo mucher easier.  Actually since we don't have xdebug installed we use a file that we require in index.php to create a global function that wraps the var_dump in pre tags so we just call pre_dump instead:
<?php
function pre_dump() {
	ob_start();
	call_user_func_array('var_dump', func_get_args());
	$dump = ob_get_clean();

	echo '<pre style="background:#fff; color:#070; text-align:left;">';
	echo preg_replace(["/]=>\n/", "/{\n *}/"], ["] =>\t", "{}"], $dump);
	echo '</pre>';
}

I'm thinking that I can  \Yii::$app->response->data  =  $data;  instead of echo - will try that.

**Comment by nd4c** [comment]
I tried using the response->data but it didn't work.  My guess is the Yii just overwrites that when it's displaying the view.  Back to square one.

**Comment by nd4c** [comment]
I guess a more robust way to resolve this might be to save the dump to a log instead of echoing it.  That would be easy enough to implement in our pre_dump method.  I can then just view the log on another screen.  I got kind of spoiled using pre_dump/var_dump - have used that for years.  Just kind of felt like the php way of debugging.  Isn't that why xdebug even existed?  Oh well, old dog, new tricks.

**Comment by nd4c** [comment]
Sorry to keep dragging this out... but I plan a doing a lot of debugging in Yii2.  

I can think of another scenario where on screen is much easier than a log.  You're testing something in a gridview and want to see why some row data displays differently, so you echo some parameter that's passed in the column data method.  Kind of nice to have it displayed on screen next in the row/column position.  Trying to figure that out from a log would be a lot harder.

**Comment by samdark** [comment]
If it's a lot, the best way is to configure XDebug.

**Comment by nd4c** [comment]
@samdark 

Thanks.  That works.  I had uninstalled xdebug when moving to php 7.0 - I seem to remember something about some issues with it - and have been working without it since.  Apparently it works fine now.  At any rate it's only on development systems.  Sorry for all the posts - but without xdebug or setting php.ini I was having a lot of issues.  We have a major Yii1 project moving over to Yii2 along with a lot new api integration, I was getting a little frustrated.  Actually my son had xdebug and he was doing fine, ha!  It was just me, the old dog...  Again, thanks!  I've been a Yii fan for years now and am very thankful for all you folks' work.

**Comment by shanezhiu** [comment]
> @nikosid use `return` rather than echo.

why?

**Comment by bizley** [comment]
The best place for discussion about this is [Yii forum](https://forum.yiiframework.com/).
