### ISSUE TITLE
wrong condition in ActiveQuery::viaTable()

### ISSUE THREAD

**Issue by cebe** [yiisoft/yii2#15876]
See https://github.com/yiisoft/yii2/commit/64d8af61a64db0b00d498800e1f20e62b4473329#diff-1776bc9373c1dbb0d6e77ba4d8081a81L762

The change is not correct, using ActiveQuery as `$modelClass` does not make sense. The call should fail if called on a non-relational query (i.e. if primaryModel is null).

**Comment by SilverFire** [comment]
Despite it was a bug, it did not affect working code because the `viaTable()` call on empty `primaryModel` does not make sense and could be caused only by wrong manual configuration of the `ActiveQuery` object.

**Comment by SilverFire** [comment]
Heh, actually it makes sense. Thanks to failed tests to point that out :)
It makes sense for `viaTable()` called from other query closure (like [this](https://github.com/yiisoft/yii2/blob/025dd072c6bcb6aa3b81cb3c8c130b84c3d1919c/tests/framework/db/ActiveRecordTest.php#L547)) during lazy loading of relations.

Fixed with commits 025dd072c and b9ee17014
Seems to be OK now
