### ISSUE TITLE
Conditional Inflector helper method

### ISSUE THREAD

**Issue by Sarke** [yiisoft/yii2#16040]
Something like:

```php
public static function autoPluralize($count, $word)
{
	if ($count > 1)
		return self::pluralize($word);
	else
		return $word;
}
```

Most of the time when you need to pluralize something you also need to check.

**Comment by samdark** [comment]
https://www.yiiframework.com/doc/guide/2.0/en/tutorial-i18n#plural

**Comment by Sarke** [comment]
@samdark, what I was specifically trying to avoid is to have to manually put in both of the singular and the plural words in the text, especially when you have this wonderful `pluralize` method.

Using the example you linked, compare the following:

```php
echo \Yii::t('app', 'You have purchased {n} {n,plural,=0{products} =1{product} other{products}}.', ['n' => $n]);
```

We have a pluralize function, why not use it?  Something like:

```php
echo \Yii::t('app', 'You have purchased {n} {n,pluralize,products}.', ['n' => $n]);
```

Thanks.

**Comment by samdark** [comment]
There are languages such as English when the rule is simple: add `s` and that's it and there are languages where it's not simple at all and varies from word to word such as in Russian. That's why trying to automate pluralization will work for a single language application (if it's English) but you'll never ever be able to introduce more languages.
