### ISSUE TITLE
Yii DB session table tries to save twice

### ISSUE THREAD

**Issue by HenonoaH** [yiisoft/yii2#16056]
### What steps will reproduce the problem?
Just login into an application and try reproducing it.

**Comment by senguttuvang** [comment]
We maintain sessions in the table. For one specific user, when they logged-in, it attempts to create session but strangely using the same hash that is already present in the table.

Basically, the issue with the framework generating session Id that already has in the table. I believe such issues are rare considering the hashing algorithm but somehow we encountered it.

{"errorInfo":["23000",1062,"Duplicate entry 'seeion-key-generated-for-us' for key 'PRIMARY'"]}

Suggested solution: 
1. Generate a session hash using a better algorithm so the same hash would not come again ever
2. Check for existence of hash in the session table before attempting to save the newly generated hash.

The issue was originally reported by my colleague @HenonoaH  but he is new to issue tracking system so he did not add sufficient details.

**Comment by rob006** [comment]
On which version of Yii this error occurs? This may be caused by race condition and it was fixed some time ago.

**Comment by rob006** [comment]
@HenonoaH This is not really helping - Yii2 has almost 30 releases already: https://github.com/yiisoft/yii2/releases . Which one you're using? `composer show yiisoft/yii2` may be helpful.

Or try upgrade to newest version:

```
composer require "yiisoft/yii2:~2.0.15"
```
