### ISSUE TITLE
diff with use Yii; && use yii;

### ISSUE THREAD

**Issue by charleneChen** [yiisoft/yii2#16106]
use Yii seems like it refers to class Yii

use yii seems like can use yii\.. blabla namespace without back slash \, and can use Yii class as well

confused ！

**Comment by cebe** [comment]
```
use Yii;
```

includes the `\Yii` class into the current namespace, so you can use it without backslash.

```
use yii;
```

includes the `yii` namespace into the current namespace so you can refer to classes via `yii\...` instead of `\yii\...`.
Using both at the same time only works on file systems that consider Yii and yii to be the same file, it does not work on most Linux file systems.

**Comment by charleneChen** [comment]
@cebe  
read from http://php.net/manual/en/language.namespaces.rationale.php
indicates that php namespace is case-insensitive

**Comment by cebe** [comment]
> so I think use yii;, can use Yii::$app without backslash \

you can do that and it will probably work because Yii class is directly included instead of loaded by autoloading. I'd still not recommend doing that and use the proper case to avoid weird autoloading issues that might come up if Yii class is autoloaded.
