### ISSUE TITLE
Proposal to add more @throws to API docs

### ISSUE THREAD

**Issue by mikehaertl** [yiisoft/yii2#16275]
Right now not all methods that could lead to an exception have the `@throws` phpdoc directive. It's often the case that a nested call could lead to an exception. For example in the `Request` class of yii2-httpclient we have:

```php
    /**
     * Sends this request.
     * @return Response response instance.
     */
    public function send()
    {
        return $this->client->send($this);
    }
```

It's not obvious that this method can throw an Exception. To find out you have to read the source code and check the `Client` class:

```php
    /**
     * Performs given request.
     * @param Request $request request to be sent.
     * @return Response response instance.
     * @throws Exception on failure.
     */
    public function send($request)
    {
        return $this->getTransport()->send($request);
    }
```

So my question is: Shouldn't we add `@throws` everywhere? I know that this could bloat the phpdoc blocks quite a bit, because we may have many generic low-level exceptions that could bubble up to some calling methods.

But maybe we can at least identify some critical cases (like IMO above) where it would make sense to add `@throws`.

**Comment by SilverFire** [comment]
Yes, it's a good idea, I have also thought about it. I don't see any reasons to avoid adding `@throws`. @yiisoft/core-developers

**Comment by samdark** [comment]
Same here. Why not?

**Comment by mikehaertl** [comment]
> Why not?

It will add a lot of "noise". For example the exceptions thrown in BaseObject/Component can essentially occur every time we call `Yii::createObject()` and this is used on 100s of places.

It's also a lot of work to really find all the possible scenarios where an exception can be thrown.

Still I think, it should be changed. Even if some exceptions are missed it's better than now.

**Comment by rob006** [comment]
I'm against doing this blindly and document generic exceptions. If you cant explain what this exception means, you should not document it. I already ignored some generic exceptions in inspections because `yii\db\Exception`, `\Exception` and `\Throwable`  are annotated almost everywhere without giving any value. Don't make it worse...

**Comment by armpogart** [comment]
@rob006 Your arguments are correct, but currently not documenting `@throws` you just don't worn developers using the framework that there can be exception in some case. And it's important to warn developer, cause he/she maybe needs to do try/catch and somehow handle the exception instead of just leaving it to the framework to show error page.

**Comment by rob006** [comment]
@armpogart Honestly, I don't care anymore. I already ignored `InvalidConfigException` and `InvalidArgumentException` in my IDE since I don't want to catch it (I should fix my code instead). And finally inspections for exceptions stopped being annoying and started to be useful. 

But basically every piece of code may throw `\Exception` or `\Throwable` (because it's PHP), almost every piece of code may throw `InvalidConfigException` and `InvalidArgumentException` (because it is Yii and some basic components/helpers throw them) and most of the code may throw `yii\db\Exception` (because DB is a external service, it could fail at any moment). Right now `@throws` are added because some dumb IDE complaining about it. If IDE would be smart enough to understand how framework works, it would be complain everywhere, because you can get one of these 5 exceptions almost everywhere. Good luck with adding `@throws` for every method to warn users ;).
