### ISSUE TITLE
Implementations must implement interface correctly

### ISSUE THREAD

**Issue by madagon** [yiisoft/yii2#16453]
##### Interface [https://github.com/yiisoft/yii2/blob/master/framework/db/ActiveRecord.php]():
`public static function updateAll($attributes, $condition = '', $params = [])`
##### Implementation [https://github.com/yiisoft/yii2/blob/master/framework/db/ActiveRecord.php]():
`public static function updateAll($attributes, $condition = null);`

### What is the expected result?
ActiveRecord must exactly implement its interface.
**$condition = ''** can not be implemented like **$condition = null**. This breaks the contract.
And why isn't **params = []** included in the implementation parameters?

### What do you get instead?

- IDE warning
- Crash possiblity

### Additional info
There are many other breaks as the example in the code.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14
| PHP version      | 7.1
| Operating system | Linux

**Comment by rob006** [comment]
Technically this does not break any contract - you can add additional parameters (with default values) and add/change default value for existing parameters - this will not change how method is used, thus implementation match interface. 

However I'm not sure what is the reason of inconsistency in this case.

**Comment by madagon** [comment]
Hi Rob,
Please try this one. This generates IDE warning in PHPStorm / PSR2
`
interface SampleModelInterface extends ActiveRecordInterface
{
...
`
...
`
class SampleModel
    extends ActiveRecord
    implements SampleModelInterface
{...
`

Is there something wrong here?

**Comment by SamMousa** [comment]
@madagon  you are right. 
Based on LSP you are allowed to widen function arguments.
What happens here is that the interface specifies a type`array` via phpdoc, but the actual type is `array|null`, since the default value is `null`. (This is something that could / should be fixed in doc).

The implementation then changes the parameter type to : `string|array` but since it doesn't mention `null` it breaks LSP. This could be fixed by allowing `null` and updating all calls in the chain.
I checked and in this case the parameter is forwarded to `QueryBuilder::buildCondition` where it is cast to a string.

Since this is only PHPDoc I think the correct fix is to allow `null` as a type everywhere. Note that this is technically a BC break since custom implementations of `QueryBuilder` might not support the `null` type.

An alternative solution is remove `null` as a parameter type altogether.

**Comment by madagon** [comment]
@SamMousa Yes. And the argument `$params` is expected to be `array` not null whereas in the implementation, by being absent it will be `null` by default.

**Comment by cebe** [comment]
The interface defines a general interface for AR implementation, the DB implementation of Yii adds another parameter that allows to pass params that can be bound to SQL query. Non-SQL AR implementations only allow array for the condition parameter, SQL AR allows also string for plain SQL condition, that is why interface and implementation differ.
