### ISSUE TITLE
CacheController "No cache components" when cache component is CacheInterface itself

### ISSUE THREAD

**Issue by educationisenemy** [yiisoft/yii2#16469]
### What steps will reproduce the problem?
I've got the following configuration of cache driver:
```
return [
    'components' => [
        'cache' => yii\caching\CacheInterface::class,
        // other components
    ],
    'container'  => [
        'singletons' => [
            yii\caching\CacheInterface::class => [
                'class' => yii\redis\Cache::class,
                // settings
            ],
        ]
    ]
];
```

run command `yii cache`
### What is the expected result?
```
The following caches were found in the system:

	* cache (yii\caching\CacheInterface)
```
### What do you get instead?
```
No cache components were found in the system.
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | 7.2
| Operating system | Any

**Comment by turboezh** [comment]
@samdark. Hi, it seems such a configuration works fine at container/components level, and we are using it in production with no other problems so far. The problem is in `console/controllers/CacheController.php`:
https://github.com/yiisoft/yii2/blob/70b78270acf8e4c4d664887457fca25de444f31f/framework/console/controllers/CacheController.php#L293
It may be patched only there somehow. Naive patch is:
```php
return is_subclass_of($className, 'yii\caching\CacheInterface') || $className == CacheInterface::class
```

**Comment by samdark** [comment]
Ah. If that's so then feel free to do a pull request. I'll merge it.
