### ISSUE TITLE
Validate mem leak

### ISSUE THREAD

**Issue by Mapteg34** [yiisoft/yii2#16537]
I have simple model:
```
class Item extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return 'item';
    }

    public function rules()
    {
        return [
            [['name'], 'required'],
            [['name'], 'string', 'max' => 32],
            [['name'], 'unique'],
        ];
    }

    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
        ];
    }
}
```
And simple code (check items before import from csv)
```
foreach ($names as $name) {
    $item = new Item();
    $item->name = $name;
    $item->validate();
    unset($item);
}
```
And when $names is big (200k elements) yii fail "Allowed memory size of 134217728 bytes exhausted (tried to allocate 16777216 bytes)".
How i can validate multiple items without large using memory?

Version is Yii Framework/2.0.15.1

**Comment by rob006** [comment]
Does calling `gc_collect_cycles()` (for example after every 1k items) helps?

**Comment by lubosdz** [comment]
If you load **huge data into memory**, it will kill PHP process regardless of what PHP framework you use because you reached PHP's `max_memory_limit`, which is 128 MB in your case.
You should use [data reader](https://www.yiiframework.com/doc/api/2.0/yii-db-datareader) to avoid memory exhaust. Perhaps you could show how you populate `$names` from DB. Also depending on database engine, for large datasets you may need to increase e.g. `read_buffer_size`, though 200k should still be probably fine. Finally increasing `max_memory_limit = 256M` - though not being the right approach, it might solve your current crash.

**Comment by Mapteg34** [comment]
1. rob006, thank, but gc_collect_cycles() not help (
2. lubosdz, i know that problem is in high memory usage. But i think, that framework must not use memory after validate call end, but it does. And problem when validate calling N times, used memory is N*memleak too. Its a "memleak" problem by a-priory. Validate - part of framework, so i think its framework problem. And i don't know way for fix this behavior.

Way "increasing max_memory_limit = 256M, increase, increase" not a right approach. With this way we give another problem with server resources.

"Perhaps you could show how you populate $names from DB". In our case we get names not from db, but from small csv file (2mb). But in this issue its not a problem, memory usage after file read ~+4mb. For test you can use (we test it)
```
for ($i=1; $i<200000; $i++){
    $item = new Item();
    $item->name = (string)$i;
    $item->validate();
    unset($item);
}
```
with the same result

**Comment by rob006** [comment]
Unable to reproduce, even without `gc_collect_cycles()`. Are you sure you don't have debug module enabled or some logging which will store everything in memory?
