### ISSUE TITLE
findOne giving Error, Key "[[fieldName]]" is not a column name and can not be used as a filter

### ISSUE THREAD

**Issue by avinashz** [yiisoft/yii2#16718]
### What steps will reproduce the problem?
`$data = GroupData::findOne(['[[nGroupID]]' => 1]);`

here **nGroupID** is not a primary key

### What is the expected result?
AR of GroupData Model

### What do you get instead?
Error:  Key "[[nGroupID]]" is not a column name and can not be used as a filter

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | 7.0.30-0+deb9u1
| Operating system | Debian
| DB | PostgreSQL

**Comment by rob006** [comment]
Since Yii 2.0.15 `findOne()` does not accept any expression as key, only simple column identifiers are supported, see https://www.yiiframework.com/news/168/releasing-yii-2-0-15-and-database-extensions-with-security-fixes

You can use just `GroupData::findOne(['nGroupID' => 1])`, Yii will quote column name anyway (same for `GroupData::findOne(['group_data.nGroupID' => 1])`).
