### ISSUE TITLE
\yii\db\ActiveRecord relation issue

### ISSUE THREAD

**Issue by hyquoccuong** [yiisoft/yii2#16759]
### What steps will reproduce the problem?
When I overwrite function fields() to  return some relations data
### What is the expected result?
Return object with relations data
### What do you get instead?
Hang and time out

### Additional info

Idea: Category object has 2 relations to itself: parent (1 - 1) and children (1 - n)
This error only happen when I use both relations, if I only use 1 relation it works properly.

My Category class code:

```
...
class Category extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return 'category';
    }

    public function fields()
    {
        $fields = parent::fields();
        //Problem appears when I keep both 2 following lines (both 2 relations used), if I comment out 1 of those lines, there is no problem
        $fields[] = 'children'; 
        $fields[] = 'parent';
        return $fields;
    }

    public function getChildren()
    {
        return $this->hasMany(Category::className(), ['parent_id' => 'id']);
    }

    public function getParent()
    {
        return $this->hasOne(Category::className(), ['id' => 'parent_id']);
    }
}
```
| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      |  7.1
| Operating system | Windows 10

**Comment by codespede** [comment]
It is because each category model is finding its parent and children models and these models again doing the same recursively(because the modification in fields() is applicable in these models too), which obviously causes huge load.

If you don't require parent and children for all the returned models(for eg:- you only need children for the top level category and you only need parent for the bottom level category), you can add conditions accordingly in `fields()` which can reduce the load.

**Comment by rob006** [comment]
You should probably use `inverseOf()` in your relations, to avoid loading the same model recursively.
