### ISSUE TITLE
Parameter sort in extraction of messages config not working?

### ISSUE THREAD

**Issue by AndersonDan** [yiisoft/yii2#16910]
### What steps will reproduce the problem?

Create the config file to extract translation messages:

```php
return [
    'color' => null,
    'interactive' => true,
    'help' => null,
    'messagePath' => '@backend/messages',
    'languages' => [
        'en',
        'pt-BR',
    ],
    'translator' => 'Yii::t',
    'sort' => false, // <---------------- here
    'overwrite' => true,
    'removeUnused' => false,
    'markUnused' => false,
    'except' => [
        '.svn',
        '.git',
        '.gitignore',
        '.gitkeep',
        '.hgignore',
        '.hgkeep',
        '/messages',
        '/BaseYii.php',
    ],
    'only' => [
        '*.php',
    ],
    'format' => 'php',
    'catalog' => 'messages',
    'ignoreCategories' => [
        'yii*',
    ],
    'phpFileHeader' => '',
    'phpDocBlock' => null,
];
```

### What is the expected result?
New messages extracted at the end of the generated translation files.

### What do you get instead?
Messages are added to the existing file and are sorted in alphabetical order.

### Additional info

| Q                | A
| --------------------- | ---
| Yii version               | 2.0.15.1?
| PHP version            |  7.2
| Operating system   | Debian GNU/Linux 9 (stretch)

**Comment by Groonya** [comment]
Not really. Option `$sort` in MessageController just controls in what order messages should be inserted into translation target (file or db). It's very important for files because you can open any file and see ordered messages. But it is useless for a database. When you do `SELECT * FROM table ` in most cases dbms doesn't guarantee the order - you have to specify the order. 
So main question here is for whom we need to order messages in the database?
For user? No, he must specify the order if he wants to see ordered messages.
For framework? No, it's not important for it how messages are ordered.
