### ISSUE TITLE
ActiveQuery when in from multiple models to get Primary_id instead of NULL

### ISSUE THREAD

**Issue by buibr** [yiisoft/yii2#17179]
```
 /**
     *  Return list of requests.
     */
    public function getRequests()
    {
        return $this->hasMany(Requests::className(), ['request_id'=>'request_id'])
                    ->via('orderRequests');
    }
```

Run as 
```
$query->andWhere(['in', 'request_id', $orders->getRequests()->select('request_id')->all() ]);
```
OR
```
$query->andWhere(['request_id'=>$orders->getRequests()->select('request_id')->all() ]);
```

produces:
```
WHERE `request_products`.`request_id` IN (NULL , NULL)
```

and if i set
```
$query->andWhere(['request_id'=>$orders->getRequests()->select('request_id') ]);
```

produces 
```
WHERE
    request_products.request_id IN (SELECT 
            request_id
        FROM
            requests
        WHERE
            request_id IN (13 , 14))
```
that i don't like cus sometime we have long amount of products request in one order.

### What steps will reproduce the problem?
I think that this can be reproduced by selectin primary id if the value of `where` is array of objects if that object is model class.

### What is the expected result?
```
WHERE `request_products`.`request_id` IN (2,3)
```

### What do you get instead?
```
WHERE `request_products`.`request_id` IN (NULL , NULL)
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14
| PHP version      | PHP 7.2.11 (cli) (built: Oct 11 2018 16:23:09) ( NTS )
| Operating system | macOS Mojave 10.14.3

**Comment by fl0v** [comment]
```php
$orders->getRequests()->select('request_id')->all();
```
returns ActiveRecord collection
and
```php
$orders->getRequests()->select('request_id');
```
returns ActiveQuery

It seams the query builder automatically converts to sql any ActiveQueryInterface it gets in ->where(), but when you give him an ActiveRecord collection i'm not sure he knows to get the pk of each object. Was this feature already implemented ? otherwise this is not a bug but a feature request.

Another way to get what you want is to produce a list of ids in your subquery
```php
$query->andWhere([
    'request_id'=> $orders->getRequests()->select('request_id')->column(),
]);
```
See [https://www.yiiframework.com/doc/api/2.0/yii-db-activequery](https://www.yiiframework.com/doc/api/2.0/yii-db-activequery) for more details.
