### ISSUE TITLE
Wildcard events

### ISSUE THREAD

**Issue by sjaakp** [yiisoft/yii2#17300]
The second example under Wildcard Events in the Guide (https://www.yiiframework.com/doc/guide/2.0/en/concept-events#wildcard-events) doesn't work for me.

I had to change 'app\models\\*' into 'app\models*' to catch the event.

My impression is that the culprit may be in StringHelper::matchWildcard(). In the source, I see '\\*' in $replacements. I don't have the courage to investigate it further.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.17
| PHP version      | 7.2.7
| Operating system | Windows 10 Home

**Comment by samdark** [comment]
It should be fixed by https://github.com/yiisoft/yii2/commit/317a73a59f7f1a0beb4a0f181e96bb775810420b

**Comment by Toma91** [comment]
@samdark I think there is a piece missing in the `Event::trigger` method.

When matching classes to wildcards (about line 300) `StringHelper::matchWildcard()` should use the third parameter and pass `['encode' => false]` like in other places, otherwise something like `Event::on('app\modules\modulename\models\*', 'eventPrefix.*', $handler)` would return `TRUE` for `Event::hasHandlers()` but `$handler` will not be called when`$model->trigger('eventPrefix.someEventName')` is invoked.

**Comment by Toma91** [comment]
PR: https://github.com/yiisoft/yii2/pull/17756
