### ISSUE TITLE
ArrayHelper $direction error when anonymous function

### ISSUE THREAD

**Issue by mariovials** [yiisoft/yii2#17372]
### What steps will reproduce the problem?
```
    \yii\helpers\ArrayHelper::multisort($items, function($item) {
      return ['attr1', 'attr2']);
    },
    [SORT_ASC, SORT_DESC]);
```

### What is the expected result?
sorted array 

### What do you get instead?
```
Invalid Argument – yii\base\InvalidArgumentException
The length of $direction parameter must be the same as that of $keys.
```

**Comment by samdark** [comment]
Yes, that's valid.

**Comment by alexkart** [comment]
@samdark, this example from the documentation is incorrect https://www.yiiframework.com/doc/guide/2.0/en/helper-array

> Second argument that specifies keys to sort by can be a string if it's a single key, an array in case of multiple keys or an anonymous function like the following one:

```php
ArrayHelper::multisort($data, function($item) {
    return isset($item['age']) ? ['age', 'name'] : 'name';
});
```

You can't use this function because you need to know sorting keys (the result of this function) before this line https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseArrayHelper.php#L651 
but currently, this function never evaluates before this line and just passed to `\yii\helpers\BaseArrayHelper::getColumn` which will not return the column of the sorted array but will return `['age', 'name']` and those values will be sorted which makes no sense and don't sort an array.

Even this example is wrong even if it isn't generating an error:

```php
        $data = [
            ['age' => 30, 'name' => 'Alexander'],
            ['age' => 19, 'name' => 'Barney'],
            ['age' => 30, 'name' => 'Brian'],
        ];
        ArrayHelper::multisort($data, function () {
            return ['age', 'name'];
        });
```

Also, an anonymous function passed to multisport could not get any arguments.

**Comment by alexkart** [comment]
This can be fixed by adding this line:

```php
public static function multisort(&$array, $key, $direction = SORT_ASC, $sortFlag = SORT_REGULAR)
    {
        $key = $key instanceof \Closure ? call_user_func($key) : $key;
        ...
```

But, there is a test case which expects that anonymous function will be passed to the `\yii\helpers\BaseArrayHelper::getColumn` and will return modified values of the array (not keys that should be used for sorting):

```php
public function testMultisortClosure()
    {
        $changelog = [
            '- Enh #123: test1',
            '- Bug #125: test2',
            '- Bug #123: test2',
            '- Enh: test3',
            '- Bug: test4',
        ];
        $i = 0;
        ArrayHelper::multisort($changelog, function ($line) use (&$i) {
            if (preg_match('/^- (Enh|Bug)( #\d+)?: .+$/', $line, $m)) {
                $o = ['Bug' => 'C', 'Enh' => 'D'];
                return $o[$m[1]] . ' ' . (!empty($m[2]) ? $m[2] : 'AAAA' . $i++);
            }

            return 'B' . $i++;
        }, SORT_ASC, SORT_NATURAL);
        $this->assertEquals([
            '- Bug #123: test2',
            '- Bug #125: test2',
            '- Bug: test4',
            '- Enh #123: test1',
            '- Enh: test3',
        ], $changelog);
    }
```

So, this is a conflict of different behaviors that anonymous function should have.
