### ISSUE TITLE
afterValidate event behaviour changed

### ISSUE THREAD

**Issue by thomaswelter** [yiisoft/yii2#17481]
`afterValidate` is now always called after validation is done.
This used to be only when the form was submited which breaks our code (and possibly others as well).

### Additional info
it happens on 2.0.23
it does not happen on 2.0.19

I think the problem is with this [commit](https://github.com/yiisoft/yii2/commit/1f9131d841eabac285d701f5117d112d3c1e9412#diff-3096f348a33d8aa1d79ebe62e5e0f304L708) introduced in 2.0.21

You can see that the `if (submitting)` statement is moved under the form trigger.

**Comment by samdark** [comment]
@czzplnm do you have some time to look into it?

**Comment by czzplnm** [comment]
> @czzplnm do you have some time to look into it?

Yeah, I'll take a look.

**Comment by czzplnm** [comment]
> You can see that the `if (submitting)` statement is moved under the form trigger.

@thomaswelter 

The purpose of my change was to allow 'afterValidate' to trigger when the form was not submitting. 

Our use case was a submit button would be 'disabled' until afterValidate notified us that everything was valid, then we would allow the user to submit the form. Before afterValidate only triggers when the form is submitting.

I'll can't find anything that would cause this in the code, but I will test it myself, but can you clarify  your use case please.

Your activeForm has ajax validation, and you are doing validateOnChange, or you are detecting the change yourself and invoking validateAttribute on the element manually?

**Comment by thomaswelter** [comment]
The way we currently use afterValidate is to show an alert to the user to show that some fields need attention. This is also shown under the input itself but that input might be on another page.

I could use `BeforeSubmit` but the problem is that it only fires if there were no validation errors.

I'l admit that the way you want to use `afterValidate` makes more sense. This is however a breaking change. I can see the use case as i had the same problem before. I suggest we create a new event that triggers after all validations are checked (after all `afterValidateAttribute` events) regardless of a form being submitted. It could be named `attributesValidated` for example.

**Comment by Alexum33Vld** [comment]
Also ran into a problem due to this change. I have a form with ajax validation and the behavior I needed before was during validation before submitting the form. Now the event is triggered even with ajax validation. When you click on any field of the form, an event is triggered. I'm not sure which behavior is correct, but I had to insert check on submit in JS.
`
$('form#{$model->formName()}').on('afterValidate', function(event,messages)
{
    if($(this).data('yiiActiveForm').submitting === false){
         return;
    }
    ... my code
});
`

**Comment by czzplnm** [comment]
@samdark 
What do you think?

**Comment by samdark** [comment]
Options are: 

1. Revert behavior to pre 2.0.21
2. Adjust it to satisfy both use cases
3. Keep it as it is. Then we need to describe how to get old behavior in `UPGRADE.md`

As I understand, variant 2 is not possible because new behavior directly contradicts old one.

**Comment by czzplnm** [comment]
@samdark  should I add a new event that can trigger when the form validates regardless if it is submitted, and revert afterValidate to its original behavior?

**Comment by samdark** [comment]
I think that is a must if we want to keep current behavior.

**Comment by Trimod** [comment]
This update broke our logic a bit too. So, yes, another vote to revert afterValidate behavior.

A simplified case:
Field 1 with ajax validation.
Field 2 with simple required validation.
We want to draw users attention to fields with errors on the form after the form has been submitted (validated completely).

User enters valid data into Field 1, ajax validation triggered, it returns an error for Field 2 because it is empty, although this error is not shown on the form.
afterValidate is now triggered, and it tells us about error of Field 2, so we show user a message "Please check errors above for Field2", however there are no errors shown on the form :)
