### ISSUE TITLE
filterHeaders() should consider user IP

### ISSUE THREAD

**Issue by koxu1996** [yiisoft/yii2#17521]
### What steps will reproduce the problem?

Let's suppose following architecture:
~~~
 Client   --->  Load Balancer  --->  Yii2 App
50.0.0.1          30.0.0.1           10.0.0.1
~~~

_Load Balancer_ is configured to replace `X-Forwarded-For` with reliable value (as advised in https://github.com/yiisoft/yii2/issues/16122#issuecomment-382419713) and _Yii2 App_ is configured to trust headers from *30.0.0.1*.

Example scenario:
 1. _Client_ connects via HTTP**S**
 2. Load balancer replaces *X-Forwarded-For* with user real IP (50.0.0.1) and appends own IP (30.0.0.1). It also sets *X-Forwarded-Proto*, so final headers look like:
    ~~~
    REMOTE_ADDR: 50.0.0.1
    X-Forwarded-For: 50.0.0.1,30.0.0.1
    X-Forwarded-Proto: https
    ~~~

### What is the expected result?

Headers should be trusted and `getIsSecureConnection()` should return `true`.

### What do you get instead?

Headers are not trusted, because [filterHeaders](https://github.com/yiisoft/yii2/blob/master/framework/web/Request.php#L300) uses `getRemoteIP` instead of `getUserIP`.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.23
| PHP version      | PHP 7.3.8
| Operating system | Arch Linux x64 5.2.9-arch1-1-ARCH

**Comment by nadar** [comment]
We do have the same problem, if filterHeaders() would take the load balancer proxy as trusted source this would just work out of the box: https://github.com/yiisoft/yii2/blob/master/framework/web/Request.php#L300

Define REMOTE_ADDR (which is taken to determine trustedHosts) on a constantly changing infrastructure like AWS, Google Cloud is almost not possible, or do i miss something? So we ended up with override `secureHeaders` with an empty array, but this does not look like a good solution.

```php
'request' => [
      'secureHeaders' => [],
],
```

@koxu1996 taking `getUserIP()` won't work as far as i can see, as headers are already resolved: https://github.com/yiisoft/yii2/blob/cdd40b8dfb3a2f29a72fb2e07ca0e9718f15494c/framework/web/Request.php#L341

**Comment by koxu1996** [comment]
I overrided `secureHeaders` as well.

@nadar You are right, it would result in mutual recursion.

**Comment by kamarton** [comment]
It seems to me to be working properly.

**Comment by nadar** [comment]
@kamarton It only works when you configured the request component accordingly, but this could be done out of the box as LB's provide those informations already without configure anything.

**Comment by kamarton** [comment]
I understand the problem: 
Before the PHP process, it is resolved by `X-Forwarded-For` (or similar method), so we have to accept the value of the remote address that it is always the user's IP address and the headers are always secure.

I created a PR:
```php
$_SERVER['REMOTE_ADDR'] = '50.0.0.1';
$_SERVER['HTTP_X_FORWARDED_FOR'] = '50.0.0.1,30.0.0.1';   // It really doesn't matter what its value is
$_SERVER['HTTP_X_FORWARDED_PROTO'] = 'https';
$request = new Request([
  // Since an endpoint has already validated this, you must accept any source here.
  'trustedHosts' => ['0.0.0.0/0'], 
  // Must be set to true because the remote address already contains the real user's IP.
  'userIpIsAlwaysRemoteIp' => true,
]);
$this->assertSame('50.0.0.1', $request->userIP);
$this->assertSame(true, $request->isSecureConnection);
```

**Comment by koxu1996** [comment]
@kamarton You should not create app that trust every host. Moreover my issue is about different situation than you presented.

**Comment by kamarton** [comment]
> You should not create app that trusts every host.

If something has done the IP resolv then it has to be accepted, therefor on the role of `trustedHosts` is only that what comes in is automatically accepted as secure ->` 0.0.0.0/0`.

> The ngx_http_realip_module module is used to change the client address and optional port to those sent in the specified header field.

"change the client address" - The `trustedHosts` function gets an resolved IP address. It's will no longer be able to manage trust (`0.0.0.0/0`).

Cases:
- IP resolv occurs: resolved based on this PR. (It was sufficient to improve the use of the `getUserIp()` function.)
- no IP resolv at all: normal use of `trustedHost`
- no need for IP resolv: no need to use `trustedHost`
- there is not always a IP resolv: custom development is not covered by the framework. Otherwise, it makes no sense to talk about resolving, because it is not possible to determine when resolving occurs, which implies that `getUserIP()`, secure headers and so on. nor can it be resolved.

> Moreover my issue is about different situation than you presented.

Real example with input and output data?

**Comment by samdark** [comment]
1. `getIsSecureConnection()` is likely wrong that it first checks `$_SERVER` and only then falls back to secure headers. If headers are trusted then they should be preferred. Current code should fail if client is using HTTP but load balancer uses HTTPS to communicate to Yii2 App.
2. There is no way to automatically determine if host is a trusted load balancer. Usage of `getRemoteIP()` instead of `getUserIP()` is intentional. Yii should not trust header-based values by default.

If there is no way to access Yii2 App host directly and there is always a load balancer which IP we don't know, the following config would work:

```php
'any' => ['X-Forwarded-Proto', 'X-Forwarded-For']
```

**Comment by samdark** [comment]
Thinking more about second point, https://github.com/yiisoft/yii2/issues/16122#issuecomment-535092821 makes perfect sense.

**Comment by kamarton** [comment]
> getIsSecureConnection() is likely wrong that it first checks $_SERVER and only then falls back to secure headers. If headers are trusted then they should be preferred. Current code should fail if client is using HTTP but load balancer uses HTTPS to communicate to Yii2 App.

I think there is little point in further developing this in Yii2. If you set up IP resolving on your web server (e.g `ngx_http_realip_module`), you can obviously assume that you trust it. This is equivalent to using "trustedHosts = [0.0.0.0/0]".

However, if you enable `trustedHost = [0.0.0.0/0]`, it will try to re-resolv the user's IP address based on `X-Forwarded-For` (the web server cannot be expected to delete this header). The PR improve this. (https://github.com/yiisoft/yii2/pull/17569)

The https://github.com/yiisoft/yii-web/issues/119 issue allows you to define additional network resolver classes for such cases, but for Yii2 this would only add more complexity to the `Request` class, which is unreasonable in terms of resolving the problem.

**Comment by kamarton** [comment]
Probably the simplest solution:

```php
'request' => [
   'class' => ...,
   'trustedHosts' => ['0.0.0.0/0'],
   'ipHeaders' => [],
]
```

**Comment by nadar** [comment]
What would you recommend to configure my application when i have a load balancer which can change the IP Adresse every time like my VM instance does? `'secureHeaders' => [],` might be even worse.

**Comment by samdark** [comment]
@nadar depends if what's behind load balancer is accessible directly or not.

**Comment by kamarton** [comment]
The end result: https://www.yiiframework.com/doc/guide/2.0/en/runtime-requests#already-respolved-user-ip
