### ISSUE TITLE
"PHP Warning – yii\base\ErrorException filemtime(): stat failed" for all site scripts

### ISSUE THREAD

**Issue by aftaa** [yiisoft/yii2#17556]
Firstly, the enviroment:

PHP 7.3 x64
Apache 2.4
Windows 10

In some moment, all the scripts display error:
PHP Warning – yii\base\ErrorException
filemtime(): stat failed for [..]\frontend\runtime/cache\2f\2f33462dc35c2b8886f3905ae3ea3939.bin

in C:\OSPanel\domains\vg\vendor\yiisoft\yii2\caching\FileCache.php line 112
`if (@filemtime($cacheFile) > time()) {`

I added the @file_exists() check:
`if (@file_exists($cacheFile) && @filemtime($cacheFile) > time()) {`

**Comment by lubosdz** [comment]
Actually supressing errors with `@` should be dropped in whole [code block](https://github.com/yiisoft/yii2/blame/c75ef05539a713aebc7a6f4ab9d2112f09526fcc/framework/caching/FileCache.php#L113-L119):

Simple check whether file exists:
`if (file_exists($cacheFile) && @filemtime($cacheFile) > time()) {`
is better solution IMHO. Supress operator `@` not even needed.

**Comment by aftaa** [comment]
> is better solution IMHO. Supress operator `@` not even needed.
absolutely agree. got carried away by dogs

**Comment by samdark** [comment]
There are more reasons for failure than non-existing file.

**Comment by rob006** [comment]
> Simple check whether file exists:
> `if (file_exists($cacheFile) && filemtime($cacheFile) > time()) {`
> is better solution IMHO. Supress operator `@` not even needed.

It is needed. `file_exists($cacheFile) && filemtime($cacheFile) > time()` is not atomic so you will have race condition: during `file_exists($cacheFile)` call file exists, but it is deleted right after it and does not exist enymore during `filemtime($cacheFile)` call. And since we can't rely on `file_exists($cacheFile)` it is redundant - original code is correct. 

If you get such errors, make sure that you don't have [scream](https://www.php.net/manual/en/book.scream.php) enabled.
