### ISSUE TITLE
I give "unserialize(): Error at offset 0 of 60 bytes" for create permission with rule

### ISSUE THREAD

**Issue by bagtim** [yiisoft/yii2#17635]
```php
 $auth = Yii::$app->authManager;

// add the rule
        $rule = new \app\rbac\AuthorRule;
        $auth->add($rule);

// add "updateOwnPost" permission and bind a rule to it
        $updateOwnPost = $auth->createPermission('updateOwnPost');
        $updateOwnPost->description = 'Update own post';
        $updateOwnPost->ruleName = $rule->name;
        $auth->add($updateOwnPost);
```
Without setted ruleName, permission is good created. But if set ruleName, i have error "unserialize(): Error at offset 0 of 60 bytes"

| Q                | A
| ---------------- | ---
| Microsoft SQL Server| 2017 (RTM) - 14.0.1000.169 (X64) | 
| Yii version      | 2.0.29 |
| PHP version   | 5.6.31  | 
| Operating system | win10 64 |

**Comment by samdark** [comment]
1. Was PHP manager used?
2. What was the name?

**Comment by samdark** [comment]
Do you store RBAC rules in MSSQL?

**Comment by samdark** [comment]
Was table created from migrations or https://github.com/yiisoft/yii2/blob/b39bb71587cb4a4964238bdc6e846535588a3cfc/framework/rbac/migrations/schema-mssql.sql?

**Comment by samdark** [comment]
What was used as the rule name?

**Comment by bagtim** [comment]
> What was used as the rule name?

From docs: 
```
class AuthorRule extends Rule
{
    public $name = 'isAuthor';
...
```
and then from topic post:
```
$rule = new \app\rbac\AuthorRule;
$auth->add($rule);
...
$updateOwnPost->ruleName = $rule->name;
$auth->add($updateOwnPost);
```

**Comment by samdark** [comment]
OK. That's enough info to try reproducing it.

**Comment by toatall** [comment]
I had an analogical problem.
I did so:
1) Change to CONVERT(VARBINARY(**MAX**), ...) in [QueryBuilder::normalizeTableRowData](https://github.com/yiisoft/yii2/blob/master/framework/db/mssql/QueryBuilder.php#L429) because default length is 30 characters ([Link MS SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/cast-and-convert-transact-sql?view=sql-server-ver15))
2) For VARBINARY field need add paramert in PDOStatement::bindParam driver_options "PDO::SQLSRV_ENCODING_BINARY" 
`PDOStatement::bindParam(column, &$var, type,length,PDO::SQLSRV_ENCODING_BINARY);`
[DbManager](https://github.com/yiisoft/yii2/blob/master/framework/rbac/DbManager.php#L360)
Or not use PDOStatement. Use PDO::exec('insert...')

**Comment by samdark** [comment]
@toatall since you're into it, would you like to prepare a pull request with a fix?

**Comment by toatall** [comment]
@samdark OK!

**Comment by samdark** [comment]
@bagtim would you please check if @toatall solution fixes the issue for you?
