### ISSUE TITLE
can't set `_retryHandler`

### ISSUE THREAD

**Issue by JimChenWYU** [yiisoft/yii2#17811]
### What steps will reproduce the problem?

```php
Yii::$app->getDb()->commandMap['mysql'] = [
    'class' => 'yii\db\Command',
    'retryHandler' => function (\yii\db\Exception $e, $attempt) {
        if (Str::contains($e->getMessage(), 'MySQL server has gone away')) {
            Yii::$app->getDb()->close();
            Yii::$app->getDb()->open();

            return true;
        }

        return false;
    }
];
Yii::$app->getDb()->commandMap['mysqli'] = Yii::$app->getDb()->commandMap['mysql'];

// `dd` is from larapack/dd
dd(Yii::$app->getDb()->createCommand(), Yii::$app->getDb()->createCommand("SELECT * FROM `user` WHERE `id`=:qp0", [':qp0' => 1]));

```

### What is the expected result?

```
Command {#2666 ▼
  +db: Connection {#2661 ▶}
  +pdoStatement: null
  +fetchMode: 2
  +params: []
  +queryCacheDuration: null
  +queryCacheDependency: null
  -_pendingParams: []
  -_sql: null
  -_refreshTableName: null
  -_isolationLevel: false
  -_retryHandler: Closure {#2662 ▶}
  -_events: []
  -_eventWildcards: []
  -_behaviors: null
}

Command {#2667 ▼
  +db: Connection {#2661 ▶}
  +pdoStatement: null
  +fetchMode: 2
  +params: array:1 [▶]
  +queryCacheDuration: null
  +queryCacheDependency: null
  -_pendingParams: array:1 [▶]
  -_sql: "SELECT * FROM `user` WHERE `id`=:qp0"
  -_refreshTableName: null
  -_isolationLevel: false
  -_retryHandler: Closure {#2662 ▶}
  -_events: []
  -_eventWildcards: []
  -_behaviors: null
}
```

### What do you get instead?

Focus on `_retryHandler`, Idon't why i can't set `_retryHandler`

```
Command {#2666 ▼
  +db: Connection {#2661 ▶}
  +pdoStatement: null
  +fetchMode: 2
  +params: []
  +queryCacheDuration: null
  +queryCacheDependency: null
  -_pendingParams: []
  -_sql: null
  -_refreshTableName: null
  -_isolationLevel: false
  -_retryHandler: Closure {#2662 ▶}
  -_events: []
  -_eventWildcards: []
  -_behaviors: null
}

Command {#2667 ▼
  +db: Connection {#2661 ▶}
  +pdoStatement: null
  +fetchMode: 2
  +params: array:1 [▶]
  +queryCacheDuration: null
  +queryCacheDependency: null
  -_pendingParams: array:1 [▶]
  -_sql: "SELECT * FROM `user` WHERE `id`=:qp0"
  -_refreshTableName: null
  -_isolationLevel: false
  -_retryHandler: null
  -_events: []
  -_eventWildcards: []
  -_behaviors: null
}
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.31
| PHP version      | 7.2
| Operating system | Ubuntu

**Comment by JimChenWYU** [comment]
i find the problem, when you call `setSql`, it also call `reset`, so it's a bug or a feature?

```php
    public function setSql($sql)
    {
        if ($sql !== $this->_sql) {
            $this->cancel();
            $this->reset();
            $this->_sql = $this->db->quoteSql($sql);
        }

        return $this;
    }

    protected function reset()
    {
        $this->_sql = null;
        $this->_pendingParams = [];
        $this->params = [];
        $this->_refreshTableName = null;
        $this->_isolationLevel = false;
        $this->_retryHandler = null;
    }
```

**Comment by samdark** [comment]
That seems to be expected. When new SQL is set, private properties are invalidated.

**Comment by erickskrauch** [comment]
Hi. I'm facing the same problem. I'm looking for a way to make a handler for the `SQLSTATE[HY000]: General error: 2006 MySQL server has gone away` error. And just like the original author of this issue, I tried to use `retryHandler`. But it always resets because absolutely all the queries generated by the ActiveRecord use the `setSql` or `setRawSql` methods, which calls `reset()` and consequently removes the error handler.

So I think that something should be changed here so that we can handle non-critical database errors and continue the normal operation of the application.

**Comment by samdark** [comment]
What would you suggest?

**Comment by erickskrauch** [comment]
The most obvious solution is simply to remove the `$this->_retryHandler = null` line from the `reset()` method. Otherwise, it's just a completely useless feature, because, as I wrote earlier, absolutely all requests generated by ActiveRecord call methods which call `reset()` inside their implementation.

I thought that maybe somewhere inside the framework there is low-level logic that uses this `retryHandler`, but I couldn't find anything. And it's impossible to use this functionality at the user level in its current form.

**Comment by samdark** [comment]
Sounds alright. Please create a separate issue / PR for it. Thanks.
