### ISSUE TITLE
Why can't an action parameter be an array?

### ISSUE THREAD

**Issue by cboulanger** [yiisoft/yii2#17955]
https://github.com/yiisoft/yii2/blob/master/framework/web/Controller.php#L134 determines that if you pass an array as an action parameter, this is considered invalid and will raise a `BadRequestHttpException`. Why is that? I can pass any other value, including objects, and it will be fine - the error is only raised in case of an array. This is a show stopper in JSON-RPC server implementations such as https://github.com/georgique/yii2-jsonrpc which need to be able to pass any JSON-compliant value as a parameter to actions.

**Comment by alex-code** [comment]
Arrays are valid, you just need to specify the type.
```php
public function actionTest(array $param) 
{
} 
```

**Comment by cboulanger** [comment]
I see, thanks, this worked. I was using a generic "echo" action to test my JSON-RPC client which had an untyped parameter. I added a special echo-array action for the array type. Still, I don't really understand what makes the array so special in this case...

**Comment by rob006** [comment]
This API is designed for handling regular web requests with params fetched from `$_GET`. In that case param may be either a scalar (as string) or array. In most cases array is not expected and may lead to exceptions or even create security issues, that is way explicit type in method signature is required for arrays. There is no special treatment for other non-scalar types, because there is no way that client could pass for example an object as `$_GET`.

**Comment by cboulanger** [comment]
Ok, thank you for the explanation!
