### ISSUE TITLE
Composite file extension validation is not supported

### ISSUE THREAD

**Issue by saidbakr** [yiisoft/yii2#18094]
### What steps will reproduce the problem?
 Try to validate composite file extension such as `tar.xz`

### What is the expected result?
 File name `file.bar.xz` should not be uploaded only `file.tar.xz` should be allowed.

### What do you get instead?
 Any file ended with `.xz` is uploaded.

### Additional info
 [Checkout this question on Stack Overflow](https://stackoverflow.com/questions/62268584/yii2-file-validation-tar-xz?noredirect=1#comment110192522_62268584)
| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 7
| Operating system |

**Comment by saidbakr** [comment]
@samdark I don't, exactly, understand what you have suggested. However, I could understand that it should allow the developer to examine whatever extension he want. In other words, any file name extension that the server's operating system allow as a valid file name.
```
public function rules()
    {
        return [
            [['imageFile'], 'file', 'skipOnEmpty' => false, 'extensions' => 'png, jpg, lib.inc, fox.box.lux'],
        ];
    }
```
@rob006 You have mixed between file type or content type and file extension. In the regarded Wikipedia at the third sentences of the first paragraph, the abstract definition of the file extension. What you have regarded has no any conflict with what I have said or with this definition.  

> **A filename extension is typically delimited from the filename with a full stop (period), but in some systems it is separated with spaces.** 

I think that `pathinfo` deals with the file name as string data. In other words, if a plain text file has been created and the name has been changed from `my.txt` to `my.png`, there is no way in the PHP to determine the real content type of that file.

**Comment by rob006** [comment]
> What you have regarded has no any conflict with what I have said or with this definition.

My interpretation has no conflict either (`mysite.index` is file name and `html` is extension - they're separated by dot), and it match further clarification for file names with multiple dots. You're just focusing on single ambiguous sentence (it does not say which dot, you just blindly assumed that it is first) and ignoring rest of the article.

> I think that `pathinfo` deals with the file name as string data. In other words, if a plain text file has been created and the name has been changed from `my.txt` to `my.png`, there is no way in the PHP to determine the real content type of that file.

Well, there is - you can check MIME type and `FileValidator` is already doing it. But there is no MIME type for `tar.xz` or `tar.gz` (there are MIME types for `xz` and `gz`), and certainly there is no MIME type for `com.html` or `index.html`. Introducing some fancy non-standard system for detecting extensions may conflict with current MIME type checks.

**Comment by samdark** [comment]
It will conflict with mime checks for sure because `tar.gz` is, according to mime type, is `.gz`.

**Comment by saidbakr** [comment]
@rob006 

> "(it does not say which dot, you just blindly assumed that it is first)"

Simply the computer may assume it as well. The first occurrence of match is the default case of matching any pattern. For example, any regex without `g` flag will match the first occurrence only.

@samdark In this case, a new option may be added to determine if the validation should apply mime check or not or even to check the textual extension and/or its supposed mime. In some cases, the developer need to make his own files or need to deal with with weird extensions files. For example, [Checkout this download page](https://quran.ksu.edu.sa/ayat/?l=en&pg=patches), you will find packages to be downloaded have the extension `ayt`. These files are nothing else zip files. i.e just rename any of them from *.ayt to *.zip and any compression application will open them well.

**Comment by samdark** [comment]
I've re-checked everything.

1. In this case we want to validate extension and mime type separately so we need to set `'checkExtensionByMimeType' => false`.
2. Mime validation would work as expected with `'mimeTypes' => ['application/x-xz']` if you'll add corresponding mime type to config.
3. As for extension, it won't work because it's not clear what to consider an extension. According PHP's `pathinfo` it is what comes after last `.` in the full name.

In order to solve point 3, we can introduce another option to validate file name according to something like regular expression. Then you'd be able to do `'mask' => '~\.tar\.xz$~i'`.

**Comment by rob006** [comment]
> @saidbakr Simply the computer may assume it as well.

But it's not. For simple implementations it is better to check extension after the last dot instead of first one, and I can't imagine any app which would decide that `com.index` is valid extension of `example.com.html` file and does not treat it as a bug.

@samdark Or we could use `StringHelper::endsWith()` for comparing list of extensions with file path to check if file name match any of extensions specified in `FileValidator::$extensions` - then user can use anything here (even `com.html`) and it still will be simpler and foolproof than regex. For MIME validation we may use "real" extension, because this is the only sane thing to do. So for `tar.gz` we should check if file name ends with `.tar.gz` and for MIME validation we would check if `application/gzip` type match `gz` extension.

**Comment by saidbakr** [comment]
> I've re-checked everything.
> 
>     1. In this case we want to validate extension and mime type separately so we need to set `'checkExtensionByMimeType' => false`.
> 
>     2. Mime validation would work as expected with `'mimeTypes' => ['application/x-xz']` if you'll add corresponding mime type to config.
> 
>     3. As for extension, it won't work because it's not clear what to consider an extension. According PHP's `pathinfo` it is what comes after last `.` in the full name.
> 
> 
> In order to solve point 3, we can introduce another option to validate file name according to something like regular expression. Then you'd be able to do `'mask' => '~\.tar\.xz$~i'`.

Ok, I agree with what ever any solution that allows the developer to regard what ever he/she considers as an extension.

**Comment by samdark** [comment]
@rob006 looks way better than regex.
