### ISSUE TITLE
getPreferredLanguage() doesn't always return best match

### ISSUE THREAD

**Issue by brandonkelly** [yiisoft/yii2#18332]
### What steps will reproduce the problem?

1. Set your browser’s Languages preference to: 
    - English (Australia)
    - English (United States)
    - English
2. Call `Yii::$app->request->getPreferredLanguage(['en-US', 'en'])`

### What is the expected result?

`en-US` will be returned.

### What do you get instead?

`en` will be returned, because it partially matched “English (Australia)”, without realizing that an exact match (“English (United States)”) could have been reached if it had allowed the loop to continue.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.38

**Comment by samdark** [comment]
What's `Accept-Language` header value that browser sends in this case?

**Comment by samdark** [comment]
According to RFC https://tools.ietf.org/html/rfc4647#section-3:

>  A simple list of ranges is considered to be in descending order of
   priority.  Other language priority lists provide "quality weights"
   for the language ranges in order to specify the relative priority of
   the user's language preferences.

So between two languages specified with the same priority we're selecting leftmost according to spec.

**Comment by brandonkelly** [comment]
Yeah on further thought I suppose the current behavior could be desired. Just not what I was expecting in the moment.
