### ISSUE TITLE
yii message command do not extract messages from "\Yii::t(" with leading symbol \

### ISSUE THREAD

**Issue by epifrin** [yiisoft/yii2#18941]
Translations won't be collected from construction \Yii::t('app', 'test'); if it has leading symbol \ and Yii do not imported in use section.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.43
| PHP version      | 8
| Operating system |

**Comment by samdark** [comment]
@epifrin please try customizing the option.

**Comment by samdark** [comment]
Now it's fixed in master branch.

**Comment by MarkoNV** [comment]
Since creating config file via console command put 
`'translator' => ['Yii::t', '\Yii::t'],`
in config of older projects, shouldn't this be mentioned in UPGRADE.md?

**Comment by WinterSilence** [comment]
@MarkoNV  it's not change behavior of older projects,  but you can add it in `UPGRADE.md` - it's can be useful

**Comment by MarkoNV** [comment]
@WinterSilence it doesn't change behaviour of older projects, but since that behaviour is bug and this is bugfix for that bug, action that need to be taken on project level for bugfix to work, should be mentioned.

I'll try to make PR next week. I tried today for other bug, but on Win machine couldn't make configuration right.
