### ISSUE TITLE
`yiisoft/yii2-swiftmailer`  is missed  in `composer.json`

### ISSUE THREAD

**Issue by WinterSilence** [yiisoft/yii2#18955]
Base application use `yiisoft/yii2-swiftmailer` by default:
https://github.com/yiisoft/yii2/blob/e22bece3df9a8ed5ba817904872e281e48c44cd3/framework/base/Application.php#L637
but that package not required in `composer.json`.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.43
| PHP version      | any
| Operating system | any

**Comment by samdark** [comment]
You're right that it's not a good practive but I'm afraid we can't change that without breaking existing apps.

**Comment by bizley** [comment]
Yes, but this is not an error. I would add it in suggested so when developer installs dependencies it can be displayed as a suggestion. And who wants to add can add it.

**Comment by lubosdz** [comment]
Please bear in mind that not everybody uses SwiftMailer, even if it's regarded within the framework. 
For example I have to use [PhpMailer](https://github.com/PHPMailer/PHPMailer) instead of SwiftMailer, because it allows much easier composing mailbody for delayed async posting from database mailqueue.

**Comment by WinterSilence** [comment]
@samdark spam (:
