### ISSUE TITLE
Breaking logic & mechanic of models

### ISSUE THREAD

**Issue by WinterSilence** [yiisoft/yii2#18990]
`Model`:
1. What's reason to use `ArrayAccessTrait` in `Model`? `Model` override all `ArrayAccess`/`IteratorAggregate` methods but ignore `count()`(`Countable`) based on undefined property `$data` (bug).

`ActiveRecord`:
1. Why default values of columns not used as attribute defaults? Why `loadDefaultValues()` not called for not loaded models?
2. Why  `loadDefaultValues()` ignore `attributes()`?
3. Why magic methods for property access as `__get()` ignore getter/setter methods of  attributes (`getAttribute()`/`setAttribute()`) and use `$_attributes` directly?
4. Why magic methods for property access as `__get()` break logic of `Model` and don't call getter/setter methods it they exists?

**Comment by samdark** [comment]
There are way too many unrelated question but I'll try to answer these and close the issue. Please open separate ones for separate issues.

> What's reason to use ArrayAccessTrait in Model?

Using array access in views to switch to arrays when extra performance is needed. That was common case when Yii 2 was developed so I assume there are still some projects doing that.

> Why default values of columns not used as attribute defaults? Why loadDefaultValues() not called for not loaded models?

Because it's not always needed. There was a discussion about that. It should be somewhere in closed issues.

> Why loadDefaultValues() ignore attributes()?

Because default values are defined in table schema. Is there any case when it won't work well?

> Why magic methods for property access as __get() ignore getter/setter methods of attributes (getAttribute()/setAttribute()) and use $_attributes directly?

As far as I remember, two reasons:

1. Performance.
2. Relations.

> Why magic methods for property access as __get() break logic of Model and don't call getter/setter methods it they exists?

They do but for non-attributes and non-relations.

**Comment by WinterSilence** [comment]
@samdark
> Using array access in views to switch to arrays when extra performance is needed. That was common case when Yii 2 was developed so I assume there are still some projects doing that.

I mean, no reason to use `ArrayAccessTrait` in `Model`: `Model` rewrite all methods defined in `ArrayAccessTrait` except `count()` and it's bug - `$data`  not defined
https://github.com/yiisoft/yii2/blob/817f956013beaba2687bf863dba09e77e96adf11/framework/base/ArrayAccessTrait.php#L41

**Comment by samdark** [comment]
Ah, that. Yeah. Maybe it is not correct.

**Comment by WinterSilence** [comment]
@samdark 
> Is there any case when it won't work well?

you can define **6** columns in table, but user's can override `attributes()` and use only **5**
