### ISSUE TITLE
https request port

### ISSUE THREAD

**Issue by andrtechno** [yiisoft/yii2#19493]
https return getServerPort() 80

![gdfgsf](https://user-images.githubusercontent.com/6948026/181846839-0e00d5bf-24b1-40ed-9186-17c5237d7c14.png)

**Comment by samdark** [comment]
What's the URL?

**Comment by andrtechno** [comment]
https://homfund.pixelion.com.ua/ вывожу Yii::$app->request->getServerPort()

**Comment by andrtechno** [comment]
ссылку могу обрать?

**Comment by WinterSilence** [comment]
@andrtechno вангую что ты используешь nginx и не можешь нормально его сконфигурировать
@samdark close issue, error in server config

**Comment by samdark** [comment]
Closing since wasn't able to reproduce it with nginx + php-fpm.

**Comment by SagePtr** [comment]
I think you are misusing getServerPort. It's not robust way to detect your inbound port if you are behind any reverse proxy.
For instance, Cloudflare [doesn't pass this header at all](https://developers.cloudflare.com/fundamentals/get-started/reference/http-request-headers/), you will end up with port on which your nginx is accepting Cloudflare connections instead of translated one.
If you want to just detect http/https, use Yii::$app->request->isSecureConnection instead.
