### ISSUE TITLE
Bug fix #20055 causes bad result for pagination using for example gridview

### ISSUE THREAD

**Issue by procin** [yiisoft/yii2#20175]
### What steps will reproduce the problem?

When creating the dataprovider, for example:
$provider = new ActiveDataProvider([
    'query' => ...,
    'pagination' => [...]
]);

Setting the 'pagination' calls the setPagination() function, which now directly calls the getTotalCount() function, which calls the prepareTotalCount() function.
Now the value for $_totalCount will be queried from the database.

When using a GridView with a SearchModel, the search parameters for the query are loaded in a later stage.
The search parameters can cause for a different number of rows to be returned.

The prepareTotalCount() is not called again, because $_totalCount is already set.

The pagination bar now works with a completely wrong count value. (for example, displays more pages than there actually are)

Calling prepareTotalCount() again is not a solution, the count on a big table can be very expensive.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.50

**Comment by samdark** [comment]
#20055 @lav45 would you please take a look?

**Comment by nadar** [comment]
@samdark it seems since 2.0.50 the active data provider is broken when using pagination and/or sort params:

yii\base\InvalidConfigException: The "query" property must be an instance of a class that implements the QueryInterface e.g. yii\db\Query or its subclasses. in /var/www/html/vendor/yiisoft/yii2/data/ActiveDataProvider.php:164
Stack trace:
#0 /var/www/html/vendor/yiisoft/yii2/data/BaseDataProvider.php(171): yii\data\ActiveDataProvider->prepareTotalCount()
#1 /var/www/html/vendor/yiisoft/yii2/data/BaseDataProvider.php(222): yii\data\BaseDataProvider->getTotalCount()
#2 /var/www/html/vendor/yiisoft/yii2/base/Component.php(180): yii\data\BaseDataProvider->setPagination()
#3 /var/www/html/vendor/yiisoft/yii2/BaseYii.php(557): yii\base\Component->__set()
#4 /var/www/html/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure()

this code breaks with the above stack trace in version 2.0.50

```
return new ActiveDataProvider([
            'pagination' => [
                'defaultPageSize' => 75,
            ],
            'query' => $query
                ->select([SchemaRow::tableName().'.id', 'title', 'subtitle', 'is_visible'])
                ->byLikeTitle($model->query)
                ->isNotTrashed()
                ->andFilterWhere([SchemaRow::tableName().'.id' => $model->ids])
                ->bySchemaId($id),
            'sort' => [
                'defaultOrder' => [
                    'title' => SORT_ASC,
                ],
            ],
        ]);
```

removing the sort/and or pagination definition and it works again. We had to downgrad to 2.0.49 in order to get the app working.

**Comment by nadar** [comment]
@samdark not sure its related to be honest. but i also have problems with the active data provider with latest version. Let me know if i should create a fresh issue.

**Comment by lav45** [comment]
@nadar fixed in to the PR https://github.com/yiisoft/yii2/pull/20176

**Comment by dfuse-dev** [comment]
Just in case this could help, seems that 'totalCount' is needed now even if no pageSize is configured.

This used to work before to get all records:

```
$dataProvider = new SqlDataProvider([
      'sql' => $query,
      'params' => $boundParams,
      'pagination' => [
        'pageSize' => 0,
      ],
    ]);
```
now it throws error "Call to a member function getQueryBuilder() on string"
in /var/www/t3/vendor/yiisoft/yii2/db/Query.php (157)

but if i set 

```
$dataProvider = new SqlDataProvider([
      'sql' => $query,
      'params' => $boundParams,
      'totalCount' => 0,
      'pagination' => [
        'pageSize' => 0,
      ],
    ]);
```
it works again

**Comment by SamMousa** [comment]
Workaround is to make sure the configuration array contains `query` before `pagination`. That way `query` is set before `pagination` is set.

**Comment by nadar** [comment]
i tested the fix in dev-master, seems to work. thanks :+1:

**Comment by samdark** [comment]
Thanks for verifying it.
