### ISSUE TITLE
Comparing operators like >,< >=,<= to search in GridView

### ISSUE THREAD

**Issue by indicalabs** [yiisoft/yii2#2022]
Yii1 Gridview has a feature to search with comparing operators like >,< >=,<= in GridView,

I can't see they are working now with gii generated code?

**Comment by mklemarczyk** [comment]
:+1: What happen with `compare` function from `CDbCriteria` class form Yii 1.x?
I need this feature because a lot of my users use it.

Notice that:
I see some potential problem with this feature in Yii 2.0, because search attributes must be valid.
For example we can have `quantity` attribute with rule `integer` and expression `>10` will be invalid.

**Comment by ilyapoz** [comment]
Hey, guys. I wonder how do you envision implementing this? I will need this for rest api in my project and can dig and make a contribution, will just need a few pointers.
Just improving the code generated by gii to replace simple `andFilterWhere` with more elaborate ones?
Where do you suggest putting the parsing code? @qiangxue @samdark

**Comment by cebe** [comment]
@ilyapoz we have no concrete ideas or plans on this. you could make a proposal for an implementation and we can discuss it.

**Comment by lennartvdd** [comment]
Something like that? ^^  I'd find this feature very helpful too. Yii 1's CDbCriteria::compare() was very user friendly.

**Comment by ilyapoz** [comment]
@lennartvdd I guess functions with the property "Note that when the value is empty, no comparison expression will be added to the search condition." have "filter" in their name in yii2 by convention.

**Comment by lennartvdd** [comment]
ah alright! Makes sense!  how about `andFilterCompare()` ?

**Comment by ilyapoz** [comment]
I guess it's time to open a PR :)

**Comment by lennartvdd** [comment]
any updates on this issue?

**Comment by ArekX** [comment]
@ilyapoz 
I would actually just extend `andFilterWhere`, `orFilterWhere`, `andWhere`, `orWhere`, etc...

To use currently available operator format `[operator, operand1, operand2, ...]` where `operator` would be an instance of an implementation of an abstract class `QueryComparator`, let's say `NumericQueryComparator`  which implements comparator functions like `compare($value, $withValue)`, in this case the comparing with operators which are in `$withValue`. Of course `QueryComparator` would at the very least extend `yii\base\Object` to allow configuration.

This way we would keep `QueryInterface` pure, and also allow for custom implementations of `QueryComparator` which people can use. And also it will allow for easier implementation for different DBMS which Yii uses.

As for validation, I would extend `NumberValidator` via additional `allowOperators` feature or make another class like `ComparableNumberValidator` which allows numbers with operators.

**Comment by Faryshta** [comment]
@ArekX i don't think its that simple and even if you manage to do that, how do you fix the validation rules?

`[['price'], 'number']`

for example, what if I send `&price=<500` on the url?

**Comment by ArekX** [comment]
That is why I said to add additonal parameter `allowOperators` so in this case it would be like:
`[['price'], 'number', 'allowOperators' => true]` and then it should recognize `price=<500` as a value with operator.

**Comment by Faryshta** [comment]
thats the proposed syntax, but how do you solve it?

i mean how do you propose allowOperators to work internally?

**Comment by ArekX** [comment]
If you look at this line in number validator: https://github.com/yiisoft/yii2/blob/ae42a054bb950caf8a7972f386b6c8b903cff98e/framework/validators/NumberValidator.php#L56

You will see a number pattern which is used for checking whether or not a value is an actual number. You can easily prefix this regex with operators so it will look like this:
`^(>|<|>=|<=|=|)\s*[-+]?[0-9]*\.?[0-9]+([eE][-+]?[0-9]+)?\s*$`

So if you make another public variable like `operatorNumberPattern` and switch the check with this pattern inside `validateAttribute` function when `allowOperators` is true checking numbers with operators becomes possible.

Of course you would have separate a number from operator to perform `min` and `max` checks, and by grouping the second part of a number like this: `^(>|<|>=|<=|=|)(\s*[-+]?[0-9]*\.?[0-9]+([eE][-+]?[0-9]+)?\s*)$` that too becomes possible. Same should also apply for when `integerOnly` is true by using with another public variable `operatorIntegerPattern` which is `integerPattern` prefixed with these operators which in this case would be `^(>|<|>=|<=|=|)(\s*[+-]?\d+\s*)$`

Because this code could easily get jumbled up with standard `NumberValidator` behavior it may be better to make another validator class (i.e. `ComparableNumberValidator` which I mentioned) which only implements `operatorNumberPattern` and `operatorIntegerPattern` without `numberPattern` and `integerPattern` to keep code clean and simple.

**Comment by Faryshta** [comment]
thats a good idea. i think you have solved it to the point where you can make a patch and tests.

**Comment by werta600** [comment]
So? Is this implemented or any plans to implement this option?

**Comment by lennartvdd** [comment]
I did not implement anything from the latest comments, but there's a PR for a GridView comparison function ready and waiting to be merged for quite a while now in #8505

**Comment by cebe** [comment]
merged https://github.com/yiisoft/yii2/pull/8505, keeping this open for documentation.
