### ISSUE TITLE
Fast start REST api documentation is wrong. 

### ISSUE THREAD

**Issue by hvprvtr** [yiisoft/yii2#20252]
Hello. This URL https://www.yiiframework.com/doc/guide/2.0/en/rest-quick-start contains wrong code. Receipt works only with 

`'enableStrictParsing' => false,`

If follow this doc step-by-step - got 404 only for every request. Fix it please. Lost many time here, just stackoverflow helped.

**Comment by hvprvtr** [comment]
There are many other errors. For example:
`POST /users: create a new user;`
It is not. 405 error. /users/create works. 

This article confusing and get a wrong way.

**Comment by bizley** [comment]
This is really weird. To quickly check it I have created project for basic template and added controller and url manager config as in the guide you linked and both GET and POST endpoints were responding properly (with the exception of actually working since basic template does not provide user active model here hence there are errors with active controller but not with 404/405 status).

Could you provide me with a minimal reproducible example of your case?

**Comment by mtangoo** [comment]
@hvprvtr can you make simple app on github and link it to verify the problem?

**Comment by hvprvtr** [comment]
It is so strange, but with simple yii2basic app i cant reproduce this bug. Sorry to bother you. If i got it in the future (then i google, many people got this bug on stackoverflow), i try to debug this and reopen the issue.

**Comment by mtangoo** [comment]
Feel free to do that
