### ISSUE TITLE
Clear schema cache after execute migrations

### ISSUE THREAD

**Issue by leandrogehlen** [yiisoft/yii2#3305]
I think would necessary clear the schema cache after execute migrations

**Comment by TimNZ** [comment]
I don't know if this is the right place, but 'console/yii cache/flush-schema' runs with no error, but doesn't actually flush the cache.  Have to restart Apache to achieve before the timeout.

**Comment by samdark** [comment]
No, it's not. Please use forums for discussions or, if you have issues, create separate tickets. Thanks.

**Comment by brandonkelly** [comment]
@qiangxue @samdark Sorry to resurrect an old issue but a Craft user is [requesting something like this](https://github.com/craftcms/cms/issues/1657), and it seems like an obvious enhancement to me – when Yii knows for sure that a table schema was just changed, why _wouldn’t_ it be a good idea to clear its schema cache for the table?

Maybe 3c70d3c31754ea9619482312b215c87e26884740 was a little heavy-handed, but would you folks be opposed to updating the schema-altering functions in `yii\db\Migration` to call `yii\db\Schema::refreshTableSchema()` ?

For example:

```php
    public function renameColumn($table, $name, $newName)
    {
        echo "    > rename column $name in table $table to $newName ...";
        $time = microtime(true);
        $this->db->createCommand()->renameColumn($table, $name, $newName)->execute();
        echo ' done (time: ' . sprintf('%.3f', microtime(true) - $time) . "s)\n";

        // clear the schema cache
        $this->db->getSchema()->refreshTableSchema($table);
    }
```

Complete list of `yii\db\Migration` methods this change should affect:

- `createTable()` _(in case the table schema had been memoized beforehand as `null`)_
- `renameTable()`
- `dropTable()`
- `addColumn()`
- `dropColumn()`
- `renameColumn()`
- `alterColumn()`
- `addPrimaryKey()`
- `dropPrimaryKey()`
- `addForeignKey()`
- `dropForeignKey()`
- `addCommentOnColumn()`
- `dropCommentFromColumn()`

(Skipping `createIndex()`, `dropIndex()`, `addCommentOnTable()` and `dropCommentFromTable()` because that info doesn’t appear to be tracked by `yii\db\TableSchema` or `yii\db\ColumnSchema`.)

This would solve the issues raised at https://github.com/yiisoft/yii2/issues/3305#issuecomment-64733768:

> Now the schema is refreshed for every migration, which is not always wanted.

This approach would only clear caches for individual tables, and only within functions where the schema-altering SQL was both generated _and_ executed, so we can be sure that the cache clearing is actually warranted.

> It refreshes the schema cache for the default `db` connection, which may not be expected if a migration is working on a different db connection.

As this is done right from the actual migration, we can be completely sure of which DB connection’s cache we should be clearing.

**Comment by SilverFire** [comment]
Migration usually contains multiple operations on the same table so cache for the table will be cleared more than once. Considering migration execution is a maintenance procedure and cache clearing is not something expensive, I'd vote for adopting this request as it will potentially prevent errors.

@brandonkelly your arguments seems to be valid in general. @yiisoft/core-developers

**Comment by rob006** [comment]
#10503

**Comment by klimov-paul** [comment]
Haven't we solved this already at #8652 ?

**Comment by SilverFire** [comment]
@klimov-paul indeed. @brandonkelly ?

**Comment by brandonkelly** [comment]
Yep looks like you’re right! That’s a better solution, but it’s incomplete. I’ll post as a new issue.
