### ISSUE TITLE
Suggestion: dynamic creating of AR relations

### ISSUE THREAD

**Issue by RomeroMsk** [yiisoft/yii2#3352]
There is no ability to create AR relations in runtime. It will be usefull for Entity-Attribute Value models.

See http://www.yiiframework.com/forum/index.php/topic/53803-dynamic-creating-of-ar-relations/

**Comment by klimov-paul** [comment]
I am unsure if relations can be defined dynamically, because there is actually no relation definition, if you think about that.
Unlike Yii1 Yii2 does not store any information about relation anywhere; there is no meta data or schema objects, which do so.

However this issue can be solved, if we allow passing an ActiveQuery instance inside `with()` and `joinWith()` methods.
So code, which uses dynamic relation can look like following:
```php
$orders = Order::find()->with(Dynamic::find()->where(['active' => 1]))->all();
```

**Comment by RomeroMsk** [comment]
I've solved my initial need by extending ActiveRecord and ActiveQuery to work with EAV attributes as with "native" attributes. So, for now I don't need this functionality. And if nobody else needs this, we can close the issue.

**Comment by lennartvdd** [comment]
I realize this is a year old issue, but since it's still open.. 

I was looking to solve a similar use case. In Yii 1.x this was very easy. You could just set the relation as if it were any other property like this `$listing->resort = $resort`, provided you previously fetched the $resort record manually with a find() or something. In Yii 2.x this no longer possible, because the AR's magic setters in yii2 can no longer set relations.

The way i've solved it is to use the `populateRelation()` method. 

So for example, when `$listing->isNewRecord == true` and `$resort->isNewRecord == false`, and you want to call: `$listing->resort->name`, that will fail, because $listing is not a record yet, has no primary key or any other field to link the relation to. 

But you can fake the relation in new records, by setting it manually like this:
`$listing->populateRelation('resort', $resort);`
and then call 
`$listing->resort->name`

@RomeroMsk Was that wat you originally intended?
You would still have to perform a $resort = Resort::findOne($listing->resort_id)
but the benefit could be that you could use the model in a form view, pre-populate the relations for the new record in the controller and simple use the relations as you would for existing records, instead of creating separate variables for them.

**Comment by RomeroMsk** [comment]
@lennartvdd, the main problem was in `joinWith()`, as I mentioned on forum.
Try to make `->joinWith('resort')` work with your approach.

**Comment by lennartvdd** [comment]
Alright different solution to a different problem, sorry. 
I got confused by the example @youanden gave.

**Comment by dynasource** [comment]
closed in favor of https://github.com/yiisoft/yii2/issues/11483
