### ISSUE TITLE
Gii: suggest for ModelSearch

### ISSUE THREAD

**Issue by mdmunir** [yiisoft/yii2#3665]
Non critical issue.
In method `ModelSearch::search()` generated by gii. we get code like this
```php
if (!($this->load($params) && $this->validate())) {
    return $dataProvider;
 }
```
it's better if we change with
```php
$this->load($params);
if (!$this->validate()) {
    return $dataProvider;
}
```
What goal of this issue is, sometimes we need to open page index with initial filter. E.g. at first time, the page just showing opened order. For now, i do like this:
```php
// in actionIndex()
$searchModel = new OrderSearch();
$formName = OrderSearch::formName();
$params = ArrayHelper::merge([
    $formName=>['status'=>Order::STATUS_OPEN]
],Yii::$app->request->getQueryParams());
$dataProvider = $searchModel->search($params);
```
With this sugget, we just do like this:
```php
$searchModel = new OrderSearch(['status'=>Order::STATUS_OPEN]);
$dataProvider = $searchModel->search(Yii::$app->request->getQueryParams());
```

**Comment by samdark** [comment]
Reverted https://github.com/yiisoft/yii2/commit/b4ba430ac43af476c01bd2d39036a84ef808ae98

**Comment by hscstudio** [comment]
Please give me reason why this is be revert.. hem :(

Yesterday runnig well.. :(

**Comment by mdmunir** [comment]
Ok, its reverted. but not resolve original issue.

**Comment by fsateler** [comment]
On Tue, Jan 6, 2015 at 11:08 PM, Hafid Mukhlasin <notifications@github.com>
wrote:

> Please give me reason why this is be revert.. hem :(


Because it was cited as a valid use case to: (a) create search models with
untrusted data without using `load()` and/or (b) set defaults via  the
`default` validator. And yet, the revert does neither.

I will note that the original (and current) implementation, it is very very
awkward to set a default for a search parameter.

Please revert the revert. It helps noone:

1. People who do not use defaults: indifferent between the reverted and the
original versions, both work.
2. People who use defaults with trusted data: better with the reverted
version than the original.
3. People who use defaults via the `default` validator: indifferent between
the reverted and original versions, neither works.
4. People who use defaults with untrusted data: indifferent between the
versions, as neither will validate the original untrusted data.

I would actively argue against usecase (a). There is a reason why there is
a `load()` method: to load untrusted values. If you feed untrusted data to
a model constructor, then you get to keep the pieces.

-- 

Saludos,
Felipe Sateler

**Comment by mdmunir** [comment]
I propose 2 code.
```php
$this->load($params);
if (!$this->validate()) {
    return $dataProvider;
}
```
and
```php
$this->load($params);
if (!$this->validate()) {
    $query->where('1=0');
    return $dataProvider;
}
```

First code, when validation invalid, it will return all record. Second, when validation invalid, it will return empty result. But both of them not provide error message(red text, exeption, hint, etc). IMO, it safe to implement this.

PS: I prefer use second propose.

**Comment by qiangxue** [comment]
Yes, we can use the second approach. We should add a comment before the `where()` line to describe why this is used and what will happen if this line is removed.

**Comment by hscstudio** [comment]
When @mdmunir propose is implemented?..

**Comment by fsateler** [comment]
On 10 Jan 2015 14:36, "Qiang Xue" <notifications@github.com> wrote:
>
> Closed #3665 via 5cb2ce4.

:)

**Comment by SDKiller** [comment]
Sorry for `post mortem` comment, just came here from https://github.com/yiisoft/yii2/commit/5cb2ce49dde5e9da837982f7361ba2ffe8e7904f#diff-4c9899459b13a582a0963f0942a71877R76

Is it really а better solution to promote ugly workarounds in core extensions? 

Nethertheless of invalid query:

```
Starting 	                        43 µs
Checking Permissions 	6 µs
Opening Tables 	        31 µs
System Lock 	                18 µs
Init 	                                35 µs
Optimizing 	                8 µs
Executing 	                8 µs
End 	                                3 µs
Query End 	                10 µs
Closing Tables 	         7 µs
Freeing Items 	                54 µs
Logging Slow Query 	3 µs
Cleaning Up 	                3 µs
```

**Comment by joeyblack835** [comment]
A very interesting post. Can someone explain: 
a) why a Search model extends the main model; why can't we have a search function inside the main model?
b) why a search function loads data while we load data in the controller when we want to save the model
c) what I should do if I don't want to load data inside the search function
d) what I should do if I don't want to validate the data; e.g. I have a common Search model for several models and then I want to make several searches using the same data and output several results under the common Search form
P.S. Yes, I expect to get an answer that this is just a template. But I don't think so. Probably I am missing something. I guess it's a part of philosophy I don't get.
Thanks in advance.
