### ISSUE TITLE
improve migrate command

### ISSUE THREAD

**Issue by schmunk42** [yiisoft/yii2#384]
* running migrations from different locations (modules)

more or less like this one from @cebe https://github.com/yiiext/migrate-command

**Comment by vladim1** [comment]
I'll leave this post here to not create the same one.
It's really pain in the ass to run migrations of the plugged in modules with specifiing their pathes.
This issue is almost 2 years.  I am waiting for this feature from milestone to milestone. What is the problem with solving it? So, we could discuss it...
PS: Is there any tool/extension to automate the process of running migrations of plugged in modules?

**Comment by schmunk42** [comment]
@vladim1 Check out our extension https://github.com/dmstr/yii2-migrate-command

**Comment by Faryshta** [comment]
I think #8202 is a good way to fix this issue for modules, extensions, external libraries and all the other cases discused here.

**Comment by jacmoe** [comment]
Since I include migrations in my test routines - ie migrations should be able to migrate all the way down and all the way up at any time - I am looking forward to a built-in solution. :+1: 
The https://github.com/dmstr/yii2-migrate-command is part of my standard tool-kit already, but it would make Yii even more cool if it was built in. Especially since newcomers wouldn't have to discover it themselves. :)

**Comment by klimov-paul** [comment]
I whould solve this matter using namespaces instead of paths, just I have proposed here:
https://github.com/yiisoft/yii2/issues/9698#issuecomment-147696833

**Comment by schmunk42** [comment]
@klimov-paul We're currently using aliases, which is essentially the same, isn't it? https://github.com/yiisoft/yii2/issues/384#issuecomment-63638791

**Comment by ItsReddi** [comment]
I discovered this issue before two years. Well the eta was RC. Any chance that this feature will be implemented in the next release or should we stick to some extensions that can handle this approach?

**Comment by klimov-paul** [comment]
Solution proposed at #12511

**Comment by klimov-paul** [comment]
Resolved by commit 8aa0e85
