### ISSUE TITLE
Consider providing CHM documentation officially

### ISSUE THREAD

**Issue by cebe** [yiisoft/yii2#4279]
No priority for now but here are some references:

- https://github.com/bisubus/yii2-apidocchm
- #1797

**Comment by lourdas** [comment]
+1000 for this. I've always liked much more the chm format (even in Linux, KchmViewer is an excellent viewer, much better than Microsoft's tool) than the pdf or online version (there are times a internet connection is **not** available), since it's much more usefull to search and find something **very quickly**. Please consider providing official support for the chm format.

Thanks.

**Comment by lourdas** [comment]
Is there any progress regarding this issue? It's been more than a year since it was opened and Yii2 still lacks a proper offline documentation format. This [forked repository](https://github.com/bisubus/yii2-apidocchm/) has issues (the latest version does not include the documentation for the jui widgets and for some reason the author has disabled the creation of issues).

**Comment by bisubus** [comment]
@lourdas Thank you for noticing that. Indeed, extension documentation for 2.0.4 seems to be broken, I will take a look at the issue.

**Comment by lourdas** [comment]
@bisubus Thanks for working on creating a nice chm file. Please consider enabling issues for the repository, so that we could notify you of any issues that arise. Maybe the Yii developers would consider merging your work at the official repository, it would be nice. Not many people know of your work towards creating a chm file.

**Comment by bisubus** [comment]
@lourdas Issue tracking is enabled now at [bisubus/yii2-apidocchm][https://github.com/bisubus/yii2-apidocchm/], feel free to create the one if you will find other problems. Adding CHM feature in a proper way requires some `yii2-apidoc` classes to be refactored, I guess that's the reason why it wasn't merged yet.

**Comment by cebe** [comment]
I am going to take a look at this as soon as we have the new website.
