### ISSUE TITLE
Attribute name must contain word characters only

### ISSUE THREAD

**Issue by twinni** [yiisoft/yii2#4408]
`activeTextInput` and `DetailView::widget` don't accept field names with non word characters like `ä` `ö` or `ü`.
In mysql these are valid characters for column names.

**Comment by drdanio** [comment]
just in "/vendor/yiisoft/yii2/helpers/BaseHtml.php" file find and replace lines:
if (preg_match('/(^|.*\])([\w\.]+)(\[.*|$)/', $attribute, $matches)) {
if (!preg_match('/(^|.*\])([\w\.]+)(\[.*|$)/', $attribute, $matches)) {
if (!preg_match('/(^|.*\])([\w\.]+)(\[.*|$)/', $attribute, $matches)) {
to:
if (preg_match('/(^|.*\])([\w\.]+)(\[.*|$)/u', $attribute, $matches)) {
if (!preg_match('/(^|.*\])([\w\.]+)(\[.*|$)/u', $attribute, $matches)) {
if (!preg_match('/(^|.*\])([\w\.]+)(\[.*|$)/u', $attribute, $matches)) {

**Comment by dynasource** [comment]
if somebody is creating a PR for this, please included the spaces scenario as noted in https://github.com/yiisoft/yii2/issues/12262

**Comment by cebe** [comment]
seems this has been fixed by #13243

**Comment by cebe** [comment]
Hm... no solved for Html though.

**Comment by SamMousa** [comment]
Working on a PR

**Comment by SamMousa** [comment]
I've chosen to use `public static $attributeRegex` instead of a constant to allow for easier customization.

Did some research regarding unicode characters.
When using the `/u` modifier, both `PCRE_UTF8` and `PCRE_UCP` are used. 
https://github.com/php/php-src/blob/bf59acdea75cf13d179f10ce89d296a30f38676d/ext/pcre/php_pcre.c#L364

This means that if Unicode properties are available then PHP with use them to decide if a character is a word character.

Before blindly addding the `/u` modifier some cases need to be considered.
1. The subject is ASCII --> no worries, all ASCII is valid UTF-8.
2. The subject is an encoding that is incompatible with UTF-8 --> the pattern matching will silently fail, in our case that means an error will always be thrown (could be considered good behavior).

**Comment by SamMousa** [comment]
Some tests with `ü`. 
Encoded in `UTF-8`:
````
preg_match('/\w+', 'ü') === 0;
preg_match('/\w+/u', 'ü') === 1;
````
Encoded in `ISO-8859-1`:
````
preg_match('/\w+/', utf8_decode('ü')) === 0;
preg_match('/\w{1}/u', utf8_decode('ü')) === false;
````

Practically this suggests that we could just enable the unicode modifier in the regular expression, if we can assume that unicode support is always available. I'm not sure what happens if it is not available, it might fail silently (ie revert to current behavior) or fail hard...

**Comment by SamMousa** [comment]
@cebe, from the spec: https://html.spec.whatwg.org/multipage/syntax.html#attributes-2

> Attributes for an element are expressed inside the element's start tag.
> 
> Attributes have a name and a value. Attribute names must consist of one or more characters other than the ASCII whitespace, U+0000 NULL, U+0022 QUOTATION MARK ("), U+0027 APOSTROPHE ('), U+003E GREATER-THAN SIGN (>), U+002F SOLIDUS (/), and U+003D EQUALS SIGN (=) characters, the control characters, and any characters that are not defined by Unicode. In the HTML syntax, attribute names, even those for foreign elements, may be written with any mix of lower- and uppercase letters that are an ASCII case-insensitive match for the attribute's name.

So the regex that I use is a lot more relaxed than the current one in Yii, yet still a lot stricter than what is allowed according to the spec.
