### ISSUE TITLE
Query before find event?

### ISSUE THREAD

**Issue by slavcodev** [yiisoft/yii2#4652]
Hello, is there a way to change Query object before it run?

`EVENT_INIT` not suitable because it triggered in constructor.
Need to attach handlers to instance of query, like

``` php
$query->on(Query::EVENT_BEFORE_FIND, $callback);
```

**Comment by dwoutsourcing** [comment]
There is an special case: GeoSpatial columns...
If you have a column of type "Point" AR will retrieve the value as a string so we should add something like:

```
	public static function find() {
		return ActiveRecord::find()->select([
			'*',
			new Expression('Y(coordenada) AS lat'),
			new Expression('X(coordenada) AS lng'),
		]);
	}
	
	public function attributes() {
		return array_merge(
			parent::attributes(),
			['lat', 'lng']
		);
	}
	
	public function setLat($value) {
		$this->lat = $value;
	}
	public function getLat() {
		return $this->lat;
	}
	public function setLng($value) {
		$this->lng = $value;
	}
	public function getLng() {
		return $this->lng;
	}
```

A behavior could be used if before_find event were triggered

**Comment by SamMousa** [comment]
How about adding an event on ActiveRecord that is triggered after query construction?

    public static function find() {
        $query = Yii::createObject(ActiveQuery::className(), [get_called_class()]);
        $event = new MessageEvent;
        $event->query = $query;
        Event::trigger(__CLASS__, self::EVENT_QUERY_CONSTRUCTED, $event);
        return $query;
    }

The issue is that a behavior on AR might want to change queries as well, since we don't have multiple inheritance it is hard to write a 3rd party library that modifies ActiveQuery since a developer will have to choose 1 or the other (since we can only have one parent class).

Now multiple 3rd party libraries get a chance to inject behaviors on a "pure" Query object allowing them to modify behavior.

**Comment by SamMousa** [comment]
This is mainly about ActiveQuery right? Wouldn't an event AFTER_PREPARE work? 
Prepare creates a new $query object which could be passed, since that object is a copy there is no risk of unexpected results as @qiangxue mentioned.

**Comment by mikk150** [comment]
I was trying to implement BEFORE_PREPARE/AFTER_PREPARE and BEFORE_JOINWITH/AFTER_JOINWITH events(for better soft-delete), and I discovered that it is impossible to do.
It would be nice, if we could add behaviours to ```Query```/```ActiveQuery``` so it could theoretically change executable query object.
But since ```Query::create()``` makes clone of ```Query```/```ActiveQuery```(not so much, because ```ActiveQuery``` gets mangled to ```Query``` in ```ActiveQuery::all()```, ```ActiveQuery::one()```, etc for no obvious reason) then events gets deleted. and since ```Component::_events``` is private, there is no way to copy events to the newly created object

**Comment by dynasource** [comment]
there are several solutions provided to fix the issue of this topic.  I you have a concrete usecase in which you think that framework extension is really required, feel free to open another topic.

**Comment by menapro** [comment]
The event `beforeFind` could be worth in cases like this:

Example context: Shop
Item: address. 

A user can have multiple addresses, that can be retrieved by `findOne`,`findAll`,`find()`,`hasOne`,`hasMany`.

Due to access restrictions we want to filter all posible results to only those where customer is the owner.
So if we could have a behavior that adds condition `where(['user_id' => Yii::$app->user->id])` will get just the right results.
