### ISSUE TITLE
BaseActiveRecord property scope and ActiveRecord::find performance

### ISSUE THREAD

**Issue by jkovacs618** [yiisoft/yii2#4839]
I am attempting to extend ActiveRecord and override ActiveRecord::populateRecord.  I would like to be able to set BaseActiveRecord _attributes and _oldAttributes myself after some custom logic.  Would it be possible to make these protected instead of private?  Perhaps _related needs to be protected also.

My intention is to override ActiveRecord & BaseActiveRecord's populateRecord method to cache the $columns array in a static array, indexed by table name, to improve the performance of large ActiveRecord::find result sets, and avoid the unnecessary work done in BaseActiveRecord::populateRecord: $columns = array_flip($record->attributes());

Also, in our extended ActiveRecord::populateRecord method, I am choosing to omit the loop over $row to call ColumnSchema->phpTypecast, which I have found to be incredibly slow on large result sets.  When possible, I try to use ActiveRecord::find()->asArray(), but often I need the ability to use the AR model as an object to call custom functions and properties.  Most of the column values are strings, and in the cases where I know they are integers, I will use php's (int) type cast as needed after AR::find returns the records.

When testing the performance, I was running ActiveRecord::find()->all() on a query returning 3200+ records.  This took about 2 seconds and I was very disappointed in the performance after upgrading to Yii2.  The same ActiveRecord::findAll() query in Yii 1.1 took 1.2s, so it was slow to begin with, but from 1.2s to 2.0s with Yii2 was significant.  When calling the same Yii2 find query with asArray(), it took 71 ms, which is great, but then I lose my ability to use the objects.  When I override BaseActiveRecord::populateRecord and put in a static array of $columnsByTable, it dropped from 2s to 1.5s.  When I took out the loop over $rows to call phpTypecast, it dropped from 1.5s to 0.6s.  

You could say that I shouldn't be trying to get 3200 ActiveRecord models, and I have rewritten some to use asArray(), but other times this won't be possible.  I'm not suggesting that any changes need to be made to BaseActiveRecord::populateRecord, since the current implementation is clean and provides value type casting for most uses cases of small ActiveRecord result sets.  But I will probably keep my custom populateRecord method, and do the (int) type casting on the outside as needed, instead of the wasted processing of string columns.  To achieve this, I am requesting the scope change on the BaseActiveRecord properties above.  Thank you.

**Comment by YasserHassan** [comment]
I want to add my vote to making `$_attributes` protected. A practical application is performing clean up to the model's attributes before saving by trimming extra spaces and converting empty strings to nulls en masse (I remember that suggestion was made before but rejected). `$_attributes` of new records do not have the primary key(s) columns as they would not be included in the INSERT statement. So iterating over `$_attributes` would get the job done directly. However, using `getAttributes()` not only adds execution overhead, but also requires knowing the primary key attribute(s) name to exclude while calling the function. Imagine using this cleaning function in a base class to handle several models with different key names so you need to account for this too in the code with extra overhead.

This is a situation where an easy solution could be applied by either accessing `$_attributes` directly or adding getter/setter. But the fact that it's private prevents that.

I hope you consider this in general, not only for this property because one doesn't know when it would become handy. But instead of finding easy solutions, he finds the private access modifier a barrier that needs work to get around which could be saved and directed to the project at hand instead.

**Comment by dynasource** [comment]
$_properties are not going to be made protected, as the underscore implies a private scope which follows out of a standard architecture with getters and setters. 

If you have an alternative solution, please open a new topic with a reference to this one. Thanks!
