### ISSUE TITLE
DateValidator::timestampAttribute should have a format

### ISSUE THREAD

**Issue by cebe** [yiisoft/yii2#5053]
DateValidator::timestampAttribute should provide an option that allows formatting the value to not only be a unix timestamp but also a date in format 'Y-m-d' to store in a database column of type 'date'.

1. db can use native fields and better deal with that data than with integers
2. parsing date values from data input adds the local time to the timestamp. this can be avoided when converted to `Y-m-d` format afterwards.

**Comment by cebe** [comment]
related: #5857

**Comment by tecnologiaterabyte** [comment]
I've checked the forum, the issues of the framework and the only solution to save a date field in MySQL is using a beforesave function.

Should I add another function which allows also save the date type field by default without using a beforesave function to give the correct format, as when working with several models and many date type fields becomes cumbersome.

For example:

My Config:

        // Formatter
        'formatter' => [
            'class' => 'yii\i18n\Formatter',
            'locale' => 'es-ES',
            'dateFormat' => 'php:d/m/Y',
            'timeFormat' => 'short',
            'defaultTimeZone' => 'America/Caracas'
        ],

My Model:

        public function rules()
        {
            return [
                [['Turn003'], 'required'],
            ];
        }

My View:

        <?= $form->field($model, 'Turn003')->widget(\yii\jui\DatePicker::classname(), [
        ]) ?>

Save Bd MYSQL: 0000-00-00.

Of course the problem is that I change the format 'yyyy-mm-dd', but because I do beforesave functions in the models, if I'm not putting any special formatting, I'm just putting my form in my language, this I meant in the issue support save format data types (date, time and numeric) that opened yesterday, its solution DateValidator :: timestampAttribute, works perfectly, but note that there is also need to save the date type field in readable format according to the language.

I hope they can do something about it as there are many applications in different issues regarding the subject.

I hope you understand now, thanks in advance the truth that his work with the formatter and validator is excellent.

Thks,

**Comment by FabrizioCaldarelli** [comment]
I've created this gist:

https://gist.github.com/FabrizioCaldarelli/eb376822f07c6832d76b

I've overwritten DateValidator class file, so changes to yii\validators\DateValidator should be simple.
