### ISSUE TITLE
blameable behavior only for non-guests

### ISSUE THREAD

**Issue by drew1two** [yiisoft/yii2#5515]
Hi,
I've noticed that BlameableBehavior updates the updated_by field when a user is requesting a password reset.  As a result, updated_by becomes NULL as this is an un-recognised user (isGuest).
I'm thinking that BlameableBehavior should only execute if user is !isGuest() .
Not sure if there other instances where BlameableBehavior can be influenced by isGuest, I'm new to yii in general, so starting with yii2.

**Comment by lubosdz** [comment]
In CLI mode `BlameableBehaviour` always throws exception `'Calling unknown method: yii\console                                                                  \Application::getSession()'` since session object does not exist in CLI mode. Inserting some `default value for guests` is highly preferred to crashing :-) Something like : 

`BlameableBehavior::defaultValue = null`

might solve the issue. The `defaultValue` would be used for all guests in HTTP requests. 

Unfortunatelly, as for CLI mode it would still need to check whether the session component exists (:-(

**Comment by samdark** [comment]
I agree that it should not crash but in case of CLI it really can't work properly because there's no "current user".

**Comment by lubosdz** [comment]
Would it not be possible to detect CLI mode inside BlameableBehavior via some Helper method ? e.g:

```
public static function isConsoleMode()
{
    return !array_key_exists('REQUEST_URI', $_SERVER);
}

```

The `defaultValue` would be set too if `isConsoleMode` returned true.
The overhead is negligable.

Currently, the only way to fix this issue is to rewrite all ActiveModels, remove BlameableBehaviour and update columns via `beforeUpdate` and `beforeInsert` methods.

**Comment by samdark** [comment]
You can detect it but there's nowhere to get user ID from. Just setting `null` doesn't make much sense to me.

**Comment by michaelnguyen547** [comment]
I encounter this issue today and would like to share my opinion. I have Super Admin user (id:1).

You can use null if your created_by / updated_by column is nullable
```
public function behaviors()
{
    return [
        [
            'class' => BlameableBehavior::className(),
            'value' => function ($event) {
                return (Yii::$app->user->isGuest) ? 1 : Yii::$app->user->identity->id;
            }
        ],
    ];
}
```

**Comment by samdark** [comment]
Yes, we can introduce something like `defaultValue` and `useDefaultValue`. First is the value itself, second is the flag to enable it. Disabled by default.

**Comment by dmirogin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[yiisoft/yii2] blameable behavior only for non-guests](https://trello.com/c/D9Olzyaq/39-yiisoft-yii2-blameable-behavior-only-for-non-guests)
