### ISSUE TITLE
Problem to Save a Date in Oracle Database

### ISSUE THREAD

**Issue by flaviofagundes** [yiisoft/yii2#6004]
Hi Guys 

I have another problem to use Yii2 ActiveRecord with oracle database.

I have tried use this config  where i define my connection:

``` php
    'on afterOpen' => function($event) {
          $event->sender->createCommand("ALTER SESSION SET NLS_DATE_FORMAT='YYYY/MM/DD HH24:MI:SS'")->execute();
```

My searchs on grid components works, but 
it not works to of ActiveRecord operations.

Always occurs the error below

```
 [SQLSTATE[HY000]: General error: 1841 OCIStmtExecute: ORA-01841: (full) year must be between -4713 and +9999, and not be 0 (/tmp/PDO_OCI-1.0/oci_statement.c:142)
```

I did a test using directly the database component and it has worked perfectly.

``` php
Yii::$app->db->createCommand("ALTER SESSION SET NLS_DATE_FORMAT='YYYY/MM/DD'")->execute();

Yii::$app->db->createCommand("INSERT INTO MYTABLE (ID, DT_EVENT, DT_REGISTER) VALUES ('45', '2014/11/11', sysdate)")->execute();
```

I tried use the method beforeSave at my model, how an alternative to define de date_format, but unfortunately doesn't works.

``` php
  public function beforeSave($insert) {
       $this->getDb()->createCommand("ALTER SESSION SET NLS_DATE_FORMAT='YYYY/MM/DD'")->execute();

       return parent::beforeSave($insert);
    } 
```

Anyone can help me?

Thanks for any help!

**Comment by apaoww** [comment]
Would  you please give example on the CLOB workaround. Especially when handle null Clob value. How you @albertborsos  use oracle nvl function on this issue?

**Comment by albertborsos** [comment]
[Here is my ActiveRecord class for Oracle](https://github.com/albertborsos/yii2-lib/blob/master/db/oci/ActiveRecord.php)

I don't remember I had any problem with null values in a CLOB field.

**Comment by apaoww** [comment]
I always got this error when Clobs data is empty:
Try to use SQLSTATE[HY000]: General error: 1405 OCIStmtFetch: ORA-01405: fetched column value is NULL.

Try to setAttributes on PDO use this one PDO::NULL_TO_STRING, but no effect. My only solution right now is to use sqlDataProvider("select nvl('clob_field', 'None')") in controller. I think have problem with pdo_oci.  My php version 5.4 on Centos 7.

**Comment by dynasource** [comment]
is this something we can fix and if so, how and where should we tackle it. Somewhere in yii\db\oci\QueryBuilder?

**Comment by albertborsos** [comment]
Sorry, I did not use Oracle since 2014, so i do not know what is the actual situation.

**Comment by samdark** [comment]
Seems the issue is abandoned then. Better wait till it occurs next time with more info...

**Comment by sucoec** [comment]
I have an issue... i'm trying to pre filter the content of my table... but when i want to use this:

`$query = Factura::find()->where(['not',['CLAVEACCESO' => null]])
                ->andWhere(['ESTA_CODI'=>'V'])
                ->andWhere(['>=','FACA_FEEM',TO_DATE('25/01/2016', 'dd/mm/rrrr')]);`

It shows me: Call to undefined function app\models\TO_DATE() what is right because in my model i don't have that function which is from oracle... i tried to use this:

`$query = Factura::find()->where(['not',['CLAVEACCESO' => null]])
                ->andWhere(['ESTA_CODI'=>'V'])
                ->andWhere(['>=','FACA_FEEM',"TO_DATE('25/01/2016', 'dd/mm/rrrr')"]);`

and it shows me this:

`Database Exception – yii\db\Exception
SQLSTATE[HY000]: General error: 1858 OCIStmtExecute: ORA-01858: a non-numeric character was found where a numeric was expected
(ext\pdo_oci\oci_statement.c:159)
The SQL being executed was: SELECT COUNT(*) FROM "TF_FACTURA_CABECERA" WHERE (NOT ("CLAVEACCESO" IS NULL)) AND ("ESTA_CODI"='V') AND ("FACA_FEEM" >= 'TO_DATE(''25/01/2016'', ''dd/mm/rrrr'')')

Error Info: Array
(
    [0] => HY000
    [1] => 1858
    [2] => OCIStmtExecute: ORA-01858: a non-numeric character was found where a numeric was expected
 (ext\pdo_oci\oci_statement.c:159)
)

↵
Caused by: PDOException
SQLSTATE[HY000]: General error: 1858 OCIStmtExecute: ORA-01858: a non-numeric character was found where a numeric was expected
(ext\pdo_oci\oci_statement.c:159)

in C:\xampp\htdocs\facturas_seted\vendor\yiisoft\yii2\db\Command.php at line 902
`

Is there a way to fix this?

Thanks in advance...

**Comment by apaoww** [comment]
Hi,

You should fixed is like this:

```
$query = Factura::find()
->where(['not',['CLAVEACCESO' => null]]) 
->andWhere(['ESTA_CODI'=>'V'])
 ->andWhere("FACA_FEEM >= TO_DATE('25/01/2016', 'dd/mm/rrrr')");
```

Let me know if it been fixed.

**Comment by sucoec** [comment]
Hi @apaoww thanks for your help it is fixed.

**Comment by sheillendra** [comment]
The best way is use db expression
```
$query = Factura::find()->where(['not',['CLAVEACCESO' => null]]) ->andWhere(['ESTA_CODI'=>'V']) ->andWhere(['>=','FACA_FEEM',new \yii\db\Expression("TO_DATE('25/01/2016', 'dd/mm/rrrr')")]);
```
