### ISSUE TITLE
i18n date formatting and mysql standard value 0000-00-00

### ISSUE THREAD

**Issue by ItsReddi** [yiisoft/yii2#6491]
Hi,
in most MySql Servers the standard date is 0000-00-00 if a date is empty.

the standard i18n formatter will format the value to
if app language is set to 'de'
`02.12.0002`

**Comment by cebe** [comment]
@yiisoft/core-developers can I have more opinions on this?

**Comment by klimov-paul** [comment]
Displaying dates like "0000-00-00" may look inlogical in "calendar" scope. That is because "zero" date simply does not exist in calendar. Zero date is a paradigm - walk around for the machine processing - which responds the situation when date is not set.
Actually for MySQL zero date value usually converted to "1970-01-01" - the Unix epoch start date.

It is fine to diplay "0000-00-00" for the empty date. At least it is better then showing "02.12.0002".
However I am usure if we can handle this properly. Do not forget that formatter should support various date formats and display zero value correspondingly, e.g. "00.00.000", "00/00/0000" and so on.

**Comment by cebe** [comment]
Just re-read the issue and found that the request is not really clear. @ItsReddi do you expect the value `0000-00-00` to be rendered as `00.00.0000` or as nullDisplay i.e. `(not set)`?

Considering `0000-00-00` as empty and treating it the same way as `null` would be possible but implementing a formatter that produces locale aware formatting like `00.00.0000` will not work.

**Comment by dimbs09** [comment]
From mySQL doc: **Illegal** DATE, DATETIME, or TIMESTAMP values are converted to the “zero” value of the appropriate type ('0000-00-00' or '0000-00-00 00:00:00'). So as Klimov said it's just a workaround that prevents a failure but **it doesn't mean that it's ok** to pass 0000-00-00. It`s there just to protect data from wrong application logic.
 
Moreover, MySQL doesnt accept TIMESTAMP values that include a zero in the day or month column or values that are not a valid date. 
The only exception is '0000-00-00 00:00:00'... 

Also the record header of InnoDB tables contains a bit vector, and the columns that are NULL do not occupy space other than the bit in that vector. Therefore passing NULL instead of 0000-00-00 00:00:00 we may save 8 bits of space per row.  

In my humble opinion, if a date is a required (NOT NULL) field, then the application shouldnt validate any of illegal formats (nor 0000-00-00 neither 2015-01-32), else if it`s not a required field then an empty value should be treated as NULL but not as a 0000-00-00 dummy which takes extra space for no reasons.

**Comment by ItsReddi** [comment]
Sry for the late reply. exams.. 
0000-00-00 is null so not set

**Comment by cebe** [comment]
Adding a conversion for this makes the implementation too complicated, the proper way to store empty dates is to store `NULL` in the database it is unambiguous and uncomplicated.
