### ISSUE TITLE
itemOptions don't apply for yii\boostrap\ActiveField::checkboxList and ::radioList

### ISSUE THREAD

**Issue by Tigrov** [yiisoft/yii2#6527]
```$options['itemOptions']``` is not used for generation inputs.

https://github.com/yiisoft/yii2-bootstrap/blob/master/ActiveField.php#L254
https://github.com/yiisoft/yii2-bootstrap/blob/master/ActiveField.php#L280

#5483

**Comment by MrEhbr** [comment]
Checked on 2.0.5 still doesn't work, but it works whith

**Comment by makroxyz** [comment]
+1

**Comment by cronfy** [comment]
This is because yii\bootstrap\ActiveField uses custom formatter by overriding 'item' option: https://github.com/yiisoft/yii2-bootstrap/blob/master/ActiveField.php#L269 (look near `!isset($options['item']`).

Implementation contradicts the [documentation] (http://www.yiiframework.com/doc-2.0/yii-bootstrap-activefield.html#radioList()-detail), where is said:

>Options (name => config) for the radio button list. For the list of available options please refer to the $options parameter of yii\helpers\Html::activeRadioList().

Indeed, options of `yii\helpers\Html::activeRadioList()` can not be used for rendering `yii\bootstrap\ActiveField::radioList()`.

Either documentation, or bootstrap radioList() implementation should be fixed.
