### ISSUE TITLE
"*" pattern for default translations

### ISSUE THREAD

**Issue by disem** [yiisoft/yii2#6762]
Can this be used by default if i18n is not configured?
This will be helpful for extensions.
I have added i18n support in my extension, but have no any translation files to share. So everybody who use my open-sourced extension must define \* category in configuration even if they don't use i18n. This adds one more step to extension installation and this can be fixed by using \* as a default source. What do you think?

**Comment by qiangxue** [comment]
What kind of message source will be used then?

**Comment by dynasource** [comment]
to what extent is this issue covered by:
* http://www.yiiframework.com/doc-2.0/guide-tutorial-i18n.html#default-message-source

`
# Specifying default message source
You can specify default message source that will be used as a fallback for category that doesn't match any configured category. You can do that by configuring a wildcard category *. In order to do that, add the following to the application config:
`

**Comment by samdark** [comment]
The original issue is about using it be default. The doc explains how to configure it overall. Since there's silence for a year, I think it's not really worth changing i.e. current defaults are OK.

**Comment by samdark** [comment]
The original issue is about using it be default. The doc explains how to configure it overall. Since there's silence for a year, I think it's not really worth changing i.e. current defaults are OK.
