### ISSUE TITLE
How to use beforeAjaxUpdate & afterAjaxUpdate within Yii2 Gridview widget?

### ISSUE THREAD

**Issue by manojsinghadha** [yiisoft/yii2#6847]
I do not found beforeAjaxUpdate & afterAjaxUpdate property within Yii2 Gridview widget.

**Comment by nirvana-msu** [comment]
There is no custom javascript supplied with these grids anymore. Instead, you should wrap your grid inside [pjax](http://www.yiiframework.com/doc-2.0/yii-widgets-pjax.html)

In the [pjax documentation](https://github.com/defunkt/jquery-pjax#events) they suggest binding your callbacks to `send` and `complete` events that are fired during pjax lifecycle (there are many other events fired as well). You can do it like so:
```js
$(document).on('pjax:send', function () {
    // Do something before pjax load
});
$(document).on('pjax:complete', function () {
    // Do something after pjax load
});
```
You could obviously use some specific selector instead of attaching listener to the `document`.

**Comment by manojsinghadha** [comment]
Thanks @cebe
