### ISSUE TITLE
[doc] anchors not works in Firefox 35 ?

### ISSUE THREAD

**Issue by pasmanp** [yiisoft/yii2#7013]
Open link:

http://www.yiiframework.com/doc-2.0/guide-db-active-record.html#accessing-column-data

In Firefox page opens, but not at anchor `accessing-column-data`.

**Comment by samdark** [comment]
We should change `<h1>Active Record <a href="#active-record" name="active-record" class="hashlink">¶</a></h1>` to `<h1>Active Record <a href="#active-record" id="active-record" class="hashlink">¶</a></h1>` i.e. using `id` instead of `name`. In the [final W3C spec](http://www.w3.org/TR/html5/text-level-semantics.html#the-a-element) `a` doesn't even have `name` attribute and the validator complains that it's deprecated.

**Comment by cebe** [comment]
Fixed, thanks for reporting!

**Comment by pasmanp** [comment]
i'm impressed by so fast patch :-)
