### ISSUE TITLE
Core Validators compare dates

### ISSUE THREAD

**Issue by ipppinto** [yiisoft/yii2#7047]
['data_inicio', 'compare', 'compareValue' => Yii::$app->formatter->asDate('now', 'yyyy-MM-dd'), 'operator' => '>'],
['data_fim', 'compare', 'compareAttribute' => 'data_inicio', 'operator' => '>'],

In my model I can't compare dates with code above. Can I use compare with dates?

**Comment by cebe** [comment]
> In my model I can't compare dates with code above.

what exactly does not work? what is the error?

**Comment by ipppinto** [comment]
In the form if I choose any date the error always appears. Now is 2014-01-27. For data_inicio if I choose 2014-01-22 or 2014-01-29 the error appears in both cases. In core validator is possible use "compare" to dates? Or only for numbers?

**Comment by Faryshta** [comment]
the problem is that those are php strings. you are trying to compare

'2014-01-27' > '2014-01-22'

You have to convert them to unix time or use date_diff

**Comment by Faryshta** [comment]
@ipppinto i solved it using http://www.yiiframework.com/doc-2.0/yii-behaviors-timestampbehavior.html for my active record models and datepicker filters. there is an example in #7014

**Comment by Faryshta** [comment]
I think i found a way to make the Compare validator accept Dates. It would be editing this line to take the values and convert them to unixtime https://github.com/yiisoft/yii2/blob/master/framework/validators/CompareValidator.php#L47

@cebe do you think thats a good idea, or do you think its better to make a different validator DateCompare so that it can support different formats or use the Yii::$app default format if its not provided?

**Comment by katzz0** [comment]
What the problem to compare strings '2014-01-27' and '2014-01-22'? These strings have a format for a reason. This format allows to compare date strings correctly. But this is not common case and if you have for example format dd.mm.yyyy (27.01.2014) then it will not convenience.

**Comment by dynasource** [comment]
duplicate https://github.com/yiisoft/yii2/issues/3581
