### ISSUE TITLE
ActiveRecord::findOne() returns 1st row instead of null

### ISSUE THREAD

**Issue by kurrata** [yiisoft/yii2#7066]
If you do ActiveRecord::findOne() passing array with 1 value pair where key isn't primary key and value is (bool)false or (int)0 result will be 1st row in table instead of null

```php
$postOffice = PostOffice::findOne([
     'post_code' => false
]);

$postOffice = PostOffice::findOne([
     'post_code' => 0
]);
```

**Comment by samdark** [comment]
Do you mean you have no record in `post_office` table with `post_code` field equals to `0` but getting a record instead of `null`?

**Comment by kurrata** [comment]
Yes, i have no rows in table matching that condition and i dont get null value as result

Table has couple of hundred rows and all post_code fields are in format "LV-\d{4}"

**Comment by Alex-Code** [comment]
If you have the debug toolbar enabled you could see the query that is being generated.

**Comment by cebe** [comment]
which database system are you using?

**Comment by nvthaovn** [comment]
If "post_code" field is string (varchar or text ...) and first character is not a numeric.
Condition 
```
'post_code' => false
```
 or 
```
'post_code' => 0 
```
always return  true ?

**Comment by kurrata** [comment]
@Alex-Code In both cases this query is generated and yii debug logs thinks it has executed corectly(line is green)
```sql
SELECT * FROM `post_office` WHERE `post_code`=
```
@cebe database and its version
```
➜  ~  mysql --version
mysql  Ver 15.1 Distrib 10.0.13-MariaDB, for Linux (x86_64) using readline 5.1

```

**Comment by Faryshta** [comment]
Do you have fields where post_office is empty? `(string) false` returns and empty string as does `(string) 0`

**Comment by Faryshta** [comment]
Using the {{%user}} table provided on the yii2-advanced-app i tried executing this query directly to mysql

~~~sql
SELECT * 
  From user
  Where auth_key = false and auth_key = 0
    and password_hash=0 and password_hash = false
    and email = false and email = 0
~~~

It returns every row empty or not.

I found that this behavior is even documented http://dev.mysql.com/doc/refman/5.5/en/type-conversion.html so `its not a bug its a feature` would be the only answer we would get from mysql devs.

```sql
Select 'something@example.com' = 0
```

returns true because

```php
Select cast('something@example.com' as SIGNED)
```

return 0.

The only way to avoid this is if your field start with a number. `cast('14something' as SIGNED)` returns 14. so `'14something' = false` returns false

So this is a documented 'feature' on mysql.

The question is. what should we do on active record? should we try to fix this behavior even when its documented?

**Comment by Faryshta** [comment]
@kurrata to fix your problem  try

```php
$postOffice = PostOffice::findOne([
     'post_code' => '' //instead of false
]);

$postOffice = PostOffice::findOne([
     'post_code' => '0' //instead of 0
]);
```

**Comment by klimov-paul** [comment]
Issue confirmed.
Unit test to reproduce:
```php
public function testIssue()
    {
        $row = Customer::findOne(['name' => false]);
        $this->assertNull($row);

        $row = Customer::findOne(['name' => 0]);
        $this->assertNull($row);
    }
```

**Comment by samdark** [comment]
What's the query generated?

**Comment by klimov-paul** [comment]
Query generated is correct:
`SELECT * FROM `customer` WHERE `name`=:qp0`

It is obvious param binding makes a mess.

**Comment by klimov-paul** [comment]
Figured this out.
This MySQL (may be some other DBMS) specifics.
If you run query
`SELECT *FROM `Customer` WHERE name = 0;`
It returns all rows.
It is like PHP comparasion `'string' == 0`.
There is nothing we can do here I am afraid.
Developer should consider conditions he compose himself.
