### ISSUE TITLE
Propose New Application Template

### ISSUE THREAD

**Issue by hscstudio** [yiisoft/yii2#7122]
Why template basic not include a important feature? it is login as database.. basic is recommendate for newbie and simple project.. but I think its too simple.. in yii1.. demo blog use login as database..

now If I want develop simple project.. I use advanced template because full feature.. and then I drop backend or frontend because I only want one application. I think drop backend or frontend not elegan way

I think its overkill to use advanced for simple project.. but basic template cannot be base simple project.. because I should copy paste feature login as database, register, and widget alert.. its importance feature.. so copy paste not elegan way.. :)

Newbie.. will confuse to start new project.. I am trainer.. so I know about it..

I propose 4 application template.. 
1. Basic Template (basic without login as database)
2. Single Application (basic with login as database and other feature as advanced)
3. Multiple Application (advanced template)
4. Benchmark 

Thank you..

**Comment by samdark** [comment]
Yeah, I've noticed it as well that I'm copying over some code from advanced into basic each time.

**Comment by hscstudio** [comment]
And we can see, a lot of people and then make their own basic templates and complete with advanced features ..

I think telling a beginner to use application templates belonging to others is not the right step .. fearing not follow best practices in Yii ..

**Comment by PrplHaz4** [comment]
Searching yii2 template on github shows a ridiculous proliferation of app templates - which to me is a clear sign something is missing...I am not really sure how to tell what the commonalities are between them, and what would be a good general case to develop for though....

I think 2. Single Application is a pretty good proposal - and I probably would have used that instead of a mish-mash of basic and advanced that I have ended up using in a few different apps.

Another pain point is that namespaces across templates (frontend/models vs web/models...etc) aren't consistent, so using pieces from advanced in basic takes a little more thought (realistically though, you only need to learn this lesson once)....

**Comment by armab** [comment]
REST API app example designed for mobile app as a consumer is good idea btw.

**Comment by samdark** [comment]
Agree but it's quite time consuming to build even if I'm familiar with Android.

**Comment by Faryshta** [comment]
i am working with something like what @armab says. But I am using angular.js to create a single page crud (ideal for mobile to avoid reloading).

Angular.js also has ionic which allows you to compile your code into an installable app for ios and android.

Would it be a good idea to publish something like that? yii2-angular-app or yii2-mobile-app or yii2-restmobile-app (i am bad with names)

**Comment by PrplHaz4** [comment]
@Faryshta that is exactly what I was thinking. @githubjeka has built https://github.com/githubjeka/angular-yii2 so I don't think creating another that does the same is a good idea (there is already an unnecessary proliferation of app templates IMO) but I have not looked into it enough to see if its worthy of being "the one"

**Comment by Faryshta** [comment]
i found two angular and yii2 proyects on windows but sadly not what i needed.

For example, they use git modules instead of composer

**Comment by githubjeka** [comment]
REST API required essence ($model - Post, Comment, Page ....). This model strongly depends on the task. This is the reason why it is impossible to create demo REST API application. Documentation and Gii-tool is enough for this purpose. If you it is still not enough, you can refer to a [specific task](https://github.com/yiisoft/yii2/issues/7122#issuecomment-73728418) and to expand it to fit their purpose.

**Comment by fernandezekiel** [comment]
a rest api client app would be nice but if we can also decide our REST API documentation would be (like `swagger` or `raml`), those two itself serves as a REST client

**Comment by schmunk42** [comment]
This topic has been discussed many times and I think there are simply different opinions on this.

For example, since I've started working with Docker to me the advanced template is a dead-end, because it does not fit into the concept of single isolated processes. Another problem for me was the total overload of config files, but other users and developers have a different opinion and the good thing about Yii is, that you have the freedom to choose.

Related issues
- https://github.com/yiisoft/yii2/issues/4734
- https://github.com/yiisoft/yii2/issues/6059
- https://github.com/yiisoft/yii2/pull/7155

**Comment by tunecino** [comment]
those are 4 templates.

the advanced one has vagrant now but not all people are using vagrant.
the basic one has no authentication. if you check the Yii related questions at Stackoverflow you'll see that most newbies are starting with the advanced template instead of the basic one due to its support of authentication.

I like the idea of 4 templates and I like vagrant being included but can't it be more dynamic for 2.1 ? something that works like yeoman.io for javascript or like [angular2 cli](https://cli.angular.io/). I mean you download the framework core + requirement.php then you do `./init` and you answer some questions before generating the proper starting template, like maybe:

```
select 1 for basic or 2 for advanced.
do you need to maintain different environments within different config files?
is it rest or web app ?
do you need authentication ?
do you need vagrant ?
will you use twitter bootstrap ?
```

that will require pre-building all those templates anyway but it will make Yii much easier to use and learn for newcomers.

**Comment by samdark** [comment]
Yeah, probably it's a good idea.

**Comment by schmunk42** [comment]
Here's our minimal (100 lines, no-db), state-of-the-art Yii2 application template with Docker: https://github.com/dmstr/docker-yii2-app

Includes also unit & functional testing with the brand-new `codeception/codeception` image.

**Comment by mikehaertl** [comment]
There are many ways how to set up a Yii app with docker. Here's our take: https://github.com/codemix/yii2-dockerized

**Comment by dynasource** [comment]
please continue any ideas & suggestions about Application templates in the other repo. Please 1 idea per topic please
* https://github.com/yiisoft/yii2-app-basic/issues
