### ISSUE TITLE
Query caching when query don't return any row (return false)

### ISSUE THREAD

**Issue by xVismutx** [yiisoft/yii2#7211]
For example

        return $db->cache(
            function ($db) use ($itemName, $userId) {
                /* @var Connection $db */
                return (new Query)
                    ->select(['item_name'])
                    ->from([$this->assignmentTable])
                    ->where(['item_name' => $itemName, 'user_id' => $userId])->scalar($db);
            },
            5
        );

I want to cache this query, when it returns false
How can i do it?

**Comment by lynicidn** [comment]
ask here on forum ? http://yiiframework.com/forum

**Comment by samdark** [comment]
Out of the box you can't because most of backends i.e. memcache, wincache etc. don't support storing null/false so there's no difference between "key contains false" and "nothing with such key". Since in many cases there's no need to cache "no result" we haven't added any wrappers to our cache layer in order for it to be simpler and more performant.

You still can implement it by choosing a special value such as `NOTHING_RETURNED` and storing/checking it manually in case query returned nothing.

**Comment by cebe** [comment]
I think the problem is in Command class which does not cover this case:

https://github.com/yiisoft/yii2/blob/master/framework/db/Command.php#L808
