### ISSUE TITLE
Disabled inputs are validated by client validators

### ISSUE THREAD

**Issue by nkovacs** [yiisoft/yii2#7341]
If a disabled input has an invalid value, Yii won't let me submit the form, even though that input won't be posted, since it's disabled.

**Comment by samdark** [comment]
By won't let you mean clientside validation?

**Comment by nkovacs** [comment]
Yes, clientside validation by default prevents form submit if the form is not valid.

**Comment by lynicidn** [comment]
it expected behavior. If client validation has errors then form do not submitted
@samdark как по мне это логично, если поле отключено, все равно валидация его нужна, можно же и curl запрос сделать, да и disabled форм отправляет значение, а следовательно нужна его валидаци, если это поле содержит ошибки, то сохранение и не должно проходить

**Comment by nkovacs** [comment]
Disabled fields are not submitted by the browser.

**Comment by nkovacs** [comment]
My specific use case is that I have a form with multiple models. One of them can be disabled (all the inputs are set to disabled, so the model isn't submitted, $model->load will be false and the php code will handle that), but the form can't be submitted because this model has required attributes and the validation still runs on the disabled inputs. I worked around this by using $.fn.yiiActiveForm's add and remove methods.

**Comment by samdark** [comment]
@nkovacs I assume the following:

1. Disabled fields aren't required.
2. Disabled fields were filled with invalid value.

Is it correct?

**Comment by nkovacs** [comment]
No (see my previous comment), but that's another possible use case.

**Comment by samdark** [comment]
OK, that makes sense. I think we could skip validation for a field if it's disabled.

**Comment by nkovacs** [comment]
One more thing. If the field has errors and it's disabled, the error class and the error message will remain.  $.fn.yiiActiveForm doesn't have a public method to update a field's error status. What would be the correct way to clear the errors in this case? The remove method in yii.activeform.js doesn't remove the error messages, so we have to reimplement some of the code from yii.activeform.js (using $form.data() to get the activeform settings), but that's not really an ideal solution.

**Comment by cebe** [comment]
If a field is disabled, i.e. the user should not be able to change it, you have to remove it from the scenario/validation rules. otherwise it is possible to edit the html, enable the field and change its value.

**Comment by nkovacs** [comment]
An average user is not going to edit the html. But if they do, then the client side validation will stop the form submission.
On the other hand, if I use .yiiActiveForm remove and disable the field, and then if the user re-enables the input, it won't be validated.
Besides, what's to stop the user from disabling javascript, for example? Client side validation is just a convenience, it can be circumvented in a million ways.

**Comment by cebe** [comment]
for that reason you have to remove it from server side too otherwise user will be able to change it even if he is not supposed to.

**Comment by nkovacs** [comment]
I don't want to remove the attribute from the server side validation. I want the attribute to be validated if it is posted. But if the input is disabled, the attribute will not be posted and will not be validated on the server, so it shouldn't stop me from posting the form.

**Comment by samdark** [comment]
I think it's a valid case. disabled = doesn't exist.

**Comment by qiangxue** [comment]
> But if the input is disabled, the attribute will not be posted and the value the user entered into the field will not be validated on the server...

Even if the input is not submitted, it will still be validated on the server. I agree with @cebe that the current behavior should be kept. You may disable client validation for disabled attributes manually.

**Comment by samdark** [comment]
What if attributes are disabled on the clientside dynamically? How to disable client validation in this case?

**Comment by lynicidn** [comment]
beforeValidate?

**Comment by qiangxue** [comment]
That's a different story, and there's js method `remove()` to remove an attribute from being validated on the client side.

**Comment by samdark** [comment]
OK. If it's covered than it's nothing to fix.

**Comment by lynicidn** [comment]
i think need docs for integrated with frontend frameworks

**Comment by samdark** [comment]
It's not about any frontend framework. If by frontend framework you mean Yii code then yes, we need to document it.

**Comment by lynicidn** [comment]
yes, i mean docs for js objects api

**Comment by fsateler** [comment]
This is a valid request. When an input is disabled it will not be posted. It effectively becomes a label, so there is no validation needed.

Use case 1: A form displays a user, and a user can have multiple addresses. Each address has a required street name. By disabling a whole address I can mark it as removed and the server can take appropriate action.

Use case 2: A field is meaningful only under certain conditions. Client side code hides and disables the input when it is not used.

Alternative methods require either clearing the input (if the validation in question is not of the required type) or deleting the input (if the validation is required).

Currently as a workaround I am inserting this on my apps:

    // Disable client-side validation when input fields are disabled.
    $('form').on('beforeValidateAttribute', function (event, attribute) {
        if ($(attribute.input).prop('disabled')) { return false; }
    });

**Comment by SamMousa** [comment]
I know this is closed, but I am unsure why.
It makes sense that if I disable a field client side it does not get validated by Yii right?


I am especially unclear  on the arguments against the alternative (and imo more intuitive) behavior.
Why would we ever want to validate a disabled input with client side validation?
1. A user cannot edit it, client validation is to improve UX.
2. If a user manually edits the page client validation is irrelevant.

Furthermore HTML5 does not validate disabled inputs AFAIK, so principle of least surprise suggests Yii2 does the same...

**Comment by SilverFire** [comment]
Agree with @fsateler and @SamMousa. There arguments are right, disabled fields should not be affected by any kinds of client validations.

**Comment by nkovacs** [comment]
@qiangxue 
> Even if the input is not submitted, it will still be validated on the server. I agree with @cebe that the current behavior should be kept. You may disable client validation for disabled attributes manually.

No, it won't be validated on the server.
A disabled field with an invalid value will prevent form submission due to client side validation. The server won't receive the invalid value, so it won't cause a validation error.

**Comment by SamMousa** [comment]
Client side validation is to tell the user there is something wrong so he can correct it without waiting for a round trip right?

So the scenario with current behavior looks like this:
1. User chooses an option from a radio button.
2. Based on that response the application (client side) disables a few fields (this is the custom part).
3. The user can no longer edit the disabled input, as per default browser behavior.
4. The user tries to submit the form.
5. Yii tells the user he can't submit because the input is wrong.
6. The user now has to figure out why the input was disabled and undo that.
7. The user fixes the input error.
8. The user re-selects his originally selected radio button.
9. The user clicks submit.
10. Now all fields are valid and Yii allows submission to proceed...

Interestingly at 5 the error message could be described as "Yes, we know the field is irrelevant and will not even be sent to the server, but still: FIX IT".

The logical and expected behavior in my opinion should be:
1. User chooses an option from a radio button.
2. Based on that response the application (client side) disables a few fields (this is the custom part).
3. The user can no longer edit the disabled input, as per default browser behavior.
4. The user tries to submit the form.
5. Yii allows submission to proceed if all enabled inputs are valid.

**Comment by nineinchnick** [comment]
If you add custom JS code that disabled some fields you should also make relevant validator rules conditional on the server side.

**Comment by SamMousa** [comment]
I agree, but that is not related to this discussion.

**Comment by nineinchnick** [comment]
Oh sorry! You've posted such a complete example I didn't notice it's for an existing issue.

I agree disabled fields shouldn't be validated, because their value/state cannot change directly.

**Comment by SamMousa** [comment]
#9928 --> I have tested it manually, and it passes automated tests, but i'm not sure they include in depth javascript testing (if at all)

**Comment by jurchiks** [comment]
This issue is still actual.
Yii 2.0.15.1, outputting a field like this:
```
<?= $form->field($client, 'patronymic')
	->textInput([
		'readonly'               => 'readonly',
		'enableClientValidation' => false,
		'enableAjaxValidation'   => false,
	])
	->label(true) ?>
```
For display purposes only, it's not read server-side.
But when I click on it and then click on something else, an AJAX request with validation is STILL being sent, even though it simply results in the validation being successful since this field is not in the rules.
This doesn't make any sense, it's just a waste of resources and traffic to do validation on a field like this.

**Comment by jurchiks** [comment]
It's the same functionally.

**Comment by samdark** [comment]
Well, it will certainly be lost here in an issue that was closed in 2015 as solved.

**Comment by maz0717** [comment]
First, readonly fields till get submitted to the server.  Use disabled instead of readonly to prevent items from being submitted to the server.  Readonly fields do still get validate by the javascript validators.  I'm not sure if that is intended or not.  Disabled fields are not getting validated.  Another problem with the posted code is that you are setting enableClientValidation and enableAjaxValidation as options to textInput() when they should be options to field().
