### ISSUE TITLE
Reorganize the guide menu

### ISSUE THREAD

**Issue by mikehaertl** [yiisoft/yii2#7395]
I find the navigation menu in the Yii2 guide to be very confusing, as it is often not quite clear, where to find information on a specific topic. This was much better organized with Yii 1.

An example: I want to read the section on "Assets", so where is it? Let's see, it sounds like a "Special Topic" ... nope. Ah, maybe "Key Concepts"... nope. Hmm. Could it be in "Widgets", as assets are often widget related? Again nothing there. Ok, last try "Handling Requests" - nothing either. By that point I open up all the main topics and finally find it under "Application Structure".

Aha, so "Assets" are part of "Application Structure". Then again "Logging" is not (it's in "Handling Requests"). Looks very arbitrary to me.

I'd suggest: Use less and more clear main topics, closer to what we had with Yii 1.

**Comment by samdark** [comment]
Any idea on how to reorder current topics?

**Comment by mikehaertl** [comment]
I can only repeat myself: I'd use fewer main topics. The current ones are too vague to really be helpful when you look for something specific. Even one single long alphabetic list of all topics would be more useful to me than what there is now. As I'm no writer, I can't really come up with better suggestions - but there for sure are some experts on technical documentation that can come up with a clearer structure.

**Comment by qiangxue** [comment]
The organization is definitely not arbitrary. Asset is a static thing,
belonging to the app structure. Logging out s not so. I don't think we
should use fewer topics. Each of the current one already has a lot of
content. Alphabetical order is not acceptable either because it's not
friendly to new users. We may consider expanding the TOC by default so that
it's easier to do search.

**Comment by philippfrenzel** [comment]
The search Works super Fine, so Menu isn't that important ... Assets will be found in a sec

**Comment by cebe** [comment]
We will definitively improve the search on the new website.

**Comment by samdark** [comment]
I think there's a point in what @mikehaertl said since as a user I'm not sure where assets should be.

**Comment by qiangxue** [comment]
> I think there's a point in what @mikehaertl said since as a user I'm not sure where assets should be.

I don't think the point holds. The guide is organized like a book not a dictionary. If you are an experienced Yii user, you should use search to quickly locate the topic you are interested in.

**Comment by creocoder** [comment]
Absoluttely agree with @mikehaertl. Can't say what exactly wrong with current Guide TOC, but something wrong. Yii 1 guide does not have such troubles.

**Comment by qiangxue** [comment]
> Yii 1 guide does not have such troubles.

Yii 1 guide doesn't even have "assets" as a separate chapter.

**Comment by qiangxue** [comment]
> Could it be in "Widgets", as assets are often widget related? Again nothing there. 

If you already see "Widgets", you should see "Assets" is next to this entry in the TOC. So it seems to me the problem is exaggerated.

Anyway, the guide is organized in a way for new users to read from the beginning to end. As an experienced user, if you are looking for the explanation of a particular concept or a particular topic, you should really use search.

**Comment by kartik-v** [comment]
Specific to the **assets** example ... I could just type **assets** in the search box and it showed up as the first item to read.

I think the guide for yii 2 seems to be a work in process (few sections still in TBD and may get merged or divided). So as a user one probably has to manage this change... as they are not used to finding what where as in Yii 1.x. I however agree building the right TOC may help - as some topics in Yii 2 are new.

**Comment by qiangxue** [comment]
Let me add some more words to the current TOC design.

* The TOC design is not arbitrary. It has taken quite some time to design and been reviewed by several people.
* Even if some topics are marked as TBD, their location in TOC is not arbitrary.
* Application Structure: this reflects the code organization in your application. Assets, like controllers and models, are static objects and organized in a separate folder in your app.
* Handling Request: this explains the typical life cycles of request handling and the common objects you may touch along the life cycle.
* Key Concepts: these serve as the foundation of Yii. They are not particularly related with Web applications or MVC framework.
* The rest of the chapters: they are organized by individual topics. When a topic is very big, it is organized as a separate chapter; otherwise, they go into "Special Topics".

If you feel necessary to adjust the location of particular sections, please point them out. Otherwise, just claiming the TOC has something wrong is not constructive.

**Comment by kartik-v** [comment]
In fact I am saying it the other way around. IMO... the Yii 2 guide is more easier to search for specific functionality than Yii 1.x an example for **assets** above automatically leads you directly to the topic.

The point I was trying to make is about the **change management** needed from the user mindset when browsing a guide in Yii2 after coming over from Yii 1. I am ok personally with this change and can adapt to the structure since this is also logical. 

On the TBD sections my point was, since some topics are TBD - the user perception maybe that information is not completely available - leading to again saying they cannot find the info they find. So once we have the entire guide filled up - and people read it over and over and can access it with a navigation flow tuned in their mind - it should work out.

**Comment by qiangxue** [comment]
Thanks, @kartik-v. :)
