### ISSUE TITLE
Gridview doesn't return selected rows (Uncaught TypeError: Cannot read property 'selectionColumn' of undefined yii.gridView.js:140)

### ISSUE THREAD

**Issue by cognitivaxx** [yiisoft/yii2#7474]
I'm using the very last version of yii2 (2.0.2). I want just get selected rows from a standar gridView widget. But, when i select a row, i get "Uncaught TypeError: Cannot read property 'selectionColumn' of undefined yii.gridView.js:140" 

I have the next code: 

In the index view: 

```php
<?= GridView::widget([
        'dataProvider' => $dataProvider,         
        'columns' => [           
            ['class' => 'yii\grid\CheckboxColumn'],            
            'id',
            'titulo',
            'user.username',           
            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
```
```javascript
<script>
  $(document).ready(function(){
    $('#MyButton').click(function(){
       
       var keys = $('#grid').yiiGridView('getSelectedRows');
        $.post({
           url: 'http://localhost/cngrx/web/index.php/ponenciaresumen/asignarevisor', 
           dataType: 'json',
           data: {keylist: keys},
         
        });
    });
  });
</script>

<input type="button" class="btn btn-info" value="Asignar a revisor" id="MyButton" >
```

Thanks for advance!

**Comment by samdark** [comment]
Can't reproduce.

```
$('#w0').yiiGridView('getSelectedRows');
```

gives `[1, 2]` as expected.

**Comment by philippfrenzel** [comment]
Hi, I think this happens, as you put the grid into an pjax container?

**Comment by Doavers** [comment]
I got the same error. Even I used Pjax or not on my GridView..
Or maybe, you should use element id #w0 or #w1 instead of #grid.

Yii2 render this script
<pre>
jQuery(document).ready(function () {
jQuery('#modal-upload').modal({"show":false});
jQuery('#w0').yiiGridView({"filterUrl":"/advanced/backend/web/index.php?r=state%2Findex","filterSelector":"#w0-filters input, #w0-filters select"});
jQuery('#w1').yiiGridView({"filterUrl":"/advanced/backend/web/index.php?r=state%2Findex","filterSelector":"#w1-filters input, #w1-filters select"});
jQuery('#w1').yiiGridView('setSelectionColumn', {"name":"selection[]","multiple":true,"checkAll":"selection_all"});
jQuery('#w2').yiiGridView({"filterUrl":"/advanced/backend/web/index.php?r=state%2Findex","filterSelector":"#w2-filters input, #w2-filters select"});
});
</pre>

**Comment by AlexStich** [comment]
You just need to add "id" for GridView:
```
<?= GridView::widget([
        'dataProvider' => $dataProvider,        
        "id" => "grid"
        'columns' => [           
            ['class' => 'yii\grid\CheckboxColumn'],            
            'id',
            'titulo',
            'user.username',           
            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
```
