### ISSUE TITLE
Join type with deep joins missing

### ISSUE THREAD

**Issue by gpoehl** [yiisoft/yii2#7486]
While query builder allows defining join types for every table that relates directly to a model this seems not be the case for deep joins. Joins defined in models are always left joins.

To create an inner join between the second and third table in a join chain I had to write such a command:

``` php
// get only those buchungen having a journal and journal has a belegdatum >= $from
$data = Finanzkonto::find()
        ->joinWith(['buchungen' => function($query) use ($from) {
            $query->innerJoinWith('journal')
            ->andwhere(['>=', 'belegDatum', $from]);
             },
        ])
        ->andwhere (['owner'=>$owner))
        ->orderBy('id', 'belegDatum')
        ->all();
```

This looks very ugly and will get worse the more tables you need to join in a chain. Please also note that the condition for the journal table has to be defined in the subquery while the conditon for the finanzkonto (and buchung) tables are placed after the join operators. 

To sove this issue I'd like to make three suggestions.
1) Enhance the hasOne() and hasMany() to allow specifying the join types. The join types need to be used only on deep joins.
2) In querybuilder allow dot syntax not only for tables but also for join types.
3) For deep allow an array to specify the join chain where each element has one link within the chain.

Any other hints are welcome.

**Comment by cebe** [comment]
What about `->joinWith(['buchungen.journal']) ...` ?

**Comment by twinni** [comment]
@cebe, then the join between buchungen and journal is a **left join**. I need an **inner join** to get only those buchungen where journal meets some requirements (e.g.  'datecolumn' > $fromdate). 
Due to the fact that yii2 runs a query for each table in the join chain you get all buchungen related to the primary table (finanzkonto) and then only those rows out of the journal table which meets the where condition.
