### ISSUE TITLE
Navbar lack of personalization

### ISSUE THREAD

**Issue by invaderhd** [yiisoft/yii2#7499]
In a project I use Navbar extensively and I found that it should be more generic, for example:
-  we should be able to set the the only the classes that we want to use, but it append allwais the navbar class (ie. Html::addCssClass($this->options, 'navbar'); )
- it's impossible to remove the toggle button (ie. echo $this->renderToggleButton();). In some layouts we may have the toggle button in a different local.

The Navbar is a great class and works like a charm in the default bootstrap theme, but in custom layouts it is not generic enough to do it job.

Keep the good working guys ;)

**Comment by creocoder** [comment]
@invaderhd 

> but in custom layouts it is not generic enough to do it job

With correct bootstrap customizing you'll always have `class="navbar ..."` start. If you feel you do not need `navbar` class this is incorrect way of extending bootstrap. There is classes like `navbar-default` and `navbar-inverse`. If you need some different navbar, just create new class `navbar-project`.

> In some layouts we may have the toggle button in a different local.

For toggle button example needed.

**Comment by patlecat** [comment]
@invaderhd You are right, the Yii-components are usually rigid and cannot be easily customized, sometimes because of lack of documentation and sometimes because it's not possible. I wanted to add an icon instead of text but not possible. There is someone working on this though now. Don't know when the rest will be reworked or rather completed.
