### ISSUE TITLE
Response::sendContentAsFile() broken in Yii 2.0.3

### ISSUE THREAD

**Issue by brandonkelly** [yiisoft/yii2#7529]
This commit (https://github.com/yiisoft/yii2/commit/9028bc5aa74ea1b168e35d7e24afcc6c8d9fda32) changed the first line of yii\web\Response::prepare() from:
```php
if ($this->stream !== null || $this->data === null) {
```
to:
```php
if ($this->stream !== null) {
```
and now, sendContentAsFile() responses (which have `$this->content` but not `$this->data`) are no longer passing the condition. As a result, they proceed down the function, hitting this condition:

```php
} elseif ($this->format === self::FORMAT_RAW) {
    $this->content = $this->data;
} ...
```
overwriting `$this->content` (which sendContentAsFile() had set to the file’s contents) to `null`, resulting in a response that has no body.

**Comment by creocoder** [comment]
@samdark , @qiangxue , @cebe , @klimov-paul Issue confirmed. I once again appeal to core developers to start use **SemVer** and start making patch versions when it make sence.

**Comment by igorbelikov** [comment]
:sob:

**Comment by mikehaertl** [comment]
@creocoder I thought, the version scheme yii uses is already following [SemVer](http://semver.org/)?

**Comment by creocoder** [comment]
@mikehaertl No, unfortunately its not.

**Comment by mikehaertl** [comment]
@creocoder Could you explain, please? E.g. 2.0.3 pretty much *is* SemVer to me, no? What would be SemVer in your opinion?

**Comment by creocoder** [comment]
@mikehaertl Have you read link? :)

Given a version number MAJOR.MINOR.PATCH, increment the:

1. MAJOR version when you make incompatible API changes,
2. MINOR version when you add functionality in a backwards-compatible manner, and,
3. PATCH version when you make backwards-compatible bug fixes.

When new features added by following SemVer you should raise MINOR version. That means that we should have: 2.1.0, 2.2.0, 2.3.0 already. Patch versions used only for patches. Usually it work next way: master and develop branches. You merge develop with master only when you plan raise MINOR version. Patches very useful for force major situations like that to make new fw version available ASAP. If short Yii use PATCH section for MINOR purposes. So Yii not follow SemVer at all :) There is many examples of projects which trully follow SemVer (look at something start from L char :) ). Following SemVer give significant advantages.

**Comment by mikehaertl** [comment]
Thanks for explaining. I always thought Yii was following SemVer pretty srtrictly but now that I read the specs more closely for the first time it seems you're right. But this is probably something that won't be changed anymore in Yii 2 to avoid versioning confusion.

On the other hand it would be a big plus to have more frequent bugfix solution. I remember a situation with Yii 1 where you had to wait quite some time for bugfixes until the next release - just to find new other bugs introduced there.

@brandonkelly Sorry for being kind of OT here.
@creocoder Maybe worth a try to open another issue for this?

**Comment by qiangxue** [comment]
@creocoder We discussed about semver internally long time ago. Our current versioning strategy can be described as this, https://github.com/jonathanong/ferver, which we considered is more practical and reasonable.

Also, ideally we hope we can have a shorter release cycle so that issues like this can be fixed sooner than later. Unfortunately, currently we are relying on git subsplit, which is a very time-consuming process (it takes 8+ hours) when we have to make a release.

**Comment by creocoder** [comment]
@mikehaertl 

>Maybe worth a try to open another issue for this?

Its already done: https://github.com/yiisoft/yii2/issues/7408

@qiangxue 

> more practical and reasonable

For whom? At the current time, the use of exotic versioning approaches make Yii "black sheep" among all other PHP packages (which majority follow SemVer novadays). This require specific composer requre rules for Yii which differs from 100% safe rules for other packages. Simple example. I can use "leagule/flysystem:~1.0" inside composer.json and never have any headache with it. Its about trust. I can't use "yiisoft/yii:~2.0", i ever can't have "yiisoft/yii:~2.0.0" and last investigations show that only one reliable variation is "yiisoft/yii:2.0.2", so concrette version here.

On other side SemVer give packages not only trust aspect, it also have some marketing aspect (belive or not users buy higher versions better). By taking into account situation that we can use only concrette versions inside composer.json it lead to situation that some Yii versions will get less feedback than others. In that concrette case version 2.0.3 will have dramatically less feedback than 2.0.2 since it contains critical bugs. This is why patch versions ASAP is important. And last, but not least this why SemVer run the show novadays.

**Comment by samdark** [comment]
Everyone, let's discuss semver at #7408. This issue isn't about it. Thanks.

**Comment by samdark** [comment]
@brandonkelly, @creocoder can you show some code to reproduce the issue?

**Comment by brandonkelly** [comment]
@samdark Sure:

```php
$response = Yii::$app->getResponse();
$response->sendContentAsFile('testing', 'testing.txt', [
	'mimeType' => 'text/plain',
	'inline' => true,
]);
Yii::$app->end();
```

That will output “testing” in 2.0.2, but you’ll get a blank response body in 2.0.3.

**Comment by samdark** [comment]
Fixed.

**Comment by samdark** [comment]
@qiangxue what should we do about this regression releasewise?

**Comment by qiangxue** [comment]
We have to admit such thing may still happen in future, even if we have 100% test code coverage. In future, other than adding more test code coverage to reduce the chance of introducing regression issues, I think we can take the following practical ways:

* If the regression issue is severe, we should make a new release asap.
* If the issue is minor (like this one) or few people are complaining about it, we can wait till the next patch release.
* Ideally if we can make the git subsplit much faster, we should strive to make more frequent hotfix releases `2.0.x.Y`.

**Comment by starrychloe** [comment]
FML. I hit the one bug in all of 2.0.3, out of all the things that could be broken, and the fix is not released yet.  This is how to send a file without using that function.

```
      $headers = Yii::$app->response->headers;
      $headers->set('Content-Disposition', 'attachment; filename="shopwiz-'.date('Y-m-d').'.csv');
      $headers->set('Content-Type', 'text/csv');
      Yii::$app->response->content = $csv;
      return;
      // return \Yii::$app->response->sendContentAsFile($csv, 'shopwiz-'.date('Y-m-d').'.csv', ['mimeType'=>'text/csv']);
```
