### ISSUE TITLE
Guidelines to make clearer the issue tracking/development

### ISSUE THREAD

**Issue by sidtj** [yiisoft/yii2#7595]
Hi guys,

I really admire and like so much Yii for years. This is why I want to help on code, 
issues, docs and translation. But I feel a bit lost in the way that the things happen.

Supposing the scenario `Like a developer I want to fix an issue X`, these are my questions :

1. Who will define who codes?
2. Should anyone to start to code at anytime?
3. Can two or more people code in the same issue?
4. When someone is `assigne` to the issue is he supposed to be the coder, or the merger, or will he just follow the issue discussion? What exactly is supposed to be the `assigne`?
5. Who will decide that the code is enough to the issue? Is that one supposed to
say it clearly in the issue or in any other place / way?
6. When we know, somehow, the code is enough, who will merge and
what is taken into account to decide *when* it will be merged?

Sorry for so many questions, but the answers will make the devel, specially for contributors, more "fluid" and predictable.

Thanks in advance.

**Comment by lynicidn** [comment]
https://github.com/yiisoft/yii2/tree/master/docs/internals

**Comment by lynicidn** [comment]
https://github.com/yiisoft/yii2/blob/master/docs/internals/translation-workflow.md

**Comment by lynicidn** [comment]
https://github.com/yiisoft/yii2/blob/master/docs/internals/git-workflow.md

**Comment by cebe** [comment]
> Who will define who codes?
> Should anyone to start to code at anytime?

If you want to work on an issue that is not assigned or has the label `ready for adoption` you can start right away.
If someone is assigned, ask before you code because maybe the assignee has already started something.

> Can two or more people code in the same issue?

If they comunicate about who will do which part this should be possibke but normally one issue is small enough for one person to work on it.

> When someone is assigne to the issue is he supposed to be the coder, or the merger, or will he just follow the issue discussion? What exactly is supposed to be the assigne?

We can only assign core team members to an issue so this is the one from the core team which is responsible for the issue. This can mean that he wants to work on it later or that he is already working on it in the background. As said above if someone is assigned, ask in the issue if you can take it or not.

> Who will decide that the code is enough to the issue? Is that one supposed to say it clearly in the issue or in any other place / way?

If something is unclear, ask/discuss in the issue first before coding. If the issue is clear/trivial, just fix it and send a PR. If the code is not sufficient we will post and discuss on the PR until it is fine for merge.

> When we know, somehow, the code is enough, who will merge and what is taken into account to decide when it will be merged?

A core team member will decide to merge the code. If the thing is not trivial we will ask other core team members for opinion.

**Comment by sidtj** [comment]
@cebe, thank you so much for the answers. Now I can see how the things work as well as which is the hierarchy. 

The main point for me is: 
I have to refer to the `assigne` in most of the time in a issue for questions, asks, etc.

Thank you one more time.
