### ISSUE TITLE
Controllers

### ISSUE THREAD

**Issue by Rathil** [yiisoft/yii2#7645]
I want to ask.
I can understand why do so in the Yii1, but why do so in the Yii2, I can not.
Why each controller (file name, class name) to add the word "Controller"?
In the second version Yii, uses a namespace and I don`t see a strong need for this suffix.
Can you explain why made this decision and left the suffix for all controllers?

Thanks in advance for your reply.

**Comment by qiangxue** [comment]
One reason for doing this is to be able to locate *all* controllers by just looking at their file names.

**Comment by Rathil** [comment]
Agree that all controllers are usually lie in the same directory.

**Comment by Rathil** [comment]
I think it is a relic of the past, from which should be abandoned.

**Comment by qiangxue** [comment]
> I think it is a relic of the past, from which should be abandoned.

Not all because of that. Imagine we remove the `Controller` suffix. Now a post controller would be named as `Post`, which is very confusing as we also have `Post` model class. In our previous discussion, we agreed certain suffixes are helpful, such as `Interface`, `Behavior`, even though they are not necessary. Closing this as we don't have plan to make the change.
