### ISSUE TITLE
Yii::getAlias('@web');

### ISSUE THREAD

**Issue by rahulsinh** [yiisoft/yii2#7699]
@samdark  Yii::getAlias('@web'); this is provide  /backend/web path but i want this path http://local.example.com/backend/web/  please help me

**Comment by pana1990** [comment]
Try 
```php
Yii::$app->request->hostInfo . Yii::getAlias('@web');
```

Use forum for questions, please.

**Comment by samfreelancer** [comment]
The way I can figure out this problem is either of the ways.
1. Save the domain name under the params.php config file and when ever required just refer to config settings. Yii::$app->params['domain_name']
2. Or can be identified on dynamic basis using the Request API and PHP parse_url function.
However the same can be used in the config file so that no hard coding.
3. Or a shortcut is yii::$app->request->getHostInfo()

**Comment by rahulsinh** [comment]
@pana1990  thanks pana  it's working

**Comment by mdmunir** [comment]
```php
Url::to('@web',true);
```
