### ISSUE TITLE
Schema creation issue

### ISSUE THREAD

**Issue by tsvetann** [yiisoft/yii2#7774]
This fails:
`Schema::TYPE_DATETIME . "(6) DEFAULT 0"`
output: `0000-00-00 00:00:00` expected `0000-00-00 00:00:00.000000`
This works:
`"DATETIME(6) DEFAULT 0"`
output: `0000-00-00 00:00:00.000000`
on mysql 5.6.22

Documentation on what I am trying to use:
http://dev.mysql.com/doc/refman/5.6/en/fractional-seconds.html

**Comment by samdark** [comment]
Are you sure? There's no magic in `Schema` constants so it will certainly result in `datetime(6) DEFAULT 0` in the first case which is equal to the string in second case.

**Comment by cebe** [comment]
abstract types are only matched in lower case so this is the reason for the difference: https://github.com/yiisoft/yii2/blob/master/framework/db/QueryBuilder.php#L594

Should be fixed by adding a default value to the timestamp and datetime abstract types in mysql. Not sure how to deal with the change of the default in different mysql versions though.

**Comment by SamMousa** [comment]
For the default it would work to always pass the extra fractional digits, they get discarded for versions < `5.6.4`.
