### ISSUE TITLE
What is the concept of shared test config

### ISSUE THREAD

**Issue by tsvetann** [yiisoft/yii2#7781]
In `tests/codeception/config/config.php` There is a comment stating `Application configuration shared by all applications and test types`. When I re-define the `db` config for example in the `tests/codeception/config/backend/config.php` the shared one still prevails! What is the concept of shared config here. I would naturally expect the specific backend config to take precedence and override the shared one!

**Comment by tsvetann** [comment]
I just figured out that defining `db` config in `tests/codeception/config/backend/config.php` doesn't even work

**Comment by samdark** [comment]
By doesn't work you mean it's taken from common config?

**Comment by tsvetann** [comment]
Yes it is taken from common config if it exists there. I would expect the backend config to have higher priority than common

**Comment by lynicidn** [comment]
`tests/codeception/config/backend/config.php` it's common testing config for acceptance, functional and unit. U need use acceptance.php or functional.php or unit.php as config file

**Comment by tsvetann** [comment]
The latest test is that database config in `tests/codeception/config/config.php` works as expected. When moved to `tests/codeception/config/backend/config.php` Yii takes the db config from `common/config`. So not sure what `tests/codeception/config/backend/config.php` is for!

**Comment by igravity** [comment]
Should not be the case. Because if you look at the entry file for testing, the configuration for the acceptance suite is called after the configuration for the application itself. What I am not sure of is if this would overwrite already set configurations.

@tsvetann the behavior in your app is expected because of the order in which the config files are loaded. Try having nothing in your `/config/config.php` pertaining to the database and only having it in `/config/backend/config.php`. Does that solve the problem?

**Comment by samdark** [comment]
Should be solved by https://github.com/yiisoft/yii2-app-advanced/pull/190
