### ISSUE TITLE
Database Exception when using gUID (Globally Unique Identifier) as primary key.

### ISSUE THREAD

**Issue by NotFake** [yiisoft/yii2#7885]
There is a need to introduce support of gUID as primary keys in a database.

https://en.wikipedia.org/wiki/Globally_unique_identifier

We are using MS SQL database. Database driver: dblib. The primary key is used gUID. Primery key datatype: binary(16).
The code generated by the CRUD-generator, will not work. As a result of execution, we will get the Database Exception.

![1](https://cloud.githubusercontent.com/assets/8996448/6846705/f1f259a8-d3c8-11e4-91c3-d439d41739b7.png)

SQL query does not receive a record identifier, or in some cases, receive part of a identifier.

In the database identifier looks like "0x8136000C296DC08B11E4A7A3DE67CE9S". Yii2 reads it as string �6' . "\0" . ')m��䧣�gΜ.
![2](https://cloud.githubusercontent.com/assets/8996448/6846708/f470ec80-d3c8-11e4-87fc-f71cb3a852c1.png)
When converting a key by function mssql_guid_string($ID), we will get it like "0C003681-6D29-8BC0-11E4-A7A3DE67CE9S". To avoid exception, it is necessary when we get data from the database to convert identifier to a string by the function mssql_guid_string. With further generating a query with this identifier, we will must to convert back to binary(16) data type. Or work with them as binary data and screening when inserting in requests.

Will there be support gUID?

**Comment by lynicidn** [comment]
discussion on russian forum http://yiiframework.ru/forum/viewtopic.php?f=19&t=23126

**Comment by klimov-paul** [comment]
I am unsure I understand demand correctly.
As far as I see 'binary' type column reading and writing is suppored. These columns will be typecast into 'resource' PHP type.
Are you saying you cann't retrieve or store binary data into the database?

As far as I see you are compning on invalid string returned from GET. Yii can't influence it anyhow.
It is up to you to process incoming request parameters.
I assume this happens because you have rendered your 'id' column as it is, while composing the link somewhere in the listing.

If `mssql_guid_string()` can do a trick for you, you probably should use 'beforeInsert', 'beforeUpdate' and 'afterFind' events to perform such convertions for your models.

Issue title seems to be actually incorrect.
If there is indeed a problem saving or retrieving binary data from database - it should be solved. But there is no way of knowing if your primary key gUID or not, as well as there is no way to determine if some string at GET or POST should be convered by some function.

**Comment by klimov-paul** [comment]
I can't see any issue related to Yii here.
