### ISSUE TITLE
REST OptionsAction() won't return, but run action instead

### ISSUE THREAD

**Issue by pappfer** [yiisoft/yii2#7966]
When there's a preflight request (with OPTIONS method) coming I see that [OptionsAction()](https://github.com/yiisoft/yii2/blob/master/framework/rest/OptionsAction.php) sets the corresponding "Allow" headers. However after that it lets the script run further, so the actual action will run and after the real request comes (for example a POST request) the action will run again.
Why isn't there a "return" or a "Yii::$app->end()" present in OptionsAction()? Now, because of the fact that the actual action runs twice it doubles the pageload time.

According to [this flowchart] (http://www.html5rocks.com/static/images/cors_server_flowchart.png) only a HTTP response should be set without the body (so the script shouldn't run the action itself).

**Comment by qiangxue** [comment]
> However after that it lets the script run further, so the actual action will run and after the real request comes (for example a POST request) the action will run again.

Do you mean the options action will run twice in the same request? How comes?

**Comment by pappfer** [comment]
No. The options action runs only ones, but it doesn't end the app, so the action I'm sending the request to will run twice.

For example a client sends a request to example.com/controller/test then this is what happens:
1. an OPTIONS http method will be sent first and OptionsAction() will run
2. OptionsAction() will set the "Allow" header and won't end the script but will let it run further
3. actionTest() will run for the first time and return with success
4. client sends the real POST request now
5. actionTest() runs again

See a screenshot what I mean (please ignore the data validation error now):
![options](https://cloud.githubusercontent.com/assets/738623/6964930/02833bea-d94e-11e4-9b5b-b6bf0c149962.png)

**Comment by qiangxue** [comment]
> 2. OptionsAction() will set the "Allow" header and won't end the script but will let it run further
> 3. actionTest() will run for the first time and return with success

I don't understand why these two steps will happen in the same OPTIONS request. In each request, only one action will run. How comes it runs two in this case?

**Comment by pappfer** [comment]
That is also what I don't understand. I guess that when there's a request with OPTIONS method Yii, will automatically run this action: https://github.com/yiisoft/yii2/blob/master/framework/rest/OptionsAction.php
But it will not return anything (only set the "Allow" HTTP header) and it will also run the requested actionTest().

**Comment by fernandezekiel** [comment]
how were you able to know that actionTest gets executed on the OPTIONS request?

**Comment by pappfer** [comment]
@fernandezekiel: I put a sleep(4) in actionTest() and I saw that the response time for OPTIONS method was also 4000ms and for the POST method it was also above 4000ms.

**Comment by fernandezekiel** [comment]
what's your URL config for actionTest?

**Comment by qiangxue** [comment]
@pappfer I think it's better you do a step-by-step debugging to find out why...
From your screenshot, it seems the OPTIONS request returns body content with length 0, which is expected. The POST request is another separate one.

**Comment by pappfer** [comment]
@fernandezekiel: I'm using default yii\rest\UrlRule for that controller. I unset actionIndex and using my own, see below.

@qiangxue I attached another screenshot. I'm using productController actionIndex(). I added a sleep(5) in actionIndex() and see the response times.
```php
public function actions()
    {
        $actions = parent::actions();
        unset($actions['index']);
        return $actions;
    }

    public function actionIndex() {
    	sleep(5);
        // + other code and at the end return HTTP 200 status here
    }
```

![product](https://cloud.githubusercontent.com/assets/738623/6965855/c925d540-d954-11e4-8c77-c9e9c47c76d7.png)

**Comment by fernandezekiel** [comment]
if you are using the `yii\rest\UrlRule` and unsetting the `index` why is your screenshot about the `POST` request?

**Comment by pappfer** [comment]
@fernandezekiel I'm unsetting the index action because I'm using my own one. I want to send a POST request to it (I think it doesn't matter in this case whether I wanna send a POST or a GET to it) and first it sends the OPTIONS request. But for both the OPTIONS and POST it gets into my actionIndex() and waits 5 seconds, so it takes 10 seconds to load this action.
What I don't understand is that why does the OPTIONS request get into my indexAction()?

**Comment by fernandezekiel** [comment]
can you show us your url rules? try also throwing an exception in the actionIndex and do a raw OPTIONS request using some kind of rest api client,

**Comment by pappfer** [comment]
Seems like the problem was indeed because of using the wrong URL. I was using "/product" instead of "/products" (I don't have enableStrictParsing enabled at the moment). I'm not sure that this behavior is normal, though.

However I experience another related problem now. I'm sending an OPTIONS request to "/products" with an `Access-Control-Request-Method: PUT` header and OptionsAction() sets the Allow header to this: `Allow: GET, POST, HEAD, OPTIONS`.
So the `PUT` method should not be allowed but still the response will be 200 OK and then the real `PUT` request will be sent (which shouldn't be the case, because it's not an allowed method).

**Comment by pappfer** [comment]
Also, when I declare a new method and add it to the URL rule, it won't respond to an OPTIONS request.
For example I have this URL rule:
```php
[
    'class' => 'yii\rest\UrlRule',
    'controller' => [
        'user'
    ],
    'except' => ['delete'],
    'extraPatterns' => [
    'POST confirm' => 'confirm',
    'POST forgotten-password' => 'forgotten-password',
    'POST change-password' => 'change-password',
    'DELETE deleteall' => 'deleteall',
]
```
When the browser sends the preflight OPTIONS request (for example to /users/confirm) it will get a 404 error, so the real request won't be sent at all.

**Comment by fernandezekiel** [comment]
> why is the real PUT request sent when it's not even an allowed method?

it should be your client app's responsibility to determine if it should still send the `PUT` request despite of the results of the `preflight`
also ... do you also not see the `Access-Control-Allow-Methods`  in the OPTIONS response?

**Comment by fernandezekiel** [comment]
>When the browser sends the preflight OPTIONS request (for example to /users/confirm) it will get a 404 error, so the real request won't be sent at all.

 is this all of your rule for `user` ? there is no pattern it seems to handle the `OPTIONS` request

**Comment by pappfer** [comment]
I thought that OptionsAction() handles it automatically. So do you mean I should have it something like this?
```php
[
    'class' => 'yii\rest\UrlRule',
    'controller' => [
        'user'
    ],
    'except' => ['delete'],
    'extraPatterns' => [
    'POST confirm' => 'confirm',
    'OPTIONS confirm' => 'options',
    'POST forgotten-password' => 'forgotten-password',
    'OPTIONS forgotten-password' => 'options',
    'POST change-password' => 'change-password',
    'OPTIONS change-password' => 'options',
    'DELETE deleteall' => 'deleteall',
    'OPTIONS deleteall' => 'options',
]`
```

**Comment by mohamed-nazim** [comment]
**Allow vs Access-Control-Allow-Methods**
I am working on angular-ionic mobile app and wired up my first REST Api with Yii2.

While trying to use a PUT request, chrome sends pre-flight OPTIONS to check if permitted methods include PUT. By default Yii2 reponds with an `Allow` header instead of the expected (by Chrome) `Access-Control-Allow-Methods`. The response contains the `Allow` header but Chrome reports `Method PUT is not allowed by Access-Control-Allow-Methods`.

Upon digging further, I found that yii\rest\OptionsAction is responsible in preparing the allowed header. I fiddled with the CORS settings for more than an hour in trying to get the expected header but without success.

I ended up creating my own class extending `yii\rest\OptionsAction` simply replacing the `Allow` in the last line:

```php
    namespace app\components;
    
    use Yii;
    
    class OptionsAction extends \yii\rest\OptionsAction {
      public function run($id = null) {
        if (Yii::$app->getRequest()->getMethod() !== 'OPTIONS') {
          Yii::$app->getResponse()->setStatusCode(405);
        }
        $options = $id === null ? $this->collectionOptions : $this->resourceOptions;
        Yii::$app->getResponse()->getHeaders()->set
        ('Access-Control-Allow-Methods', implode(', ',
          $options));
      }
    
    }
```

then I overrode the actions in my controller:

```php
    public function actions() {
      $actions = parent::actions();
      $actions['options'] = [
        'class' => 'app\components\OptionsAction',
      ];
      return $actions;
    }
```

**I wonder if anyone else has come across this one or a better solution**

**Comment by mohamed-nazim** [comment]
In fact: [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Access-Control-Allow-Methods) expects `Access-Control-Allow-Methods` NOT `Allow`

**Comment by adantart** [comment]
@mohamed-nazim  , I had the same problem. I'm making a call with $.ajax command adding the Header of Authorization Bearer and my access token. My method is POST in this case.

As I can read here:
http://stackoverflow...ax-cors-request

when you do that, browser makes an extra call to the same URL with OPTIONS method as described here.

I saw your approach but ... is there something needed in the urlManager rules ?
(like maybe here: https://github.com/yiisoft/yii2/issues/7966#issuecomment-111701983)

Because, I think I'm not reaching the controller because the rules.

Thank you !

**Comment by mohitkadelongraph** [comment]
This might help. Add this code in web/index.php

    // Allow from any origin
    if (isset($_SERVER['HTTP_ORIGIN'])) {
        header("Access-Control-Allow-Origin: {$_SERVER['HTTP_ORIGIN']}");
        header('Access-Control-Allow-Credentials: true');
        //header('Access-Control-Max-Age: 86400');    // cache for 1 day
    }

    // Access-Control headers are received during OPTIONS requests
    if ($_SERVER['REQUEST_METHOD'] == 'OPTIONS') {
        if (isset($_SERVER['HTTP_ACCESS_CONTROL_REQUEST_METHOD']))
            header("Access-Control-Allow-Methods: GET, POST, OPTIONS, PATCH, PUT, DELETE");         
        if (isset($_SERVER['HTTP_ACCESS_CONTROL_REQUEST_HEADERS']))
            header("Access-Control-Allow-Headers: {$_SERVER['HTTP_ACCESS_CONTROL_REQUEST_HEADERS']}");
        exit(0);
    }

**Comment by mohitkadel** [comment]
The problem was with CORS. Earlier,browsers did not allow ajax requests to be made to a domain which is different than that of a client as it was considered as a security threat. Modern browser's can make cross domain ajax request's as long as the server co-operates with the client.So this is what actually happens when there is a cross domain request from a browser:

* First the browser sends 'Preflight' request to the service to gather authorization information(which was a request with the header method as 'OPTIONS' in my case) from the WCF service. In return the Web Service sends Access Control Allow Origin as a part of its response header.
* Chrome and Safari then made a second request to the Web Service now that they have the authorization details of the service.Whereas Firefox and IE did not prefer to make a second ajax request to the service

So the solution was to modify the response from the WCF service in case there is a 'Preflight request' made to it.I modified the response sent by the service in case there is a 'Preflight request' to send an HTTP 200 OK Response. This allowed browsers like IE and Mozilla to send the actual request after the preflight request.

Add this code in web/index.php

    // Allow from any origin
    if (isset($_SERVER['HTTP_ORIGIN'])) {
        header("Access-Control-Allow-Origin: {$_SERVER['HTTP_ORIGIN']}");
        header('Access-Control-Allow-Credentials: true');
        header('Access-Control-Max-Age: 86400');    // cache for 1 day
    }

    // Access-Control headers are received during OPTIONS requests
    if ($_SERVER['REQUEST_METHOD'] == 'OPTIONS') {
        if (isset($_SERVER['HTTP_ACCESS_CONTROL_REQUEST_METHOD']))
            header("Access-Control-Allow-Methods: GET, POST, OPTIONS, PATCH, PUT, DELETE");         
        if (isset($_SERVER['HTTP_ACCESS_CONTROL_REQUEST_HEADERS']))
            header("Access-Control-Allow-Headers: {$_SERVER['HTTP_ACCESS_CONTROL_REQUEST_HEADERS']}");
        exit(0);
    }

[Server Side Access Controll](https://developer.mozilla.org/en-US/docs/Web/HTTP/Server-Side_Access_Control)

**Comment by tunecino** [comment]
CORS issues here could be related to https://github.com/yiisoft/yii2/issues/6254

**Comment by cebe** [comment]
I do not see an issue in yii code here, everything discussed here seems to be for clarifying how yii should be configured to work as expected. closing this.
