### ISSUE TITLE
Mailer / swiftmailer / Autoload seems to be broken

### ISSUE THREAD

**Issue by joshualivesay** [yiisoft/yii2#8021]
Please refer to the following:

http://stackoverflow.com/questions/29520373/swift-message-not-found-error-after-swiftmailer-installed-in-yii2

1. in /var/www/website/vendor/yiisoft/yii2-swiftmailer/Message.php at line 317
308309310311312313314315316317318319        return $this->getSwiftMessage()->toString();
    }
 
    /**
     * Creates the Swift email message instance.
     * @return \Swift_Message email message instance.
     */
    protected function createSwiftMessage()
    {
        return new \Swift_Message();
    }
}

**Comment by klimov-paul** [comment]
Looks like the composer installation problem.

Does 'swiftmailer/swiftmailer' installed correctly? Can you locate it inside'vendor' dir?
Check file 'vendor/composer/autoload_files.php', does it contains following string:
```
$vendorDir . '/swiftmailer/swiftmailer/lib/swift_required.php',
```

Make sure you have installed 'composer-asset-plugin' before running 'composer install' otherwise it will produce incorrect results.

**Comment by Fh-jlivesay** [comment]
composer install
Completed without error.

     vendor/swiftmailer/swiftmailer  - path has files and looks correct.
     vendor/yiisoft/yii2-swiftmailer - path has files and looks correct.

File vendor/composer/autoload_files.php DOES contain the line:

     $vendorDir . '/swiftmailer/swiftmailer/lib/swift_required.php',

I ran the following command to ensure that composer-asset-plugin was installed:

     composer global require "fxp/composer-asset-plugin:1.0.0"

I then deleted the folders for vendor/swiftmailer and yiisoft/yii2-swiftmailer and removed the line from vendor/composer/autoload_files.php that I verified above.

 After verifying that all of the above is still inline I tested and again receive the following error.

     PHP FATAL ERROR
     Class 'Swift_Message' not found

 I'm going to move some of the information from my stackoverflow question to this thread for proper troubleshooting.  I may have the subject wrong IF this is in fact not related to the autoloader.  My guess is that it is related to "lazy loading" because of very similar issues on the symphony framework that I have verified exist when using swiftmailer.

 Here is the procedure I followed:

In composer.json 

     "yiisoft/yii2-swiftmailer": "*"

Followed by:

     composer install

In my config I have:  (Yes, I just want it to save a file for now.)

    'components' => [
        'mailer' => [
            'class' => 'yii\swiftmailer\Mailer',
            'useFileTransport' => true,
        ],

Then I placed this into a controller:

     \Yii::$app->mailer->compose()
       ->setFrom('from@domain.com')
       ->setTo('to@domain.com')
       ->setSubject('Message subject')
       ->setTextBody('Plain text content')
       ->setHtmlBody('<b>HTML content</b>')
       ->send();

My error is:

> PHP FATAL - Class 'Swift_Message' not found

**Comment by klimov-paul** [comment]
Does you entry script contains 'vendor/autoload.php' require? Does it pointing to the correct file?
Try to manually put `die('swiftmailer')` at 'vendor/swiftmailer/swiftmailer/lib/swift_required.php' - it should appear at any application run.

**Comment by Fh-jlivesay** [comment]
`die('swiftmailer');` had no effect.

`vendor/autoload.php` is not required. 

I'm sorry and thank you.  Such a simple problem.  I assumed that because other extensions were installed in a similar fashion that this autoload was already in the execution path.  

I'm guessing now that previous developers are not even using those other installed extensions.  

Thank you

**Comment by garima-goyal** [comment]
@klimov-paul  
I am also getting the same error.
I checked my entry script
vendor/autoload.php is required. 

on any application run getting : swiftmailer

but yet My error is:

    PHP FATAL - Class 'Swift_Message' not found


Plz help
Thanks in advance

**Comment by Aabir1** [comment]
Put this => "yiisoft/yii2-swiftmailer": "*", in the composer.json file and run php composer.phar update

**Comment by garima-goyal** [comment]
running on shared hosting so cant update composer.phar

 vendor/swiftmailer/swiftmailer  - path has files and looks correct.
 vendor/yiisoft/yii2-swiftmailer - path has files and looks correct.

all classes exist in the correct way..

yet getting the error.

**Comment by Aabir1** [comment]
@garima-goyal its Ok that all classes exist in the correct way but i think Yii uses some thing like cache which can easily maintained by composer.phar

**Comment by garima-goyal** [comment]
Is there another alternative way to make it workable ?
without having to go through composer update

**Comment by Aabir1** [comment]
hope this will help you 
http://www.yiiframework.com/forum/index.php/topic/53891-yii-2-extensions-without-composer/
