### ISSUE TITLE
Multiple file validation is not working. what am i wrong?

### ISSUE THREAD

**Issue by serhatozles** [yiisoft/yii2#8042]
![1](https://cloud.githubusercontent.com/assets/4962332/7102425/89105aca-e089-11e4-8495-d7ed568992e3.PNG)
![2](https://cloud.githubusercontent.com/assets/4962332/7102426/896367c4-e089-11e4-876d-628a710c4506.PNG)
![3](https://cloud.githubusercontent.com/assets/4962332/7102427/8969a8b4-e089-11e4-9dd4-47b8a56ed6f2.PNG)
everything looks ok, but i can't understand. Maybe, there could any problem in Yii2 file validation. it's working when i'm removing file rule in model. Can you help me?

**Comment by M0on75e1l** [comment]
I think the problem is that neither the first nor the second version of Yii contains validation classes to deal with arrays. That was the reason why I've used that [powerfull Symfony2 component](https://github.com/symfony/Validator) in one of my projects for complex validation. See the answer [here](http://stackoverflow.com/questions/27252934/yii2-validation-rule-for-array).

**Comment by cebe** [comment]
@serhatozles please provide the full stack trace of the error so we can easier find the cause.

**Comment by serhatozles** [comment]
@cebe i found where is wrong. the wrong is here: $model->load(Yii::$app->request->post());
load function is not loading files request. 'couse it is not coming with $_POST is coming with $_FILES. so load function couldn't find a file. There is not a problem if we are using like this;
	    $model->load(Yii::$app->request->post());
	    $model->images = UploadedFile::getInstances($model, 'images');
but if it is like this, there is something wrong;
	    $model->images = UploadedFile::getInstances($model, 'images');
	    $model->load(Yii::$app->request->post());
So the wrong is me :d
