### ISSUE TITLE
[Enh] implement functionality to work with database view

### ISSUE THREAD

**Issue by unclead** [yiisoft/yii2#8347]
Based on issue #8152
Separate issue for implementation functionality to work with database `VIEW`.

Reference about _CREATRE VIEW_ functionality
**MySQL**
https://dev.mysql.com/doc/refman/5.0/en/create-view.html

**Cubrid**
http://www.cubrid.org/manual/93/en/sql/schema/view.html

**PostgreSQL**
http://www.postgresql.org/docs/9.3/static/sql-createview.html http://www.postgresql.org/docs/9.3/static/sql-creatematerializedview.html

**Oracle**
https://docs.oracle.com/javadb/10.8.3.0/ref/rrefsqlj15446.html
http://docs.oracle.com/cd/B28359_01/server.111/b28286/statements_6002.htm#SQLRF01302
http://docs.oracle.com/cd/B28359_01/server.111/b28286/statements_8004.htm#SQLRF01504

Probably we have to implement not only method createView but also
- dropView
- alterView
- renameView

**Comment by samdark** [comment]
Yep. Good idea.

**Comment by igravity** [comment]
Are there any updates on this?

**Comment by samdark** [comment]
No. If you want to work on it, feel free to do so.

**Comment by Faryshta** [comment]
what about a functionality for triggers?

**Comment by Faryshta** [comment]
and views work based on select queries. The main issues is that not all db have the same select queries so we can't make it simple like

`$this->createView('newView',  'Select * from table')` since it might not work the same on all supported db's.

Maybe it would be good to allow the second parameter to be an instance of `yii\db\Query` or `yii\db\ActiveQuery` at that point you might already have created the models (such as you are executing the migrations after installing a repo from composer) or a command `new Query` will work on the existint tables.

Plus it would solve the issue with handling prefixes.

**Comment by cebe** [comment]
both, string and Query object could be supported.

**Comment by cebe** [comment]
DB prefixes are supported by command and connection, you do not need Query for that.

**Comment by samdark** [comment]
Basic create/drop added.

**Comment by samdark** [comment]
The rest won't be implemented in 2.0.
