### ISSUE TITLE
ActiveRecord refresh() is failed when using transactions and default attrib is by Expression

### ISSUE THREAD

**Issue by mootensai** [yiisoft/yii2#8390]
I try to implement UUID on insert, so i use 

```php
class MyModel extends ActiveRecord{
    public function rules(){
        return ['id', 'default', 'value' => new Expression("REPLACE(UUID(),'-','')")]
    }
}
```

but when i do this

```php
$db = $model->getDb();
$db->transaction(function ($db){
    $trans = $db->beginTransaction();
    if($model->save()){
        var_dump($model->refresh()); // output : bool(false)
        print_r($model_attributes);
//    output :
//    [id] => yii\db\Expression Object
//        (
//            [expression] => REPLACE(UUID(),'-','')
//            [params] => Array
//                (
//                )
//        )
        $child->parent_key = $model->id // i can't use this
    }
}
```

NB : 
even if i use 
```php
$db->transaction(function($db){
    //my command
});
```
it's not working.

i still have to use 
```php
$db->transaction(function($db){
    $trans = $db->beginTransaction();
    //my command
    ($model->save()) ? $trans->commit() : $trans->rollback();
});
```

It's not the same as the documentation here : 
http://www.yiiframework.com/doc-2.0/guide-db-dao.html#performing-transactions

**Comment by cebe** [comment]
1. validation rules are to be used to validate user input. With the above code, the user could send arbitrary input as the ID...
2. refresh works by using the primary key. If you generate the primary key in the DB, active record does not know how to load the data because it does not know the key.

Is it possible to get the value from last_insert_id?

**Comment by nineinchnick** [comment]
@mootensai what database do you use? It should work for PostgreSQL and Oracle. It won't work for any other database, this is just not possible as the database evaluates the expression on INSERT but there's no way to return the value of the PK. You'd have to run that expression yourself and use a value in your filter.

**Comment by mootensai** [comment]
@cebe 
1. I don't create input field for ID
2. I try your work around and the result is zero. Here's what i try
```php
$model->save();
print_r(mysql_insert_id());//output : 0
print_r($model->getDb()->lastInsertID); //output : 0
```
@nineinchnick I use MySQL. but when i try $model->save(), it insert to my table with generated UUID. 
If I change the rules to this 
```php
class MyModel extends ActiveRecord{
    public function rules(){
        return ['id', 'default', 'value' => $this->generateUUID()] // PHP generated UUID
    }
}
```
$model->refresh() is working.
print_r($model->id) is outputting generated UUID. 

Can't I use the DB generated UUID?

**Comment by nineinchnick** [comment]
@mootensai that's the way MySQL works. If you issue an `INSERT INTO (pk_col) VALUES (expression)` statement, the expression gets evaluated but you won't be able to retrieve the value. Since it's your primary key, you can't identify the new row created in the database. You have to know it before executing that statement. That's why you have to calculate it in PHP. It's the only way to associate your model with the new db record.

MySQL only allows you to associate last inserted record if using an autoincrementing column and the lastInsertId value, assuming you insert just one row.

Other databases, like PostgreSQL and Oracle, can return values from the insert statement, even if they're expressions. This is supported by Yii since the latest version, 2.0.4.

I think this issue should be closed.

**Comment by nineinchnick** [comment]
@mootensai a workaround is to generate the UUID like this:

~~~php
class MyModel extends ActiveRecord{
    public function rules(){
        return ['id', 'default', 'value' => $this->getDb()->createCommand("REPLACE(UUID(),'-','')")->queryScalar()];
    }
}
~~~

**Comment by mootensai** [comment]
@nineinchnick : your code works!! Thanks a lot!

**Comment by cebe** [comment]
still it does not belong into `rules()` because someone can send a different ID in the POST request.

**Comment by mootensai** [comment]
@cebe Ok, Thanks!
