### ISSUE TITLE
send file and set speed

### ISSUE THREAD

**Issue by EngRajabi** [yiisoft/yii2#8439]
send file
\Yii::$app->response->sendFile('path/to/file.txt')->send();
bute send file with speed 
\Yii::$app->response->sendFile('path/to/file.txt',900)->send();
add property set speed

**Comment by EngRajabi** [comment]
in many projects , there are some send file that are needed to set speed send file

**Comment by lynicidn** [comment]
http://www.nginxtips.com/how-to-limit-nginx-download-speed/

**Comment by EngRajabi** [comment]
bute im used to \Yii::$app->response->sendFile()->send();
not used popular nginx

**Comment by cebe** [comment]
can't the nginx limit be combined with sendFile() ?
Not sure if/how Yii could control download speed...

**Comment by alexandernst** [comment]
Maybe http://stackoverflow.com/questions/4002106/limit-download-speed-using-php ?
Doesn't sound as a bad idea if you can control the timeout of each PHP process. And if not, Yii could ignore the speed limit (or throw a warning/error)

**Comment by usualdesigner** [comment]
It should be implemented on the web-server's side IMO.

**Comment by alexandernst** [comment]
@usualdesigner Yii is on the server side. Anyways, I get what you mean: the web server should take care about that. There is a problem with that: you can't programaticaly control how the webserver sends the file.

**Comment by lynicidn** [comment]
>      sleep(1);  
it's not true for highload

**Comment by samdark** [comment]
@lynicidn ???

**Comment by lynicidn** [comment]
@samdark script work up time

**Comment by lynicidn** [comment]
set_time_limit(0) - not true :)

**Comment by samdark** [comment]
Can't get what you're trying to say. Sorry.

**Comment by lynicidn** [comment]
@samdark

**Comment by samdark** [comment]
А, ну это понятно.

**Comment by SamMousa** [comment]
I don't think this should be in the core.

Extensions could be created that support a specific sending backend (nginx, apache, PHP) and implement the limit there.

Note that implementing this in PHP could be a bad idea because the webserver tends to buffer the response which could cause weird results like getting lower throughput.
For example if the webserver buffers 10 seconds of ratelimited output and then sends that to the client at once, who cannot handle that data fast enough, then the effective download speed will be much lower than intended.

**Comment by samdark** [comment]
Agree.
