### ISSUE TITLE
make model::getFirstError($attribute = null)

### ISSUE THREAD

**Issue by callmez** [yiisoft/yii2#8449]
```php
public function getFirstError($attribute = null)
{
    if ($attribute === null) {
        $errors = reset($this->errors);
        return !empty($errors) ? reset($errors) : null;
    }
    return isset($this->_errors[$attribute]) ? reset($this->_errors[$attribute]) : null;
}
```
i just want to get first error (without the $attibute), is this can be accept? thanks

**Comment by lynicidn** [comment]
```php
if ($model->hasError($attribute)) {
    $model->getFirstErrors()[$attribute];
}
```

**Comment by mdmunir** [comment]
:+1:

**Comment by cebe** [comment]
I don't get the request here, we already have getFirstErrors() to get all of them and getFirstError() to get one.
What is the use case for getting a random error message?

**Comment by callmez** [comment]
```
<?php
public function actionIndex()
{ 
    $model = new User();
    if ($model->load(Yii::$app->request->post())) {
        if (!$model->validate()) {
            if (isset($_POST['ajax'])) {
				Yii::$app->getResponse()->format = Response::FORMAT_JSON;
	            // We also can use ActiveForm::validate($model); return all errors to yii.validation.js, right?
	            // But ActiveForm is not the only way in web design. 
	            // Sometimes we just want return first error(first error of first attribute)
	            return [
	                // if we use $this->getFirstError() return first error, it will be more flexible and won't broke the function.
	                'message' => $model->firstError, // instead of array_values($model->firstErrors)[0]
	                'type' => 'error'
	            ]; 
            }
        }
    }
}
```

**Comment by lynicidn** [comment]
@cebe `and getFirstError() to get one.` - it's missing ?

**Comment by lynicidn** [comment]
@callmez may be help - reset($model->firstErrors)

**Comment by callmez** [comment]
no, `reset($model->firstErrors)` will return the first attribute errors

**Comment by klimov-paul** [comment]
Calling of `getFirstError()` without attribute specification make absolutely no sense.
Even if implemented it will produce inconsistent result, because `Model` does NOT remember the order of the appeared errors. So such `getFirstError()` will return first error for some random attribute, but NOT the first occured error.

**Comment by joeyblack835** [comment]
@klimov-paul @cebe I see that the order of getErrors()/getFirstErrors() elements isn't random. It depends on the order of the rules. Or am I mistaken? Can't  we consider the first element of getErrors()/getFirstErrors() array to be the first met error?
I agree with the OP. Sometimes (due to the application design limitation) we cannot show all the errors to the user.

**Comment by cebe** [comment]
still unclear to me, what is requested. Please give a detailed example.

**Comment by joeyblack835** [comment]
@cebe No, I just commented the issue for I faced the same problem. Also I disagreed with your explanation about "random" error.

The details are the following:
Suppose I have some application which gets the user data, process it and sends the response back to the user, and due to the design limitation (API, mobile app etc.) we cannot (or we don't want to) show all the errors to the user. So, we want to show only one error.

**Comment by omzy83** [comment]
I agree. Sometimes you just need to get the very first validation error. This should be possible without having to specify the attribute.

In Laravel, you can do this:

```
if ($validator->fails()) {
   $error = $validator->errors()->first();
}
```

Can we get something similar for Yii 2?

**Comment by githubjeka** [comment]
I'm tired of doing this

```php
if (!$this->validate()) {
     throw new \Exception(Json::encode($this->getErrors()));
}
```
