### ISSUE TITLE
yii.activeForm.js. Add 'updateInput' to 'methods'.

### ISSUE THREAD

**Issue by bupy7** [yiisoft/yii2#8481]
Function of ```updateInput``` very need! 
**Example:** Now I was make auto-save form after successfully validation via Ajax. And we can change one field at a time and get errors by this field. I would like to have a possibility set errors manually after validation. This can handle ```updateInput``` in ```yii.activeForm.js```, but  this method is private. 

Please, add to public methods. =)

**Comment by andrewblake1** [comment]
Periodically I scan to see if any progress on this. In case it isn't realized this is the same issue as https://github.com/yiisoft/yii2/issues/5420
https://github.com/yiisoft/yii2/pull/7260
https://github.com/yiisoft/yii2/issues/5991
https://github.com/yiisoft/yii2/issues/3017

Currently I used a hacked yii.activeForm.js with 
```
    var methods = {
        updateInputs: function (messages) {
            updateInputs($(this), messages, true);
        },
        init: function (attributes, options) { ...
```

In order to access updateInputs. Am not good at explaining my use cases and tend to over-complicate but figured others would find the same issue and raise it - which is happening. No major - other than using  a hacked framework file. Am sure it is in the pipeline to be resolved but thought I would aggregate the issues together here.
