### ISSUE TITLE
How to make mock of static method in utin tests

### ISSUE THREAD

**Issue by xVismutx** [yiisoft/yii2#8519]
I can't make mock of static methods...
For exaple my code
```php
    protected function _generateFolders()
    {
        $folders = str_split($this->hash, self::FOLDER_TITLE_LENGTH);
        $folders = array_slice($folders, 0, $this->foldersDepth);
        $folders = implode('/', $folders) .
            ($this->accessDir ? '/' . $this->accessDir : '');

        $path = self::getPathToFiles() . '/' . $folders;
        FileHelper::createDirectory($path);

        return $folders;
    }
```
how i can mock FileHelper::createDirectory($path); in my tests ?

I use codeception

**Comment by tomtomsen** [comment]
codeception uses phpunit.

in general static methods are unit-testing-killers (http://misko.hevery.com/2008/12/15/static-methods-are-death-to-testability/). here filehelper::createDirectory is just a wrapper for mkdir. so you are not losing anything.

hopefully this helps you: https://phpunit.de/manual/4.6/en/test-doubles.html#test-doubles.mocking-the-filesystem

otherwise maybe the yii2 forum is a better place to ask such a question: http://www.yiiframework.com/forum/index.php/forum/42-general-discussions-for-yii-20/
