### ISSUE TITLE
data-confirm and data-method with pjax

### ISSUE THREAD

**Issue by xskif** [yiisoft/yii2#8582]
Is there any way to do this?
In rails `remote` option work together with `method` and `confirm` options, in yii they not.
Maybe if we change `handleAction` behavior when `confirm` specified but `method`not:
```js
//--------------------------- handleAction --------------------------
            if (method === undefined) {
                if (action && action != '#') {
                    // window.location = action; // <- delete this
                    return false; // <- this one

//--------------------------- initDataMethods -----------------------

            if (message !== undefined) {
                pub.confirm(message, function () {
                    pub.handleAction($this);
                });
            } else {
                pub.handleAction($this);
            }

            if (method !== undefined) {
                event.stopImmediatePropagation();
                return false;
            }
            return true;
```

And when `method` specified we can add data-pjax attribute like that:
```js
if (data.pjax !== undefined) {
    $form.attr('data-pjax', data.pjax);
}
```

**Comment by armpogart** [comment]
I have the same issue. We have anchor with `data-confirm` attribute to show prompt, and `data-confirm` breaks pjax request.

**Comment by xskif** [comment]
@armpogart , I was found temporary solution:
You can wrap links with `data-method` by `form` with `data-pjax`. `data-confirm` also works fine if you have `data-method` on the link

**Comment by nkovacs** [comment]
Aside from the form missing the data-pjax attribute (so the default pjax form selector doesn't pick it up), the other problem is that it's appended to body.
The default form selector in the Pjax widget is `'#' . $id . ' form[data-pjax]'`, so it won't find the form, since it's outside the widget's container.

**Comment by nkovacs** [comment]
I have not tested this thoroughly: https://github.com/nkovacs/yii2/commit/c636e506bae6198727fb3359a2d13a8c08d2d63c
You have to add data-form-pjax to the link, so it's opt-in. Since `data-pjax="0"` is used to disable pjax on links, I didn't want to overload it with this, though there wouldn't really be a conflict (`data-pjax` would mean enable pjax on the generated form, `data-pjax="0"` would mean disable pjax).
It also inserts the invisible form after the element instead of append it to the body. I don't know what the side-effects of this change are.

**Comment by xskif** [comment]
@nkovacs , i think this:
```php
if (data.pjax !== undefined) {
    $form.attr('data-pjax', data.pjax); // there are dynamic value
}
```

better than this:

```php
if ($e.data('form-pjax') !== undefined) {
    $form.attr('data-pjax', true); // there are the hardcoded value
}
```

**Comment by nkovacs** [comment]
what's data.pjax? Do you mean $e.data('pjax')?

This won't work:
`$form.attr('data-pjax', data.pjax);`

Event if data.pjax is 0, pjax will still pick up the form, because the selector is `form[data-pjax]`, so `<form data-pjax="0">` is actually the same as `<form data-pjax="1">` and `<form data-pjax>`, they'll all be selected.

**Comment by xskif** [comment]
@nkovacs 
```js
var data = $e.data();
console.log(data.pjax) // logs data-pjax attr value
```
the selector is `form[data=pjax]` thats correct, but in the source of pjax jq plugin we have code like this:
```js
if (data.pjax === 0) {
    return false;
}
```

**Comment by nkovacs** [comment]
> `var data = $e.data();`

There is no such line in https://github.com/yiisoft/yii2/blob/master/framework/assets/yii.js.

> the selector is form[data=pjax] thats correct, but in the source of pjax jq plugin we have code like this:
> ```js
> if (data.pjax === 0) {
>     return false;
> }
> ```

Only in handleClick, not in handleSubmit. By default all links are selected, but data-pjax="0" disables pjax on specific links. On the other hand, forms are opt-in, so there is no such code in handleSubmit.

**Comment by xskif** [comment]
> There is no such line in https://github.com/yiisoft/yii2/blob/master/framework/assets/yii.js.

this can be easily added.

> Only in handleClick, not in handleSubmit.

Ok, my mistake.

**Comment by Bhoft** [comment]
> I was found temporary solution:
You can wrap links with data-method by form with data-pjax. data-confirm also works fine if you have data-method on the link and form[data-pjax] as wrapper

@xskif can you give an example code or do you have some link to some tutorial because i have also this issue and i am not sure how to fix this at the moment.

**Comment by xskif** [comment]
@Bhoft sure:

```php
ActiveForm::begin(['options'=>['data-pjax'=>true]]);

// Here the link or the GridView with delete or another link which contains data-method and (optional) data-confirm attributes.
// E.g.
echo Html::a('Link', ['post/delete'], ['data-method'=>'post']);

ActiveForm::end();
```

**Comment by nirvana-msu** [comment]
+1 would be really nice if `pjax` worked with `data-method` and `data-confirm`.

The workaround suggested by @xskif (wrapping link in a dummy form) works great for simple cases, but still does not help me when I have links inside actual form which I do not want to validate/submit (but still want to use pjax + post/confirm for these links). Wrapping into another (nested) form does not seem to work.

A simple example illustrating my issue is a `cancel` action when a user edits his comment. This action is a link inside a form, next to the actual button that submits the form. Moving the link outside the form would ruin the markup. When a user clicks `cancel`, we don't want to validate or submit the form, instead we simply want to ask for confirmation and reload old comment with pjax.

**Comment by derekisbusy** [comment]
Try to apply my patch and see if it works.

**Comment by xskif** [comment]
@nirvana-msu , HTML does not support nested forms =) You can try to create your own js/ajax component for the same links. For example: i created for myself the reroute plugin which change action attribute on the parent form of the link after click on they.

You can create something similar.
