### ISSUE TITLE
Create an attribute by adding rules in DynamicModel

### ISSUE THREAD

**Issue by zhdanovartur** [yiisoft/yii2#8588]
Now when I use dynamic validation like this:

```php
$model = new DynamicModel();
$model->load($params);
switch ($way) {
    case 'first':
        $model->addRule('time', 'required');
        $model->addRule('time', 'integer', ['min' => 1, 'max' => 1800]);
        break;
//    ...
    case 'last':
        $model->addRule(['speed'], 'required');
        $model->addRule('speed', 'integer', ['min' => 0, 'max' => 320]);
        break;
}
$model->validate();
```
the error occurs:
`Getting unknown property: yii\base\DynamicModel::time`.

I understand that following code will be work:
```php
switch ($way) {
    case 'first':
        $model = new DynamicModel(array_replace(['time', 'factor'], $params));
        $model->addRule('time', 'required');
        $model->addRule('time', 'integer', ['min' => 1, 'max' => 1800]);
        break;
//    ...
    case 'last':
        $model = new DynamicModel(array_replace(['speed'], $params));
        $model->addRule('speed', 'required');
        $model->addRule('speed', 'integer', ['min' => 0, 'max' => 320]);
        break;
}
$model->validate();
```
but why preset an attributes before?
Maybe сreate an attribute by `addRule` if it not set early?
It's really a dynamic approach.

**Comment by klimov-paul** [comment]
> Now when I use dynamic validation like this....

Method `Model::load()` can set only safe model attributes, which are none, unless you specify any attribute explicitly or declare a validation rule.

> I understand that following code will be work...

If you don't have 'time' or 'speed' attribute inside the data to be validated, why do you add a rules for them?

This issue seems like abuse of the `DynamicModel`, which was created to facilitate direct vaidation of the  abstract value. It should not serve for handling incoming user requests of unknown strucutre.
