### ISSUE TITLE
Apps and extensions that use Json::encode are still vulnerable to CVE-2015-3397

### ISSUE THREAD

**Issue by nkovacs** [yiisoft/yii2#8622]
So CVE-2015-3397 was [fixed](https://github.com/yiisoft/yii2/commit/78d3a856d3b2691a6071d23acd0f75cafe3808e0) in Yii 2, but what about extensions and applications that use `Json::encode` to pass options to a javascript snippet? They'll all have to be updated to use `Json::htmlEncode` too. Just upgrading to Yii 2.0.4 won't fix your code.
The changelog doesn't contain a lot of information about this, and I couldn't find any info on CVE-2015-3397, why it happens in IE and doesn't happen in other browsers. The [news item on the website](http://www.yiiframework.com/news/86/yii-2-0-4-is-released/) implies that just upgrading to Yii 2.0.4 is enough to fix the vulnerability in your app, but this is not true if you used `Json::encode` or an extension that uses `Json::encode`.

**Comment by cebe** [comment]
The official extensions have been adjusted, so if you upgrade all to 2.0.4 you are not vulnerable to the issue. For the application code and other extensions you should use `Json::encodeHtml()` instead of `Json::encode()` if you use the result in Javascript code that is embedded in a HTML page.

I will update the news item.

**Comment by nkovacs** [comment]
Yeah, I meant third-party extensions. Thanks.

**Comment by cebe** [comment]
done. http://www.yiiframework.com/news/86/yii-2-0-4-is-released/
