### ISSUE TITLE
DAO layer is broken

### ISSUE THREAD

**Issue by creocoder** [yiisoft/yii2#8627]
```php
$db = Yii::$app->db;
$db->createCommand()->createTable('foo', ['id' => Schema::TYPE_PK, 'bar' => Schema::TYPE_INTEGER])->execute();
$db->createCommand()->insert('foo', ['bar' => 1])->execute();
$db->createCommand()->alterColumn('foo', 'bar', Schema::TYPE_STRING)->execute();
$db->createCommand()->insert('foo', ['bar' => 'hello'])->execute();
```

Result:

```
id | bar
 1 | 1
 2 | 0
```

Should be:

```
id | bar
 1 | 1
 2 | hello
```

Same thing using pure PDO show that everything is fine. So this is fw DAO layer bug.

**Comment by creocoder** [comment]
Tested on 2.0.4 release version.

**Comment by cebe** [comment]
how to you get the result? It is not part of the commands above...

**Comment by creocoder** [comment]
@cebe Before report i made investigations around 6 hours. This trouble happens on production server when apply migrations. This bug was reproduced on 3 different machines with different OS, php versions and mysql server version. Also its cleanly Yii 2 DAO layer bug. Because when using pure PDO everything is fine.

> how to you get the result?

Just run code on your machine.

**Comment by cebe** [comment]
have you tried turning off the schema cache?

**Comment by creocoder** [comment]
@cebe Ofcourse ;-)

**Comment by cebe** [comment]
okay :)

**Comment by creocoder** [comment]
@cebe I assume this trouble caused by wrong PDO usage and prepared statement. Most interesting thing is if you kill first insert everything will be fine with second insert. So bug is very funny. On other side its extremally dangerous especially for production environment. For example consider you have 4 migrations: 1) create table, 2) insert into that table, 3) alter table, 4) insert into that table. On dev environment you'll run migrations step by step and you'll get one result. When you run `yii migrate` on production and all migrations in one step you'll be very surprised.

**Comment by creocoder** [comment]
@cebe Look PDO example:

```php
$db = Yii::$app->db;
$db->createCommand()->createTable('foo', ['id' => Schema::TYPE_PK, 'bar' => Schema::TYPE_INTEGER])->execute();

$sth = $this->db->pdo->prepare('INSERT INTO foo (bar) VALUES (:bar);');
$sth->bindValue(':bar', 1, PDO::PARAM_INT);
$sth->execute();

$db->createCommand()->alterColumn('foo', 'bar', Schema::TYPE_STRING)->execute();

$sth = $this->db->pdo->prepare('INSERT INTO foo (bar) VALUES (:bar);');
$sth->bindValue(':bar', 'hello', PDO::PARAM_STR);
$sth->execute();
```

Work as expected. Result:

```
id | bar
 1 | 1
 2 | hello
```

**Comment by cebe** [comment]
It is the schema cache, add the following after alterColumn and it will work:

```php
$this->db->schema->getTableSchema('testAlterTable', true); // true = refresh
```

**Comment by creocoder** [comment]
@cebe Again, it not schema cache :) I specially double check that it is disabled inside config.

**Comment by creocoder** [comment]
@cebe As i said before. If you kill first insert, second will work as expected. So trouble is VERY COMPLEX. Adding additional commands after of before something affect result.

**Comment by cebe** [comment]
The problem is the dbCast call in insert method of QueryBuilder.

this line:
https://github.com/yiisoft/yii2/blob/master/framework/db/QueryBuilder.php#L151
which calls the typecast function and here you turn your `'hello'` into `0`:
https://github.com/yiisoft/yii2/blob/master/framework/db/ColumnSchema.php#L134

It is not the cache itself but the tableschema is cached per request.

**Comment by cebe** [comment]
make a step debug with xdebug on the second insert call and you will see it cast to int there.

**Comment by cebe** [comment]
> If you kill first insert, second will work as expected.

Yes, because it will not have loaded table schema yet.

**Comment by creocoder** [comment]
@cebe Most important thing is, code:

```
$db = Yii::$app->db;
$db->createCommand()->createTable('foo', ['id' => Schema::TYPE_PK, 'bar' => Schema::TYPE_INTEGER])->execute();
$db->createCommand()->insert('foo', ['bar' => 1])->execute();
$db->createCommand()->alterColumn('foo', 'bar', Schema::TYPE_STRING)->execute();
$db->createCommand()->insert('foo', ['bar' => 'hello'])->execute();
```

**MUST** lead to result:

```
id | bar
 1 | 1
 2 | hello
```

How this will be fixed and where is the trouble is does not matter.

**Comment by samdark** [comment]
We should create a test out of it. The fix, I think is to update schema cache when schema is modified.

**Comment by samdark** [comment]
Scenario is quite common for migrations.

**Comment by cebe** [comment]
I have a test here, the problem is, that we do not really know when schema changes.

**Comment by samdark** [comment]
Well, alter statements such as `createTable` or `alterColumn` are red flags.

**Comment by cebe** [comment]
consider the following code:

```php
$db = Yii::$app->db;
$db->createCommand()->createTable('foo', ['id' => Schema::TYPE_PK, 'bar' => Schema::TYPE_INTEGER])->execute();
$db->createCommand()->insert('foo', ['bar' => 1])->execute();
$db->createCommand('ALTER TABLE foo CHANGE bar bar varchar(255);')->execute();
$db->createCommand()->insert('foo', ['bar' => 'hello'])->execute();
```

We can not know that the table has changed without actually parsing that SQL.

**Comment by cebe** [comment]
> Well, alter statements such as createTable or alterColumn are red flags.

the problem here is that we do not know when such a command was executed.

**Comment by samdark** [comment]
Searhing for `ALTER` in SQL could work...

**Comment by cebe** [comment]
There is the alterColumn method in Command:
https://github.com/yiisoft/yii2/blob/master/framework/db/Command.php#L621
it just sets the SQL to be executed, we can not refresh table schema at this point, we have to wait for execute() to be called...

**Comment by samdark** [comment]
If it's there local cache could be reset.

**Comment by creocoder** [comment]
```
Well, alter statements such as createTable or alterColumn are red flags.
```

Its not reliable. Per request cache should be removed complettely!

**Comment by creocoder** [comment]
@samdark What if schema changes not inside application. Or in the middle of request or...

**Comment by cebe** [comment]
> Per request cache should be removed complettely!

this is only true for migrations, for the normal page you do not want to reload every schema info for each table each time you make a query or access some AR attributes...

**Comment by cebe** [comment]
here is the test case #8628:

it is passing if you uncomment this line:
https://github.com/yiisoft/yii2/pull/8628/files#diff-e48002914d2773120698a96387ecabd2R337

**Comment by creocoder** [comment]
@cebe 

> this is only true for migrations, for the normal page you do not want to reload every schema info for each table each time you make a query or access some AR attributes...

We have `Connection::enableSchemaCache`. This trouble reproducable even if this setting is false. Seems there is another per request cache which enabled always. This cache should be removed completelly. Its disservice from Yii 2.

**Comment by qiangxue** [comment]
I don't think we should remove the internal cache. It is important to keep high performance for common SQL queries.

For this issue, I propose:

- Add documentation to emphasize that whenever you make schema change, you should consider calling `getTableSchema()` (or add `refreshTableSchema()`). This is important anyway, because if you use schema caching, you would have to do the same thing.
- For schema changing methods such as `alterColumn()`, we may consider automatically clearing the corresponding table schema. But I prefer we don't do this because it makes code more complex, and it doesn't cover all situations, just cebe pointed out.

Schema change is not a common operation in normal Web app requests, while it is quite common you would rely on schema information to properly prepare SQL queries. Just imagine if you execute 10 SQLs in a single request, do you want to execute

**Comment by klimov-paul** [comment]
We may consider to automatically call `yii\db\Schema::refresh()` before migration `up()` or `down()`.
This will at least prevent unexpected insert/update results if several migrations are applied in sequence.

**Comment by samdark** [comment]
Agree about migrations.

**Comment by creocoder** [comment]
@klimov-paul 

> We may consider to automatically call yii\db\Schema::refresh() before migration up() or down().

How it will help for migration like this?

```php
$this->createTable('plan', [
    'id' => Schema::TYPE_PK,
    'interval' => Schema::TYPE_INTEGER,
]);

$this->insert('foo', [
    'bar' => '1',
]);

$this->alterColumn('plan', 'interval', Schema::TYPE_STRING);

$this->insert('plan', [
    'bar' => 'month',
]);
```

And main question... Inside config we have `Connection::enableSchemaCache = false`. Even with that setting troubles happened. So internal cache is one of biggest disservice from Yii especially when nobody ask for that cache. Guys please turn off things which may cause serious side effects.

To be honest i do not saw more critical bug for 8 years working with Yii. And i wonder you still thinking

> I don't think we should remove the internal cache.

Probably we should not. But at least it should be disabled by default and have corresponding option for configuration with clean documentation about how dangerous it is and with explaination all side effects.

**Comment by klimov-paul** [comment]
> How it will help for migration like this?

Are you really writing your migrations like this?
Usually I write my DDL before any DML inside migrations.
Still docs about possible needed manual refresh still should be added.

>  internal cache is one of biggest disservice from Yii especially when nobody ask for that cache. Guys please turn off things which may cause serious side effects.

@creocoder, Alex, please calm down. It is not you. 
Do you really think we should throw internal schema cache away? Do you realize, what will happen next?
If we do so, each time to perform any(!) SQL query against any(!) table, Yii will execute `SHOW CREATE TABLE` first. This will double the amount of the SQL queries peformed per each request, producing a huge perfromace impact.

> at least it should be disabled by default and have corresponding option for configuration

And just how it will resolve your migration example? In production mode you will probably enabled schema caching, will not you? So updating your production server and running such migration will still produce invalid result.

**Comment by creocoder** [comment]
@klimov-paul 

> Are you really writing your migrations like this?

No it was 4 different migrations. But after run `yii migrate` it cause troubles. But migration i shown is also legal. This is why you suggestion about 

> We may consider to automatically call yii\db\Schema::refresh() before migration up() or down().

Is nonsense.

**Comment by kidol** [comment]
Mabe add method-calls around such schema modifications?

`Schema::beginEdit()` - Flushes local cache and makes sure it will not be filled again.
`Schema::endEdit()` - Allows local cache again and flushes component cache.

**Comment by creocoder** [comment]
@klimov-paul 

> Still docs about possible needed manual refresh still should be added.

Sorry, but it also nonsense. Its like "manual how to fight with disservices". When you write migrations you expect that it will work without any refreshing. Also i claim that such code is absolutte legal inside regular application. Yes its non usual, but legal.

> Do you realize, what will happen next?

Yes and seems it caused by DAO architecure and choosen approaches. I'm looking into other DAO's to make final conclusions.

**Comment by klimov-paul** [comment]
> No it was 4 different migrations. But after run yii migrate it cause troubles. But migration i shown is also legal. 

I have never told it is illegal. Still it is a rare scenario.

> Is nonsense

I can say just the same about:

> Per request cache should be removed complettely!

Refreshing schema before applying/reverting migration is a compromise, which allows to avoid problems in the most of the cases. Do you think we should not do it? Let it be as it is?

@creocoder, once again you are unable to listen any other opinion but yours. It is a pity.
Instead of criticize so much, can you direct your energy on searching for the acceptable solution, instead the "Per request cache should be removed complettely!"?

**Comment by klimov-paul** [comment]
> I'm looking into other DAO's to make final conclusions.

Here you go:
https://github.com/yiisoft/yii2/blob/master/framework/db/QueryBuilder.php#L134

Here we are using `TableSchema` (the one cached per request) to retrieve column schamas and perform  the typecasting.

**Comment by klimov-paul** [comment]
Here is a commit, which adds this feature: 20bde29 (22.07.2013)

**Comment by klimov-paul** [comment]
I am unable to find an issue related to this commit, perhaps @qiangxue could.
From this point, I can see only one way to break DAO layer affection by schema - removing column-based typecasting. However, it will certainly break some other feature, I am not sure which exactly.

**Comment by klimov-paul** [comment]
I suppose for migrations we can invoke `Schema::refresh()` automatically after following methods:
1) `addColumn()`
2) `dropColumn()`
3) `renameColumn()`
4) `alterColumn()`
5) `renameTable()`
6) `dropTable()`
7) `execute()`
8) `addPrimaryKey()`
9) `dropPrimaryKey()`

1-4 are obvious.

Attention to 5 and 6. At present state after particular table is dropped or renamed it remains in the cache by its old name. If a new table named as already not existing one is created Yii will use old schema for it.

7 - I suppose it is fine to clear cache after `execute()` without extra checks. Schema altering are common for such method, while performance inside migration is not so crucial.

8-9 - Primary key information is stored inside the schema and affects data manipulation.

**Comment by qiangxue** [comment]
Agree. We should add a new method named `invalidateTableSchema()` which simply removes the loaded table schema from the internal cache.

**Comment by creocoder** [comment]
@klimov-paul, @qiangxue So you disagree that internal schema cache should be removed **at least** for insert and update. Ok. Than another serious issue:

```php
$db = Yii::$app->db;
$db->createCommand()->createTable('foo', ['id' => Schema::TYPE_PK, 'bar' => Schema::TYPE_INTEGER])->execute();
$db->createCommand()->insert('foo', ['bar' => 'hello'])->execute();
```

Will silently inserts 0, when standart database exception should be shown. Great. DAO is not just broken, it complettely broken. Early i just do not have time to deeply investigate its new architecture, now i see...

Btw, i made both 3 tests (code from first topic inside migration, schema change on fly inside application, last code i shown in that post) in Laravel 5 DAO. **All 3 tests passed.**

**Comment by creocoder** [comment]
@klimov-paul 

> once again you are unable to listen any other opinion but yours. It is a pity.
Instead of criticize so much, can you direct your energy on searching for the acceptable solution, instead of the "Per request cache should be removed complettely!"?

It is **only** acceptable solution. For me personally it become absolutly obvious after @cebe said that this is because some internal schema cache. First mind after that should be: "I just ask fw to insert record into database. Why it need schema for that?!". When you ask fw insert it should do INSERT and nothing more. It should not pretend on super smart guy role, it should not use schema cache on background for type casting (for what? for silent ignorance serious mistakes?).

**Comment by klimov-paul** [comment]
> So you disagree that internal schema cache should be removed

Yes, I disagree. Internal table schema cache should be present allowing to avoid duplicated `SHOW CREATE TABLE` SQL queries. It does not matter if this query perfromed before insert. update or anything else.
Do you remember this PR: #2070 ? You were so eager to reduce the number of performed queries while saving multiple records, but now you are telling it is fine to perform extra `SHOW CREATE TABLE` query before each(!) insert or update.

> Because it is only acceptable solution.

Just as I said: you don't want to listen.
Lets assume we have accepted PR #8646. So if `Connection::enableSchemaCache` is `false`, no internal cache will be used. Now your application workflow varies on single parameter inside config! If `enableSchemaCache` disabled - your code works fine, once it enabled - code fails silently! And the most problem is: `enableSchemaCache` - is a config parameter, which should be used for perfromance tuning, not for program logic change!
If you disable `enableSchemaCache` while development, write the code from your example - it works fine. After you switched into production mode - your code fails silently!
And you call this behavior the only solution. This is simply irresponsible solution!

> Will silently inserts 0, when standart database exception should be shown. Great. DAO is not just broken, it complettely broken.

I am afraid this is not completely true. Database exception can be thrown, but can be not - it depends on actual DBMS. Some have strict rules, other - milder.
Of course, I admit using column-based typecast is weird. As well as I have said that the only way to make DAO free from table schema, and thus from table schema cahce, is removing this typecast:
https://github.com/yiisoft/yii2/issues/8627#issuecomment-107949340
Still, you continue to insist we should remove CACHE.

The problem is you are not the only user of DAO. I can not just remove some functionality, because it may break the BC, and then some other upset developer will complain on me just like you are doing now.
I can't even tell you for sure, which functionality depends on column-based typecasting. I assume it related to Oracle or MSSQL support. Perhaps @nineinchnick can clarify this matter.

That is why I am proposing clearing the schema cache on DDL invokations. This will at least solve the bug, allowing migrations (and perhaps even other DDL related code) works without troubles no matter, which configuration parameters are used. Also such solution will work even if `enableSchemaCache` enabled and `schemaCacheDuration` > 0, automatically clearing related cache, so web application will use actual schema after migration been applied without extra actions.

**Comment by creocoder** [comment]
@klimov-paul 

> This will at least solve the bug

So you still think its acceptable solution inside framework. Something that "at least solve the bug". First of all. It solve it not complettely. Schema maybe changed externally. Second. Schema may be changed without awaring Yii about that. For example if you use another DAO with Yii. Just example. Third. I always though framework is set of services. But not set of disservices and methods to fight with them. And main thing:

> All 3 tests passed.

This just proof that troubles and tasks can be solved simplier, without using schema at all.

> because it may break the BC, and then some other upset developer will complain on me just like you are doing now

As i said before i do not remember more critical bug than that. I'm pretty sure there is already lot of Yii applications with corrupted data on production and devs just do not know about that. Does BC is still so important in that case?

**Comment by klimov-paul** [comment]
> First of all. It solve it not complettely.

I have never told you it will solve it completely. I consider this issue as a bug inside 'db migration' feature as it was reported.
Decoupling plain `insert()` and `update()` from table schema can be part of this issue as well as can be not.

> This just proof that troubles and tasks can be solved simplier, without using schema at all.

I already have 2 links to my comments, which tells that: https://github.com/yiisoft/yii2/issues/8627#issuecomment-107949340 and https://github.com/yiisoft/yii2/issues/8627#issuecomment-108780399 . You can stop reminding me this already.
Removing DAO from table schema should be considered at milestone 2.1, not in 2.0.x. If we will use my approach as a solution for 'db migration' issue, we should open another ticket about separating DAO from table schema - no one here is questioning its validity.

> i do not remember more critical bug than that

Of course you don't. Any developer reporting more or less crucial bug thinks it is a center of the world. But I have seen many critical bugs and many major mistakes we have made. 
Don't mind me wrong: I appreaciate your effots and your attention. Finding this have costed you a lot of  nerves for sure. I understand that. And I expect you can understand me as well: I need to maintain balance between different people demands, which sometimes contradict each other.
I am not your enemy, I am not fighting against you - I just try to make things right.

Back in Yii1 we also used table schema. Although it was used at other layer - Active Record. Still it has same problems you describe. I don't remember you have complained Active Record at Yii1 will behave inconstently if "Schema maybe changed externally".

> Does BC is still so important in that case?

BC is always important. We have rejected many issues and demands at Yii 1.x repository as they broke the BC. We have to leave many inconsistencies at Yii1 framework, just to keep it compatible with ealier versions. Most of those rejected features were implemented at Yii2.
The only unquestionable reason for BC break is security breach, which this issue does not expose.

**Comment by creocoder** [comment]
@klimov-paul 

> Any developer reporting more or less crucial bug thinks it is a center of the world. 

Ok. lets think. How many production servers already affected by this bug and developers even do not know that? Can you garantee that no one? For some people it may even be timebomb. But i still do not see BIG warning on main site. I do not even see CRITICAL label on this issue. Same time you reasoning about BC... BC is about trust right? Think of that issue from trust aspect. IMO that issue is so critical that minimum actions is: 1) big warning inside news to ensure devs know about that and start checking their dev and prod data in db, 2) new bugfix version ASAP.

**Comment by samdark** [comment]
@qiangxue do you remember why we're using schema in insert?

**Comment by samdark** [comment]
Was it introduced to always write `null` in case of empty form field submitted?

**Comment by creocoder** [comment]
@samdark Looks like it introduced to write null to INT and other non string columns when empty field submitted. But it does not take into account situation when '  ' submitted. So https://github.com/yiisoft/yii2/commit/20bde29f58472416d2a071fc8c28bad935be7300 is useless, careful developer still need default validator with null value for INT fields.

**Comment by qiangxue** [comment]
The key point is  that `getTableSchema()` is used in many places, not just `insert()`. The whole ActiveRecord relies on it.

As @klimov-paul already pointed out, it doesn't make sense to remove internal schema cache because it would otherwise involve significant performance impact.  Just search for `getTableSchema()` in the ActiveRecord class, and you will know what I mean.

@creocoder I understand it is frustrating that you spent a lot of time finding out the issue. We certainly need to fix this issue one way or another. But please calm down a little bit and do not over-exaggerate the issue only because you have spent a lot of time. How common do you think it is that you would change the table schema immediately followed by data insertion into the same table? And compared to the performance degradation, do you think it is worthwhile to remove the internal cache? Just imagine each time when you access an AR attribute, you would have to re-fetch the table schema to ensure accuracy, as you proposed. Isn't that crazy?

Unless there are other suggestions, I think we should go for the solution of invalidating the internal cache each time when a schema-changing query is performed.

**Comment by fernandezekiel** [comment]
maybe we should just write a wiki for this instead... it seems a very rare case but devs can take a note nonetheless

**Comment by creocoder** [comment]
@qiangxue Seems you misunderstand my suggestion. I do not suggest remove schema cache complettely. I suggest only remove code:

```php
        if (($tableSchema = $schema->getTableSchema($table)) !== null) {
            $columnSchemas = $tableSchema->columns;
        } else {
            $columnSchemas = [];
        }
```

From insert, update and similar methods. This not affect perfomance at all and competelly resolve issue.

About that warn users

> How common do you think it is that you would change the table schema immediately followed by data insertion into the same table?

I think you're really underestimating issue dangerous. "Immidiately" does not requirement there for data corruption. Ok, simple example:

```php
create_foo_table
...
another 10 migrations
...
alter_foo_table
...another 10 migrations
insert_foo_table
```

Now cases:

1) Developer one run `yii migrate` after creating every migration
2) New developer come and run `yii migrate`
3) After releasing software part of deploy procedure was `yii migrate`

In 2) and 3) cases data will be corrupted. Even if between first and last migration 1000 migrations.

**Comment by qiangxue** [comment]
Unless you changed your opinion somewhere, but you wrote this: "This cache should be removed completelly".

And please read carefully my last comment. I was suggesting "I think we should go for the solution of invalidating the internal cache each time when a schema-changing query is performed." Also I said because AR relies on `getTableSchema()`, it doesn't make sense to just remove the typecasting in `insert()`, hoping it will solve all problems.

**Comment by creocoder** [comment]
> And please read carefully my last comment. I was suggesting "I think we should go for the solution of invalidating the internal cache each time when a schema-changing query is performed."

I read it carefully. You fix based on the assumption that inside Yii aplication schema may change only using Yii tools. Its not reliable. I can show examples when fix will not work. Seems we differently see situation and acceptable solution. For me personally acceptable === 100% reliable solution, while you try to defend typecast. Btw typecast lead to another 2 bugs.

**Comment by qiangxue** [comment]
> You fix based on the assumption that inside Yii aplication schema may change only using Yii tools. Its not reliable.

If you read my comment here (https://github.com/yiisoft/yii2/pull/8652/files#r31779714), you will not draw this conclusion. I fully understand Yii methods are not the only way to change table schema. This is the tradeoff we have to take between performance and inconvenience of manually invalidating table schema when raw SQLs are being used.

>  For me personally acceptable === 100% reliable solution, while you try to defend typecast. Btw typecast lead to another 2 bugs.

Assume we take your suggestion to "fix" `insert`. Now do you think the following code will work 100% correctly? 

```php
$db->createCommand()->renameColumn('foo', 'name', 'id')->execute();
$foo = Foo::findOne(1);
```

I don't want to spend time investigating `insert` now, because clearly this is not the culprit of the issue. It would be silly to make the change and later find it not only breaks BC but also leaves the root issue unsolved.

**Comment by qiangxue** [comment]
Just FYI, in Yii 1.1, we are doing typecasting in insert too. I don't want to dig for the original reason behind it, but one reason I can think of is to ensure proper data types when we perform DB parameter binding which relies on the PHP type of the parameter value to set proper binding type. For example, if you are inserting `'1'` into a boolean column, instead of binding it as a string, it should be converted into a boolean value and be bound as a boolean. Otherwise some DBMS may have trouble.

**Comment by klimov-paul** [comment]
> I do not even see CRITICAL label on this issue. 

Ok, I have added this label. i hope it make you feel better...

> Ok. lets think. How many production servers data already affected by this bug and developers even do not know that? 

No one is questioning that. Still there are many importatn issues, for example we have issue #8572, which breaks a huge amoung of existing code realying on `yii\db\Expression`. Have you missed it?

> Same time you reasoning about BC... 

This is funny. Do you remeber issue #7408 ? Back then you were so eager convincing people to use strict versioning policy, separate features from bug-fixing, introducing patches and so on.
Now you are saying: who cares about that - the main goal - the code should be like I want it to be!

> You fix based on the assumption that inside Yii aplication schema may be changed only by using Yii tools. Its not reliable.

Many Yii db layer feature depends on table schema. Not only `insert()` and `update()`. Same situation was back in Yii1. If database schema changed by external means, you should call `Schema::refresh()`.
People usually understad this, for instance: https://github.com/yiisoft/yii/issues/2005 .

**Comment by samdark** [comment]
@qiangxue I think we don't do any schema-based typecasting in Yii 1.1 insert/update:

- https://github.com/yiisoft/yii/blob/master/framework/db/CDbCommand.php#L1255
- https://github.com/yiisoft/yii/blob/master/framework/db/CDbCommand.php#L1293

**Comment by klimov-paul** [comment]
@samdark, yes we have not.
At Yii1 DAO layer was free of table schema usage. However it was not completely.
Check Oracle insert composition:
https://github.com/yiisoft/yii/blob/master/framework/db/schema/oci/COciCommandBuilder.php#L108
It relies on table schema information, which can be cached.

**Comment by klimov-paul** [comment]
We have the same situation with Oracle at Yii2. Check this:
https://github.com/yiisoft/yii2/blob/master/framework/db/oci/QueryBuilder.php#L192
Here insert SQL composition also depends on table schema even if do not mind the column-based typecast.

**Comment by creocoder** [comment]
> Assume we take your suggestion to "fix" insert. Now do you think the following code will work 100% correctly?

```php
$db->createCommand()->renameColumn('foo', 'name', 'id')->execute();
$foo = Foo::findOne(1);
```

Did not though about that. Thanks for explaination. On that background invalidate cache after some operations is best solution.

**Comment by miraage** [comment]
DAO uses schema caching.
The fix is clearly easy - just reset/reload table schema cache after any alter manipulations.
