### ISSUE TITLE
Empty help-block DIV below form elements

### ISSUE THREAD

**Issue by evilito** [yiisoft/yii2#8666]
Hi, the ActiveField seems to be printing an emtpy and unnecessary DIV element for the help block. i.e. the following code:

    <?php $form = ActiveForm::begin(); ?>
    <?= $form->field($model, 'field')->textInput() ?>
    <?php ActiveForm::end(); ?>

generates this at the end of the input:

    <div class="help-block"></div>

This isn't much of a problem when display a simple form alone, but if you need, for example, put some ActiveField elements in a table row with other elements, it's a nightmare to align them correctly since the empty div has its own CSS style, including margins.

What I expect is that, if no errors or any content is found to be displayed in the help-block DIV, it shouldn't be rendered at all, not even if it's empty.

I also don't want to get rid completely of the help-block because I still want to be able to display errors if they are found.

Can it be fixed? Thank you.

**Comment by klimov-paul** [comment]
`<div class="help-block"></div>` serves for error messages display. It can not removed, otherwise client or ajax validation will not work correctly.

**Comment by afranioce** [comment]
Remove using
```php
<?= $form->field($model, 'field', ['errorOptions' => ['tag' => null]])->textInput() ?>
```

**Comment by darksnake747** [comment]
I know this is old, but it comes up pretty high on Google and I feel a solid response for Yii 2's current state is missing. So, first off, it is important to note that the error div is intentional - added by design for field-level error message display and error display with AJAX validation. However, it certainly can be removed and may make sense for your use case.

You can shut the tag off on a specific field like this:

```php
<?= $form->field($model, 'field', ['errorOptions' => ['tag' => false]]) ?>
```

Pretty much identical to the above response, but Yii's documentation states (at this time) to use false. Either way, I personally see this question as more of "how can you change the way an input field is rendered", which I would direct you to the field's template. The default for this is: label, input, hint, then error. If you want to remove any of those or change the order of them, you can easily do that by overriding the template setting on an individual field OR an entire form.

Single Field:

```php
<?= $form->field($model, 'field', ['template' => "{label}\n{input}\n{hint}\n{error}"]) ?>
```

Entire Form:

```php
$form = ActiveForm::begin([
    'fieldConfig' => [
        'template' => "{label}\n{input}\n{hint}\n{error}"
    ]
])
```

The above code snippets show the template being set to the default value. If you don't want the label, remove {label}. If you want the hint above the input field, simple move {hint} to before {input}. In my opinion this is the nicest way to control how a field is rendered in a form widget. 

Do note the use of double quotes in the value setting so that PHP parses and properly handles the newline characters.

While it may not be the best idea to remove the error div, you can do it easily. And there are use cases for it. Personally, I think the field level error display looks a  little crowded and I generally remove the them in favor of a single error summary. However, on more complex forms or fields, sometimes I do opt to display a very specific error message on the field-level. Just depends on what YOU want and need.

Hope this helps someone. :)

-Cheers-

**Comment by Khasan-web** [comment]
Just select your form in css and make:

.form-group .help-block {
    display: none;
}

**Comment by kambizzandi** [comment]
I know this is old, but may be this code helps:

`.form-group .help-block:empty {
  display: none;
}`
