### ISSUE TITLE
Maintaining Application up-to-date

### ISSUE THREAD

**Issue by fedemotta** [yiisoft/yii2#8681]
I created several apps based in the yii2 Advanced template and I am looking for an easy way to keep my apps updated to the latest version changes of the template. Now, I am looking for the changes committed to master and applying it to my apps. 
Obviously It is impossible to keep track of all the changes because every app is different, but from time to time there is a an important fix or change to update to my apps. I am worried that I missed some important updates.

Please understand that I am talking about the templates, not the yii2 core or yii2 extensions, which are being handled by composer. 

Some questions to better understand this issue:
1. Is there any recommended way to keep application (based on advanced or basic template) up-to-date?
2. Could the Application Templates being improved to allow them as a composer dependencies of our applications?
3. Is it possible to separate the advanced template in different templates? In example, front, back and common templates?
4. Could the basic template being one of the new templates created in 3.?
5. Could the developer Application extend from one (or many) Application templates?

Thanks

**Comment by samdark** [comment]
1. Overall, you don't need to since changes are usually minor and won't affect your app but if you want a diff of changes, git can help if you have an idea when you've updated last. Clone advanced project template with git, cd there and execute `git diff $(git rev-list -n1 --before="14 days ago" master)` .
2. No. Once you've used a template, it's your app and you can modify it as you need.
3. Technically yes but I see no reason to do so.
4. Again, technically yes.
5. No.
