### ISSUE TITLE
yii2 cache serializer property doesn't support closure.

### ISSUE THREAD

**Issue by zhaosih** [yiisoft/yii2#8797]
I got err 

PHP Fatal Error 'yii\base\ErrorException' with message 'Cannot use object of type Closure as array'
in /vendor/yiisoft/yii2/caching/Cache.php:198

my setting is 
            'serializer'=>function(){
                $serializer=new \SuperClosure\Serializer();
                return[[$serializer,'serialize'],[$serializer,'unserialize']];
            },
could you make this support?

**Comment by samdark** [comment]
It's planned for 2.1 to use SuperClosure.

**Comment by zhaosih** [comment]
Really expect this feature. When will the 2.1 be ready?

**Comment by samdark** [comment]
When it's done ;)

**Comment by Mirocow** [comment]
Please use it ** SuperClosure**

**Comment by klimov-paul** [comment]
Since #15410 you can define your own serializer class.
The serializer, which wraps `SuperClosure\Serializer` should be created as an extension since it requires extra dependency.
Issue removed from the core scope.

**Comment by samdark** [comment]
@sergeymakinen could be interesting to use your closure serializer for something like that.

**Comment by sergeymakinen** [comment]
@samdark if we apply my changes to `yii\helpers\BaseVarDumper::exportClosure()`, it's probably possible to implement our `ClosureSerializer` since it would be possible to serialize uses from closures (I mean `function () use(…)`).
I guess in most cases it would be just enough. For complex scenarios we already have #15410.
