### ISSUE TITLE
base\Model::load() return documentation is misleading

### ISSUE THREAD

**Issue by tom--** [yiisoft/yii2#8803]
The [docs for yii\base\Model::load()](https://github.com/yiisoft/yii2/blob/master/framework/base/Model.php#L791) says it returns:

>       boolean whether the model is successfully populated with some data

when it also returns true if it populates nothing at all, for example if the data contains no safe attributes.

I don't have a suggestion for better text. I think `load()` returns false if and only if the data are not structured in a way it understands. But that's not a very useful text for the docs.

**Comment by ajayvembu90** [comment]
The 'load()' method in Model class is mostly overloaded either with 'Yii::$app->request->post()' or 'Yii::$app->request->get()', so it returns false when there is no request and true if there is a request and some of the model fields are present.

If you try to use 'load()' without a request it will always return true as some includes none.

**Comment by tom--** [comment]
In normal English, "some" and "none" are mutually exclusive. For example, "Some apples are on the table," is a false statement if there are in fact "none".

I wasted time looking in the wrong places for why a `assertFalse($model->load([test data]))` was failing. Eventually I looked at source of `load()` and saw that the test is wrong because it was designed according to the described behavior instead of the actual behavior.

**Comment by PowerGamer1** [comment]
I think the behavior of `Model::load()` should be changed to actually be as currently documented, i.e.: `load()` should return `true` only if at least ONE of the model fields was populated with value from provided array.

Currently, load() basically tests if provided array was empty or not, caller of `load()` method could perform such test easily using PHP's built-in functionality. On the other hand, a test to see if at least a single form field was provided in $_GET or $_POST would be quite cumbersome to implement outside of Model::load() method (which, in contrast could do such test rather easily).

Besides, when model formName() returns an empty string (makes URL prettier when submitting form by GET) and $_GET contains only some additional params (which are not related to the HTML input form at all) and not a single param from the corresponding form model class, Model::load() will return `true` which is very bad, because it does not allow to distinguish between the first time opening of the page with form and form submission.
