### ISSUE TITLE
Can't get memcache value if it was set from node.js

### ISSUE THREAD

**Issue by IBleSSeDI** [yiisoft/yii2#8997]
We have a Yii2 application. And we use memcache. In our system node.js writes to cache and php reads from cache. But I get the following error in php:

> MemcachePool::get(): Failed to uncompress data

How to read data from php if memcache value was set in node.js?

**Comment by cebe** [comment]
you can set the serializer property of the cache to false http://www.yiiframework.com/doc-2.0/yii-caching-cache.html#$serializer-detail

this way yii will store the raw data instead of serializing it and it will also not try do unserialize after reading.

**Comment by IBleSSeDI** [comment]
Yes, I did that, but it didn't help. The issue still presents.

**Comment by klimov-paul** [comment]
Can you retrieve data from cache using plain `memcache` PHP extension?

**Comment by IBleSSeDI** [comment]
No, I cannot :(

**Comment by klimov-paul** [comment]
Well, It is not Yii issue then.

**Comment by IBleSSeDI** [comment]
Agree. Storing data as plain text fixes the issue. Thanks.

**Comment by ApXaHgheJI** [comment]
There is also a problem : 
I store from other project an key=value
When I try to get it from Yii2: Key = app_routes_urls - it make a md5 of this key.
Because in my key are "_" simbol.

Problem 
`$key = ctype_alnum($key) && StringHelper::byteLength($key) <= 32 ? $key : md5($key);`

There is no flag for leave the key unchanged.
I think its a good idea for cases like this - when you need to work with external MemCache service.

**Comment by cebe** [comment]
@ApXaHgheJI please open a new issue for this.
