### ISSUE TITLE
ViewAction resolveViewName does allow directory backward jumps "../"

### ISSUE THREAD

**Issue by thejahweh** [yiisoft/yii2#9070]
In the Method "resolveViewName" of the class "ViewAction", there is a possibility to change the directory to something like `viewdir/../../../importantphpfile` and render some files, which shouldn't be rendered.

**Comment by thejahweh** [comment]
https://regex101.com/r/gN7cN0/2

**Comment by samdark** [comment]
Thanks! Fixed.

**Comment by cebe** [comment]
@thejahweh thanks for reporting this security issue. We have made a release to fix this: http://www.yiiframework.com/news/87/yii-2-0-5-is-released-security-fix/

For the next time and also to everyone who is reading this. For security issues, please consider to [contact us](http://www.yiiframework.com/security/) privatly before disclosing a secutiry issue publicly so that we have time to prepare a fix and the release. Thanks!
