### ISSUE TITLE
ErrorHandler::handleError() should log errors not included into error_reporting()

### ISSUE THREAD

**Issue by mrsombre** [yiisoft/yii2#9183]
Yii by default uses own errorHandler, that handle all errors, but ignore them by error_reporting level setting. In my oppinion it's comon situation you wont stop execution of entire application when notice, warning or strict error raised. But you may want to catch and log this errors in a common way by yii log.
And you dont want to miss these errors, instead you should see them in log files and deside how fix them or suppress by @ operator.

**Comment by kidol** [comment]
So currently Yii completly ignores unconfigured error levels and with the patch Yii does only throw for configured error levels while continue to run and log for unconfigured ones?

So if I run with `E_ALL` nothing will change with patch.
If I run with `E_ALL ^ E_DEPRECATED` then the deprecated messages will be logged.

Is this really the way to go? If I use `E_ALL ^ E_DEPRECATED`, then I obviously don't care about deprecated warnings, so there is no need to force me to use `@`.

I think it's better teaching people to use the correct error reporting settings.

**Comment by mrsombre** [comment]
@kidol 
> I think it's better teaching people to use the correct error reporting settings.

Imagine a big complex site/system, without 100% test coverage. Some day u make a mistake, witch cause a very rare error, ex when user logged and do some action. You can't ever find it by yourself. And you don't want your application show 500 error page in case of simple type in some of your variables. Then what?

Without proper loggin you'll never found this error, because it only shows in really rare situations.

BTW ANY notice of warning not suppressed by @ operator is a potential problem in yr code. I think you should receive a log first. And then it's up to you to suppress this potential error with @ if you never ever care about it, or maybe you need to fix something.

**Comment by kidol** [comment]
> Without proper loggin you'll never found this error
> ANY notice of warning not suppressed by @ operator is a potential problem in yr code

Yes, that's why people should configure proper error level. Want to see E_NOTICE? Include in error level. Don't want to see E_DEPRECATED? Exclude from error level.

And no I don't see problem with 500 error page. The app won't work anyway if there is error in underlying logic.

In the end it's up to the developer isn't it? Want strictness use `E_ALL` and you can be sure everything will be logged.

Does this issue affect you and why? Why can't you set error level to `E_ALL ^ DEPRECATED` for example?

**Comment by mrsombre** [comment]
@kidol My production config is 
```
error_reporting(E_ALL ^
        (E_WARNING | E_NOTICE | E_STRICT | E_DEPRECATED | E_USER_WARNING | E_USER_NOTICE | E_USER_DEPRECATED));
```

Because in most cases this errors does not cause any problems with user experience and can be hidden. But i check logs every few days and fix errors if any.
Also good for old stuff, libraries, etc.

Okay, personally i fix this with custom ErrorHandler. But what the problem with logging errors on production if you can? And why your site should be not available because notice or warning?

If you prefer a good stability instead of availability then you can set E_ALL and break site with 500 on every micro problem why not.

Maybe somebody else can provide opinion?

**Comment by samdark** [comment]
Won't implemenent it. Continuing exection on any sort of error, be it a notice or deprecation warning, could lead to very serious issues such as data corruption. In order to notice these errors you may use something like http://rollbar.com or http://getsentry.com.

If you want it bad, solve it with custom error handler.
