### ISSUE TITLE
Yii2 httpcache issue

### ISSUE THREAD

**Issue by niteenach** [yiisoft/yii2#9248]
Hi,
I have set httpcache in one of my controller but on ajax call it is not setting the http cache-contol headers..
Behaviour looks like as below..

```php
 public function behaviors()
 {
     return [
         'access' => [
             'class' => AccessControl::className(),
             'only' => ['logout'],
             'rules' => [
                 [
                     'actions' => ['logout'],
                     'allow' => true,
                     'roles' => ['@'],
                 ],
             ],
         ],
         'httpCache' => [
              'class' => 'yii\filters\HttpCache',
              'cacheControlHeader' => 'public, max-age=0',

     ],
     ];
 }
```

**Comment by cebe** [comment]
please show the code you are using to make the ajax request. also use [markdown](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown) to format your code so that we can read it.

**Comment by microinginer** [comment]
Ajax request is [not sent](http://stackoverflow.com/questions/5173656/how-to-check-if-jquery-ajax-request-header-status-is-304-not-modified?answertab=active#tab-top) if-modified-since header, so the server does not know whether or not taken answer from the cache because it meets the code 200 and header last-modified, and the browser focusing on the header last-modified to take the answer from cache.
