### ISSUE TITLE
QueryInterface::from method missed?

### ISSUE THREAD

**Issue by creocoder** [yiisoft/yii2#9341]
Am i right? Or it should not be there? Probably more methods missed. Using that interface very useful for typehints like:

``` php
$query = User::find()->joinWith([
    'subscription.nextPlan' => function (ActiveQueryInterface $query) { // look there
        $query->from(['next_plan' => 'plan']);
    },
]);
```

**Comment by klimov-paul** [comment]
Signature of the `from()` may vary, see:
https://github.com/yiisoft/yii2-elasticsearch/blob/master/Query.php#L466
https://github.com/yiisoft/yii2-mongodb/blob/master/Query.php#L97

Thus is is unlikely can be made a part of the `QueryInterface`.

> Using that interface very useful for typehints like

In your example you are refering to `ActiveQueryInterface` - not `QueryInterface`. Exposing `from()` to it does not seem to be right, because `ActiveQuery` determines source from `ActiveRecord` class.

**Comment by creocoder** [comment]
@klimov-paul 

> Signature of the from() may vary

Got it. So correct type hint will be `function (ActiveQuery $query)`, right?

**Comment by cebe** [comment]
correct, joinWith is only part of the SQL query anyway so you would not get anything else passed to the function.
