### ISSUE TITLE
Yii 2 Truck Factor

### ISSUE THREAD

**Issue by gavelino** [yiisoft/yii2#9373]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **Yii 2** and obtained a value of **3**.

The developers responsible for this TF are:

Qiang Xue - author of 41% of the files
Alexander Makarov - author of 23% of the files
Carsten Brandt - author of 19% of the files

To validate our results, we would like to ask **Yii 2** developers the following three brief questions:

(a) Do you agree that the listed developers are the main developers of **Yii 2**?

(b) Do you agree that **Yii 2** will be in trouble if the listed developers leave the project (e.g., if they win in the lottery, to be less morbid)?

(c) Does **Yii 2** have some characteristics that would attenuate the loss of the listed developers (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by samdark** [comment]
a) Yes and no at the same time. You're definitely missing many major contributors and core team members: https://github.com/yiisoft/yii2/graphs/contributors.
b) Not really. Framework is used by many major businesses and they're actively contributing so one of these companies could throw resources on it.
c) Yes. There are docs. There are internal docs. All the code is well documented.

**Comment by cebe** [comment]
> [...] if they win in the lottery [...]

If I would win in the lottery I could work fulltime on Yii without needing to care about making money so that would rather be positive effect on Yii contribution from my side ;)

For a) I'd like to add that all of the core team members are familiar with most of the code or at least able to adopt parts currently covered by others. The core team currently consists of @qiangxue, @cebe (me), @samdark, and @klimov-paul. So the factor would be at about 4.

For b) I do not agree, we have a community which is actively participating in the project and contributing code so there is a huge set of developers that are familiar with the framework internals.

For c) We have a team of core developers which is distributed over the planet, USA, Germany, Ukraine, Russia. So the chance of loosing the whole team at once is very rare, if members go we will look for new ones to keep our team big enough to be able to replace people that have no time to contribute for a specific time frame or leave for other reasons.

**Comment by cebe** [comment]
> We calculated the TF for Yii 2 and obtained a value of 3.

btw, your preprint pdf lists yii2 at TF2, not 3...?

**Comment by dynasource** [comment]
Looked at the good examples Cebe & Samdark are giving over here, I dont think you can conclude anything with respect to this truck factor. It typically is something one 'wise' theorist got really 'excited' about and finally had something to put on paper again.

I would suggest you to either look at 'the main reasons why the truck factor can lead to inaccurate conclusions' or at 'factors from which one can actually do get a good indication of the risk of continuation of a project'

**Comment by phpnode** [comment]
It would be extremely unfortunate if those 3 legends left the project, but the project would not die without them. Qiang et al have gone out of their way to make Yii's source incredibly simple, there are no dark, crufty corners that only certain people understand, the whole thing is like a book. On top of that, Yii has been around long enough that there are a lot of other people who are not members of the core team that understand the design decisions and know it very well, well enough to step up and contribute if need be. 

The loss of Qiang, Alex and Carsten would be a major setback, but not fatal.

**Comment by gavelino** [comment]
Thank you for the answers. I really appreciate the feedback.

@cede sorry for the mistake. The correct value is 3. This is just a pre-print and we'll fix this in the final version.

**Comment by samdark** [comment]
Hope the final version will reflect the fact that bus factor isn't 3 in this case...
