### ISSUE TITLE
Advanced Yii2 codeception not loaded

### ISSUE THREAD

**Issue by Aimandis** [yiisoft/yii2#9407]
So I decided to test Codeception on an old personal project.
I am trying to run the default Codeception tests from my project ( I'm aspecting for an error anyway, cause i dont have that classes anymore, but not this kind of error ).

I wrote in my console: 
php codecept.phar run tests/codeception/frontend/acceptance/ContactCept.php
and I got this : 
[Codeception\Exception\ConfigurationException]
Suite codeception was not loaded

Any idea why?

**Comment by dynasource** [comment]
it all depends on where you're .yml are located and how you are calling codeception so its situation specific. 

Your issue is about the 'suite' which is in fact either a missing 'acceptance' or 'functional' in your run.
Try this:

* go inside the folder with codeception.yml
* run php codecept.phar run acceptance ContactCept.

**Comment by armpogart** [comment]
Just a remark that there is new major release of codeception, and it breaks compatibility with the old code in some vases. So maybe problem lies in version of codeception you use.

**Comment by dynasource** [comment]
nope, this exception is because of calling the suite wrong. You cannot call a Cept file outside its codeception.yml scope.

**Comment by Aimandis** [comment]
Ok. I managed to fix it.
It was a problem with my codecept.phar's path. I started all over again and used the instructions from the README.md file and now works fine. 
Thanks for help.
