### ISSUE TITLE
Each validator doesn't show error messages below input field instantly

### ISSUE THREAD

**Issue by AnDroidEL** [yiisoft/yii2#9481]
When I have many fields with the same attribute and I use the "each" validator in model as for example:

```php
<?php
// Using ActiveForm by widget package and bootstrap package ...

// ...
['name', 'each', 'rule' => ['required']],
// ...
```
... the input doesn't shows an instantly error with a message saying that must be a "required input", same that you do use other validator type. When you don't use the each validator and use only the required validator, the error message is visible below input field.

```php
<?php
// Using ActiveForm by widget package and bootstrap package ...

// ...
['name', 'each', 'rule' => ['required']], // It doesn't shows the instantly error message below input field
['name', 'required'], // It does shows the instantly error message below input field
// ...
```

How can I solve this problem?

**Comment by SVVladymyr** [comment]
Hi. If properly understood the question, https://github.com/yiisoft/yii2/blob/master/docs/guide/input-validation.md (Declaring Rules):
[['name', 'each', 'rule'], 'required'],

**Comment by AnDroidEL** [comment]
@SVVladymyr is not this.

If I need add more than 5 datas in a same attribute and I use the "each" validator to take these datas, it's OK, it's works. But the problem is that it doesn't shows instantly a error message notifying to user that input field is required, the same thing happens with others validators inside "each" validator, for example: string, integer, etc.

Natively, I use Bootstrap 3 in Yii2.

I will explain as an example:

I create a input field in a form and I define in the rules function, of the model, a string validator and a required validator for it. If you go to the form and click inside after outsite of the input field, it shows an error message saying that is required! Now, use the same validators inside "each" validator. No effect.

Did you understand now?

**Comment by SVVladymyr** [comment]
'each' with ['required'] does not work.

**Comment by lynicidn** [comment]
work, but only unexpected behavior for empty array
foreach ([] as $el) {
if (empty($el)) //this not called
}

**Comment by AnDroidEL** [comment]
@SVVladymyr I know that "required" doesn't works! That's was an example! See my quote:

> [...] the same thing happens with others validators inside "each" validator [...]

**Comment by AnDroidEL** [comment]
@lynicidn How and where do I use it? Explain it.

**Comment by lynicidn** [comment]
@AnDroidEL i don't understand your last question

**Comment by lynicidn** [comment]
http://www.yiiframework.ru/forum/viewtopic.php?f=19&t=31815
use forum or see framework code

**Comment by AnDroidEL** [comment]
![captura de tela de 2015-09-01 07-04-58](https://cloud.githubusercontent.com/assets/9509498/9601459/10d93fe0-5078-11e5-9ade-8f61571740a7.png)

@lynicidn It's what I want to say. You see it showing an error when, for example, I put an invalid email. But, when I don't use in model:

```php
['email', 'email'],
```

But ...


```php
['email', 'each', 'rule' => ['email']],
```

It doesn't shows that errors instantly. Did you understand now?

**Comment by lynicidn** [comment]
show request data - he contain answer on your question

**Comment by klimov-paul** [comment]
`EachValidator` does not have client-side validation, thus it does not triggered on user typing? droopdown changes and so on.

**Comment by AnDroidEL** [comment]
@klimov-paul so... do you have any alternative to solve my problem? For example: in a form, an user is inputting the data about itself, and in a part of the form it may add 3 data or more. If I use the "Each" validator I will have that limitation. So, what the best alternative to this?

**Comment by klimov-paul** [comment]
Use tabular model input.

**Comment by dmitriy-luch** [comment]
Hello.
I'm not sure if it is the correct topic but my question is why each validator does not have client-side validation?
I tried to implement my own solution and it worked (I used range validator in rules for testing purpose)
`
class EachValidator extends Validator
...
public function clientValidateAttribute($model, $attribute, $view)
{
    $validator = $this->getValidator();
    $data = $validator->clientValidateAttribute($model, $attribute, $view);
    return 'if (value instanceof Array){value.forEach(function(value){'.$data.'})} else {'.$data.'};';
}
`

I'll be find with my own EachValidator that extends default EachValidator. But here comes another issue: getValidator() method is a private one and I'm not able to use it.
Is there an other way to resolve the problem or it should be used as it is due to some restrictions that I'm not aware?

@klimov-paul, could you please explain "tabular model input" a bit more detailed? 
In my example I have array of IDs and a multiselect dropdown. I would like to validate that each value in dropdown is in the provided range.
I am able to do that on the server side using Each and Range validators. I would like to enable client side validation too without copy-pasting EachValidtor code.

**Comment by SVVladymyr** [comment]
Hi!If properly understood the question.The Yii framework is on the server side and only performs validation on the server side (that which comes from the client).Validation on the client side must be implemented independently.Simply use the ready. Many validation JavaScript frameworks implemented.I do not forget about the possibilities of HTML5.24.02.2016, 18:29, "dmitriy-luch" <notifications@github.com>:Hello. I'm not sure if it is the correct topic but my question is why each validator does not have client-side validation? I tried to implement my own solution and it worked (I used range validator in rules for testing purpose)  class EachValidator extends Validator ... public function clientValidateAttribute($model, $attribute, $view) { $validator = $this->getValidator(); $data = $validator->clientValidateAttribute($model, $attribute, $view); return 'if (value instanceof Array){value.forEach(function(value){'.$data.'})} else {'.$data.'};'; }I'll be find with my own EachValidator that extends default EachValidator. But here comes another issue: getValidator() method is a private one and I'm not able to use it. Is there an other way to resolve the problem or it should be used as it is due to some restrictions that I'm not aware?@klimov-paul, could you please explain "tabular model input" a bit more detailed?  In my example I have array of IDs and a multiselect dropdown. I would like to validate that each value in dropdown is in the provided range. I am able to do that on the server side using Each and Range validators. I would like to enable client side validation too without copy-pasting EachValidtor code.—Reply to this email directly or view it on GitHub.

**Comment by dmitriy-luch** [comment]
@SVVladymyr, many Yii core validators have client side validation (JavaScript) code among with the server side (PHP) one. http://www.yiiframework.com/doc-2.0/guide-input-validation.html#client-side-validation
My question was regarding Each validator, and why it does not have client side validator. I'm trying to understand whether it was made intentionally or such feature can be added.
