### ISSUE TITLE
Documentation search bug

### ISSUE THREAD

**Issue by nkovacs** [yiisoft/yii2#9541]
Go to http://www.yiiframework.com/doc-2.0/index.html and search for "sort" or "Sort". There will be no results.

"sor" and "sorti" works.

**Comment by hofrob** [comment]
Another example: typing "mult" lists a lot of pages including for example:

* Abstract Class yii\web\\**Mult**iFieldSession
* Getting Data for **Mult**iple Models
* Database Access Objects (probably because of this paragraph: "Tip: You can configure **mult**iple DB application components if your application needs to access **mult**iple databases.")

Typing "multi" (just adding the "i") produces only one result:
* Class yii\sphinx\ColumnSchema

**Comment by cebe** [comment]
Reproduced, This is because the search does not do auto extension of terms when an exact term is matched.
