### ISSUE TITLE
active form pjax yii2 conflict

### ISSUE THREAD

**Issue by margeslt** [yiisoft/yii2#9566]
I have problem with  pjax and Active form.
When I use HTML Form: the form send is Pjax.
And if I use Active form the form send from Active form js file. ().
Although the attribute is set  'data-pjax' => true, the container forms wrapped pjax.

**Comment by derekisbusy** [comment]
This might be related to this issue...

https://github.com/yiisoft/yii2/pull/9432

The pull request I sent is only a partial fix. In order to properly get Yii and Pjax working someone has to rewrite Pjax so that the Pjax settings for each instance are accessible outside the instance, ie. accessible from yii.js. It basically means the entire Pjax script will have to be rewritten. I will try to get it fixed if I have time unless the Yii dev team doesn't want to... ?

**Comment by margeslt** [comment]
I understand active form.js priority responds to the submit event of the form, without checks, whether hanging on it pjax ('data-pjax' => '1' or 'data-pjax' => true) and process and this event is triggered first stopping the pjax.
