### ISSUE TITLE
Not logical behavoir in joinWith and relation queries

### ISSUE THREAD

**Issue by smsteel** [yiisoft/yii2#9595]
I've got one model with relation one-to-many to another:

    class Commodity extends ActiveRecord
    {
         public function getDiscount()
         {
             return $this->hasOne(Discount::className(), [Discount::commodityId() => self::id()]);
         }
         public static function findForCurrentCompany()
         {
             return static::find()->...(conditions)...->joinWith('discount');
         }
         public function afterFind()
         {
              // Discount calculations for multiple prices
         }
    }

What will happen:
Yii2 will execute join query, will populate Commodity models with data and call afterFind method.
In afterFind i will call to `$this->discount` and execute `SELECT ... id IN()` query and receive an error due to database limitations. Only after that Commodity models will be filled with Discound models, which is not logical - i expect afterFind in 'base' model called after filling with relations, not before.

Or is there anything i can use instead that i just don't know of?

**Comment by dynasource** [comment]
If you want people over here to understand what your problem is, you should formulate your issue better. You are talking about multiple issues and a example of code which doesnt really say anything.

About afterFind and its chronology, take a look at the code over here:
https://github.com/yiisoft/yii2/blob/master/framework/db/ActiveQuery.php#L229

If you still think something is wrong, please repost all the code necessary to understand your issue, as slim as possible (without redundant/unnecessary code).
