### ISSUE TITLE
Error if role name is 0

### ISSUE THREAD

**Issue by Claud** [yiisoft/yii2#9775]
I have default roles

``` php
const ROLE_SUPER_ADMIN = 0;
const ROLE_ADMIN = 1;
....
```

This check not work

https://github.com/yiisoft/yii2/blob/master/framework/rbac/DbManager.php#L219

**Comment by samdark** [comment]
That's quite weird name for a role... Usualy names are meaningful strings like "role_super_admin".

**Comment by dynasource** [comment]
the whole RBAC architecture is built around strings. Examples:
* the empty() functions
* variable names ($itemName)
* several method arguments
* method docs

A lot has to be changed in the architecture in order to accept integers. 

Its easier for you to implement strings for your constants. This which would not lead to many problems if these are applied consistently. An example:
```php
const ROLE_SUPER_ADMIN = 'super-admin';
const ROLE_ADMIN = 'admin';
```

Please elaborate if integers are of vital importance  in order for this issue to be opened again.

**Comment by dynasource** [comment]
more opinions about this https://github.com/yiisoft/yii2/pull/9832#issuecomment-145531425
