### ISSUE TITLE
Use PHP 7 random_bytes() in \base\Security

### ISSUE THREAD

**Issue by tom--** [yiisoft/yii2#9878]
\base\Security::generateRandomKey() should use [random_bytes()](https://secure.php.net/manual/en/function.random-bytes.php) as a first priority when it is available.

**Comment by samdark** [comment]
Agree. Could you work on a pull request?

**Comment by tom--** [comment]
Yes, this one is easy. The next two require some consideration.

**Comment by tunecino** [comment]
a quick question. I don't know how those libs works, so when doing this:
```php
$authKey = \yii\base\Security::generateRandomString();
```
which is built on top of `generateRandomKey()` and maybe `random_byte()` in a future. Is there any probability that 2 users may have the same authKey ?  or is it safer to do something like this instead :
```php
$authKey = \yii\base\Security::generateRandomString() . '_' . time();
```

**Comment by tom--** [comment]
@tunecino `generateRandomString()` is just plain random, like rolling dice, so repetitions are possible. But your proposed solution is risky, see below.

You can make the probability of repetitions very small by making the random string long enough. For the full story, read about the [Birthday Problem](https://en.wikipedia.org/wiki/Birthday_problem). I can't be bothered with that so I ask for a 12-byte string (which has 64^12 ~ 4.7E21 different values) and assume the chance of repetitions is so small I can ignore it.

If you append `'_' . time()` then you are still not safe. One second is a long time on modern processors. And the algorithm is so obvious that it makes it easy to guess things. If you want to do that you might want to run the result through something like sha256 to hide the algorithm, although that reintroduces the very small chance of repetitions, although the number of different outputs of sha256 is much bigger than the Shannon number.

**Comment by samdark** [comment]
@tom-- so it this issue still here for 2.0.7?

**Comment by tunecino** [comment]
@tom-- I think you are right. tagging each generated token with its manufacturer date is just making it easier to reorder & compare a couple of them. at least that. and I'm not sure if running that result thought sha256 will not just look like throwing dices one more time and just getting a different random number.

I'm trying to apply OAuth 2.0 with a long living refresh_token (maybe 30 days) + a short living access_token (maybe 1 hour) so it won't be a good idea to check DB for existence each time I generate an access_token (maybe if using cache to hold them instead of DB. I'm not sure about). 

But any way, for now, I think I'm going to use `generateRandomString()` with its default value ($length = 32) for both tokens. Maybe in a future when getting a huge user table I should consider increment bytes as I should have better hardware any way to support that number of users so performance should be a less issue to consider by that time.

I also made more searches about `/dev/urandom` and I found [this answer by @ThomasPornin](http://security.stackexchange.com/questions/3936/is-a-rand-from-dev-urandom-secure-for-a-login-key) :  
> ...A sequence of random bytes does that well, provided that it uses randomness of adequate quality (/dev/urandom is fine) and that it is long enough. As a rule of thumb, if you have less than 2n users (n = 33 if the whole Earth population could use your system), then a sequence of n+128 bits is wide enough; you do not even have to check for a collision with existing values: you will not see it in your lifetime. 161 bits fits in 21 bytes.

Which also shares your suggestion. Thanks for the great explanation and the Birthday Problem link.

**Comment by tom--** [comment]
@samdark I want to keep the issue to remind me to rewrite the `generateRandomKey()` method. It's not a scary security issue, it's just about making improvements based on things I learned since the last rewrite. The PR I put forwards is however not worth keeping.

**Comment by tom--** [comment]
@tunecino Thomas Pornin is right, as usual.

It's worth taking some time playing with the numbers to get a feel for it, as far as one can with such big numbers. For example, if you have 32 characters of base 64, you have 64^32 different values. If all the VMs at AWS ran for a year generating at 1 number every 10 ns, how many collisions to expect? If you can answer those kinds of questions, you can consider yourself a numerate programmer:)
