### ISSUE TITLE
HTTP-500 error on Shared Hosting. (No entry in Log file) !

### ISSUE THREAD

**Issue by osnwach** [yiisoft/yii2#9939]
I am using Yii2 Advanced.
On localhost I worked with Windows WAMP, Php 5.4.  No issues, everything worked Fine ! 

Now I have uploaded my files to a Shared Hosting Server - Linux, Apache, Php 5.5

If i visit the site e.g -www.mysite.com , I get HTTP-500 Internal Server Error. No Entry is being made to app.log file.

I have changed Yii DEBUG to TRUE and YII_ENV to dev.

I want all errors to display on the Browser so I can quickly see it, But I keep getting HTTP-500 Internal Server Error !

Please kindly help solve this issue !!

**Comment by SilverFire** [comment]
`frontend/web/.htaccess`

http://stackoverflow.com/questions/6127980/enabling-error-display-in-php-via-htaccess-only

**Comment by osnwach** [comment]
@SilverFire,  Here is the content of my .htaccess file:

Options +FollowSymLinks
IndexIgnore */*

RewriteEngine on

# if a directory or a file exists, use it directly
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d

# otherwise forward it to index.php
RewriteRule . index.php

php_flag display_startup_errors on
php_flag display_errors on
php_flag html_errors on
php_flag  log_errors on
php_value error_log  /home/tryjambc/public_html/PHP_errors.log

Am still having same issue : INTERNAL SERVER ERROR

**Comment by SilverFire** [comment]
If there is still nothing in `/home/tryjambc/public_html/PHP_errors.log` you have to contact support of the shared hosting and ask for logs.

I can make a wild guess that PHP requirements are not satisfied or the webroot points to the wrong location.

**Comment by osnwach** [comment]
The file /home/tryjambc/public_html/PHP_errors.log
is not being created.

Is it to be created Automatically, or Am I the one to create it myself ?

**Comment by SilverFire** [comment]
I see you have `/home/tryjambc/public_html/` dir, but document root have to be `(path to yii)/frontend/web`. Did you set correct document root?

Depends on directory privileges. You may try to create it and set chmod 666 for test, but it's better to contact server administrator, because setting `php_flag` id `.htaccess` is usually restricted administratively on shared hostings.

Please notice that this is not a support forum. We are happy to help you on [support forum](http://www.yiiframework.com/forum/) or in gitter room https://gitter.im/yiisoft/yii2/rus
